### ISSUE TITLE
Multiselect widget for DynamicMaps and/or for Bokeh HoloMaps

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#1056]
Currently, a numerical HoloMap dimension is mapped to a slider widget by default, and an enumerated/categorical dimension is mapped to a selection box (see e.g. the GridMatrix example at http://holoviews.org/Tutorials/Containers.html), allowing one of the discrete values along that dimension to be selected using the widget.  However, in many cases it would be meaningful and useful to be able to select *multiple* values along that dimension, creating an overlay.  E.g. instead of choosing *one* discrete value to select one Curve, one could choose several discrete values to select several Curves.  

Such functionality is currently possible using streams, as illustrated using a ListSelector in https://anaconda.org/jbednar/stock_dashboard/notebook, but it seems like this is something that would just generally be useful for a categorical dimension, perhaps as a plot option -- in many cases a multi-select would be more useful than a single select, and where meaningful the multiselect subsumes the single select.  

Implementing it at the JavaScript level would let such functionality work in exported notebooks, and even if it still required a Python kernel due to using a DynamicMap, this way would still be far simpler for users than having to build up a special stream for such a common requirement.

**Comment by philippjfr** [comment]
Our design really does not currently make this seem particularly feasible. Specifically making this work at the Javascript level is almost certainly out-of-scope, because it would have to cache every possible combination of selections for it to work.

**Comment by jbednar** [comment]
Because the selector widget is selecting between existing plots?  Ok, what about not at the JavaScript level?

**Comment by philippjfr** [comment]
If this is were only allowed on a DynamicMap it's at least theoretically possible, but would require a considerable reorganization of the widget and plotting code. What would need to happen would be that it would automatically instantiate an ``OverlayPlot``, this plot would then use the key containing a list of values to dynamically sample the DynamicMap and return an NdOverlay that can be plotted. I can see this getting quite hairy but I can at least see a path to make that possible.

**Comment by jbednar** [comment]
Ok, let's not worry about it for any time in the foreseeable future. Would have been nice, though!

**Comment by jbednar** [comment]
In Bokeh, would it not be possible to implement this at the JavaScript level for a HoloMap by setting some of the curves (or whatever Element) to a transparent color?  I.e. have just one plot, not a set of them, and enable or disable the Elements individually?  This might still be a big pain, because it's not how things are currently done, but at least it wouldn't require storing every combination of values, which would indeed be infeasible.

**Comment by philippjfr** [comment]
Yes, making this work with bokeh does seem feasible but for obvious reasons it could never be supported in matplotlib.

**Comment by philippjfr** [comment]
While I originally said this could be feasible for bokeh DynamicMaps I no longer think that's actually true. Toggling individual renderers as visible is not something any conceivable widget design will ever do. If we eventually expose a way to add JS hooks to widgets, which seems conceptually feasible, the user could define something like this, but I do not see there ever being a general purpose solution that will work consistently. I'm basically back to my original position that this is out-of-scope.

**Comment by jbednar** [comment]
I have the luxury of not knowing what's actually involved in the HV widget system, but from that perspective it just seems like connecting the state of a widget to an alpha value on a glyph should be a reasonable thing to do in JS.

**Comment by philippjfr** [comment]
It's something a user should be able to set up easily, but is way too specific for our core widgets.
