### ISSUE TITLE
Latex axis labels with bokeh backend

### ISSUE THREAD

**Issue by denglert** [holoviz/holoviews#1159]
It would be nice to improve the aesthetic quality of the plots generated by the bokeh backend by including the option to add latex axis labels.

Example:
~~~~
all_ds = all_ds.redim(mH=('mH', r'$m_{H}$ [GeV]'), mHc=('mHc', r'$m_{H^\pm}$ [GeV]'), cba=('cba', r'$\cos(\beta - \alpha)$'), tb=('tb', r'$\tan \beta$'))
a  = all_ds.to(hv.Points, kdims=['cba', 'tb'], vdims=[], groupby=['mA_bin'])
b = a.map(lambda x: x.clone(kdims=['mH', 'mHc'], vdims=[]), [hv.Points])
(a + b).cols(2)
~~~~
Currently the labels are not rendered at all, and the only latex syntax is displayed.

From bokeh side there seems to be some support for latex labels introduced in 0.12.2:
- https://bokeh.github.io/blog/2016/9/6/release-0-12-2/
- http://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/latex.html
- https://github.com/bokeh/bokeh/issues/647

Although for me it seems that with this feature you can only place labels on top of the canvas, but not modify the axis labels.
Another concerned user:
http://stackoverflow.com/questions/41664768/use-latex-in-bokeh-axis-label

**Comment by jlstevens** [comment]
I agree we should expose bokeh LaTeX label support especially as this is supported for the matplotlib backend. Thanks for filing this issue!

**Comment by rabernat** [comment]
+1

**Comment by jlstevens** [comment]
I've moved the milestone in case this isn't too hard to implement allowing us to tackle it sooner rather than later.

**Comment by gioarma** [comment]
Hello, I saw that since September 2021 Latex labels are supported by Bokeh (bokeh/bokeh#6031).

Do you think it would be feasible to have this nice feature in holoviews/bokeh as well?

**Comment by philippjfr** [comment]
@gioarma Thanks for the reminder. If you have bokeh 2.4.2 this should already work out-of-the-box:

```python
import numpy as np

x = np.arange(-2*np.pi, 2*np.pi, 0.1)
y = np.sin(x)
hv.Curve((x, y)).opts(xlabel=r"\[\sin(x)\]", ylabel=r"\[x\cdot\pi\]")
```
![bokeh_plot - 2022-02-15T121708 746](https://user-images.githubusercontent.com/1550771/154051526-247755d9-aa77-4770-a94a-b86390212667.png)
