### ISSUE TITLE
Annotating plots

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#1185]
People use plots to help understand data, and it would be great if we could capture some of that understanding for future use and for sharing with colleagues.  For instance, when looking at a timeseries plot, one often notices unusual or surprising features, which eventually become clear after enough inspection, domain knowledge, comparison to other plots, or outside information.  It would be great to support being able to add such annotations to a plot, by adding a Bokeh tool that creates a glyph with associated text at a clicked-on location in data space.  There would need to be a way to extract the list of such annotations so that it could be persisted and then re-applied in a later session.

Presumably streams make this possible, but it's likely to be simpler to implement this once 
[Bokeh's PR#5941](https://github.com/bokeh/bokeh/pull/5941)  has been merged.

**Comment by philippjfr** [comment]
Another dashboard example for the docs.

**Comment by philippjfr** [comment]
Since keypress events didn't make it into bokeh yet, the only way I can see to solve this for now is using a paramNB widget for text entry and confirming the selection. I'll try to come up with an example for our gallery.

**Comment by jbednar** [comment]
Sounds awkward.  Should we not just try to get keypress events into Bokeh now?

**Comment by jlstevens** [comment]
I agree with Jim. Let's figure out how to get this working properly with Bokeh for 2.0 which means figuring out how to handle keypress events properly in Bokeh itself.

**Comment by philippjfr** [comment]
Maybe it's worth discussing what the UI for this would look like. A pure event based version would presumably add a point or VLine on double tap and could then listen to key input events until you hit enter. This would probably be fine but I'm not sure whether key events will even make it into bokeh 2.0 because there are all kinds of issues with focus which are especially acute in the notebook. Providing a text input box, which is activated by a double tap and a button to persist the annotation seems like the most intuitive solution that has is definitely going to be supported in the near future.

**Comment by jbednar** [comment]
Just listening for key events seems like an awkward interface (typing blindly); seems better to pop up a text-input box.  And you say that's definitely going to be supported?  By whom?

**Comment by philippjfr** [comment]
>Just listening for key events seems like an awkward interface (typing blindly); seems better to pop up a text-input box. And you say that's definitely going to be supported? By whom?

Right, popping one up would be the ideal solution, I was just talking about adding one manually that's there persistently but only works after a double tap, using paramNB and in future parambk (param bokeh).

**Comment by jbednar** [comment]
Ah.

**Comment by philippjfr** [comment]
A custom bokeh tool which could be merged back into bokeh might make the most sense.

**Comment by jbednar** [comment]
That does sound reasonable; this seems like something many people would want to do.

**Comment by jlstevens** [comment]
Reassigning to the 2.0 milestone.

**Comment by philippjfr** [comment]
This is now possible by using the draw streams and a linked editable table. We should add a demo to show this approach being used for annotation something though.

**Comment by jlstevens** [comment]
Agreed that we should have a demo for this now it is possible.

**Comment by jbednar** [comment]
See http://earthsim.pyviz.org/user_guide/Drawing_Tools.html for examples of how to use the new tools. We still need examples of the type of thing originally mentioned in this issue, but it should be feasible to build them now.

**Comment by philippjfr** [comment]
Annotators and drawing tools have now both been merged and are documented.
