### ISSUE TITLE
Add holoviews.operation.dynamic subpackage

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#1395]
The distinction between operations with ``dynamic=True`` by default and those with ``dynamic=False`` by default can get confusing. 

To help organize things properly, we've agreed that everything in ``holoviews.operation.datashader`` is expected to by dynamic and that a new ``holoviews.operation.dynamic`` subpackage will hold all other operations that default to ``dynamic=True`` (currently just ``decimate``).

Afterwards all operations are expected to be partitioned such that only operations in  ``dynamic`` and ``datashader`` have ``dynamic=True`` by default.

**Comment by jlstevens** [comment]
Doubt this will happen for 1.8. Moving to the next milestone.

**Comment by philippjfr** [comment]
We never found any additional dynamic operations we wanted to add.
