### ISSUE TITLE
Simplify BarPlot classes

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#1407]
As we have discussed in multiple places the Bars Element is quite annoying in its current form for a number of reasons:

1) The bokeh implementation is based on the charts API which will be deprecated in bokeh 0.12.6.
2) The matplotlib and bokeh implementations are currently inconsistent as bokeh supports grouping and stacking the bars at the same time while bokeh only allows for one at a time (after #1405 is merged fixing various bugs in the current bokeh implementation).
3) The matplotlib implementation is inefficient, ugly and too complex.

Other limitations:
    * No support for log axes (#1233)
    * Bars may not be negative in the bokeh backend (#862)
    * ``invert_axes`` option not supported by either backend, making horizontal bars impossible

As we will have to replace the bokeh bar plot implementation soon anyway I'd suggest the following way forward:

1) Rewrite the bokeh and matplotlib implementations allowing for either stacking or grouping of bars but not both (this limits the complexity). Target this for 2.0 release.
2) Once we have worked out issues with nested coordinates and categorical axes, both stacking and grouping can be supported by overlaying multiple Bars. Target for 3.0?

**Comment by thoth291** [comment]
Thanks!
What about log axes, @philippjfr ?

**Comment by philippjfr** [comment]
>What about log axes, @philippjfr ?

The problem with log axes is that bars usually start at zero but it seems that bokeh blows up when you give it a range starting at zero. We could use a value very close to zero but unfortunately the bokeh log axis then adjusts down to the supplied order of magnitude. If you have a good suggestion on how to deal with this issue, I'd be happy to implement it, unfortunately I haven't found a good approach.

**Comment by jlstevens** [comment]
@philippjfr Have you asked one of the bokeh devs about this? Seems like an important limitation!

**Comment by philippjfr** [comment]
Looks like this was fixed recently https://github.com/bokeh/bokeh/pull/6122, could be that it just works in 0.12.6.

**Comment by philippjfr** [comment]
Managed to find a workaround https://github.com/ioam/holoviews/pull/1416 now also adds support for applying ``logy``.

**Comment by philippjfr** [comment]
The bokeh BarPlot implementation has now addressed all the issues mentioned above. The matplotlib version still needs to be rewritten from scratch.
