### ISSUE TITLE
Add a constructor for Scatter similar to Path

### ISSUE THREAD

**Issue by ea42gh** [holoviz/holoviews#1409]
Given
    x      = np.arange(10)
    vals  = np.random.rand(10, 50)

Allow a constructor
    hv = Scatter( (x,vals) )  # similar to hv.Path()
rather than a construct such as
    hv.Scatter( (np.repeat(x, 50), vals.flatten()) )

**Comment by philippjfr** [comment]
Theoretically there's no issue in allowing the constructor handle this. It would simply have to expand the x-coordinates internally as shown above.

**Comment by jbednar** [comment]
Sounds like a good case for a user-submitted PR! :-)

**Comment by ea42gh** [comment]
# Example: 
%%opts Path [width=500] (alpha=0.3 color='darkred')

n_data  = 10
n_paths = 50
x_vals  = np.linspace(1,n_data,n_data)
values  = np.random.normal(size=(n_data,n_paths))

h       = hv.Scatter((np.repeat(x_vals, n_paths), values.flatten())) * \
          hv.Path((x_vals, values)) #.transpose()))
h.redim.range(x=(0,11), y=(-3,3))

**Comment by ea42gh** [comment]
Should hv.Path() allow an empty cpnstructor?

**Comment by jlstevens** [comment]
> Should hv.Path() allow an empty constructor?

I think so - we should aim to allow empty constructors for all elements.

**Comment by philippjfr** [comment]
-1 on this at this point. We have a lot of constructors already.
