### ISSUE TITLE
Support for twin axes in bokeh

### ISSUE THREAD

**Issue by jordansamuels** [holoviz/holoviews#1594]
There have been several discussions on [chat](https://gitter.im/ioam/holoviews) about support for twin axes.  @philippjfr generously supplied some examples for matplotlib and for bokeh, but the bokeh one doesn't work.  It is below, and with 1.7.0 and 1.8dev2 (with bokeh 0.12.6), it produces a graph which has both left and right y-axes the same.

![image](https://user-images.githubusercontent.com/610909/27399975-44da61de-5684-11e7-9fea-b88d33e0a7ba.png)

```
%%opts Curve [toolbar='above']
from bokeh.models import LinearAxis, Range1d

def twinx(plot, element):
    # Setting the second y axis range name and range
    start, end = (element.range(1))
    label = element.dimensions()[1].pprint_label
    plot.state.extra_y_ranges = {"foo": Range1d(start=start, end=end)}
    # Adding the second axis to the plot. 
    linaxis = LinearAxis(axis_label=label, y_range_name='foo')
    plot.state.add_layout(linaxis, 'right')

a = hv.Curve(([1,2], [3,21]), vdims=['A'])
b = hv.Curve(([1,2], [50, -10]), vdims=['B'])(plot=dict(finalize_hooks=[twinx]), style=dict(color='red'))
h = a * b
h.redim.range(x=(0,3))
```

**Comment by iweey** [comment]
![image](https://user-images.githubusercontent.com/2853214/30250595-90b33e1a-9616-11e7-9c87-ed03bad3e1a2.png)

%%opts Curve  [width=800 height=400 tools=['hover','box_select', 'lasso_select' ] toolbar='above'] 
from bokeh.models import LinearAxis, Range1d

def twinx(plot, element):
    # Setting the second y axis range name and range
    start, end = (element.range(1))
    label = element.dimensions()[1].pprint_label
    plot.state.extra_y_ranges = {"foo": Range1d(start=start, end=end)}
    # Adding the second axis to the plot. 
    linaxis = LinearAxis(axis_label=label, y_range_name='foo')
    plot.state.add_layout(linaxis, 'right')



curve_all = hv.Scatter(ot.drive_pbdf, kdims=['date'], vdims=['speed_kmph'] ) 
curve_all_a = hv.Curve(ot.drive_pbdf, kdims=['date'], vdims=['speed_kmph'] ) 
cc = curve_all*curve_all_a
# curve_all*curve_all_a + curve_acc

curve_acc = hv.Scatter(ot.drive_pbdf, kdims=['date'], vdims=['speed_kmph_acc']) (plot=dict(finalize_hooks=[twinx]), style=dict(color='red'))


# b = hv.Curve(([1,2], [50, -10]), vdims=['B'])(plot=dict(finalize_hooks=[twinx]), style=dict(color='red'))
h =cc * curve_acc
h
# h.redim.range(x=(0,3))




how to set two Y-axis symmetric  ?

**Comment by iweey** [comment]
%%opts Curve  [width=800 height=400 tools=['hover','box_select', 'lasso_select' ] toolbar='above'] 
from bokeh.models import LinearAxis, Range1d

def twinx(plot, element):
    # Setting the second y axis range name and range
    start, end = (element.range(1))
    label = element.dimensions()[1].pprint_label
    plot.state.extra_y_ranges = {"foo": Range1d(start=start, end=end)}
    # Adding the second axis to the plot. 
    linaxis = LinearAxis(axis_label=label, y_range_name='foo')
    plot.state.add_layout(linaxis, 'right')



curve_all = hv.Scatter(ot.drive_pbdf, kdims=['date'], vdims=['speed_kmph'] ) 
curve_all_a = hv.Curve(ot.drive_pbdf, kdims=['date'], vdims=['speed_kmph'] ) 
cc = curve_all*curve_all_a
# curve_all*curve_all_a + curve_acc

curve_acc = hv.Scatter(ot.drive_pbdf, kdims=['date'], vdims=['speed_kmph_acc']) (plot=dict(finalize_hooks=[twinx]), style=dict(color='red'))


# b = hv.Curve(([1,2], [50, -10]), vdims=['B'])(plot=dict(finalize_hooks=[twinx]), style=dict(color='red'))
h =cc * curve_acc
h
# h.redim.range(x=(0,3))

**Comment by bacalfa** [comment]
I know this has been closed, but I'm unable to get two y axes with the following code.

```
%%opts Curve [toolbar='above'] {+framewise}
from bokeh.models import LinearAxis, Range1d

def twinx(plot, element):
    # Setting the second y axis range name and range
    start, end = (element.range(1))
    label = element.dimensions()[1].pprint_label
    plot.state.extra_y_ranges = {"foo": Range1d(start=start, end=end)}
    # Adding the second axis to the plot. 
    linaxis = LinearAxis(axis_label=label, y_range_name='foo')
    plot.state.add_layout(linaxis, 'right')
    
data = dict(A=["A1", "A1", "A2", "A2"], B=["B1", "B1", "B2", "B2"], C=[10, -5, 23, 9], D=[0, 5, -7, 6], E=[2, -5, 8, 5])
df = pd.DataFrame(data=data)

df_hv = hv.Dataset(df)

curve1 = df_hv.to.curve(kdims=["C"], vdims=["D"], groupby=["A", "B"])
curve2 = df_hv.to.curve(kdims=["C"], vdims=["E"], groupby=["A", "B"])
curve1 * curve2
```

**Comment by Mulan-94** [comment]
Hi, 
I would like to get twin axes for the x-axis but the `plot.extra_x_ranges` (referencing plot from the code in the previous above comment) does not seem to work and the only way that works is `plot.extra_y_ranges` while putting the extra axis *above*. but even with this, the ranges i specify are not reflected. 
@philippjfr  Any help in countering this?
