### ISSUE TITLE
Fix outstanding broken links

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#1650]
[Here is a Google Sheet](https://docs.google.com/spreadsheets/d/1yajKejf15ekvq01_Qt83F7Ut2Mrfalv_zBZA9xaRQKA/edit#gid=0) with remaining broken links. We should fix these soon.

**Comment by jlstevens** [comment]
#1618 is probably in the list but referencing the issue to make sure.

**Comment by jlstevens** [comment]
PR #2509 fixed a bunch of links for 1.10.

I'm assigning this issue to 1.10.x as a reminder to run a link checker again after the website is updated to catch any other (or new) broken links that aren't fixed by that PR.

**Comment by bewt85** [comment]
Hi, I don't think you have these which I found in [the showcase tutorial](http://holoviews.org/Tutorials/Showcase.html)
http://holoviews.org/Tutorials/Introduction.ipynb
http://holoviews.org/Tutorials/Exploring_Data.ipynb
http://holoviews.org/Tutorials/Options.ipynb
http://holoviews.org/Tutorials/Elements.ipynb
http://holoviews.org/Tutorials/Containers.ipynb

Thanks for making a great tool.

**Comment by philippjfr** [comment]
Closing this since the list is outdated.
