### ISSUE TITLE
Charts should enforce a single kdim

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#1668]
The following works when it should be disallowed:

![image](https://user-images.githubusercontent.com/890576/27766470-c820aa20-5ec8-11e7-885a-aec2715e97e1.png)

With a dataframe with enough columns, multiple kdims can be declared on curve (for instance) when only one should ever be allowed.

**Comment by philippjfr** [comment]
The PandasInterface had to add some special handling because this is not done yet, should do this soon.

**Comment by philippjfr** [comment]
There is some discussion to be had here, now that bokeh supports nested categorical axes and certain elements like Bars, BoxWhisker and soon Violin plot treat multiple kdims as nested categoricals it may be worth considering whether all Chart like elements should do this. For example take this example:

![bokeh_plot](https://user-images.githubusercontent.com/1550771/34258707-16f5c4b2-e657-11e7-8beb-8413e68f21e3.png)

If I wanted to overlay Scatter points on top, I'd currently have no way of doing so but if Scatter treated two kdims as nested categoricals it would work fine.

**Comment by jbednar** [comment]
Sounds like valid reasoning to me!

**Comment by philippjfr** [comment]
I would have liked to have done this for 1.11 but it's a big task, so bumping to 1.12.

**Comment by philippjfr** [comment]
Sadly I forgot to go through with the plan we had come with here for 1.13.0, which was to explicitly disallow 2 key dimensions on charts.
