### ISSUE TITLE
Document map and traverse methods

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#1688]
We've been meaning to document the map and traverse methods for a while but haven't gotten around to it. We should add it to the user guide about working with nested data.

**Comment by jlstevens** [comment]
We also need to document that map drops return values of None and other such behaviour.

**Comment by philippjfr** [comment]
`.map` and `.traverse` are now low-level methods and `.apply` is documented. So I think documenting them in the API reference is sufficient.
