### ISSUE TITLE
Ref docs hard to scan

### ISSUE THREAD

**Issue by bryevdv** [holoviz/holoviews#1727]
The layout of params makes very difficult to scan:

<img width="391" alt="screen shot 2017-07-14 at 09 44 08" src="https://user-images.githubusercontent.com/1078448/28232616-4f60a7b8-68b7-11e7-8017-a1e5b5eff498.png">

Suggest:

* ditch the redundant "param" (e.g put all params in a section labeled "param" instead)
* don't present these as functions, the function signatures are very cluttering. Additionally I think it would make more sense to describe the relevant param settings (defaults, read only) etc as properties of a param (maybe listed below) rather than as function args which is a confusing low level detail
* put the type *after* the param name (or in the section below) so  that the actual param names line up vertically. Right now they are all over the place horizontally because of some short and some very long type names. This makes it extremely difficult to scan quickly by name.

**Comment by jlstevens** [comment]
I totally agree. The reference documentation hasn't had much love and the sphinx extension output could be improved a whole lot.

**Comment by philippjfr** [comment]
All the suggestions here, were independently implemented. It's still not great but improving this will be part of improving param docs in general.
