### ISSUE TITLE
Unite "aspect" and "width/height" plot options

### ISSUE THREAD

**Issue by michaelaye** [holoviz/holoviews#1768]
The docs state that "plot options" are meant to be the same for different backends.

I take it that means that the fact that bokeh plots use "width" and "height" and matplotlib using "aspect" is still an aspect that awaits unification?
I strongly support these unification efforts, there's almost no sense in using a top-wrapper on existing plotting libs, if I still would have to learn all underlying options independently for each backend.

Using most recent conda-forge version.

**Comment by jlstevens** [comment]
> I take it that means that the fact that bokeh plots use "width" and "height" and matplotlib using "aspect" is still an aspect that awaits unification?

That is correct, we would love a unified interface!

Unfortunately, it is technically quite challenging as different plotting extensions work in different ways. Even without considering the plotly extension, getting both matplotlib and bokeh working consistently is quite challenging as these two libraries have very different models when it comes to sizing things.

**Comment by jbednar** [comment]
I would *love* to see some consistent way to size things across these two backends.  It's very frustrating that it's not currently possible, and it just seems like it *should* be possible to unify them somehow!  I haven't ever looked at the code to realize just why this is difficult, though, and I'm afraid to in case it changes my optimism here!

**Comment by michaelaye** [comment]
I would imagine, all that one need's is a "translator" lookup dictionary that points to transformer functions for the respective currently active backend. But I might be naive. ;)

**Comment by ea42gh** [comment]
In the meantime, I see a need for a tutorial/example page somewhere.
I had explored the issue in CurvesAndPaths, but never really formalized it.
Would there be interest if I tried putting together a notebook (and hopefully
getting input from interested parties)?

**Comment by michaelaye** [comment]
Revisiting holoviews, I could again not find how to set width for the matplotlib backend. Is `aspect` documented somewhere? I can't see it in http://holoviews.org/user_guide/Customizing_Plots.html

**Comment by philippjfr** [comment]
@michaelaye Have a look at http://holoviews.org/user_guide/Plotting_with_Matplotlib.html

**Comment by zertrin** [comment]
See also related issue #3598 for matplotlib backend sizing issues

**Comment by philippjfr** [comment]
Aspect is now supported across backends. I absolutely don't see any way to unify width/height options across backends however.
