### ISSUE TITLE
Stream memoization is very slow for large datasets

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#2009]
Streams were generally designed for receiving small amounts of data like a single x/y coordinate or range, which can easily be hashed and memoized. There are certain use cases where one might want to push actual large datasets through a stream and in those cases particularly for dataframes the deep json based hashing we perform is **very** slow. Indeed in my current case it's a factor 100x slower than actually running the callback, entirely defeating the point of memoization in the first place. There are certain cases where pushing data through a stream is desirable, the first is when sending path/polygon data back from JS, as the drawing tools I'm working on do. The second is when using ``streamz``, where pushing the data to an intermediate datastructure seems pointless when you could just pipe it into a HoloViews ``stream.event`` method.

I'd like to come up with some policy that performs better for large arrays or dataframes in general. But in the meantime I'd like to suggest two improvements that will alleviate this issue. First of all I think the hashing should work via hooks you can register by type so I can easily replace the hashing function. Secondly I think instead of hashing directly on the ``contents`` I believe a Stream should be able to define a custom ``hashkey`` method (or similar) which just returns the contents by default but can be overridden to return any hashable object.

**Comment by jlstevens** [comment]
That all makes sense though it does add a fair bit of complexity, having to register various hooks etc.

**Comment by philippjfr** [comment]
Haven't seen any need for this now. Hashing of large datasets really isn't feasible whatever we do.
