### ISSUE TITLE
Suggestion to have "What's new" page for new releases

### ISSUE THREAD

**Issue by Gerenuk** [holoviz/holoviews#2205]
A "What's new" page, which exists for most projects, is incredibly helpful to keep up with the new exciting features of a package.

It would be very useful to have one for Holoviews, so that one can get to know new features of new releases.

Searching for "what's new" did not give me a similar page.

**Comment by jbednar** [comment]
We already have notes for each release:

   https://github.com/ioam/holoviews/releases

But yes, we probably should haev a more graphical page showing off new capabilities as they appear.  Right now, we are adding features way quicker than anyone can learn about them!

**Comment by jlstevens** [comment]
I really like how bokeh announces releases in a blog post style. We should do that too but we would need to set up a static page generator, link to it properly etc as well as write some nice content for each release!

**Comment by philippjfr** [comment]
>We should do that too but we would need to set up a static page generator, link to it properly etc as well as write some nice content for each release!

I like bokeh's blog style page, but it seems simpler to just have a section like that on our website.

**Comment by jlstevens** [comment]
Sure, but then I would still want a page per release.

**Comment by jbednar** [comment]
I don't think we need any special blogging support to do this, but one thing to consider is that the rest of our web site and notebooks are all things that we promise to keep up to date and are dynamically generated each time we have a release.  A blog post isn't like that; it's explicitly dated, and there's no promise that what's on there will be modified later if APIs or dependencies change. 
 So would we store a static copy of such pages, or would we commit to fixing them forever into the future until we delete them?

**Comment by Gerenuk** [comment]
As a user I do the following:
1. Study documentation first
2. Keep up with changes through "What's new" (instead of scanning the docs for changes)

So, I'm aware that "What's new" may be overridden by a newer entry. I wouldn't know how else to get to know about new features.

Btw, ideally a "What's need" can be added to a news reader (i.e. support RSS)

**Comment by philippjfr** [comment]
We now have a releases page: http://holoviews.org/releases.html

That can certainly still be improved (and in fact the headings are broken in the current deployment).
