### ISSUE TITLE
Feature request: add the ability to map colours to particular categories in an overlay.

### ISSUE THREAD

**Issue by pallenmar** [holoviz/holoviews#2291]
As discussed in https://stackoverflow.com/questions/48525032/how-does-holoviews-know-which-colours-to-assign-to-each-scatterplot-in-an-overla/48526352?noredirect=1#comment84095072_48526352, perhaps one feature that could be added would be to allow the user to choose which colours are assigned to which categories in a categorical dimension on an overlay.

**Comment by philippjfr** [comment]
This can now be done explicitly:

```python
dim_expr = hv.dim('category').categorize({'A': 'red', 'B': 'green', 'C': 'blue'})
hv.NdOverlay({chr(65+i): hv.Scatter(np.random.rand(10, 2)).opts(color=dim_expr) for i in range(3)}, 'category')
```
