### ISSUE TITLE
Callable argspec validation should allow kwargs for kdim arguments

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#2318]
When writing DynamicMap callbacks you sometimes want to write a general callback which will work with different numbers of key dimensions. Currently the Callable argspec validation completely prevents this because each key dimension needs to be explicitly named in the callback signature. This makes it completely impossible (or at least very painful) to write a library level callback that handles different numbers of dimensions. I'd **very** strongly argue that using ``kwargs`` should lift the restrictions on validation as it already does for stream parameters.

**Comment by jlstevens** [comment]
I am happy to change policy so this style is disallowed. It makes validation weaker when used so I in turn would *strongly* recommend *not* using this style unless necessary. But I do agree we shouldn't disallow it.
