### ISSUE TITLE
Missing plot in docs

### ISSUE THREAD

**Issue by michaelaye** [holoviz/holoviews#2475]
On http://holoviews.org/reference/streams/bokeh/Selection1D.html
no graphics appear, while the linking page 
http://holoviews.org/reference/index.html
has a preview for it?

Tried on iOS Safari.

**Comment by philippjfr** [comment]
Bit confused, either this was fixed or the gif that's there didn't load before.

**Comment by michaelaye** [comment]
The graphic didn’t load before AND that has been fixed. :)
