### ISSUE TITLE
Best holoviews approach for appmode

### ISSUE THREAD

**Issue by rsignell-usgs** [holoviz/holoviews#2490]
I wanted to show off the cool datashader trimesh capability where folks could play with it on binder, using appmode, and I made this demo 
https://github.com/reproducible-notebooks/Tides_TriMesh_Datashader/blob/master/tide_trimesh_widgets.ipynb
which you can:

 [RUN ON BINDER](https://mybinder.org/v2/gh/reproducible-notebooks/Tides_TriMesh_Datashader/master?urlpath=%2Fapps%2Ftide_trimesh_widgets.ipynb):

![2018-03-28_10-19-29](https://user-images.githubusercontent.com/1872600/38035432-695d78be-3272-11e8-8ace-bed2cec84003.jpg)

I first tried putting the holoviews rendering inside an @interact function, but that didn't produce output, I guess because of the JS?

So the only approach I could figure out that worked was to use the "run all cells below" approach when you click  the "execute" button.

Is there a better way?

The startup is a bit confusing for users because they are tempted to hit "execute" before the map appears, which takes some time.   Improvements welcome.

Still a cool demo to show off the impressive zoom and pan capabilities of Datashader/Holoviews/Geoviews.
![2018-03-28_10-43-16](https://user-images.githubusercontent.com/1872600/38036568-f9b5d544-3274-11e8-8878-68d956f91505.jpg)

**Comment by philippjfr** [comment]
Cool example, we definitely want to make this kind of thing easier eventually, for now I'd suggest looking into HoloViews streams. I've rewritten your example using them:

```python
vars = ['Depth','M2 Elevation Amplitude',
        'S2 Elevation Amplitude','N2 Elevation Amplitude',
        'O1 Elevation Amplitude','K1 Elevation Amplitude']

var = ipyw.Dropdown(options=vars, value=vars[0])
display(var)

button = ipyw.Button(button_style='info',description="Execute")
display(button)

# Link button and dropdown to a HoloViews
value_stream = hv.streams.Stream.define('Value', value='Depth')()
button.on_click(lambda button: value_stream.event(value=var.value))

def gen_trimesh(value):
    if value == 'M2 Elevation Amplitude':
        z = nc['Amp'][0,:]   
    elif value == 'S2 Elevation Amplitude':
        z = nc['Amp'][1,:]   
    elif value == 'N2 Elevation Amplitude':
        z = nc['Amp'][2,:]        
    elif value == 'O1 Elevation Amplitude':
        z = nc['Amp'][3,:]    
    elif value == 'K1 Elevation Amplitude':
        z = nc['Amp'][4,:]    
    else:
        z = -nc['depth'][:]
    v = np.vstack((u['nodes']['x'], u['nodes']['y'], z)).T
    verts = pd.DataFrame(v, columns=['x','y','z'])
    points = gv.operation.project_points(gv.Points(verts, vdims=['z']))
    label = '{} (m)'.format(value)
    return hv.TriMesh((tris, points), label=label)

tiles = gv.WMTS('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}.jpg')

dynamic_trimesh = hv.DynamicMap(gen_trimesh, streams=[value_stream])
plot = tiles * rasterize(dynamic_trimesh, aggregator=ds.mean('z'), precompute=True) 
```

```python
%opts Image [colorbar=True clipping_colors={'NaN': (0, 0, 0, 0)}] (cmap=palettable.cubehelix.perceptual_rainbow_16.mpl_colormap)
%opts WMTS [width=700 height=400]
plot
```

The basic idea is that we link the button callback to the stream. We then declare a DynamicMap which constructs a TriMesh depending on the currently selected dropdown value. We then apply ``rasterize`` to the DynamicMap of TriMeshes, and whenever the dropdown changes that updates the plot.

I'd also recommend looking into https://github.com/ioam/paramnb (built on ipywidgets) and https://github.com/ioam/parambokeh (built on bokeh widgets), which are meant to make this kind of thing easy.

**Comment by jbednar** [comment]
FYI, we've put tutorials at [PyViz.org](pyviz.org) that cover precisely this sort of scenario; those should be a good starting point!

**Comment by rsignell-usgs** [comment]
Ooh, cool!  Thanks @philippjfr and @jbednar !
I'll work my way up to:
http://pyviz.org/tutorial/13_Deploying_Bokeh_Apps.html

**Comment by philippjfr** [comment]
At this point Panel should cover this use case well.
