### ISSUE TITLE
Multiindex support?

### ISSUE THREAD

**Issue by spott** [holoviz/holoviews#2537]
Are there any plans on supporting multiindexes in holoviews in the future?

**Comment by jlstevens** [comment]
This issue is related to #2310. I don't believe this is currently supported but we will investigate it adding support in future.

**Comment by jlstevens** [comment]
I've had a discussion with @philippjfr about handling wide data and that involved using multiindex iirc although that was mostly as an internal optimization. How exactly would you like to see multiindex supported?

**Comment by KevinYanesG** [comment]
Hi! Any news on this? :)

**Comment by jlstevens** [comment]
Unfortunately not though I think we should seriously consider this feature for holoviews 2.0!

**Comment by hCraker** [comment]
Bump! Any news on if holoviews 2.0 is in the works and if it supports multiindex?

**Comment by droumis** [comment]
I'm going to close this in light of #6061 being merged, which will likely be included in the upcoming minor HoloViews release. There will always be more work to be done, but I think general 'multiindex support' is too broad and more appropriate for a discussion thread on the [HoloViz Discourse or Discord](https://holoviz.org/community.html). If there are specific/actionable features requests or bugs, please file a new issue on GitHub.
