### ISSUE TITLE
What files should a user get via holoviews --install-examples ?

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviews#2644]
With a conda install, I get the bokeh gallery apps, but I don't get them with a pip install. I have created https://github.com/pyviz/pyct/issues/22 to track the general issue (applies to all pyviz projects), but here maybe someone could say which files were intended to be included for hv.

**Comment by jlstevens** [comment]
I think it is supposed to be everything in ``/examples``.

**Comment by philippjfr** [comment]
I believe this is now the case.
