### ISSUE TITLE
Add image hover examples to documentation and gallery

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#2697]

**Comment by jlstevens** [comment]
I'm happy to do this.

**Comment by philippjfr** [comment]
Should we close this now? Or is there more you want to add?

**Comment by jlstevens** [comment]
I'm still debating what do do for the datashader user guide. I do think it should show at least one hover example or maybe enable it throughout?

**Comment by philippjfr** [comment]
There already is a hover example in the datashader guide.
