### ISSUE TITLE
Deprecate BarPlot group_index and stack_index

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#2828]
The Bars ``group_index`` and ``stack_index`` plot options were introduced in the initial matplotlib BarPlot implementation which is very poorly designed but allowed both grouping and stacking at the same time. The bokeh implementation is considerably simpler and only allows either grouping **or** stacking so these parameters are at best confusing. Therefore I would like to propose that once the matplotlib implementation is rewritten we immediately deprecate these options and replace them with a simple stacked boolean toggle.

**Comment by jlstevens** [comment]
I agree with this proposal. My only question is whether you will be able to support the old options once it is rewritten (with deprecation warnings) or will this be a 'hard' deprecation where the old options will immediately stop working?

**Comment by philippjfr** [comment]
These options have warned for two releases now so I've removed them now.
