### ISSUE TITLE
 %%opts  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by derelearnro** [holoviz/holoviews#2881]
There are currently two source here why I cannot run these two source code here:

```
%%opts Image (cmap='RdYlGn') Curve (color='b' line_dash="dotted") HLine (line_color='white' line_width=9)
((grating * hv.HLine(y=0)).hist() + grating.sample(y=0))
```

[ref: https://github.com/bokeh/bokeh-notebooks/blob/master/tutorial/A3%20-%20High-Level%20Charting%20with%20Holoviews.ipynb]

and 

```
%%opts Points.A [width=300 height=300] Points.B [width=600 height=300]
hv.Points(data, group='A') + hv.Points(data, group='B')
```

[Ref: http://holoviews.org/user_guide/Plotting_with_Bokeh.html]

Outout of error 
%%opts Image (cmap='RdYlGn') Curve (color='b' line_dash="dotted") HLine (line_color='white' line_width=9)
    ^
SyntaxError: invalid syntax

**Comment by jlstevens** [comment]
Is the magic on the first line of the cell? Otherwise I can't spot anything that might obviously be wrong...other than maybe try single quotes for 'dotted' (though it should be that!)

**Comment by jbednar** [comment]
Also, that's code only valid in IPython (either inside a Jupyter notebook, or using IPython separately).  If you want it to work in regular Python, you can convert it to use .options():

```
hv.Points(data).options(width=300,height=300) + hv.Points(data).options(width=600,height=300)
```

**Comment by philippjfr** [comment]
We are no longer improving or supporting magic syntax and will eventually remove it. All options should be set using the `.opts` method now.
