### ISSUE TITLE
Feature request: hv.Caption() and hv.HoverText()?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#2896]
hv.Caption: Readily describe plots, like hv.Text, but outside the plot?

hv.HoverText: like hv.Text but wherever you pan, it'll stay in the same area of the plot box (not sure if this exists yet)

**Comment by jbednar** [comment]
Are you imagining hv.Caption to apply to each subplot, or for a layout would it apply to the entire layout?  If the latter, it might not be something best done outside of HV; seems like anything could be captioned, e.g. a Pandas dataframe's representation.

**Comment by philippjfr** [comment]
>hv.Caption: Readily describe plots, like hv.Text, but outside the plot?

I think this could be supported easily by adding the renderer ``level`` as a style option which would allow the text to be placed outside the plot area.

>hv.HoverText: like hv.Text but wherever you pan, it'll stay in the same area of the plot box (not sure if this exists yet)

Sounds like this would be best addressed by allowing the position to be specified in screen coordinates.

**Comment by jbednar** [comment]
> I think this could be supported easily by adding the renderer level as a style option which would allow the text to be placed outside the plot area.

Would the layout then take the size of this text into account?  Seems like that approach would end up with text overwriting something else on the HTML page, if there is a long caption.

**Comment by philippjfr** [comment]
>Would the layout then take the size of this text into account?

No you will only be able to draw within the area of the plot canvas. I'm not aware of an easy way of making layout level annotations like you are imagining possible.

**Comment by jbednar** [comment]
That's what I thought.  That's why I'm suggesting a non-HoloViews solution for this problem, i.e. at a level where the whole layout is embedded into a larger structure that includes the caption.

**Comment by philippjfr** [comment]
What do you mean by non-holoviews? You could already do this by embedding the plot in an HTML template and presumably you will be able to do it at the parambokeh level using the new row/column based layouts.

**Comment by jbednar** [comment]
Right.  This is a request for hv.Caption, but I'm suggesting something outside of hv, e.g. parambokeh.  It's something we *could* add to a layout, but I don't *think* it's appropriate to do so.

**Comment by ahuang11** [comment]
I think this is now possible in pn.pane.Image caption
