### ISSUE TITLE
No plot for rasterize with a single value

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#2936]
If I start with https://anaconda.org/jbednar/datashade_vs_rasterize/notebook, edit the 
line:

```
tiles * rasterize(points, x_sampling=10, y_sampling=10, aggregator=ds.std('dropoff_hour')).options(**opts)
```
to change `aggregator=ds.std` to `aggregator=ds.max` and add `df.dropoff_hour=12` above it, the entire corresponding HoloViews plot disappears:
![image](https://user-images.githubusercontent.com/1695496/43975813-7523a23a-9ca4-11e8-9687-365feef96321.png)
Interestingly, it works fine with `df.dropoff_hour=0`:
![image](https://user-images.githubusercontent.com/1695496/43975842-8dba051e-9ca4-11e8-8a68-bd959179ed5b.png)
It also works fine with `df.dropoff_hour=12` if I use `datashade()`:
![image](https://user-images.githubusercontent.com/1695496/43975886-a9e2744c-9ca4-11e8-8273-90f19154141c.png)

So:

1. Seems like it's a problem in the normalization, since it occurs for a data (z) range of 0
2. Maybe we have a special case when the data range is 0, but the value is also 0?
3. Seems like it's not directly a problem in Datashader, since (a) it only occurs for rasterize (where HoloViews and Bokeh are in charge of colormapping and normalization), and (b) the entire plot disappears with no Python warning, indicating some JS issue?

When there is a problem, the JS console says:
```
VM965:251 Uncaught RangeError: Invalid array length
    at Object.a [as range] (eval at append_javascript (outputarea.js:761), <anonymous>:251:62250)
    at t.get_ticks_no_defaults (eval at append_javascript (outputarea.js:761), <anonymous>:251:415989)
    at t.get_ticks (eval at append_javascript (outputarea.js:761), <anonymous>:251:411325)
    at t.tick_info (eval at append_javascript (outputarea.js:761), <anonymous>:251:144000)
    at t._get_label_extent (eval at append_javascript (outputarea.js:761), <anonymous>:251:140071)
    at t.compute_legend_dimensions (eval at append_javascript (outputarea.js:761), <anonymous>:251:135773)
    at t._get_size (eval at append_javascript (outputarea.js:761), <anonymous>:251:134842)
    at t.e.get_size (eval at append_javascript (outputarea.js:761), <anonymous>:251:119878)
    at Object.r.update_panel_constraints (eval at append_javascript (outputarea.js:761), <anonymous>:251:32200)
    at t.update_constraints (eval at append_javascript (outputarea.js:761), <anonymous>:251:355082)
```

Maybe Datashader is returning something surprising in this case, not well handled by HoloViews or Bokeh?

**Comment by jbednar** [comment]
Note that the same problems occur without `tiles *` and with `dynamic=False`, so it's not an issue with overlays or DynamicMaps.

**Comment by jbednar** [comment]
It may be a problem with the colorbar, as it works fine when I set colorbar=False earlier in the notebook:
![image](https://user-images.githubusercontent.com/1695496/43976238-948835b8-9ca5-11e8-9332-5f691a465781.png)

**Comment by jbednar** [comment]
I tried reproducing with bokeh alone by hacking https://bokeh.pydata.org/en/latest/docs/user_guide/examples/plotting_color_bars.html to return a constant value of 12, but then I just get a colorbar with no labels, not a missing plot:
![image](https://user-images.githubusercontent.com/1695496/43976613-d5111cc0-9ca6-11e8-8e98-6bef741da5c6.png)
```
import numpy as np

from bokeh.plotting import figure, output_file, show
from bokeh.models import LogColorMapper, LogTicker, ColorBar

output_file('color_bar.html')

def normal2d(X, Y, sigx=1.0, sigy=1.0, mux=0.0, muy=0.0):
    z = (X-mux)**2 / sigx**2 + (Y-muy)**2 / sigy**2
    return 12 + 0 * np.exp(-z/2) / (2 * np.pi * sigx * sigy)

X, Y = np.mgrid[-3:3:100j, -2:2:100j]
Z = normal2d(X, Y, 0.1, 0.2, 1.0, 1.0) + 0.1*normal2d(X, Y, 1.0, 1.0)
image = Z

color_mapper = LogColorMapper(palette="Viridis256")

plot = figure(x_range=(0,1), y_range=(0,1), toolbar_location=None)
plot.image(image=[image], color_mapper=color_mapper,
           dh=[1.0], dw=[1.0], x=[0], y=[0])

color_bar = ColorBar(color_mapper=color_mapper, ticker=LogTicker(),
                     label_standoff=12, border_line_color=None, location=(0,0))

plot.add_layout(color_bar, 'right')

show(plot)
```

**Comment by philippjfr** [comment]
Might be fixed by:

https://github.com/ioam/holoviews/pull/2869

**Comment by jbednar** [comment]
Thanks, but it doesn't seem to be affected by using that branch, and that branch appears to be about regrid, while this issue is for aggregate.

**Comment by philippjfr** [comment]
Looks like this now:

![Screen Shot 2020-06-08 at 3 34 56 PM](https://user-images.githubusercontent.com/1550771/84036547-a0259a80-a99d-11ea-899b-af98c0e94c77.png)
