### ISSUE TITLE
Accidentally using numpy.int32 for indexing on 64-bit windows?

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviews#2949]
I think that anywhere python's int or np.int_ is used as a dtype, that means on windows it'll end up as np.int32. numpy's default int type is C long (https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html), which on windows is 4 bytes. If using np.int_ for indexing, at best this will unnecessarily restrict the sizes of stuff on windows (e.g. getting 'array size too large' or whatever), but could also lead to garbage results.

There was a concrete example in #2895, which has now been fixed, but ideally we should check for other places this might occur (and if no other such places, this issue can be closed).

**Comment by jbednar** [comment]
Is there some way we could systematically search for such locations?

**Comment by ceball** [comment]
I guess starting with uses of numpy's product() would cover some (its behavior seems a bit surprising, at least to me - see example in https://github.com/ioam/holoviews/issues/2895#issuecomment-409180560).

**Comment by philippjfr** [comment]
I'll close, issues should be opened for specific cases where we identify this as an issue.
