### ISSUE TITLE
Gif support for Bokeh HoloMaps

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#2956]
If I do `%%output filename="tmp" holomap='gif', it works with the Matplotlib backend, but with a Bokeh backend I get `Format 'gif' does not appear to be supported`.  It seems like Bokeh should now be supportable, now that Bokeh provides PNG output?

Note that #2460 proposes to remove the ImageMagick gif creation that would be one way to implement this, but presumably the pillow-based support used with Matplotlib would also work here?

**Comment by philippjfr** [comment]
Yes, but without a persistent selenium session running that will be unusably slow which is why it was not implemented immediately. So it's definitely possible but probably not useful until we have a way of reusing a selenium session.

**Comment by jbednar** [comment]
Unusably slow compared to what?  Right now the alternative, which I am watching someone do right now, is to export every figure to disk one frame at a time, then manually patch in a gif. Surely it can't be slower than that?  So I don't see why not to simply do it and then worry later about reusing a session.
