### ISSUE TITLE
Groupby time, overlay, and its trying to find pd.Timestamp instead of np.datetime64

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#2999]
![image](https://user-images.githubusercontent.com/15331990/45572472-32772980-b81e-11e8-98e5-d9dc6e514df0.png)

![image](https://user-images.githubusercontent.com/15331990/45572481-37d47400-b81e-11e8-8e01-99c3a8014c13.png)

**Comment by ahuang11** [comment]
A work around this is to build a holomap manually and convert time to pd.Timestamp

hv.HoloMap({(pd.Timestamp(time), var): hv.Curve(...)})

**Comment by ahuang11** [comment]
Reproducible example
```
import xarray as xr
import pandas as pd

ds = xr.Dataset()

ds.coords['member'] = [0, 1, 2, 3]
ds.coords['time'] =  pd.date_range('2017-01-01', '2017-01-04') # [pd.datetime(2017, 1, 1), pd.datetime(2017, 1, 1), pd.datetime(2017, 1, 2), pd.datetime(2017, 1, 2)]

ds['temp'] = (('member', 'time'), np.random.rand(4, 4))
ds['prcp'] = (('member', 'time'), np.random.rand(4, 4))

import hvplot.pandas
import holoviews as hv

hv.HoloMap({(var, time): ds[var].sel(time=time).to_dataframe().hvplot() for time in ds['time'].values for var in ds.data_vars}, kdims=['var', 'time']).overlay('var')
```

**Comment by philippjfr** [comment]
Thanks that helps, I can reproduce several issues here, some in holoviews and some in hvplot.

**Comment by ahuang11** [comment]
Really glad that helps :)

**Comment by philippjfr** [comment]
Appears to be fixed, please reopen if issues persist.
