### ISSUE TITLE
Layout of DynamicMaps won't render with too many frames

### ISSUE THREAD

**Issue by nbren12** [holoviz/holoviews#3008]
I am opening this issue following a brief discussion on the gitter channel.

When I try to make a layout of DynamicMaps, which I create using`hv.Dataset` and xarray I get an error when I try to render: `[Total item frames exceeds max_frames on OutputSettings (500)]`.

This happens even when I can plot each DynamicMap object individually. 

Here is a small working example:
https://gist.github.com/8b6f08c37419d2490ea3c8b476253d5f

@philippjfr

**Comment by philippjfr** [comment]
Thanks @nbren12, the offending code is here:

https://github.com/ioam/holoviews/blob/master/holoviews/ipython/display_hooks.py#L210

This code is highly problematic anyway because expanding all the DynamicMap keys is extremely inefficient in any case. This is fairly high priority.

**Comment by nbren12** [comment]
No problem! Is there any downside to disabling that check if all the elements of the layout are DynamicMaps or simple elements?

**Comment by philippjfr** [comment]
This was fixed a while back.
