### ISSUE TITLE
Cannot display Holoviews datashade secondary y-axis for second Curve

### ISSUE THREAD

**Issue by alkestream** [holoviz/holoviews#3011]
I am really pleased  to try using Bokeh server + Holoviews and its datashade operation because this a very powerful tool !
This is a great work, well done !
I need to serve my Holoviews plots on the Bokeh server using doc=renderer.server_doc(datashaded). Another constraint I have is to use datashade operation of Holoviews because I a starting from a large dataframe (7 milions (datetime, float64)) from a parquet resource 
I am able to serve and display one timeserie signal curve and then add on the left another chart/figure to display another timeserie signal curve with its own independent y-axis and well-scaled range 
curve = hv.Curve((df['time'], df['convValue'].astype('float64')), kdims=['DateTime'], vdims=['Measurement'], label='Weight & Depth')
curve2 = hv.Curve((df['time'], df['convValue2'].astype('float64')), kdims=['DateTime'], vdims=['Measurement'], label='Weight & Depth')

curve_plot_opts = {'RGB': dict(width=1200, height=600, show_grid=True, axiswise=True)}
datashaded = datashade(curve, cmap=["blue"], y_range=(-150,200)).opts(plot=curve_plot_opts) + datashade(curve2, cmap=["red"]).opts(norm=dict(axiswise=True), plot=dict(show_grid=True))

Previously I set the following options but I do not know if it is over or wrongly configured :
options = hv.Store.options(backend='bokeh')
options.Curve = hv.Options('plot', show_frame=False, labelled=[], tools=['hover'], height=900, width=900, show_legend=True)
options.Curve = hv.Options('style', color=hv.Cycle(values=color_sequence), line_width=2)
options.Curve = hv.Options('RGB', shared_axes=False, axiswise=True, framewise=True)

But when I am trying to plot the two curves on the same chart/figure with on the left the y-axis well-ranged of the first curve and on the right the y-axis with a different range adapted for the second curve.
On the attached figure you can see the so small blue curve but it is scaled on the range of the red signal therefore you cannot efficiently visualize the leverage of one with the second one.
And at the end I would like to add an overlay legend for each of the two curves, but it is clearly not a priority.

Could you help me please ? Because I am not sure at all I am on the right way.

![capture6](https://user-images.githubusercontent.com/43272077/45922164-e6368400-bec4-11e8-88ea-38015a1fb235.PNG)

**Comment by jbednar** [comment]
It sounds like you want twin axes for y?  That's not directly supported by HoloViews, but there's an example of implementing it at: https://github.com/ioam/holoviews/issues/396#issuecomment-392832894

**Comment by alkestream** [comment]
Thanks James for quick answer but the issue you are pointing on does not set a second curve with its own fitted y-axis and does not use the datashade operation. Moreover using the display trough bokeh server directly via python script (no jupyter notebook,), has an impact.
I tried this hook to add a secondary y-axis and apply a formatter that loads a secondary signal timesrie but it is so long to load this second curve though the two curves have already been loaded in the following instructions : 
curve = hv.Curve((df['time'], df['convValue'].astype('float64'))...
curve2 = hv.Curve((df['time'], df['convValue2'].astype('float64'))...
...
datashaded = datashade(curve, cmap=["blue"], y_range=(-150,200)).opts(plot=curve_plot_opts) + datashade(curve2, cmap=["red"]).opts(norm=dict(axiswise=True), plot=dict(show_grid=True))

And furthermore, after everything loaded including the apply_formatter hook, a last repaint instruction is triggered and the final chart/figure is reloaded to display what you can see on the attached figure above.
Do you thiink what I want to achieve can be done without any finalize_hook ?
Or if using a hook is mandatory for a second axis for a second curve, how may I get it naturally without reloading all the curve2 data (7 milions points).

**Comment by TylerTCF** [comment]
I believe the secondary axis doesn't work with the bokeh server now per #396.  It works for matplotlib, but not bokeh.  If you use matplotlib, I've been getting errors when trying to overlay a line on a Bar chart with twin axes.

**Comment by alkestream** [comment]
Thanks TylerTCF to notice as me this is not working with Bokeh.
I need to use bokeh and not matplotlib as everything has been coded for it.
It would be good if a specialist could fix this in a next release.
