### ISSUE TITLE
Doc strings error?

### ISSUE THREAD

**Issue by ericmjl** [holoviz/holoviews#3046]
Hello Holoviews team,

I'm not sure if this is an error or not, but I thought I saw an inconsistency in the docstrings for `hv.Path`.

<img width="800" alt="screen shot 2018-10-04 at 11 45 15 am" src="https://user-images.githubusercontent.com/2631566/46486184-379b1900-c7cb-11e8-8350-59c0cd4f860d.png">

Is the doc-string supposed to refer to "Path" instead of "Image"?

**Comment by philippjfr** [comment]
Thanks, definitely not and a good catch. I suspect we have to do a major audit and rewrite of a ton of docstrings.

**Comment by philippjfr** [comment]
Appears to have been fixed, now refers to a "geometry", which is accurate.
