### ISSUE TITLE
Use full descriptive label for Histogram frequency axis

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#3093]
A histogram doesn't seem to be respecting the descriptive label for a dimension, using the column name instead:

```
data = hv.Dataset(df, [('cenlon', 'Longitude'), ('cenlat', 'Latitude')],
                     [('tstar_avg_prcp', 'Annual Precipitation (mm/yr)')])
data.hist('tstar_avg_temp_prcp')
```

![image](https://user-images.githubusercontent.com/1695496/47237387-7f619900-d3a4-11e8-8849-301c45128846.png)

I think it should be using the full name, not the column name.

**Comment by philippjfr** [comment]
Now labels the axis with frequency.
