### ISSUE TITLE
Support for bokeh BoxAnnotations

### ISSUE THREAD

**Issue by gregmuellegger** [holoviz/holoviews#3112]
In many cases it makes sense to highlight particular value ranges in a plot by tinting the background for parts of a dimension (say for all values `x<5`). In Bokeh this can be achieved with the `BoxAnnotation`, and using that in holoviews currently looks like:

```python
import holoviews as hv
from bokeh.models import BoxAnnotation

def add_box(plot, element):
    high_box = BoxAnnotation(right=5, fill_alpha=0.1, fill_color='red')
    plot.state.add_layout(high_box)

hv.Points(range(11)).options(finalize_hooks=[add_box])
```
![image](https://user-images.githubusercontent.com/88278/47653732-839e6b00-db89-11e8-8f05-211c9b6f18cf.png)

A native support by holoviews would be helpful. Other annotations like Arrows are already supported: http://holoviews.org/reference/elements/bokeh/Arrow.html

**Comment by philippjfr** [comment]
`VSpan` and `HSpan` were added in 1.13.0.
