### ISSUE TITLE
Add Travis tests for core environment

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#3179]
Currently travis installs all our optional dependencies to run the maximal number of tests. I notice that when you have a *minimal* environment, there are lots of test errors/failures (even using `-a '!optional'`). We should fix these, using `SkipTest` for the tests that cannot be run due to missing dependencies and have this minimal environment tested on travis.

**Comment by philippjfr** [comment]
There is a cron job which runs a minimal dependency set of tests.
