### ISSUE TITLE
issue with rasterize on this simple example?

### ISSUE THREAD

**Issue by rsignell-usgs** [holoviz/holoviews#3184]
Strange behaviour here: 
![2018-11-19_9-07-27](https://user-images.githubusercontent.com/1872600/48711964-94675d00-ebda-11e8-97af-ec1248df3db0.png)

Reproducible notebook here: 
https://nbviewer.jupyter.org/gist/rsignell-usgs/cbbc15c75b91fd83eabeed2a6c04f80a

**Comment by philippjfr** [comment]
Thanks for filing this, this has been fixed since.
