### ISSUE TITLE
Hover tool on hv.Area

### ISSUE THREAD

**Issue by wabu** [holoviz/holoviews#3187]
The hover tool on an Area chart does not show any information for me. Here's a small example:

```pythonimport numpy as np
import numpy as np
import holoviews as hv
hv.extension('bokeh')

# create some example data
python=np.array([2, 3, 7, 5, 26, 221, 44, 233, 254, 265, 266, 267, 120, 111])
pypy=np.array([12, 33, 47, 15, 126, 121, 144, 233, 254, 225, 226, 267, 110, 130])
jython=np.array([22, 43, 10, 25, 26, 101, 114, 203, 194, 215, 201, 227, 139, 160])

dims = dict(kdims='time', vdims='memory')
python = hv.Area(python, label='python', **dims)
pypy   = hv.Area(pypy,   label='pypy',   **dims)
jython = hv.Area(jython, label='jython', **dims)

overlay = (python * pypy * jython).options('Area', fill_alpha=0.5, tools=['hover'])
overlay.relabel("Area Chart") + hv.Area.stack(overlay).relabel("Stacked Area Chart")
```

I would except the hover information to show up either on any location inside the area with the nearest x value and respective y value, or at least show up when hovering the borderline of an area.

bokeh: 1.0.0rc4
holoviews: 1.11.0a10

**Comment by SandervandenOord** [comment]
There's 3 separate SO questions about adding hover to Area plot:
https://stackoverflow.com/questions/52954885/holoviews-bokeh-area-plot-add-hovertool-to-area-plot
https://stackoverflow.com/questions/55365897/how-to-change-color-of-area-plot-with-hover-tool-bokeh-or-holoviews
https://stackoverflow.com/questions/56546878/hover-tooltip-with-stacked-area-chart-in-holoviews

**Comment by whfreelove** [comment]
None of those SO questions have useful answers.

The only one that's close just points back to this Issue.

**Comment by SandervandenOord** [comment]
I agree @whfreelove . I added them to this issue to point out that multiple users have this problem or would like to have this feature. Can you add an example your workaround for other users to use?

**Comment by philippjfr** [comment]
I think we should just use that workaround internally as well and replot the data as a line.

**Comment by jbednar** [comment]
But won't that fail to hover when the pointer is over the bulk of the area (not the border)?

**Comment by philippjfr** [comment]
Sure but it's better than nothing. Bokeh won't support pointwise hover on polygons

**Comment by whfreelove** [comment]
@SandervandenOord sorry for getting your intent wrong!

```python
tooltips_logs = [
  ('Time', '@time{%H:%M:%S.%3N}'),
  ('Value', '@measurement{0,0}'),
  ('Target', '@target{0,0}')
]
formatters_logs = {
    'time': 'datetime'
}
hover_logs = HoverTool(tooltips=tooltips_logs, formatters=formatters_logs, mode='vline')

hv_log_area = hv.Area(data, 'time', ['measurement', 'target'])
hv_log_curve = hv.Curve(data, 'time', ['measurement', 'target']).opts(tools=[hover_logs])
```

Where `data` is a Pandas Dataframe containing at least those three columns. For context, these are some logs with timestamps, measured values, and intended target value.

In the HoverTool setup, `mode='vline'` gets you the behavior of showing the tooltip while in the area. It doesn't quite work when zoomed in, however, since the Curve hover tooltip only shows when the matching segment of line on the same `x` is visible.

**Comment by jlstevens** [comment]
I will close this issue in favor of discussion on the more recent issue on this topic referenced above (https://github.com/holoviz/holoviews/issues/5375). Please feel free to weigh in with your thoughts there!
