### ISSUE TITLE
Datetime Groupbys to Overlay hover does not format time

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#3264]
dts = pd.date_range('2017-01-01', '2017-02-01')
tzt = pd.DataFrame({'groupby': dts + pd.Timedelta(days=1), 'y': range(len(dts))}, index=dts)
tzt.hvplot.scatter('index', 'y', groupby='groupby').overlay()

![image](https://user-images.githubusercontent.com/15331990/49678824-ed891a80-fa3b-11e8-9083-ca71d3d91ca3.png)

**Comment by philippjfr** [comment]
Appears to have been fixed.
