### ISSUE TITLE
Auto decide the best range for each subplot

### ISSUE THREAD

**Issue by dclong** [holoviz/holoviews#3406]
When layout multiple plots together the x/y ranges are decided by the first subplot, which might not be a good range to use for other subplots. Is it possible (at least have an option) to decide the best range for each plot?

**Comment by philippjfr** [comment]
Yes, you can set ``axiswise=True`` on each subplot, but I think ``shared_axes=False`` should also disable normalization so I'll mark this as a bug.

**Comment by philippjfr** [comment]
This was fixed.
