### ISSUE TITLE
Consider simplified Graph constructor(s)

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#3424]
In the [network graphs tutorial](http://pyviz.org/tutorial/06_Network_Graphs.html) the first example of such a graph (described as 'simple') is:

```python
simple_graph = hv.Graph(((source, target),))
```

It is a little confusing to see a 1-tuple of a tuple as the constructor for the simplest example. Of course this isn't arbitrary but a consequence of our past decisions on how to express network graphs in general. That said, we might consider that:

1. This is presented as the simplest case.
2. Perhaps this means this is a common case and worth supporting as a special constructor?

This would be worthwhile only if we think such a constructor would simply common usage without being too confusing in the context of more complex examples.

**Comment by philippjfr** [comment]
I don't see a concrete proposal to improve this and this has served us well in practice so far.
