### ISSUE TITLE
Consider easier ways of defining operations

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#3431]
In [Transforming data](http://holoviews.org/user_guide/Transforming_Elements.html) the only way given to define a custom operation is to build a parameterized function by defining a class.

It might be nice to have something analogous  to `Stream.define` to avoid needing a class in the simple case. Something like:

```
def residual_fn(element, key=None, label='Residual'):
    ...
    return transformed_element

residual = Operation.define(residual_fn)
```

This is also analogous in that the keywords (other than `key` ) could be automatically promoted to the parameters of the parameterized function according to type. The start of the signature is what you need for defining the `_process` method normally.

This is just one proposal for simplifying things, I'm sure there are others.

**Comment by philippjfr** [comment]
We now have the ability to apply simple functions so I see little value here. Please reopen if you still think **strongly** believe this is a good idea (I don't and am -1 on this).
