### ISSUE TITLE
Documentation working with stream data, display broken

### ISSUE THREAD

**Issue by xavArtley** [holoviz/holoviews#3489]
Hello,

in http://holoviews.org/user_guide/Streaming_Data.html

All figures seems to have a problem :
![image](https://user-images.githubusercontent.com/18531147/52633587-35f20800-2ec5-11e9-9cc7-16371b5c367a.png)
![image](https://user-images.githubusercontent.com/18531147/52633602-3d191600-2ec5-11e9-95b6-ccedd89879cd.png)

Chrome : Version 72.0.3626.96 (Build officiel) (64 bits)

**Comment by philippjfr** [comment]
That notebook shouldn't be run since we embed the output as gifs. All plots are initialized as empty and then populate as the data streams in but on the website no data ever arrives so they are empty.

**Comment by philippjfr** [comment]
Seems to have been fixed a long time ago.
