### ISSUE TITLE
Add a Multi-Segments element

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#3498]
In recent versions of datashader there are much more efficient means of drawing fixed length segments, however we have to way of representing that data in HoloViews. I therefore propose we add a ``Segments`` element where the x-/y- coordinates are stored as key dimensions. This can also be used to render a TriMesh wireframe (indeed internally the `trimesh_rasterize` operation already does this). Once added I'd therefore create a public property on TriMesh which makes the wireframe available as a Segments element.

**Comment by poplarShift** [comment]
+1!

You mean something like Bokeh's segment, so `kdims=['x0', 'x1', 'y0', 'y1']`?

**Comment by philippjfr** [comment]
I haven't started yet no, we were thinking of a slight generalization of ``kdims=['x0', 'x1', 'y0', 'y1']`` which would allow multiple vertices per row, i.e. ``kdims=['x0', 'x1', 'x2', ..., 'y0', 'y1', 'y2', ...]``. That does stretch the definition of segment a bit, so maybe a different name would be more appropriate.

**Comment by philippjfr** [comment]
Also should decide whether alternating (``['x0', 'y0', 'x1', ...]``) or consecutive (``['x0', 'x1', 'y0', ...]``) x/y dimensions are more intuitive.

**Comment by poplarShift** [comment]
In that case I'd prefer alternating - it would be easier to modify the number of nodes, just clipping/pasting in one place instead of at least two per node.

**Comment by philippjfr** [comment]
Segments were added.
