### ISSUE TITLE
Improve default node padding on Sankey

### ISSUE THREAD

**Issue by quantumdot** [holoviz/holoviews#3501]
Generating a Sankey diagram with many nodes results in a plot with many overlaps of nodes and crisscrossing of edges. It's nearly impossible to interpret the data with so many overlapping nodes and crisscrossing edges. 

Example:
```
sankey = hv.Sankey(data, kdims=['source', 'target'], vdims='value') \
               .opts(width=1000, height=700, label_position='left', edge_color='target', node_color='index', cmap='tab20')
```
Produces the following plot:
![bokeh_plot 2](https://user-images.githubusercontent.com/8483606/52969710-47cd2280-337f-11e9-8605-96d8a2da1a54.png)

Where data looks like:
source | target | type | value
-- | -- | -- | --
B45 | C0 | 2 | 339
B45 | C6 | 2 | 318
B45 | C78 | 2 | 185
B45 | C52 | 2 | 179
B45 | C67 | 2 | 158
B45 | C92 | 2 | 144
B60 | C71 | 2 | 131
B45 | C65 | 2 | 122
B45 | C13 | 2 | 121
B49 | C71 | 2 | 107
B45 | C93 | 2 | 86
B45 | C9 | 2 | 83
B14 | C92 | 2 | 82
B60 | C69 | 2 | 82
B78 | C93 | 2 | 81
B30 | C91 | 2 | 75
B92 | C9 | 2 | 74
B45 | C83 | 2 | 73
B49 | C41 | 2 | 73
B80 | C45 | 2 | 73
B45 | C71 | 2 | 70
B38 | C45 | 2 | 65
B13 | C71 | 2 | 62
B45 | C60 | 2 | 61
B60 | C93 | 2 | 55
B60 | C99 | 2 | 55
B49 | C33 | 2 | 53
B45 | C34 | 2 | 52
B83 | C56 | 2 | 52
B92 | C6 | 2 | 51
... | ... | ... | ...
A5 | B77 | 1 | 48
A5 | B17 | 1 | 45
A5 | B9 | 1 | 40
A5 | B37 | 1 | 38
A5 | B68 | 1 | 38
A5 | B84 | 1 | 35
A5 | B56 | 1 | 31
A5 | B59 | 1 | 31
A5 | B74 | 1 | 30
A5 | B25 | 1 | 28
A5 | B11 | 1 | 21
A5 | B34 | 1 | 20
A5 | B61 | 1 | 20
A5 | B98 | 1 | 19
A5 | B12 | 1 | 15
A5 | B6 | 1 | 15
A5 | B33 | 1 | 14
A5 | B19 | 1 | 13
A5 | B23 | 1 | 9
A5 | B46 | 1 | 9
A5 | B44 | 1 | 7
A5 | B36 | 1 | 6
A5 | B70 | 1 | 6
A5 | B42 | 1 | 5
A5 | B53 | 1 | 3
A5 | B26 | 1 | 2
A5 | B3 | 1 | 2
A5 | B8 | 1 | 2
A5 | B15 | 1 | 1
A5 | B16 | 1 | 1

997 rows × 4 columns

**Comment by jbednar** [comment]
Are you asking for things to be sorted automatically to reduce such overlap, or to respect the order you've given things (where you reduced overlap manually), or...?

**Comment by quantumdot** [comment]
I suppose that I would expect the plot to automatically sort the nodes and edges to minimize crossing and overlaps. (although sorting the data manually seems to not change the final layout). The crisscrossing of the edges is lower priority, while the fact that the nodes themselves overlap is a major issue. For example, in the image in the OP note the large (blue-ish?) band coming from node `A5` on the left, it is impossible to tell the destination node (prefixed with `B` in the center "column").

I can't seem to find documentation on how to affect the layout meaningfully, and the default output seems non-optimal.

**Comment by philippjfr** [comment]
The Sankey layout algorithm minimizes the overlap of the edges by default, but there's only so much it can do automatically so I don't know if that can be improved much. You are right that the overlap of the nodes seems like a major issue and I thin if that's occurring that's a bug. I've always wondered whether a Sankey is useful beyond a few dozen nodes and my conclusion is that it probably isn't.

**Comment by quantumdot** [comment]
Regarding minimization of edge overlaps, it could be true that the edges traversing from the second column of nodes to the third column is minimized, however, edges traversing from the first column of nodes to the second column almost appears to be maximized. Note that edges on the bottom of column one on average traverse to the top of column two, and the opposite for those at the top of column one.

**Comment by jbednar** [comment]
Right -- it does seem like the layout of the second column of edges is highly non-optimal, and could easily be reordered to reduce crossing in that stage, though I wouldn't know where to start on trying to improve that.

**Comment by quantumdot** [comment]
I made a comparison, using the same data, between the sankey plot produced by holoviews with bokeh back-end and one produced using [ipysankeywidget ](https://github.com/ricklupton/ipysankeywidget) (based on [d3-sankey-diagram](https://github.com/ricklupton/d3-sankey-diagram)). Supposedly, holoviews Sankey is based on/ported from d3-sankey-diagram per #1123 (I think the faces in that thread will look familiar).

I know that I am asking a lot from the layout algorithm with the data that I am supplying, but I feel that the layout generated from ipysankeywidget looks much clearer, and allows at least some interpretation.

## Holoviews:
```
import holoviews as hv
hv.extension('bokeh')

sankey = hv.Sankey(data, kdims=['source', 'target'], vdims='value') \
           .opts(width=1000, height=700, label_position='left', edge_color='target', 
                 node_color='index', cmap='tab20')
```
![image](https://user-images.githubusercontent.com/8483606/53047178-e0d36a80-345f-11e9-9040-4dfdcc43b0e0.png)

## ipysankeywidget:
```
from ipysankeywidget import SankeyWidget
from ipywidgets import Layout

layout = Layout(width="1000", height="900")
w = SankeyWidget(links=data.to_dict('records'),
                 align_link_types=True, 
                 layout=layout, 
                 linkLabelFormat='.1f'
                )
```
![image](https://user-images.githubusercontent.com/8483606/53047204-ef218680-345f-11e9-94fb-a41ab5a59ce6.png)

**Comment by jbednar** [comment]
That's very interesting, thanks!  The first stage is obviously much easier to track in the ipysankeywidget version. The second stage is a bit crazy in both, but on balance I think it's also better in the ipysankeywidget version.  I wonder what the difference in implementation is...

**Comment by philippjfr** [comment]
Seems like the holoviews version has a lot of node padding which ends up taking up a lot of space, what happens when you use ``hv.Sankey(...).opts(node_padding=2)`` (the default is 10)?

**Comment by philippjfr** [comment]
For example here is some synthetic data

#### node_padding=10

![screen shot 2019-02-21 at 3 49 28 am](https://user-images.githubusercontent.com/1550771/53142437-c1396080-358b-11e9-8b0c-284360699253.png)

#### node_padding=2

![screen shot 2019-02-21 at 3 49 14 am](https://user-images.githubusercontent.com/1550771/53142441-c72f4180-358b-11e9-82ce-04465eeb2406.png)

**Comment by quantumdot** [comment]
Yes, looks better with `node_padding` < ~5. Thanks for the suggestion.

**Comment by mangecoeur** [comment]
In addition to node padding, it seems d3-sankey also supports an explicit node-sort option, is that also supported in Holoviews (can't find anything in the docs)?

**Comment by bpoti** [comment]
with node padding, can we also set order of nodes for Sankey plot

**Comment by philippjfr** [comment]
>In addition to node padding, it seems d3-sankey also supports an explicit node-sort option, is that also supported in Holoviews (can't find anything in the docs)?

Not currently I don't think but when I next have a look at this I'll implement it. Otherwise if someone else wants to take a look, [the code](https://github.com/pyviz/holoviews/blob/master/holoviews/element/sankey.py#L17) is pretty much a straight port of a now outdated version of d3-sankey so exposing the sort function should be reasonably straightforward.

**Comment by odoublewen** [comment]
I also had this question.  Seems like [the code example in the Holoviews docs](http://holoviews.org/reference/elements/bokeh/Sankey.html) also offers an example of non-optimal behavior, in that nodes overlap unnecessarily with edges.  I would expect the method to try to minimize not just node-node overlap but also node-edge overlap.

For example, why is the "Early Career Researcher" node superimposed on top of the edge that connects "PhD" and "Career Outside Science"?  
![bokeh_plot](https://user-images.githubusercontent.com/1421445/57672091-7b5cc900-75cb-11e9-9f7b-1e54bd1c46f5.png)

Here's an even simpler example:

```python
nodes = ["node0","node1","node3", "node4", "node5"]
nodes = hv.Dataset(enumerate(nodes), 'index', 'label')
edges = [(0,1, 100),
         (1,2, 90),
        (1,3, 10),
        (3,4,10)]
reads = hv.Sankey((edges, nodes), ['From', 'To'])
reads.opts(opts.Sankey(labels='label', node_padding=10, label_position='right', width=900, height=300, cmap='Set1',
            edge_color=dim('To').str(), node_color=dim('index').str()))
```

Why does node4 have to be plotted inside of the edge connecting node3 and node5?

![bokeh_plot (1)](https://user-images.githubusercontent.com/1421445/57672960-27ec7a00-75cf-11e9-9813-7202a9f4c102.png)

**Comment by wazcodez** [comment]
I'm facing a similar issue as @odoublewen's second example. I have hit a roadblock here - any recommendations on how to solve this?

**Comment by philippjfr** [comment]
Please reopen the request to expose the sorting function as a new issue.
