### ISSUE TITLE
Update Sankey algorithm to match latest d3-sankey

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#3548]
Michael Bostock has made some major improvements to the overlap avoidance algorithms in d3-sankey over the last week. Since the code in holoviews is a fairly straightforward Python port of that code it should be reasonably straightforward to update our code to match. [Here](https://github.com/d3/d3-sankey/compare/v0.7.1...master)'s a link to the diff for all the updates.

**Comment by Yura52** [comment]
I'd like to work on this. Are there any good examples where the improvements after the update can be observed?

**Comment by Yura52** [comment]
@philippjfr @jbednar 

Hi! I am almost done with the implementation, just want to double check if there is still interest in it.

**Comment by philippjfr** [comment]
@Yura52 Amazing! We are definitely still interested. Would love to see a PR.

**Comment by Yura52** [comment]
Sorry for the delay. The implementation is finished. However, I [cannot find data](https://github.com/holoviz/holoviews/issues/3548#issuecomment-718082283) where improvements can be observed. Do you have any examples?

The screenshot is based on [this](https://holoviews.org/gallery/demos/bokeh/energy_sankey.html#demos-bokeh-gallery-energy-sankey) example. 1.13.5. on the left, my implementation on the right. The first row shows [nodes](https://github.com/holoviz/holoviews/blob/a684a09bfab538e798351dd21db941903833fb77/holoviews/element/sankey.py#L66), the second row shows [edges](https://github.com/holoviz/holoviews/blob/a684a09bfab538e798351dd21db941903833fb77/holoviews/element/sankey.py#L67). The "problem" is that the final sankey plot is absolutely the same in both cases and looks like in the gallery example.
<img width="799" alt="Screenshot 2020-11-17 at 23 23 18" src="https://user-images.githubusercontent.com/8861742/99445307-6da9a180-292e-11eb-87ac-a0d8cac9944b.png">

**Comment by Yura52** [comment]
@philippjfr I _can_ create a PR, but I would prefer to make sure that the results I see are expected. Any additional infomation will be helpful.

**Comment by philippjfr** [comment]
Sorry for not getting back to you before. I'd say open the PR and then I can play around with it and give feedback.

**Comment by jnettels** [comment]
Hello there, just an occasional user here. I was curious about the progress and saw the images in the PR.

As another user mentioned here https://github.com/holoviz/holoviews/issues/3501#issuecomment-492085153 the biggest issue with holoviews sankey currently seems to be how nodes are aligned towards the center, creating unnecessary overlap of edges and nodes.
I wonder if this PR is a chance to change this behaviour or (maybe instead) expose some parameters to control this behaviour.

Regards, and thanks for your work!

**Comment by Yura52** [comment]
@jnettels Hi! Have you seen the latest [PR update](https://github.com/holoviz/holoviews/pull/4707) ? What do you think of the (possibly) upcoming changes?

P.S. I would suggest leaving comments in that PR since it contains screenshots and some other information.
