### ISSUE TITLE
__mul__ and __add__ compatible with user classes

### ISSUE THREAD

**Issue by fuzznaut** [holoviz/holoviews#3577]
I have a custom class that holds the plot and extra data. I wanted to be able to keep using the holoviews operators in the same way with my class. 
I implemented both `__add__` and `__radd__` on my class, while `__add__` worked just fine, `__radd__` was never triggered because holoviews wasn't raising a `NotImplementedError` on the `__mul__` and `holoviews` shouldn't be expecting my class. Is it possible to add a check for unknown objects in the operators or that would break other parts of the code?

Here's the traceback I got when trying to do something like `hvplot * myclass`.

<details>
<summary>Traceback</summary>

```python
/usr/local/anaconda3/envs/pkg/lib/python3.6/site-packages/holoviews/core/overlay.py in __mul__(self, other)
     41             return NotImplemented
     42 
---> 43         return Overlay([self, other])
     44 
     45 

/usr/local/anaconda3/envs/pkg/lib/python3.6/site-packages/holoviews/core/overlay.py in __init__(self, items, group, label, **params)
    141         self.__dict__['_group'] = group
    142         self.__dict__['_label'] = label
--> 143         super(Overlay, self).__init__(items, **params)
    144 
    145     def __getitem__(self, key):

/usr/local/anaconda3/envs/pkg/lib/python3.6/site-packages/holoviews/core/dimension.py in __init__(self, items, identifier, parent, **kwargs)
   1475         params = {p: kwargs.pop(p) for p in list(self.params().keys())+['id', 'plot_id'] if p in kwargs}
   1476 
-> 1477         AttrTree.__init__(self, items, identifier, parent, **kwargs)
   1478         Dimensioned.__init__(self, self.data, **params)
   1479 

/usr/local/anaconda3/envs/pkg/lib/python3.6/site-packages/holoviews/core/tree.py in __init__(self, items, identifier, parent, dir_mode)
     67         items = list(items) if items else items
     68         items = [] if not items else items
---> 69         for path, item in items:
     70             self.set_path(path, item)
     71 

/usr/local/anaconda3/envs/pkg/lib/python3.6/site-packages/holoviews/core/element.py in __iter__(self)
     89     def __iter__(self):
     90         "Disable iterator interface."
---> 91         raise NotImplementedError('Iteration on Elements is not supported.')
     92 
     93 

NotImplementedError: Iteration on Elements is not supported.
```
</details>

**Comment by philippjfr** [comment]
Sorry I never replied, adding a check for other types of objects seems very reasonable.

**Comment by douglas-raillard-arm** [comment]
Holoviews should actually return NotImplemented rather than raising NotImplementedError in order to fall back on the reflected operation on the 2nd operand:
https://docs.python.org/3/library/constants.html#NotImplemented

I ran into the same issue while trying to wrap a holoviews plot such that it is displayed inside a panel:
https://discourse.holoviz.org/t/replace-holoviews-notebook-rendering-with-a-panel/2519/12
