### ISSUE TITLE
Figsize has no effect on matplotlib layout

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#3588]
`hv.Bars([0, 1, 2]).opts(fig_size=200) + hv.Bars([0, 5, 6]).opts(fig_size=200)`

**Comment by philippjfr** [comment]
Debating whether or not to consider this a bug, the ``fig_size`` is specifically about the figure as a whole not the subplots so currently it has to be set on the outermost object, i.e.

```python
(hv.Bars([0, 1, 2]) + hv.Bars([0, 5, 6])).opts(fig_size=200)
```
