### ISSUE TITLE
Cannot change the width of Table column

### ISSUE THREAD

**Issue by xtutran** [holoviz/holoviews#3613]
Hi,

I am trying to change the width of column and also the formatter of column. But it seems not to work as expected. Here is my code!

```
import holoviews as hv
from bokeh.models import HTMLTemplateFormatter

hv.extension('bokeh')

def apply_format(plot, element):
    plot.handles['table'].columns[0].width = 100
    plot.handles['table'].columns[0].formatter=HTMLTemplateFormatter(template='<a href="<%= value %>"><%= value %></a>')

gender = ['M','M', 'M','F']
age = [10,16,13,12]
weight = [15,18,16,10]
height = [0.8,0.6,0.7,0.8]
profile=['http://a.com', 'httmp://b.com', 'http://c.com', 'http://d.com']

table = hv.Table({'Gender':gender, 'Age':age, 'Weight':weight, 'Height':height, 'Profile': profile},
                 ['Profile', 'Gender', 'Age'],  ['Weight', 'Height'])
table.groupby('Gender').opts(height=140, width=700, hooks=[apply_format])
```

Anyone has the same issue or know how to do this properly?

Thanks,
Tran

**Comment by youngsaj** [comment]
In experimenting with this I found instead of
plot.handles['table'].columns[0].width = 0
set
plot.handles['table'].columns[0].width = 300  (I think the amount of pixel width of column)
Not sure if this is ideal...

**Comment by xtutran** [comment]
> In experimenting with this I found instead of
> plot.handles['table'].columns[0].width = 0
> set
> plot.handles['table'].columns[0].width = 300 (I think the amount of pixel width of column)
> Not sure if this is ideal...

Hi,

Thank you for your attention! I noticed that I put a wrong number of width. But it did not matter even if we change it to any number. That's something I still dont understand. You can try this piece of code and see what happen :)

Regards
Tran

**Comment by thoth291** [comment]
I added this `fit_columns=False` to the table creation - but it still doesn't work. Wonder why?

**Comment by suiluj** [comment]
@xtutran I am trying to change individual column widths aswell. Did you find a solution? I would be very interested. Thank you. :)

**Comment by suiluj** [comment]
I noticed that column width resizing did not work until i changed the default `autosize_mode`


```python
def apply_format(plot, element):
    # plot.handles['table'].index_position = None # hide index
    # plot.handles['table'].index_width = 100 # change index size
    plot.handles['table'].autosize_mode = "none"
    plot.handles['table'].columns[0].width = 60 
    plot.handles['table'].columns[1].width = 100
    plot.handles['table'].columns[2].width = 50
    plot.handles['table'].columns[3].width = 200
```

- More column width details here: [autosize_mode doc](https://docs.bokeh.org/en/latest/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.DataTable.autosize_mode)
- hide index info here: https://github.com/holoviz/holoviews/issues/3918#issuecomment-523865218

**Comment by xtutran** [comment]
> I noticed that column width resizing did not work until i changed the default `autosize_mode`
> 
> ```python
> def apply_format(plot, element):
>     # plot.handles['table'].index_position = None # hide index
>     # plot.handles['table'].index_width = 100 # change index size
>     plot.handles['table'].autosize_mode = "none"
>     plot.handles['table'].columns[0].width = 60 
>     plot.handles['table'].columns[1].width = 100
>     plot.handles['table'].columns[2].width = 50
>     plot.handles['table'].columns[3].width = 200
> ```
> 
> * More column width details here: [autosize_mode doc](https://docs.bokeh.org/en/latest/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.DataTable.autosize_mode)
> * hide index info here: [#3918 (comment)](https://github.com/holoviz/holoviews/issues/3918#issuecomment-523865218)

Ah nice! Sorry for late reply! I gave up on this for long time. I think disable `autosize_mode` makes lot of sense 👍

**Comment by suiluj** [comment]
@xtutran no problem. Do you still use the hv.Table somewhere. In case it helped you could close this issue then.

**Comment by suiluj** [comment]
I improved a few things for my custom column widths. Perhaps it helps someone in the future.

This way you can set the column width by column name and in case the column width is not custom definded give the other columns a default width:

```python
column_width = {
    "column_x": 120,
    "column_y": 200
}
column_default_width = 100

def apply_format(plot, element):
    for column in plot.handles['table'].columns:
        try:
            column.width = column_width[column.field]
        except:
            column.width = column_default_width

    plot.handles['table'].autosize_mode = "none"
```
