### ISSUE TITLE
Add `responsive` option for the Plotly backend

### ISSUE THREAD

**Issue by GdMacmillan** [holoviz/holoviews#3634]
Hi guys,

I was wondering if it would be possible to add the option responsively resize plots drawn in either a notebook or a browser tab. I'm using the plotly extension for the 3D plotting capability and I currently explicitly set the height and width aspect.

This is currently an option in plotly:
[https://plot.ly/javascript/responsive-fluid-layout/](https://plot.ly/javascript/responsive-fluid-layout/)

my plot object call looks like this, with the current call and what I want it to look like as a comment:

```
plot_obj = plot_obj.opts(width=1900, height=1000, aspect=aspect) 
# plot_obj.opts(responsive=True, aspect=aspect)
```

It displays in a browser tab using panel:

```
import panel as pn
pn.extension('plotly')
pane = pn.panel(plot_obj)

pane.servable()
server = pane.show(threaded=True, port=23764)
```

`type(plot_obj)`
holoviews.core.overlay.Overlay

**Comment by jbednar** [comment]
I've update the title to reflect that this is a Plotly-specific request, as we already have support for `responsive=True` in the Bokeh backend: https://github.com/pyviz/holoviews/blob/master/holoviews/plotting/bokeh/element.py#L106

Not sure how hard it is to enable that here, but it does seem like a good thing to ask for.
