### ISSUE TITLE
Spatially distributing NdOverlay elements

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#3654]
Over the years, I've noticed a certain pattern cropping up where you want to spatially distribute the elements of an `NdOverlay` along an axis. This axis then appears to be categorical with the keys mapping to the labels.

Here is one example from google image search relating to neural signals:

<img src="https://user-images.githubusercontent.com/890576/56769061-bbbbea80-6775-11e9-8d97-8a94b9b95106.png" width="50%"></img>

Here you have multiple traces spread out along the y-axis but overlapping in the same space (e.g where the green and cyan traces cross). Another example that illustrates this is the bokeh [ridgeplot example](https://bokeh.pydata.org/en/latest/docs/gallery/ridgeplot.html):

![image](https://user-images.githubusercontent.com/890576/56769184-0ccbde80-6776-11e9-9931-5356775ba55c.png)

The tall green distribution illustrates clearly that this is an overlay and not a layout type such as `NdLayout` or `GridSpace` (although the concept does share features with these container types).  In this situation, a bunch of separate axes along in the y-direction would not be particularly helpful.  In addition, using an `NdOverlay` would be useful here is you can return it from a `DynamicMap` and change the number of items shown easily (which you can't do with layout types).

I don't think this idea merits a new container type - instead I think this could be achieved with new plot options for `NdOverlay`. For instance you could make a key dimension of the `NdOverlay` to the y-axis by default then invert the axes to put the categorical values along the x-axis instead.

In the simplest case, a single dimension could be spread out equidistantly along the chosen axis but there could be lots of other features e.g 1) adjustable spacing between the components spread out spatially 2) custom or non-equal spacing 3) multiple keys mapped onto an axis for a hierarchical categorical axis.

When building this sort of plot 'manually', I've generally faked a categorical axis on a continuous axis by setting the key labels explicitly. A more solid and general (bokeh) implementation could use the categorical axis model instead. I'm not sure how this could be nicely generalized to the matplotlib or plotly backends though...

This idea could potentially be generalized to cover existing elements e.g [`BoxWhisker`](http://holoviews.org/reference/elements/bokeh/BoxWhisker.html#bokeh-gallery-boxwhisker) plots:

![image](https://user-images.githubusercontent.com/890576/56769511-05590500-6777-11e9-91b7-cf61a3856840.png)

Or [`Violin`](http://holoviews.org/reference/elements/bokeh/Violin.html#bokeh-gallery-violin) plots:

![image](https://user-images.githubusercontent.com/890576/56769588-405b3880-6777-11e9-8a07-d943060fea15.png)

Or even [`Bars`](http://holoviews.org/reference/elements/bokeh/Bars.html#bokeh-gallery-bars):

<img src="https://user-images.githubusercontent.com/890576/56769673-844e3d80-6777-11e9-9d04-ccba5b388d2a.png" width="50%"></img>

Obviously we can't refactor everything into a new system right away but it would be worth trying to see if there is a general concept here that subsumes some of these cases. For instance a legend would be used to disambiguate the dimensions of the `NdOverlay` not labelled and positioned spatially.

Two other thoughts we had when I discussed this proposal with @jbednar and @philippjfr is that 1) this may well be related to the notion of insets in some way 2) it is possible a bokeh model for a sub-coordinate system (or axis) would help with the implementation.

Issue https://github.com/pyviz/holoviews/pull/3385 is related and there are probably other related issues I haven't noticed yet. At this stage I think we should focus on discussion to see if this fits in neatly with the hierarchy of objects and containers we already have.

**Comment by jbednar** [comment]
Thanks, @jlstevens, I think this captures the outcome of our discussion very well.  @bryevdv may have comments on whether it makes sense for there to be some underlying "inset" coordinate system in Bokeh that we then use to provide this support, which would be the same as the main continuous axis but scaled and offset in some way.  The advantage of doing more of the work in Bokeh is that we can then naturally support hovering and other interactive features; the disadvantage is that this type of plot would be harder to port to the Matplotlib and Plotly backends.

**Comment by bryevdv** [comment]
I have wanted to afford subplots / anchoring plot frames at arbitrary canvas coordinates for some years: https://github.com/bokeh/bokeh/issues/3821 However, it's never been  prioritized. I will say having waited is probably good since after 1.1 will be a better foundation I think. I would love to help assist with this tho I'm not sure how much actual implementation I could do myself in the short term.

**Comment by jbednar** [comment]
Thanks, Bryan.  

@jlstevens , it seems important to distinguish between this offset-NdOverlay concept and the already-available [GridSpace](http://holoviews.org/reference/containers/bokeh/GridSpace.html) support in HoloViews.  Seems like GridSpace already supports plots like these:

![img](http://media.juiceanalytics.com/images/smallmultiples1.png)

![img](http://brunelvis.org/wp-content/uploads/2015/04/signature-songs.png)

Compared to these, I guess an offset NdOverlay differs in that (1) it's an overlay, i.e. items may and often do overlap, (2) only a single axis may be offset (if two, then it's definitely a GridSpace?), and (3) there's no way to draw the subaxes on each overlaid item (which might make an offset NdOverlay faster than a GridSpace?).

Note that people will often need to add a separate I-shaped or L-shaped legend if they don't have subaxes, and we'd eventually need to support that:

![image](https://user-images.githubusercontent.com/1695496/56775038-e3697d80-678a-11e9-9f98-13fd00fca300.png)

**Comment by droumis** [comment]
closed by https://github.com/holoviz/holoviews/pull/5840 and other subcoordinate_y and related 'subcoordinate_y' PRs
