### ISSUE TITLE
legend not working for grouped bar plot 

### ISSUE THREAD

**Issue by sophiamyang** [holoviz/holoviews#3710]
I am trying to do a grouped bar plot in hvplot. Both of the following won't work:
`df.hvplot.bar('size', ['Group A', 'Group B'], legend=True)` and `df.hvplot.bar('size', ['Group A', 'Group B']).opts(show_legend=True)`. @philippjfr said it is because it was hardcoded in holoviews:
`          if not (self.stacked or self.stack_index) and ds.ndims > 1:
            cmapping.pop('legend', None)
            mapping.pop('legend', None)`
It'd be really helpful if I can use legend in my grouped bar plot. Thanks!

**Comment by philippjfr** [comment]
This can now be controlled with the `multi_level` option.
