### ISSUE TITLE
Add possibility to plot as muted/invisible

### ISSUE THREAD

**Issue by hojo0590** [holoviz/holoviews#3730]
It would be cool to have the possibility to initialise parts of plots as muted, so to say that you have more possible information available on plotting but you're not being overwhelmed with it in the first moment. Something like a muted flag to be passed:

```
hv.Overlay([
    hv.Curve((np.arange(5)), label='increase') *
    hv.Curve((np.arange(5)*-1+5), label='decrease', muted=True)
])
```
I know there is the possibility in bokeh to set the visible attribute for lines [bokeh#6968](https://github.com/bokeh/bokeh/issues/6968#issuecomment-332519403) and I'm quite sure that this could already be achieved with the `hooks` functionality - though I can't and I'd be in favour of an easy option to pass that.

If this was already discussed somewhere around - my apologies I did not find anything helpful.

**Comment by philippjfr** [comment]
This should be very easy to add, we should consistently expose ``muted`` and ``visible`` properties on all elements. Just to be clear the spelling would be:

```python
hv.Overlay([
    hv.Curve((np.arange(5)), label='increase') *
    hv.Curve((np.arange(5)*-1+5), label='decrease').opts(muted=True)
])
```

**Comment by hojo0590** [comment]
> 
> 
> This should be very easy to add, we should consistently expose `muted` and `visible` properties on all elements. Just to be clear the spelling would be:
> 
> ```python
> hv.Overlay([
>     hv.Curve((np.arange(5)), label='increase') *
>     hv.Curve((np.arange(5)*-1+5), label='decrease').opts(muted=True)
> ])
> ```

Damn you're quick. If you see an useful feature therein I could absolutely live with that spelling.

**Comment by julioasotodv** [comment]
+1 for this exposure. It would help me to create a workaround for #4171

**Comment by philippjfr** [comment]
I'll add it to this milestone.
