### ISSUE TITLE
Holoviews not showing plots with plotly backend in vscode

### ISSUE THREAD

**Issue by alenucci** [holoviz/holoviews#3733]
As I said in the title, I'm using Visual Studio Code's interactive window and while bokeh's and matplotlib's backends work properly plotly doesn't.
![bug](https://user-images.githubusercontent.com/47231644/58383331-b4d30280-7fd5-11e9-97b5-2c1d876bb5da.png)

**Comment by jlstevens** [comment]
Thanks for reporting this. To be honest, I didn't really expect bokeh to work in vscode so it is good to hear that it does!

**Comment by alenucci** [comment]
Maybe it has something to do with this old issue with mime types (I don't know what those are) regarding the other two backends
#3353

**Comment by chanana** [comment]
have there been any updates on this? For more context, when I try [this example](https://holoviews.org/reference/elements/plotly/Scatter.html) I get nothing as an output.

![image](https://github.com/holoviz/holoviews/assets/15051933/6a1dd9d0-b8d3-4f3b-802b-ac7ab5166313)

**Comment by chanana** [comment]
oh wow. That was it? That definitely works!

**Comment by Hoxbro** [comment]
Glad to hear :+1: 

I will close this issue as it is possible to use Plotly in VS code, even if it is a bit cumbersome.
