### ISSUE TITLE
Plots in tab layout do not have linked axes

### ISSUE THREAD

**Issue by timothydmorton** [holoviz/holoviews#3763]
For example:
```
l = (hv.Curve([]) + hv.Curve([]))
l.opts(tabs=True)
```

**Comment by poplarShift** [comment]
Holoviews only links axes it sees as "the same", so when you pass no data there is nothing to link. I have not tested this on empty plots but in general the way to force a link is to use `DataLink`.

**Comment by philippjfr** [comment]
Seems to be fixed.
