### ISSUE TITLE
Legend Formatting Issue

### ISSUE THREAD

**Issue by Sravz-Solv** [holoviz/holoviews#3780]
![Capture](https://user-images.githubusercontent.com/44657023/59644016-f2800280-911f-11e9-857a-a4f51376d7e3.JPG)

I am trying overlay data from about 40 different sensors in a single overlay plot. But with my current plot length and width settings, I cannot see all the entries in the legend, there by limiting all legend interactivity. Is there a way around this issue like dividing the legend into multiple columns or just ability to scroll through legend entries ?

**Comment by poplarShift** [comment]
Not sure if there's a nice way of doing it in pure holoviews (I could think of some ugly hacks but they'd probably be very inefficient), but this sounds like a case for `panel`.

**Comment by Sravz-Solv** [comment]
How do you think panel would help with this issue?

**Comment by Sravz-Solv** [comment]
gotcha. Thanks for the quick response.

**Comment by poplarShift** [comment]
Hm, you should ask that over in the panel repo, I think I've seen pycharm kinda working mentioned somewhere but I don't really know.

Also, if you would really to try and hack something together, here's a start but the DataLink isn't working yet:
```
from holoviews.plotting.links import DataLink

obj = hv.Overlay([hv.Curve(np.random.rand(10,2), label='entry'+str(i)) for i in range(40)]).opts(
    opts.Curve(show_legend=True, width=400), opts.Overlay(show_legend=False),
)

leg = obj.clone().map(lambda x: x.iloc[:0], hv.Curve).opts(
    opts.Curve(width=200, height=800, xaxis=None, yaxis=None, show_frame=False),
    opts.Overlay(legend_position='right', show_legend=True), 
)
DataLink(obj, leg)
obj+leg
```

**Comment by geoHeil** [comment]
Has this been solved? Is there a better way more than a year later? I am facing the same problem. http://holoviews.org/user_guide/Customizing_Plots.html#Legend-customization shows that:

overlay.opts(legend_muted=True, legend_cols=2)

should work. However, for me only the legend_muted is accepted. Specifying any legend_cols is not changing the layout.

**Comment by tom-andersson** [comment]
Bump. Having a similar problem as @geoHeil with the `legend_cols` parameter with `holoviews 1.14.4`. In fact, specifying any `legend_cols` value turns the legend into a single row. What's going on here?

**Comment by maximlt** [comment]
Bokeh doesn't yet offer the possibility to control the legend layout (https://github.com/bokeh/bokeh/issues/3880). For sure, as soon as this is added to Bokeh this will supported by HoloViews!

**Comment by TheoMathurin** [comment]
I think this may be closed? Through https://github.com/holoviz/holoviews/pull/5669.

**Comment by Hoxbro** [comment]
You are right. Thank you for reporting this :+1:
