### ISSUE TITLE
Date axis disappearing when plots are composed

### ISSUE THREAD

**Issue by jg10545** [holoviz/holoviews#3845]
I've been trying to reproduce something like your lovely [measles example](https://holoviews.org/gallery/demos/bokeh/measles_example.html#bokeh-gallery-measles-example), with data aggregated to the day rather than the year. The behavior of the date axis seems really counterintuitive; is this intended?

`hv.__version__` 1.12.3
```
import numpy as np
import pandas as pd
import datetime as dt

import holoviews as hv
hv.extension("bokeh")

# generate fake event data
N = 1000
df = pd.DataFrame({
    "date":[dt.datetime(2019,1,1,0)+dt.timedelta(hours=x) for x in
           np.random.uniform(0, 1000, size=N)],
    "foo":np.random.choice(["foo", "bar", "foobar", "barfoo"], size=N)
})
df["date"] = df.date.dt.date

# aggregate to counts per foo per day
df = df.groupby(["date", "foo"]).size().reset_index()
df.columns = ["date", "foo", "count"]

# build a heatmap
heatmap = hv.HeatMap(df).opts(width=500, height=200, xaxis=None)

# also aggregate results across foo for a line plot
agg = hv.Dataset(heatmap).aggregate("date", np.sum)
line = hv.Curve(agg).opts(width=500, height=150)
```

The `hv.Curve` plot automagically builds a date axis:
![image](https://user-images.githubusercontent.com/42722768/61756800-cd6c5880-ad8b-11e9-9693-053dc12fad82.png)

If I compose the heatmap and the curve, the x-axes are linked but the axis labels are screwed up:
![image](https://user-images.githubusercontent.com/42722768/61756856-0efd0380-ad8c-11e9-8e16-fc1fc35b4600.png)

If I compose them with the order reversed, the date axis comes back but the plots become unlinked:
![image](https://user-images.githubusercontent.com/42722768/61756886-3784fd80-ad8c-11e9-8306-cdbd4fbaf705.png)

Seems spooky. Is this intended or am I doing something horribly wrong?

**Comment by philippjfr** [comment]
The problem here is that it's trying to link the axes despite the fact that one is a datetime axis and the other a categorical axis.
