### ISSUE TITLE
Saving Holomap with html format does not show widgets

### ISSUE THREAD

**Issue by Jacob-Barhak** [holoviz/holoviews#3849]
When using HoloMap and saving into an html file and specifying the format as html, then widgets do not show - only a static image. See the following example code:
```
import holoviews as hv

import numpy as np

hv.extension('bokeh') 

frequencies = [0.5, 0.75, 1.0, 1.25]


def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

phases      = [0, np.pi/2, np.pi, 3*np.pi/2]
curve_dict_2D = {(p,f):sine_curve(p,f) for p in phases for f in frequencies}
hmap = hv.HoloMap(curve_dict_2D, kdims=['phase', 'frequency'])


hv.save(hmap,'test.html',fmt='html')
```
To fix this, try to remove the fmt at the end and the widgets will appear. I am using python 3.7.3 bokeh 1.2.0 and holoviews 1.12.3 and Windows 10 . 

Hopefully, there is a simple fix here.

**Comment by philippjfr** [comment]
Seems to be fixed, output looks odd though.

**Comment by Jacob-Barhak** [comment]
Yes, this is indeed fixed in  development version:
holoviews version 1.13.0a22

Closing the issue.
