### ISSUE TITLE
Dropdown menu not working in exported html when overlay includes arrows

### ISSUE THREAD

**Issue by faymanns** [holoviz/holoviews#3861]
Overlaying arrows for annotation on a plot with a dropdown menu seems to break the functionality of the dropdown menu in exported html files rendered with bokeh.

An example that can reproduce this issue is the [Dropdown Economics example](http://holoviews.org/gallery/demos/bokeh/dropdown_economic.html) in the documentation. The dropdown menu on the [website](http://holoviews.org/gallery/demos/bokeh/dropdown_economic.html) is not working and it can be reproduced using the following two lines to save the plot as html:
```
renderer = hv.renderer('bokeh')
renderer.save((gdp_curves * gdp_unem_scatter * annotations), 'plot')
```

The drop down menu does work when the annotations (arrows) are not included.

Furthermore, this doesn't seem to be an issue in previous releases.
The exact same code produces a html with working dropdown menu and arrows in version 1.10.5 but not versions 1.11.3 and 1.12.3.

**Comment by mc51** [comment]
I can confirm this with the following [env](https://termbin.com/n6kd).
When removing the `annotations` overlay it works.

**Comment by philippjfr** [comment]
Thanks for looking into that, the error in JS is:

```
Uncaught Error: event model wasn't known
```
