### ISSUE TITLE
Holoview on networkx Graph returns DataError: None of the available storage

### ISSUE THREAD

**Issue by sorenwacker** [holoviz/holoviews#3888]
I have a graph that represents a chemical reaction. I can plot the graph with `networkx.draw_networkx` and combine it to other graphs. I am exploring options to plot that grap. I tried `holoview` (1.12.4) and `hvplot.networkx`. Both return the following error:

Here  is the function that creates the graph:

    import numpy as np
    import hvplot.networkx as hvnx
    import holoviews as hv
    import networkx as nx
    from holoviews import opts

    def create_reaction_graph(products, educts, stoi_prod, stoi_educ, label):
        R = nx.DiGraph(directed=True, label=label)
        n_prod = len(products)
        n_educ = len(educts)
        R.add_node(label, pos=(0, max(n_prod-1, n_educ-1)/2), node_type='reaction', label=label)
        ndx_prod = range(n_prod)
        ndx_educ = range(n_educ)
        for n, stoi, cmp in zip(ndx_prod, stoi_prod, products):
            R.add_node(cmp, pos=(-1, n), node_type='compound')
            R.add_edge(cmp,  label, stoichiometry=stoi, label=label)
        for n, stoi, cmp in zip(ndx_educ, stoi_educ, educts):
            R.add_node(cmp, pos=(1, n), node_type='compound')
            R.add_edge(label, cmp, stoichiometry=stoi, label=label)
        return R

    data = (np.array(['"adenosylcob(III)yrinate a,c-diamide', 'ATP', 'H2O',
                'L-glutamine'], dtype='<U36'),
            np.array(['adenosylcob(III)yrate', 'ADP', 'H(+)', 'L-glutamate',
                'phosphate"'], dtype='<U21'),
            np.array([1, 4, 4, 4]),
            np.array([1, 4, 4, 4, 4])
           )

    R = create_reaction_graph(*data, 'R1')

[![enter image description here][1]][1]

    hvnx.draw(R)

> DataError: None of the available storage backends were able to support the supplied data format.

I can plot nx.karate_club_graph() without problems. Does anybody know what causes this error?

  [1]: https://i.stack.imgur.com/h5BdH.png

**Comment by soerendip** [comment]
https://stackoverflow.com/posts/57420094/edit
