### ISSUE TITLE
recursive_model_update exception with clipping_colors

### ISSUE THREAD

**Issue by joltman61** [holoviz/holoviews#3895]
I am trying to use clipping_colors with `cmap='Reds'` to set the color to 'white' when the z value is 0 when using hv.Points.

```
clipping = {'min': 'white', 'NaN': 'black'}
    plot_spectrum = hv.HeatMap(restore_data, kdims=['Channel', 'Domain'], vdims=['Restoration Count']).sort()
    plot_spectrum.opts(tools=['hover'], colorbar=True, cmap='Reds', clipping_colors=clipping, logz=True)
    plot_spectrum = plot_spectrum.redim.range(z=(0.1, 1000000000))
```

I seem to get an exception in util.py when the recursive_model_update is called.  I added a print statement and seem to get the exception where k= 'group_orientation' and it raises a KeyError when accessing valid_properties[k].  When I stop trying to use clipping_colors, the error goes away and my plot works okay.

**Comment by philippjfr** [comment]
Thanks for the issue. Could you please include the version of holoviews you are using? Also it is much easier to investigate issues which include a **runnable**, minimum reproducible example.

**Comment by philippjfr** [comment]
Can't reproduce this.
