### ISSUE TITLE
Add element.where method support dim expressions

### ISSUE THREAD

**Issue by jonmmease** [holoviz/holoviews#3933]
It would be nice to have an xarray-style `where` method (http://xarray.pydata.org/en/stable/generated/xarray.DataArray.where.html) on elements.

The signature would be something like
```python
Element.where(cond, other=nan)
```

Here `cond` could be a boolean array matching the size of the element, or it could be a `dim`-expression.  The result would be an element of the same type as the input, with the same size, but the values where `cond` is `True` would be replaced by `other`.

One application of this method would be to support arbitrary `dim` expression filtering on gridded datasets.  If `other` is `nan`, this would make it possible to overlay a subset of an image on top of itself, where the subset is not a clean slice, but an arbitrary function of the element's dimensions.

**Comment by philippjfr** [comment]
Similar to https://github.com/holoviz/holoviews/issues/4312, I'll close this and continue discussion there but we may want to keep the `where` API.
