### ISSUE TITLE
Allow reset (clearing) of auto archive

### ISSUE THREAD

**Issue by jhermann** [holoviz/holoviews#3944]
# Use-case / Problem statement
As a notebook user, if you repeatedly use "Run All", the archive grows with each iteration. It would be nice if you could clear remnants of older executions on activation.

Right now, this is only possible via `hv.archive._files.clear()` after the `hv.archive.auto` call.

## Proposed solution
Add a public `clear()` method to the `FileArchive` class, delegating that call to the `_files` attribute (see above).

As a convenience, maybe also add a new `clear=True` kwparam (default: `False`) to the `auto()` call that triggers the new method.

**Comment by jlstevens** [comment]
This is a very reasonable feature request that I support. It would also be a nice simple fix that would be suitable for a user contributed PR so I'll tag this with 'good first issue'. :-)

**Comment by Yura52** [comment]
Looks like the issue can be closed, since the corresponding PR is merged.

**Comment by jhermann** [comment]
That related PR is #4410
