### ISSUE TITLE
Aspect ratio of plot and legend changes in Holomap vs dynamicMap

### ISSUE THREAD

**Issue by kkumawat25** [holoviz/holoviews#4002]
![Untitled](https://user-images.githubusercontent.com/54132236/65780556-9a698b00-e167-11e9-8bac-13ff14e6a23d.png)

Hi, 
 As in attached plot, why the plot and legend  aspect ratio is changed from dynamicMap to HoloMap ?

**Comment by philippjfr** [comment]
I believe this was fixed in 1.13.0, please reopen if it persists.
