### ISSUE TITLE
legends of hv.GridSpace of NdOverlay object

### ISSUE THREAD

**Issue by kkumawat25** [holoviz/holoviews#4003]
Hi, 
grid = hv.GridSpace(cum_ret_plot)
grid.opts(opts.GridSpace(plot_size=300,shared_xaxis=True,shared_yaxis=True),
            opts.Curve(width=100,show_legend=True,axiswise=True))

creates grid space and it shows legends of each Ndoverlay element but that is redundant, is there any way to show legends once and that outside the gridspace i.e. legend_position='right'

**Comment by ahuang11** [comment]
Don't think it's implemented, but you can hack it:
https://github.com/pyviz/holoviews/issues/3026

**Comment by droumis** [comment]
`show_legend=True` on a GridSpace now places a single legend outside the subplots

https://discourse.holoviz.org/t/one-legend-in-subplot-grid/4164
