### ISSUE TITLE
Better xformatter and yformatter for time

### ISSUE THREAD

**Issue by jsignell** [holoviz/holoviews#4009]
The tick formatters don't feel very flexible for time axes. I'll just put an example for simplicity.

```python
import numpy as np
import pandas as pd
import hvplot.pandas

df = pd.DataFrame(np.random.randn(1000, 4), 
                  index=ts.index, columns=list('ABCD'))
df = df.cumsum()
df.A.hvplot.line()
```

<img width="785" alt="Screen Shot 2019-10-01 at 11 35 17 AM" src="https://user-images.githubusercontent.com/4806877/65977242-94153080-e43f-11e9-87bd-d6be22846b5d.png">

In theory I can specify the `xformatter` as an f string. For instance this should work:

```python
df.A.hvplot.line(xformatter='%b %Y')
```

But it does not. I would expect the x ticks to look like the following:

```python 
>>> f'{df.index[0]:%b %Y}'  
'Jan 2000'
```

**Comment by philippjfr** [comment]
Note that the formatter has to be translated to a bokeh tick formatter. Afaik there is no bokeh tick formatter that will accept arbitrary string formatters **AND** do so for different time resolutions, see the bokeh docs for reference:

https://docs.bokeh.org/en/latest/docs/reference/models/formatters.html#bokeh.models.formatters.DatetimeTickFormatter

**Comment by gioarma** [comment]
Had the same problem and solved with:

```python
from bokeh.models.formatters import DatetimeTickFormatter
df.A.hvplot.line(DatetimeTickFormatter(days = '%b %d'))

```

**Comment by jsignell** [comment]
Thanks @gioarma !
