### ISSUE TITLE
QuadMesh not respecting line_* options

### ISSUE THREAD

**Issue by poplarShift** [holoviz/holoviews#4016]
If I read the docs correctly, in the bokeh backend I should be able to modify the outlines of each QuadMesh cell (bokeh's `Patches` or `Quad`) glyphs by specifying e.g. the `line_width` option. The following does not seem to have any effect, though:

```
import numpy as np
import xarray as xr
import holoviews as hv
hv.extension('bokeh')
hv.QuadMesh(xr.DataArray(np.random.rand(10, 10))).opts(line_color=10000)
```

**Comment by philippjfr** [comment]
Seems like line_alpha=0 by default, e.g. this works:

```
hv.QuadMesh(xr.DataArray(np.random.rand(10, 10))).opts(line_width=3, line_alpha=1)

**Comment by poplarShift** [comment]
Hm, I am reasonably sure I checked that too but it works now. Thanks a lot!
