### ISSUE TITLE
Starting in release 1.12.4 , radial heat maps are having issues with sizing

### ISSUE THREAD

**Issue by chris-ratcliffe** [holoviz/holoviews#4046]
If you look at the radial heat map examples:

https://holoviews.org/reference/elements/bokeh/RadialHeatMap.html
https://holoviews.org/gallery/demos/bokeh/nyc_radial_heatmap.html

you will see the error.  The rendered bokeh image is sized incorrectly, such that it is extremely small.  

When I attempted to run the sample code from https://holoviews.org/reference/elements/bokeh/RadialHeatMap.html in my own notebook environment, where I had 1.12.5 installed, I saw the same error.  When I reverted back to 1.12.3 it was fine, but 1.12.4 also has the issue.

**Comment by philippjfr** [comment]
Thanks @chris-ratcliffe.
