### ISSUE TITLE
Gridspace doesn't respect height and width

### ISSUE THREAD

**Issue by jsignell** [holoviz/holoviews#4051]
It appears that this used to be supported, but no longer is. I would expect the plots in the grid below to have width 300. 

```python
import numpy as np
import holoviews as hv
hv.extension('bokeh')

def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals])).opts(width=300)

phases      = [0, np.pi/2, np.pi, 3*np.pi/2]
frequencies = [0.5, 0.75, 1.0, 1.25]
curve_dict_2D = {(p,f):sine_curve(p,f) for p in phases for f in frequencies}

gridspace = hv.GridSpace(curve_dict_2D, kdims=['phase', 'frequency'])
gridspace

**Comment by philippjfr** [comment]
You have to use frame_width/frame_height I believe.

**Comment by wmayner** [comment]
I just ran into this as well. It would be helpful if this was documented in the [tutorial](http://holoviews.org/reference/containers/matplotlib/GridSpace.html).

**Comment by wmayner** [comment]
It seems that this isn't documented in `hv.help(hv.GridSpace)` either.

**Comment by LaurensvanG** [comment]
I don't know if the `frame_width` used to work but it now gives a `ValueError`:

ValueError: In opts.GridSpace(...), unexpected option 'frame_width' for GridSpace type across all extensions. Similar options for current extension ('bokeh') are: ['framewise', 'width'].

**Comment by AlifCor** [comment]
Also experiencing this with version 1.14.5 

Here's a working workaround mentioned in #3856 by @jjoonathan :

> I'm seeing it too. Here's a workaround. It sets the size of each individual plot in the matrix, so if you want to fix the size of the entire grid (which is what I want) you have to do some math, but that's comparatively easy :)
> 
> ```
> my_grid_matrix.opts(plot_size=(800,100))  # (width,height)
> ```

**Comment by droumis** [comment]
setting `frame_width`/`height` works, tested in HoloViews 1.17.0a1

it is documented in hv.help(hv.Curve)

**Comment by G-Guillard** [comment]
> it is documented in hv.help(hv.Curve)

Since it doesn’t only affect `hv.Curve` (I can confirm with `hv.Histogram`), shouldn’t it rather be documented in `hv.help(hv.GridSpace)` ?
