### ISSUE TITLE
Pass additional operation parameters through rasterize

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#4077]
Currently, `rasterize` is one of the main entry points to datashading in HoloViews that supports many element types. Some of the rasterizers for specific element types have additional parameters that you may want to specific when calling `rasterize`: for instance `regrid` has an `upsample` parameter you may want to specify (when rasterizing from an `Image` to another regridded `Image`).

It would be helpful if additional parameters are passed through `rasterize` to the dispatched functions to avoid having to invoke the specific function explicitly.

**Comment by philippjfr** [comment]
This was implemented.
