### ISSUE TITLE
Change order of legend keys in NdOverlay

### ISSUE THREAD

**Issue by kazimuth** [holoviz/holoviews#4082]
I've got an NdOverlay with several cleanly separated datasets, one above the other. However, their entries on the legend are in a different order, which makes the graph harder to read. Is there a way to customize order of legend entries? I can't figure it out.

**Comment by DancingQuanta** [comment]
The order of legend entries always follows the order of the plotted data.
What are the version of holoviews are you using, backend and an minimal example code?

**Comment by philippjfr** [comment]
No reproducible example provided, closing.
