### ISSUE TITLE
https site has mixed content warnings

### ISSUE THREAD

**Issue by QuLogic** [holoviz/holoviews#4091]
If you go to https://holoviews.org/, then the browser complains about mixed-content warnings.

All example images (at least on the homepage) use http:// instead of https:// :
![Screenshot from 2019-11-10 02-09-05](https://user-images.githubusercontent.com/302469/68540381-3f7aa480-035f-11ea-8a40-8d8fa1ac7fb9.png)

**Comment by jlstevens** [comment]
@philippjfr Thanks for fixing this!
