### ISSUE TITLE
Variable nodesize for from_networkx()

### ISSUE THREAD

**Issue by Zylatis** [holoviz/holoviews#4093]
Hi I am trying to recreate a networkx plot in HV so i can have an interactive html page (which is awesome btw, thank you).

My nx object just has source, target, and an edgeweight parameter but when i plot I also map variable node sizes from a list using

```python
nx.draw(display_graph,pos, node_size=node_size_info, font_size=18, width = weights, font_weight='bold',with_labels = True)
```

My HV attempt is 
```
plot = hv.Graph.from_networkx(display_graph, pos).opts(plot=dict(width=1000, height=1000,xaxis=None, yaxis=None,node_size = node_size_info)).redim.range(**padding)
```

which indeed produces that network but the node sizes are unchanged. How do I pass the list of node sizes to HV to render, and similarly with edge weights?

I see that node attributes were made accessible via
https://github.com/pyviz/holoviews/issues/2696
but it's still not clear to me how to pass a list of values for the node sizes

Thanks,
Z

Update/Edit:
I have *sort* of made the graph I would like to make with HV, any tips on the best way to do this would be appreciated. In this image it's far too busy to actually statically have the edge weights there, ideally they would appear on mouseover. Also being able to somehow ensure the labels always fit inside the nodes, or are shifted above with an appropriate background color for contrast/readibility
![Graph](https://user-images.githubusercontent.com/1456631/68560263-6edefd80-0494-11ea-9dc7-5f03c0c5e21e.png)

**Comment by philippjfr** [comment]
Sorry I never responded, this really turned out to be more of a usage question which is best placed for our [Discourse](https://discourse.holoviz.org).
