### ISSUE TITLE
Feature request: Split violin plots

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#4096]
![seaborn-violinplot-4](https://user-images.githubusercontent.com/15331990/68688995-5246d200-0535-11ea-99fc-1fa137d32f0d.png)
https://seaborn.pydata.org/generated/seaborn.violinplot.html

**Comment by NumesSanguis** [comment]
Would request this feature as well.
When I asked about this on the bokeh Gitter chat, I got the following reply: "You can draw that double-sided violin chart in Bokeh today. But it is up to you to compute the polygons".

A ridgeplot example that might be useful: https://docs.bokeh.org/en/latest/docs/user_guide/categorical.html#categorical-offsets
With the following information: "... plots distributions separately one per category, but you could certainly flip some signs and draw some of those ridges back to back just like a violin plot".
