### ISSUE TITLE
Support any named cmaps with hv.Cycle

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#4099]
```
def format_list(l):
    print(' '.join(sorted([k for k in l if not k.endswith('_r')])))

format_list(hv.Cycle.default_cycles.keys())
```

**Comment by ahuang11** [comment]
Actually I think there should be some util function that converts LinearSegmentedCmaps into list of colors to use for hv.Cycle

**Comment by philippjfr** [comment]
The problem with that is that it's ambiguous how many colors to cycle over, hence why we have hv.Palette instead.
