### ISSUE TITLE
Change semantics of multi-interface datasets

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#4101]
For consistency when we added MultiInterface types to support geometries we made them act like they consisted of a single large array separated by NaNs. This seemed reasonable at the time but it's also inefficient in some important ways and ends up being awkward to use. 

In effect ragged array formats are just treated as a single large array so methods like `len`, `values` or `select` operate on the individual values in each ragged arrays, which can end up causing other issues for operations like `groupby`. Instead we should consider treating each ragged array (or shapely geometry) as a single value and add special support for selecting on them as needed (e.g. when selecting some part of a geometry). 

This will also make sure that other methods like `.sort` or `.iloc` can work without breaking the semantics. Currently these are disabled because they do not make much sense given the current semantics, e.g. sorting the coordinates in a geometry or selecting the first 10 coordinates among a possible large list of geometries doesn't make sense. However sorting overlapping geometries by some value to achieve a desired zorder or selecting the first N geometries does make sense.

This will align Dataset more closely with the way geopandas and pandas ragged array libraries work and make them a bit more intuitive to use.

**Comment by philippjfr** [comment]
So to clarify here's the changes in behavior I'm proposing:

| Operation                  | New                                                                     | Old                                                     |
|----------------------------|-------------------------------------------------------------------------|---------------------------------------------------------|
| ``len``                    | Returns the number of geometries                                        | Returns the number of coordinates (plus nan separators) |
| ``iloc``                   | Selects among geometries                                                | NotImplemented                                          |
| ``sort``                   | Allows sorting by non-geometry columns                                  | NotImplemented                                          |
| ``values(expanded=False)`` | Returns some RaggedArray type or numpy array of arrays with object type | Returns flattened data                                  |
| ``dtype``                  | Gains new argument to return ragged array types                         | Returns np.dtype('float') for all geometry columns      |

**Comment by philippjfr** [comment]
Beyond that I'd also like to implementing slice/selection for all geometry interfaces. Hopefully spatialpandas will gain that ability soon, geopandas and shapely interfaces can already support this and then we only need to implement it for our native interface. This is one of the last obstacles to deprecating the `extents` parameter and resolving issues like: #181, #566 and #1433.

**Comment by jbednar** [comment]
Sounds good to me. The previous behavior of `len`, `iloc`, `sort`, and `dtype` seem like the were unlikely ever to have been useful.  People might have used `values`, but the new behavior seems much more useful.

**Comment by philippjfr** [comment]
>People might have used values, but the new behavior seems much more useful.

This is true but the default behavior of `values` does not change, it only changes if you call `.dimension_values(dim, expanded=False)`, which would not have been common for users.

One modification I have made to the semantics described above is that MultiPoint has special handling. I'd like to continue treating an array of MultiPoint geometries as a flat array of points so that certain assumptions aren't broken, e.g. if you use a Selection1D stream on a Points element backed by a spatialpandas DataFrame containing MultiPoint geometries I'd like the flat index to continue to work. With these new semantics Selection1D streams will work on all geometry elements.

**Comment by jbednar** [comment]
> This is true but the default behavior of values does not change, it only changes if you call .dimension_values(dim, expanded=False), which would not have been common for users.

Sounds good.

> One modification I have made to the semantics described above is that MultiPoint has special handling. I'd like to continue treating an array of MultiPoint geometries as a flat array of points so that certain assumptions aren't broken, e.g. if you use a Selection1D stream on a Points element backed by a spatialpandas DataFrame containing MultiPoint geometries I'd like the flat index to continue to work. With these new semantics Selection1D streams will work on all geometry elements.

I'm not sure.  I can see why that would be good for selecting points, but what if you want to select MultiPoints, where each collection of points is meant to stay together?  Seems ambiguous.

**Comment by philippjfr** [comment]
>what if you want to select MultiPoints, where each collection of points is meant to stay together?

If you need to do that I think you should do that directly on the data. I believe our methods should be useful for the kinds of operations you will perform within HoloViews. It's worth noting that only `len` and `iloc` are affected by these altered semantics, each group of points has the same values so sorting stays the same and `values` already returns the flattened array by default and will retain the grouping if `expanded=False`. 

However from HoloViews perspective and from the perspective of the plotting backends (i.e. bokeh and plotly) there is no concept of a collection of Points beyond them sharing some values. For example you can group a set of points by their values but there it still doesn't matter how they are stored in the underlying `.data` since you are grouping by value not by index. So I believe `.iloc` and `length` should reflect that.

Note also that despite the fact that `iloc` has these semantics the actual MultiPoints will still stay together you are simply selecting among the points in the groups rather than each group.

**Comment by jbednar** [comment]
Ok, sounds good. I can't think of cases where I want points to stay grouped like that that aren't better served by a collection of polygons, not disconnected points.
