### ISSUE TITLE
Option to make all fontsizes in your plot with the same scale larger (like in seaborn)

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/holoviews#4107]
It would be great in Holoviews if you would have a nice, easy and fast way to make your plot more readable without having to specify every fontsize for every part of the plot separately.

Seaborn has the option to scale all your fontsizes (such as title, xlabel, ylabel, xticks etc) with the same factor, like this:

```python 
import seaborn as sns
sns.set(font_scale=2.0)
```
This will not set all fontsizes to the same size, but rather multiply every separate fontsize with the same factor.

Currently you have to do in Holoviews:
```python
my_plot.opts(fontsize={'title': 20, 'yticks': 14, 'xticks': 14, 'xlabel': 16})
````
This is great if you want to define your plot precisely, but not if you want to rapidly change your plot.

(solution could be something like ```my_plot.opts(fontscale=2.0)``` or ```hv.output(fontscale=200)```, but these are just suggestions.)

**Comment by ahuang11** [comment]
Turns out it's harder to implement than expected since holoviews doesn't have the default fontsizes available in `self` (https://github.com/holoviz/holoviews/blob/master/holoviews/plotting/plot.py#L512 simply returns an empty dict if None) and I think to get the defaults, you need to either hardcode the defaults or render the figure and painstakingly retrieve the attributes (p.title.text_fontsize, p.xlabel.axis_label_text_font_size, etc)

One workaround for bokeh is doing `fontsize={'ticks': '200%', 'labels': '200%'}`

**Comment by philippjfr** [comment]
I think we'll probably have to do this sadly, each backend will have to implement a method that returns the defaults.

**Comment by jbednar** [comment]
Having done so, wouldn't we then be able to implement a font_scale property that would multiply all those values by a factor?  I can't quite see how to integrate that with the options system, though.

**Comment by philippjfr** [comment]
>Having done so, wouldn't we then be able to implement a font_scale property that would multiply all those values by a factor, for the current backend (loop through the defaults, and multiply each by the factor)?

I think that's exactly what's being proposed here. I think the idea would be that it would live at the hv.output level just like the size scaling option, so you could do it globally.

**Comment by jbednar** [comment]
The hv.output level sounds good.  Your previous wording sounded like you were giving up on having a global scaling option in favor of only a dictionary of defaults, but it now it sounds like we're all on the same page; the dictionary would be a way to implement the global scaling. Sounds good!

**Comment by ahuang11** [comment]
> I think we'll probably have to do this sadly, each backend will have to implement a method that returns the defaults.

As in hardcode the defaults or render the plots each time to get the default?
