### ISSUE TITLE
Extra space for legend in HoloMaps

### ISSUE THREAD

**Issue by eliaborras** [holoviz/holoviews#4118]
Hi,
I have a HoloMap object with an slider.  
I need the legend outside the plot (in this eg on the left).
I am rendering "and I need to render it using bokeh". 
HoloMap has an extra large space. Some times even bigger. 
Making the plot smaller and having to set width some times up to 2000,
and Then scrolling to the left to view the plot.
I have played with margins. But margins are 0. when this issue is there. 
I would like to remove this space and I don't know how. 
Any help would be very much appreciated. 
Below the picture and dummy code that produces the bug. 

![image](https://user-images.githubusercontent.com/38831184/70134497-1e685380-1680-11ea-94c9-a0fcf1efde37.png)

### Eg 1 There is a huge space between the legend and the plot That I would like to get rid off.
```
hv.HoloMap({1:hv.Overlay([hv.Curve(([1,2,3,4], [1,2,3,4]), label='first plot'), 
            hv.Curve(([1,2,3,4], [2,3,4,1]), label='second plot')]).opts(legend_position='left'),
           2:hv.Overlay([hv.Curve(([1,2,3,4], [6,2,3,4]), label='first plot'), 
            hv.Curve(([1,2,3,4], [4,3,2,1]), label='second plot')]).opts(legend_position='left')}).opts(
width=900)
```

### Eg 2  I can use legend_offset and I can place the legend close to the plot, but yet the plot size is smaller because the extra space on the left remains. 
```
hv.HoloMap({1:hv.Overlay([hv.Curve(([1,2,3,4], [1,2,3,4]), label='first plot'), 
            hv.Curve(([1,2,3,4], [2,3,4,1]), label='second plot')]).opts(legend_position='left'),
           2:hv.Overlay([hv.Curve(([1,2,3,4], [6,2,3,4]), label='first plot'), 
            hv.Curve(([1,2,3,4], [4,3,2,1]), label='second plot')]).opts(legend_position='left')}).opts(
width=900, legend_offset=(290,0))
```

### Eg 3 Even using panel, to solve the slider being placed in the middle, the gap between the legend and the plot remains.
```
p = pn.panel(hv.HoloMap({1:hv.Overlay([hv.Curve(([1,2,3,4], [1,2,3,4]), label='first plot'), 
            hv.Curve(([1,2,3,4], [2,3,4,1]), label='second plot')]).opts(legend_position='left'),
           2:hv.Overlay([hv.Curve(([1,2,3,4], [6,2,3,4]), label='first plot'), 
            hv.Curve(([1,2,3,4], [4,3,2,1]), label='second plot')]).opts(legend_position='left')}).opts(
width=900))
pn.Column(p[0], p[1][0])
```

You can use bokeh themes or have a background_fill_color to view the space:
from bokeh.themes.theme import Theme
theme = Theme(
    json={
    'attrs' : {
        'Figure' : {
            'background_fill_color': '#2F2F2F',
            'border_fill_color': '#116588',
            'outline_line_color': '#444444',
            'min_border_left':0,
        },
        'Grid': {
            'grid_line_dash': [6, 4],
            'grid_line_alpha': .3,
        },
        'Title': {
            'text_color': 'white'
        },
    }
})
hv.renderer('bokeh').theme = theme
hv.HoloMap({1:hv.Overlay([hv.Curve(([1,2,3,4], [1,2,3,4]), label='first plot'), 
            hv.Curve(([1,2,3,4], [2,3,4,1]), label='second plot')]).opts(legend_position='left'),
           2:hv.Overlay([hv.Curve(([1,2,3,4], [6,2,3,4]), label='first plot'), 
            hv.Curve(([1,2,3,4], [4,3,2,1]), label='second plot')]).opts(legend_position='left')}).opts(
width=900, legend_offset=(290,0))

tbw, it is not the margin.

**Comment by philippjfr** [comment]
The legend offset issues were resolved in Bokeh at some point:

<img width="1030" alt="Screen Shot 2020-09-02 at 3 14 14 AM" src="https://user-images.githubusercontent.com/1550771/91920856-662d1180-ecca-11ea-807a-25e5e7ace321.png">
