### ISSUE TITLE
Map/Points don't show when datashaded on the same latitude

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#4124]
```
import pandas as pd
import geoviews as gv
import cartopy.crs as ccrs
from holoviews.element.tiles import OSM
gv.extension("bokeh")

from holoviews.operation.datashader import datashade

df = pd.DataFrame({'lon': [0, 1, 2], 'lat': [40, 40, 40]})

map_tiles = gv.tile_sources.OSM()

points = gv.Points(df, ['lon', 'lat'], crs=ccrs.PlateCarree())

map_tiles * datashade(points, y_sampling=1, x_sampling=1)
```

regardless, I expect to see the map tile when zoomed out

If you change lat as suggested by @jbednar it works

"that example has all the points at the same latitude, which can make for confusing plots because of how Datashader has to guess what y range you might have wanted when it autoranges. The autoranging was recently improved, but it will never be perfect; Datashader and HoloViews have no way to know whether a y range of 0.1, 1, 10, 100, or 1000 should be used in such a case. If you have data not all on the same latitude the y range is deducible:"
```
import pandas as pd, cartopy.crs as ccrs
from holoviews.element.tiles import OSM
from holoviews.operation.datashader import datashade
gv.extension("bokeh")

df = pd.DataFrame({'lon': [0, 1, 2], 'lat': [40, 20, 40]})
points = gv.Points(df, ['lon', 'lat'])

OSM() * datashade(points, y_sampling=1, x_sampling=1)
```

**Comment by philippjfr** [comment]
Looks like this for me in latest versions, which seems fine:

<img width="334" alt="Screen Shot 2020-09-02 at 3 12 10 AM" src="https://user-images.githubusercontent.com/1550771/91920708-29f9b100-ecca-11ea-956d-f8e77a762872.png">
