### ISSUE TITLE
[Bug] Figure title disappears when updating data in a stream

### ISSUE THREAD

**Issue by harmbuisman** [holoviz/holoviews#4130]
#### 
holoviews: '1.12.6',
bokeh: '1.4.0'

#### Description of expected behavior and the observed behavior
When updating the data in a stream, the title of the (Sankey) plot disappars.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
from bokeh.models import Button
from bokeh.plotting import curdoc
import holoviews as hv
hv.extension('bokeh')

data = pd.DataFrame({'A':['A'], 'B':['B'], 'Count':[1]})
stream = hv.streams.Pipe(data=data)

def update_sankey(_):
    data['Count'] = data['Count'] + 1
#   title = self.sankey_plot.title.text
    stream.send(data)
#   sankey_plot.title.text = title

def plot_sankey(data):
    """Callback for dynamic holoviews sankey plot"""
    return hv.Sankey(data)

dmap = hv.DynamicMap(plot_sankey, streams=[stream])
sankey_plot = hv.render(dmap)
sankey_plot.title.text = "Sankey with title"

btn = Button(label='+1', name="button")
btn.on_click(update_sankey)

curdoc().add_root(sankey_plot)
curdoc().add_root(btn)
```

#### Workaround
Reassign the title of the plot after updating the stream as commented in the update_sankey method

#### Screenshots or screencasts of the bug in action
State 0:
![image](https://user-images.githubusercontent.com/7702207/70997444-64d49e00-20d5-11ea-8dfe-68f47afcd460.png)

State 1 after pressing "+1" button:
![image](https://user-images.githubusercontent.com/7702207/70997468-74ec7d80-20d5-11ea-90d2-148aef99196c.png)

**Comment by philippjfr** [comment]
Sorry for the delayed reply. Since this is non-standard usage of HoloViews, modifying the bokeh models directly this is really not unexpected behavior. If you set the title via `.opts(title=...)` it should work just fine.
