### ISSUE TITLE
hv.Histogram with Plotly backend not working

### ISSUE THREAD

**Issue by BenMoon** [holoviz/holoviews#4134]
Hi,
I tried to run the expample script
`examples/reference/elements/plotly/Histogram.ipynb`
and get the error:
`WARNING:param.LayoutPlot01137: Plotly plotting class for Histogram type not found, object will not be rendered.`

I tried two different installations:
- jupyterlab
  holowviews:  1.12.7 
  plotly:  4.4.1
  numpy: 1.17.4
  python: sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
  param: 1.9.2

- jupyterhub with classic notebook
  holowviews:  1.12.7
  plotly:  4.3.0
  numpy: 1.17.3
  python: sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
  param: 1.9.2

Scatter3D, Curve, Scatter, Image, Surface, TriSurface, Violin work just fine. What am I missing?

Thanks a lot, best

Ben

**Comment by philippjfr** [comment]
Histograms are simply not implemented for plotly yet. You can see all supported elements by clicking the Plotly button in the [reference gallery](http://holoviews.org/reference/index.html). Any help in making the Plotly backend more complete is greatly appreciated.

**Comment by philippjfr** [comment]
Actually turns out this has been implemented on master and will be in the 1.13.0 release.
