### ISSUE TITLE
Typo in Annotators.ipynb

### ISSUE THREAD

**Issue by kcpevey** [holoviz/holoviews#4144]
Super excited to see Annotators making their way into Holoviews!   
  
I was trying out the latest dev release 1.13.0a16 and I noticed a typo in the last cell of the example notebook `Annotators.ipynb`. To be clear, the works as expected (creates a poly annotator), but the labels are misleading (its labeled as path and should be poly)
  
The code is:  
```
poly_annotator = annotate.instance()
path_layout = path_annotator(hv.Polygons([]), annotations=['Label'])

annotate.compose(hv.element.tiles.Wikipedia(), point_layout, path_layout)
```
It should be:
```
poly_annotator = annotate.instance()
poly_layout = poly_annotator(hv.Polygons([]), annotations=['Label'])

annotate.compose(hv.element.tiles.Wikipedia(), point_layout, poly_layout)
```

**Comment by kcpevey** [comment]
I can open a PR if that would be helpful.

**Comment by jbednar** [comment]
Yes please!

**Comment by kcpevey** [comment]
@jbednar As you know, I'm great at breaking things. I found bugs with poly_annotators. Is that worth reporting or is this still a WIP?

**Comment by kcpevey** [comment]
@jbednar or @philippjfr Can you give me access to create a branch and open a PR?

**Comment by philippjfr** [comment]
Done.
