### ISSUE TITLE
Unable to customize the HoloMap widgets

### ISSUE THREAD

**Issue by atticusfyj** [holoviz/holoviews#4150]
Version: 1.12.7

In #84 it was mentioned that "widgets on the right don't have enough space for large figures". After panel was integrated into holoviews, this issue was closed.

However, according to the current docs, I cannot find any solution to, for example, placing a HoloMap dropdown in a separate row. User guides like [Data Processing Pipelines](https://holoviews.org/user_guide/Data_Pipelines.html) or [Creating interactive dashboards](https://holoviews.org/user_guide/Dashboards.html) provided panel-assisted solutions, but still require a live python kernel. What is the right approach to customize HoloMap widgets then?

**Comment by philippjfr** [comment]
There has not yet been a release with the panel integration.

**Comment by atticusfyj** [comment]
> There has not yet been a release with the panel integration.

Can I assume it's currently not possible to customize HoloMap widgets?

**Comment by philippjfr** [comment]
You can use the HoloViews pane from Panel directly (see
http://panel.pyviz.org/reference/panes/HoloViews.html) or wait for the
release next week.

**Comment by philippjfr** [comment]
Let me know if you need further guidance, but since this is a usage question at this point I'd direct you to [our discourse](http://discourse.holoviz.org/).
