### ISSUE TITLE
Layout toolbar doesn't show correct active tool + toolbar unusable after selecting box_zoom

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/holoviews#4164]
I've created a layout from 2 plots. For both I've changed the active tool to 'box_zoom'.
I would expect the layout to also show 'box_zoom' as the active tool in the toolbar.

However as can be seen in the image below, the toolbar shows 'pan' as the active tool.
But, although it now seems 'pan' is the active tool, it is actually 'box_zoom' that is active and you can use box zoom right away.

However, if you would now actually select 'box_zoom', the result is both 'pan' and 'box_zoom' won't work anymore.

I'm using:
holoviews: 1.13.0a17.post12+g89bfcfbe
bokeh: 1.4.0

``` python
import holoviews as hv
hv.extension('bokeh')

curve1 = hv.Curve(range(0, 10)).opts(active_tools=['box_zoom'])
scatter1 = hv.Scatter(range(0, 10)).opts(active_tools=['box_zoom'])

curve1 + scatter1
```

![weird toolbar behavior layout](https://user-images.githubusercontent.com/7305600/71897363-aa294000-3156-11ea-92b8-8641a0d2f2e0.png)

**Comment by philippjfr** [comment]
Very strange indeed, the bokeh ProxyToolBar seems pretty broken. I'll try to file appropriate bug reports with bokeh.

**Comment by philippjfr** [comment]
This has been resolved upstream in bokeh.

**Comment by thatlittleboy** [comment]
@philippjfr What version is this fixed? I'm still facing the same problem.

```
bokeh==3.1.1
holoviews==1.16.2
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.6.0
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
panel==1.1.0
```

![image](https://github.com/holoviz/holoviews/assets/30731072/b0eb23ba-9164-4a0e-b38a-3b5cd652cd88)

**Comment by MarcSkovMadsen** [comment]
Hi @thatlittleboy . I think the issue you are experiencing is this open issue https://github.com/holoviz/holoviews/issues/5119.
