### ISSUE TITLE
Change FAQ explanation on axiswise

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/holoviews#4175]
In the [FAQ](https://www.holoviews.org/FAQ.html) it is stated to use axiswise=True and framewise=True on a layout. This seems incorrect:
Quote from FAQ:
"You can change the axiswise normalization option to True, making each object be normalized independently:
```python
your_layout.options(axiswise=True)
```
"

Example should be corrected to something like:
```python
your_layout.options(opts.Scatter(axiswise=True))
```
Or:
```python
plot1 = hv.Scatter(df1).opts(axiswise=True)
plot2 = hv.Scatter(df2).opts(axiswise=True)
plot1 + plot2
```

This also relates to Documenting Layout axiswise behavior:
#3650 

Tested on: holoviews 1.13.0a17.post12+g89bfcfbe

**Comment by jbednar** [comment]
I don't think we should keep any usages of ".options()" that are around; right, @jlstevens?
