### ISSUE TITLE
For HoloMap legend_positions [right, left, top, bottom] not working

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/holoviews#4191]
**legend_positions [right, left, top, bottom] are NOT working for HoloMap in the example below.**

legend_positions [top_right, top_left, bottom_left, bottom_right] DO work for HoloMap.

If you use legend_position='right' no plot is shown.

This came from this **SO question:** 
[https://stackoverflow.com/questions/55634513/how-to-control-the-legend-position-of-a-holoviews-holomap-figure](https://stackoverflow.com/questions/55634513/how-to-control-the-legend-position-of-a-holoviews-holomap-figure)

**Example code:**
```python
import pandas as pd
import holoviews as hv
from holoviews import opts
hv.extension('bokeh')

df = pd.DataFrame(dict(x=[1, 2], y1=[0, 1], y2=[1, 0], y3=[0.8, 0.8], y4=[0.2,0.2]))
curve1 = hv.Curve(df, 'x', 'y1', label='curve1').opts(ylabel='y')
curve2 = hv.Curve(df, 'x', 'y2', label='curve2').opts(ylabel='y')
curve3 = hv.Curve(df, 'x', 'y3', label='curve3').opts(ylabel='y')
curve4 = hv.Curve(df, 'x', 'y4', label='curve4').opts(ylabel='y')

cc12 = (curve1 * curve2)
cc34 = (curve3 * curve4)

hm = hv.HoloMap({'a':cc12, 'b':cc34})
hm.opts(opts.Overlay(legend_position='top_right'))
```

holoviews==1.13.0a21.post9+ge61bf826
hvplot==0.5.2.post12+g1c76c1f

**Comment by philippjfr** [comment]
Something has definitely changed about legend positions, if you provide enough width it does show up but leaves a  **huge** gap. This is a release blocker for 1.13.0.

**Comment by SandervandenOord** [comment]
Tested this on the example I gave with:
holoviews==1.13.0a22.post32+gfb71e9eae

No issues found, so fixed.
