### ISSUE TITLE
Use __signature__ to generate opts object signatures

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#4193]
Currently we use a docstring trick to generate custom backend dependent signatures for the `hv.opts.[object]` utilities. This approach is no longer supported by IPython in recent versions and is also pretty hacky (and ugly to look at in a docstring since all the keywords appear there). Instead we should use the ``__signature__`` object (see [PEP362](https://www.python.org/dev/peps/pep-0362/)).

![Screen Shot 2020-01-18 at 9 51 33 PM](https://user-images.githubusercontent.com/1550771/72670351-b8236e80-3a3c-11ea-87a9-1077571a698a.png)

**Comment by philippjfr** [comment]
Would like to do this as soon as 1.13.0 is out and we are dropping Python <3.5 support.

**Comment by philippjfr** [comment]
Actually I think I'd like to see this in 1.13.0 already and use it if Python > 3.3, then right after the release we can drop the old codepath.

**Comment by jlstevens** [comment]
I'm looking into this now. The docstring approach was used in param a fair bit (and I agree it is hacky but it was the only thing we could support at the time) so I'll coordinate there as well.
