### ISSUE TITLE
New Pandas 1.0: Check if HoloViews runs okay (with new datatypes etc)

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/holoviews#4204]
Later this month pandas 1.0 is coming out, pre-release is already available:

> pip install --pre pandas==1.0.0rc0

They have some new datatypes such as pd.NA (a new experimental NA scalar), pd.BooleanDtype(), pd.Int64Dtype, pd.StringDtype() = a real string datatype, so besides object datatype, there will also be now a string datatype.

See also:
https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html

**Comment by philippjfr** [comment]
Going to close, we've added handling for pd.NA but any further issues should be raised as they are discovered.
