### ISSUE TITLE
Chord diagram does not work with Numpy >= 1.18.0

### ISSUE THREAD

**Issue by julioasotodv** [holoviz/holoviews#4209]
Hi,

It turns out that the Chord diagram in HoloViews will not work if Numpy >= 1.18.0 is installed, due to an old deprecation that it is not deprecation anymore and now raises an error in Numpy.

The deprecation involves `numpy.linspace()` not admitting anymore a float as the `num` argument (https://github.com/numpy/numpy/pull/14620): it has to be an integer.

Given that currently the Chord diagram uses `linspace` in https://github.com/holoviz/holoviews/blob/9549d8baed98f56e76172bf173e80835dea51a34/holoviews/element/graphs.py#L679 and the argument `n_conn` is provided as a float, the Chord diagram does not work.

To demonstrate this, I will just copy and paste here the simple example in HoloViews' documentation for the Chord diagram (https://holoviews.org/reference/elements/bokeh/Chord.html):

```python
import pandas as pd
import holoviews as hv
from holoviews import opts, dim
from bokeh.sampledata.les_mis import data

hv.extension('bokeh')
hv.output(size=200)

links = pd.DataFrame(data['links'])

hv.Chord(links)
```

Does fail when Numpy >= 1.18.0 is installed due to this.

Thank you!

**Comment by philippjfr** [comment]
Thanks for reporting this! Seems like an easy fix, would you have time to send a PR our way?

**Comment by julioasotodv** [comment]
Sure! Here it is

#4216

**Comment by julioasotodv** [comment]
Merged. Thank you!
