### ISSUE TITLE
hv.Overlay does not display all curves

### ISSUE THREAD

**Issue by Patrickens** [holoviz/holoviews#4213]
When making an overlay with ```hv.Overlay``` instead of multiplying ```*``` curves, which is preferable when overlaying 20+ curves due to performance, one of the curves is lost in the overlay.

```
import holoviews as hv
import numpy as np

hv.extension('bokeh')

def curve_data(n, f, dtype='sin'):
    time = np.random.random(n)*50
    time.sort()
    if dtype=='sin':
        data = np.sin(time*f)*10+10
        data += np.random.random(n)*4
    return time, data 

def make_curves(m,f,label,color):
    curve_ls = []
    for i in range(m):
        t,d = curve_data(n=np.random.choice(range(20,40)),f=f)
        curve = hv.Curve(
                (t, d),
                label=label
            ).opts(
                width=400,
                height=400,
                xrotation=45,
                color=color,
            )
        curve_ls.append(curve)
    return curve_ls


curve_ls = []
for label, color, f in [('A', '#e6ac00',0.08),('B', '#00e600',0.14),('C', '#0000e6',-0.12)]:
    curve_ls.extend(make_curves(m=3,f=f,label=label,color=color))
overlay = hv.Overlay(items=curve_ls).opts(show_legend=True)  

overlay
print(len(overlay.data),len(curve_ls))
```
![image](https://user-images.githubusercontent.com/25825395/73551822-6bca2c80-4447-11ea-9d30-cab6f799432f.png)

The overlay data has a length of 6, whereas the number of curves in the list is 9. We can thus see that there are 2 curves per label in the plot instead of the expected 3. This behaviour is persistent for every number of curves per label over 2 (e.g. for 6 expected curves, only 5 are shown).

**Comment by philippjfr** [comment]
Appears to have been fixed.
