### ISSUE TITLE
Zoom not working with datashader + bokeh from examples in the documentation

### ISSUE THREAD

**Issue by jmakov** [holoviz/holoviews#4218]
I've followed the install instructions and ran [Timeseries notebook](https://github.com/holoviz/datashader/blob/master/examples/user_guide/3_Timeseries.ipynb) in a local Jupyter Lab instance (also the latest version). In the "Dynamic Plots" section there's talk about how zooming in would increase resolution of the plot. This is not the case. Zooming in only shows bigger pixels, the plot is not updated.

**Comment by jbednar** [comment]
Jupyterlab requires extensions to be installed separately, so if you're using jllab, make sure you've run `jupyter labextension install @pyviz/jupyterlab_pyviz` as described at holoviews.org, then restart jlab. If you see somewhere that step should be mentioned in the datashader docs, please let me know or make a PR adding it to the right spot.

If you've installed the extension and it still doesn't work, please list the versions of jupyterlab, holoviews, bokeh, and datashader that you have installed, along with the output of your browser's JavaScript console (under More Tools/Developer Tools in Chrome) when you are seeing the problem.

**Comment by jmakov** [comment]
That's it, thank you! And it's already documented on holoviz.org, I somehow missed that. Just a few comments that solved my issue: the extension required nodejs to be installed and since I'm connecting from a remote server where Jupyter Lab is running, I had to forward all the ports on which python was listening. Only so the plots are zoomable. Thanks again!

**Comment by weiji14** [comment]
Hi, I'm encountering a similar issue when following this [Datashader Bokeh notebook example](https://github.com/bokeh/bokeh-notebooks/blob/master/tutorial/A2%20-%20Visualizing%20Big%20Data%20with%20Datashader.ipynb). Zooming in on a datashaded plot doesn't seem to update the plot, the pixels remain the same size.

I've set up a [Github gist](https://gist.github.com/weiji14/4373876ac24a58dda82da24b67675d6b) with a Binder link [![Binder](https://binder.pangeo.io/badge_logo.svg)](https://binder.pangeo.io/v2/gist/weiji14/4373876ac24a58dda82da24b67675d6b/master) to reproduce this issue, complete with a minimal conda `environment.yml` file, a `postBuild` script that runs `jupyter labextension install @pyviz/jupyterlab_pyviz`. Have also tested it in classic notebook but it doesn't work. The installed dependencies are as follows:

```
name: datashader
channels:
  - conda-forge
dependencies:
  - python=3.8
  - datashader
  - hvplot
```

Output of `bokeh info`:
```
Python version      :  3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 08:20:52) 
IPython version     :  7.11.1
Tornado version     :  6.0.3
Bokeh version       :  2.0.1
BokehJS static path :  /srv/conda/envs/notebook/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  v10.20.1
npm version         :  6.14.4
```
Using `datashader=0.10.0` and `holoviews=1.13.2`.

**Comment by philippjfr** [comment]
@weiji14 The notebook in that binder seems to have invalid JSON in it and I can't seem to open it at all.

**Comment by weiji14** [comment]
Oops sorry, I've replaced it now. Give it a few minutes to rebuild and it should work again. The two cells contain these code:

```python
import pandas as pd
import numpy as np

np.random.seed(1)
num=10000

dists = {cat: pd.DataFrame(dict(x=np.random.normal(x,s,num),
                                y=np.random.normal(y,s,num),
                                val=val,cat=cat))
         for x,y,s,val,cat in
         [(2,2,0.01,10,"d1"), (2,-2,0.1,20,"d2"), (-2,-2,0.5,30,"d3"), (-2,2,1.0,40,"d4"), (0,0,3,50,"d5")]}

df = pd.concat(dists,ignore_index=True)
df["cat"]=df["cat"].astype("category")
```

```python
import datashader as ds
import holoviews as hv

from holoviews.operation.datashader import datashade, dynspread

hv.extension('bokeh')

color_key = dict(d1='blue', d2='green', d3='red', d4='orange', d5='purple')

dynspread(datashade(hv.Points(df, ['x', 'y'], 'cat'), color_key=color_key, aggregator=ds.count_cat('cat')))
```

**Comment by philippjfr** [comment]
So that actually works fine for me on the second time I try to display the plot. Not sure what's wrong on the first attempt.

**Comment by weiji14** [comment]
> So that actually works fine for me on the second time I try to display the plot. Not sure what's wrong on the first attempt.

Huh, and so it does for me too. If I restart the kernel and run it a second time it works on first try. Not sure if this counts as a bug.

**Comment by philippjfr** [comment]
>would love to find out what's causing this.

Me too. I suspect it's some race condition involving initialization of the notebook comms which occurs after hv.extension is run.

**Comment by GGDRriedel** [comment]
The install through the command on the website is now depreceated in the current jupyter lab version, this needs to be updated

**Comment by Hoxbro** [comment]
Can you please open a new issue with a link to the command?
