### ISSUE TITLE
Documentation for Matplotlib has an error and large traceback

### ISSUE THREAD

**Issue by ivirshup** [holoviz/holoviews#4219]
The matplotlib documentation  has a long traceback from a failed command under the ["Video" section](http://holoviews.org/user_guide/Plotting_with_Matplotlib.html#Videos):

![image](https://user-images.githubusercontent.com/8238804/73817148-60f40b00-483e-11ea-97c9-b813d216e030.png)

**Comment by philippjfr** [comment]
Despite this issue being earlier I'll close in favor of https://github.com/holoviz/holoviews/issues/4238

**Comment by philippjfr** [comment]
Thanks for reporting in any case!
