### ISSUE TITLE
Control panel overlaps plots if plots take up width of cell

### ISSUE THREAD

**Issue by smackesey** [holoviz/holoviews#4224]
#### Versions

- Python: 3.7.4
- bokeh==1.4.0
- holoviews==1.12.7
- ipykernel==5.1.3
- ipython==7.11.1
- ipywidgets==7.5.1

#### Description of expected behavior and the observed behavior

When a DynamicMap's (or Holomap's?) plots take up the width of the cell, the control panel should be drawn over or under the plots (as opposed to on top of them).

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import holoviews as hv
hv.extension('bokeh')
import numpy as np

x = range(100)
ys = [ np.random.randn(100) for _ in range(3) ]

def curve_func(shift):
  curves = [ hv.Curve((x, y + shift), 'x', 'y') for y in ys ]
  return hv.Layout(curves)

kdims = [
  hv.Dimension(('shift'), range=(0,10))
]

hv.DynamicMap(curve_func, kdims=kdims)
```

#### Screenshots

<img width="1087" alt="holoviews-panel-overlap" src="https://user-images.githubusercontent.com/1531373/74475040-88a92b80-4e5b-11ea-9c70-7cb8f3c63d37.png">

**Comment by jbednar** [comment]
It would definitely be nice if the widgets behaved better in cases like this, but when I've seen such overlap it's generally been when my browser's page magnification has been set higher than 100%.  Please let us know if that's the case here...

**Comment by smackesey** [comment]
@jbednar Changing the browser's zoom has no effect on the above layout.

**Comment by jbednar** [comment]
Thanks.

**Comment by jbednar** [comment]
Hmm; that's odd; when I run your code with 100% zoom I get a scroll bar instead:
![image](https://user-images.githubusercontent.com/1695496/74475835-cdd65900-4e6d-11ea-9006-593b4951d954.png)

(scrollbar not shown, but I dragged it to the right to show the widgets)

**Comment by smackesey** [comment]
@jbednar Maybe there is a Jupyter setting controlling cell overflow behavior that differs between us?

**Comment by jbednar** [comment]
I wonder!

**Comment by jbednar** [comment]
My .jupyter/nbconfig file is:

```
{
  "keys": {
    "command": {
      "bind": {
        "ctrl-cmd-a": "jupyter-notebook:confirm-restart-kernel-and-run-all-cells",
        "shift-cmd-a": "jupyter-notebook:restart-kernel-and-run-all-cells"
      }
    }
  },
  "load_extensions": {
    "jupyter_bokeh/extension": true
  },
  "Notebook": {
    "Header": false,
    "Toolbar": true
  }
}
```

**Comment by smackesey** [comment]
If I shrink my window, then a cell scrollbar appears but the panel slider remains on top of the plots:

<img width="706" alt="holoviews-panel-overlap-2" src="https://user-images.githubusercontent.com/1531373/74476096-8a73ee80-4e5d-11ea-9fc0-c1e8ce7a1b0a.png">

**Comment by jbednar** [comment]
Maybe @jlstevens or @philippjfr knows...

**Comment by philippjfr** [comment]
This has been fixed on HoloViews master since we switched to Panel widgets. Once 1.13.0 is released it will no longer be an issue.

**Comment by jbednar** [comment]
Yep, I'm on HoloViews master.  Yay for Panel widgets!
