### ISSUE TITLE
Strange output saving as matplotlib SVG

### ISSUE THREAD

**Issue by jchutrue** [holoviz/holoviews#4235]
I have a spectrogram that I explore interactively but eventually want to save as a static SVG file. I first ran this code:

```python
import holoviews as hv
from holoviews.operation.datashader import rasterize
quad = hv.QuadMesh(sg_data, kdims=['time', 'frequency'])
r_quad = rasterize(quad)
r_quad
```
![Selection_279](https://user-images.githubusercontent.com/14321886/74984993-3b4d3100-53fc-11ea-9b02-2c4e6079e2f2.png)

So far, so good.

But when I try to save as an SVG, I get this: 
![Selection_280](https://user-images.githubusercontent.com/14321886/74985105-6b94cf80-53fc-11ea-9bdf-4b6a45985f91.png)

This is the code I used. Perhaps there are some options I am missing?

```python
renderer = hv.Store.renderers['matplotlib'].instance(fig='svg')
renderer.save(r_quad, 'example_specgram.svg')
```

**Comment by philippjfr** [comment]
The default aspect for image type in matplotlib is 'equal'. If you set it to square you'll probably get what you need:

```python
hv.save(r_quad.opts(aspect='square', backend="matplotlib"), 'example_specgram.svg')
```
