### ISSUE TITLE
Exception raised in the online docs: Video output in matplotlib depends on ffmpeg

### ISSUE THREAD

**Issue by eldad-a** [holoviz/holoviews#4238]
The documents are showing an an exception raised: 
>   `ValueError: Invalid file object: <_io.BufferedReader name=56>`

under **Video output in matplotlib depends on ffmpeg** found at [Plotting with Matplotlib](http://holoviews.org/user_guide/Plotting_with_Matplotlib.html)

Hope that helps.

BTW, I am experiencing the same issue, and haven't found a solution yet.
Tried both solution found at [Unclear error when saving Animation using FFMpeg #12357](https://github.com/matplotlib/matplotlib/issues/12357/#issuecomment-426609141)

1.  installing `bzip2` using conda, as well as 
2. defaulting to the system installed `ffmpeg` , using `hv.plotting.mpl.matplotlib.rcParams['animation.ffmpeg_path'] = '/usr/bin/ffmpeg'`, as suggested in 

The first one was not helpful as I was already had `bzip2` installed; the second fixed the issue for `webm`, yet `mp4` still does not work.
If anyone can direct to the fix, that would be great!

**Comment by philippjfr** [comment]
Sorry we never found a fix for you. This appears to be fixed in the recent website build on dev.holoviews.org so I'll close. Questions for help getting ffmpeg working for the matplotlib backend should probably be directed to matplotlib directly.
