### ISSUE TITLE
Horizontal/vertical interval annotation

### ISSUE THREAD

**Issue by poplarShift** [holoviz/holoviews#4245]
Sorry if this is a duplicate - I cannot find this issue even though I think I've seen discussions on this somewhere.

In addition to `HLine`, `VLine`, and `Bounds`, holoviews should have another set of annotations for horizontal or vertical intervals. I propose to name them `HInterval` and `VInterval`. These would return a shaded area between two x or y values, extending infinitely into the other dimension.

A problem is that bokeh seems to not yet have such models, but one could emulate this as an `Area` element that adapts to the axis ranges (on the first rendering, anyway). For matplotlib, I see no problem. What about plotly?

**Comment by philippjfr** [comment]
HSpan and VSpan have already been added.

**Comment by poplarShift** [comment]
Ah, thanks! That's what happens when you don't stay up to date for a couple months...
