### ISSUE TITLE
Normalize object independently, but keep the zoom relationship

### ISSUE THREAD

**Issue by zhqrbitee** [holoviz/holoviews#4274]
Hi,
First, I'm a new user to holoviews, so maybe this feature already exists. Please let me know if this is the case.

I have curves (time series) with the same  x length, but different y length, so I want to keep them normalized independently in y-axis.
I looked through https://holoviews.org/FAQ.html and it suggests me to use 'axiswise=True'.
E.g.
```python
import numpy as np
import holoviews as hv

hv.extension('bokeh')
data = np.random.randn(1000).cumsum()

opts = {"width": 960, "height":600, "xlabel": 'Time (s)', 'axiswise': True}

#  y range of `source` is twice of that of `target` 
source = hv.Curve(2 * data).opts(**opts) 
target = hv.Curve(data).opts(**opts)

(target + source).cols(1)
```
However, I can only zoom them independently after setting `axiswise=True`.

Instead I would like them to be zoomed together w.r.t their y ranges:
E.g. for `source`,  if the zoom window is [A, B] in y axis, then `target` should be zoomed together in [A/2, B/2] in y axis.
I think this case is quite common for signals with the same time domain.

BTW, I only tried `DataLink`, but it seems require y length to be the same and can only works for two objects (not multiple objects).

**Comment by philippjfr** [comment]
Thanks for the issue. Questions like this are best addressed using a [Discourse post](https://discourse.holoviz.org/c/holoviews). As a quick suggestions I would recommend giving the two Curve objects different dimension names/labels.
