### ISSUE TITLE
Stacked barchart does not render x labels as datetime.

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/holoviews#4284]
![image](https://user-images.githubusercontent.com/31582215/76446890-1bc37b80-639e-11ea-9863-40a166af43ae.png)

`
index=pd.date_range('2020-01-01','2020-02-02')
columns=['APPL','GOOG','MSFT']
data = np.random.rand(len(index), len(columns))
portfolios = (data.T / data.sum(axis=1)).T

df = pd.DataFrame(data=portfolios, index=index, columns=columns)

df.hvplot.line()

df.hvplot.bar(stacked=True)
`

**Comment by jbednar** [comment]
It looks like they are datetimes to me, if you rotate them to be readable:

```
import pandas as pd, numpy as np, hvplot.pandas

index=pd.date_range('2020-01-01','2020-02-02')
columns=['APPL','GOOG','MSFT']
data = np.random.rand(len(index), len(columns))
portfolios = (data.T / data.sum(axis=1)).T

df = pd.DataFrame(data=portfolios, index=index, columns=columns)

df.hvplot.line()

df.hvplot.bar(stacked=True).opts(xrotation=90)
```

![image](https://user-images.githubusercontent.com/1695496/76448436-532f2980-6398-11ea-88d2-13c01b7485e8.png)

Are you asking to have the formatting for bars be more like the formatting for lines, i.e. skipping intermediate values? If so, I think there is already an issue for that for categorical values in general; it's a tricky issue.

**Comment by LinuxIsCool** [comment]
You nailed the question. That's exactly what I was asking, but also, the rotation solution is perfectly fine for now. Thank you 🙏
