### ISSUE TITLE
Incorrect Legend for hv.Curve Overlay

### ISSUE THREAD

**Issue by martintb** [holoviz/holoviews#4287]
**Description**
For tabular data with the Bokeh backend, the legend shows incorrectly when the *label* kwarg passed to *hv.Curve* matches the name of the column in the dataset object. This bug may be related to issues #4213 and #4197.

**Environment**
macOS 10.14.6 (Mojave)
Chrome Version 80.0.3987.132
Python 3.7.6
JupyterLab 2.0.1
Holoviews 1.12.7
@pyviz/jupyterlab_pyviz v0.9.0
Numpy 1.16.4
Pandas 0.24.2

**Example**
```python
import numpy as np
import holoviews as hv
import pandas as pd
hv.extension('bokeh')

A = np.linspace(10,20,10)
B = np.random.random(10)
C = np.random.random(10)

df = pd.DataFrame(np.transpose([A,B,C]),columns=['A','B','C'])
ds = hv.Dataset(df,kdims=['A'],vdims=['B','C'])

plot1 = ds.to(hv.Curve,'A','B',label='BB')*ds.to(hv.Curve,'A','C',label='CC')
plot2 = ds.to(hv.Curve,'A','B',label='B')*ds.to(hv.Curve,'A','C',label='C')

plot1 + plot2
```
![image](https://user-images.githubusercontent.com/6588826/76544053-c51d7680-645d-11ea-9098-49c9d4000f68.png)

**Comment by philippjfr** [comment]
This appears to have been fixed in 1.13.0.
