### ISSUE TITLE
PointDraw annotator fails on table row selection with plot hook

### ISSUE THREAD

**Issue by kcpevey** [holoviz/holoviews#4303]
#### ALL software version info
holoviews 1.13.0b12  
bokeh 2.0  
  
#### Description of expected behavior and the observed behavior
Starting with the PointDraw example from the Annotators notebook, I added a hook to swap out the glyph. The following code will successfully render, but if you select a row in the table, it will throw a js error and the drawing will also fail (crash? look like a bunch of inset boxes?)   

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
import param
import panel as pn
from holoviews import opts, streams
from holoviews.plotting.links import DataLink
from bokeh.models import Triangle  

hv.extension('bokeh')

data = ([0, 0.5, 1], [0, 0.5, 0], ['red', 'green', 'blue'], [2, 4, 8])
points = hv.Points(data, vdims=['color', 'sizes']).redim.range(x=(-.1, 1.1), y=(-.1, 1.1))
point_stream = streams.PointDraw(data=points.columns(), num_objects=10, source=points, empty_value='black')
table = hv.Table(points, kdims=['x', 'y'], vdims=['color', 'sizes'])
DataLink(points, table)

tri_glpyh = Triangle(x="x", y="y", size="sizes", line_color="#99d594", line_width=2, fill_color=None)

def hook(plot, element):
    plot.handles['glyph_renderer'].glyph = tri_glpyh
    
(points.opts(hooks=[hook]) + table).opts(
    opts.Layout(merge_tools=False),
    opts.Points(active_tools=['point_draw'], color='color', height=400,
                size=10, tools=['hover'], width=400),
    opts.Table(editable=True))
```

#### Stack traceback and/or browser JavaScript console output
```
TypeError: Cannot read property '0' of undefined
    at _render (eval at evalInContext (vendors~main.479571ea0f6c7741ac01.js:2), <anonymous>:553:266)
    at _.render (eval at evalInContext (vendors~main.479571ea0f6c7741ac01.js:2), <anonymous>:354:1093)
    at w.render (eval at evalInContext (vendors~main.479571ea0f6c7741ac01.js:2), <anonymous>:346:5373)
    at k._paint_levels (eval at evalInContext (vendors~main.479571ea0f6c7741ac01.js:2), <anonymous>:569:16973)
    at k.paint (eval at evalInContext (vendors~main.479571ea0f6c7741ac01.js:2), <anonymous>:569:16561)
    at k.repaint (eval at evalInContext (vendors~main.479571ea0f6c7741ac01.js:2), <anonymous>:569:15443)
    at k.eval (eval at evalInContext (vendors~main.479571ea0f6c7741ac01.js:2), <anonymous>:569:13472)
    at k.eval (eval at evalInContext (vendors~main.479571ea0f6c7741ac01.js:2), <anonymous>:333:438)
    at o.emit (eval at evalInContext (vendors~main.479571ea0f6c7741ac01.js:2), <anonymous>:276:662)
    at o.emit (eval at evalInContext (vendors~main.479571ea0f6c7741ac01.js:2), <anonymous>:276:747)
```

**Comment by philippjfr** [comment]
Why swap out the Triangle in this way?

**Comment by jbednar** [comment]
>  the drawing will also fail (crash? look like a bunch of inset boxes?)

That's definitely a failure mode that I have seen with Bokeh but have never been able to reproduce, so if we have a reproducible way to make it happen, that's something to investigate!

**Comment by philippjfr** [comment]
>That's definitely a failure mode that I have seen with Bokeh but have never been able to reproduce, so if we have a reproducible way to make it happen, that's something to investigate!

It's really just bokeh's failure mode when there's a JS error during layouting, so there's no single cause for this.

**Comment by kcpevey** [comment]
> Why swap out the glyph in this way?  
  
This is a first step into something more complicated. Theoretically I'd like to have, say, a single hv.Point element that had different glyphs for every point. This can be done in hv with markers, but I'd like to create my own custom glyphs to use. I was hoping to use this approach to do that. I was planning on a `discourse` topic to discuss if this was possible, but hadn't gotten that far yet.

**Comment by jbednar** [comment]
> It's really just bokeh's failure mode when there's a JS error during layouting, so there's no single cause for this.

If it's reproducible, then it would be great to use that as a way to improve the user experience when this sort of error happens, i.e. to print a useful error message, point people to what can be used to debug it, catch the error and redisplay if that makes sense, etc.

**Comment by philippjfr** [comment]
Don't see inset boxes anymore, also this is not a supported workflow. Closing.
