### ISSUE TITLE
missing modules when install with conda 

### ISSUE THREAD

**Issue by gandroz** [holoviz/holoviews#4305]
When installing holoviews with conda, I noticed missing modules like `annotate` class in `annotators.py` module.

I'm working on Ubuntu 18.04 and did the following steps to install:

```
$> conda create -n dev python=3  # will create a virtual env with python 3.8
$> conda activate dev
$> conda install -c pyviz holoviews bokeh
$> conda install -c conda-forge jupyterlab nodejs numpy
$> jupyter labextension install @pyviz/jupyterlab_pyviz
```

Then, I launched a jupyter lab instance and tried to reproduce the `Annotator.ipynb` notebook

![image](https://user-images.githubusercontent.com/38106881/77126123-65efd100-6a1e-11ea-887f-cea17aecfc23.png)

From the virtual environment, I can confirm that the module is not here:

![image](https://user-images.githubusercontent.com/38106881/77125954-e530d500-6a1d-11ea-850b-95128c3368ae.png)

And here are the first lines of the `__init__.py` file inside the package:

```
from __future__ import print_function, absolute_import
import os, io

import numpy as np # noqa (API import)
import param


__version__ = str(param.version.Version(fpath=__file__, archive_commit="$Format:%h$",
                                        reponame="holoviews"))

from . import util # noqa (API import)
from .core import archive, config                        # noqa (API import)
from .core.boundingregion import BoundingBox             # noqa (API import)
from .core.dimension import OrderedDict, Dimension       # noqa (API import)
from .core.element import Element, Collator              # noqa (API import)
from .core.layout import (Layout, NdLayout, Empty,       # noqa (API import)
                          AdjointLayout)
from .core.ndmapping import NdMapping                    # noqa (API import)
from .core.options import (Options, Store, Cycle,        # noqa (API import)
                           Palette, StoreOptions)
from .core.overlay import Overlay, NdOverlay             # noqa (API import)
from .core.spaces import (HoloMap, Callable, DynamicMap, # noqa (API import)
                          GridSpace, GridMatrix)

from .operation import Operation                         # noqa (API import)
from .element import *                                   # noqa (API import)
from .element import __all__ as elements_list
from .util import (extension, renderer, output, opts,    # noqa (API import)
                   render, save)
from .util.transform import dim                          # noqa (API import)
```

which misses the line
```
from .annotators import annotate                         # noqa (API import)
```

Furthermore, I tried to install with `pip` instead, but with `pip install 'holoviews[all]', I got the error 

```
ERROR: Could not find a version that satisfies the requirement bzip2; extra == "all" (from holoviews[all]) (from versions: none)
ERROR: No matching distribution found for bzip2; extra == "all" (from holoviews[all])
```

and when installing with 'holoviews[recommended]' I got 

```
ERROR: panel 0.9.2 has requirement bokeh>=2.0.0, but you'll have bokeh 1.4.0 which is incompatible.
```

because whereas I manually installed `bokeh v2.0.0`, it is downgraded during pip installation

**Comment by philippjfr** [comment]
annotate has sadly not been released yet so this issue is effectively the same as https://github.com/holoviz/holoviews/issues/4293. We're currently gearing up to the 1.13.0 release.

**Comment by gandroz** [comment]
ok my bad, I thought the documentation was reflecting the version in prod...

**Comment by philippjfr** [comment]
Hmm, what documentation were you looking at? It shouldn't be appearing on holoviews.org yet.

**Comment by gandroz** [comment]
I just made a research on Google `interactivate annotation bokeh python` or something like that and I was refered to http://build.holoviews.org/user_guide/Annotators.html

**Comment by philippjfr** [comment]
Ah thanks! We need to make sure the build and dev websites aren't indexed.

**Comment by ceball** [comment]
@philippjfr Originally, nbsite (and the theme) set the [canonical link element](https://en.wikipedia.org/wiki/Canonical_link_element), but looks like that has broken somewhere along the way. I no longer know if that is even the right way to do achieve this goal any more.

Here's where the canonical link was originally specified in conf.py for a project (not exactly clear/well named - not even sure that serves only one purpose :( ): 
```
    # WEBSITE_SERVER is optional for tests and local builds, but allows defining a canonical URL for search engines
    'WEBSITE_SERVER': 'http://holoviz.org',
```
https://github.com/pyviz-dev/nbsite/blob/master/nbsite/templates/basic/conf.py#L34

And then that should work its way through to the theme and hence the website, but seems that does not happen any more:

![Screenshot from 2020-03-20 18-24-23](https://user-images.githubusercontent.com/1929/77194556-1a016280-6ad8-11ea-9eea-f49d18d6d634.png)

Maybe something got renamed somewhere (and of course there are no tests to catch that...).

**Comment by ceball** [comment]
Hmm, a brief search of code (using github) for nbsite and sphinx_holoviz_theme suggests that it's a mixup between `WEBSITE_SERVER` in conf.py and `WEBSITE_URL` in the template. Unless I have missed something? Also seems like it should just be called `CANONICAL_URL` or similar in the first place?
