### ISSUE TITLE
Layout of plot list skips one plot

### ISSUE THREAD

**Issue by gioarma** [holoviz/holoviews#4321]
#### Version info
holoviews 1.13.0
bokeh 2.0.0
JupyterLab 2.0.1

#### Description of expected behavior and the observed behavior
If I create a list of plots and then plot it with Layout, the second element of the list is not plotted.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import pandas as pd
import holoviews as hv
import hvplot.pandas
pd.options.plotting.backend = 'holoviews'

S = pd.Series(range(10))
S_plots_list = [S[:i].plot() for i in range(5,11)]
hv.Layout(S_plots_list).cols(2)

```

In the resulting layout, the 2nd plot with indeces from 0 to 5 is missing. Only those from 0 to 4 and from o to 6 appear.

**Comment by jbednar** [comment]
Whoa, that's quite an obvious bug!  I see the same thing on my system:

![image](https://user-images.githubusercontent.com/1695496/77464708-95fbf300-6dd5-11ea-9f6e-e51937f61602.png)
