### ISSUE TITLE
Annotator plots don't render

### ISSUE THREAD

**Issue by kcpevey** [holoviz/holoviews#4326]
#### ALL software version info
bokeh 2.0.0  
holoviews 1.13.1  
panel 0.9.3    

#### Description of expected behavior and the observed behavior
Running code from the Annotator docs throws an error. The only viz that shows up is the bokeh toolbar (not the plot itself, and there is no "empty space" where the plot should go).   
   
#### Complete, minimal, self-contained example code that reproduces the issue

```
points = hv.Points([(0.0, 0.0), (1.0, 1.0), (200000.0, 2000000.0)]).opts(size=10, min_height=500)

annotator = hv.annotate.instance()
layout = annotator(hv.element.tiles.Wikipedia() * points, annotations=['Label'], name="Point Annotations")

layout
```

#### Stack traceback and/or browser JavaScript console output
```
VM300:888 
Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not callable
    at init (<anonymous>:888:3209)
    at new SlickGrid (<anonymous>:888:65878)
    at x.render (<anonymous>:837:3928)
    at p.render (<anonymous>:533:1836)
    at p.render (<anonymous>:539:2094)
    at render (<anonymous>:533:1836)
    at u.render (<anonymous>:533:1836)
    at n.render (<anonymous>:533:1836)
    at n.build (<anonymous>:533:2446)
    at n.renderTo (<anonymous>:533:2399)
```
#### Screenshots or screencasts of the bug in action
![Screen Shot 2020-03-25 at 9 24 15 AM](https://user-images.githubusercontent.com/15659110/77546815-6e129b00-6e7a-11ea-8913-289a6d8b413e.png)

**Comment by philippjfr** [comment]
I think this is a JupyterLab extension issue. I'll have to publish a new version. The main issue there is that the new version will not be compatible with HoloViews<1.13.0...

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/pyviz_comms/pull/51

**Comment by philippjfr** [comment]
Seems to be compatible with older HoloViews versions too, which was worrying me.

**Comment by philippjfr** [comment]
Fixed, @pyviz/jupyterlab_pyviz is now published.

**Comment by kcpevey** [comment]
Thanks!
