### ISSUE TITLE
Selection1D never gets the points?

### ISSUE THREAD

**Issue by afonit** [holoviz/holoviews#4350]
#### ALL software version info
![image](https://user-images.githubusercontent.com/1798497/78139575-bd1a7c00-73f6-11ea-9895-25429b829aaa.png)
This is on windows 10 (I tried this on Linux and the selection coordinates were passed through to the other chart)
I also built a clean conda environment on windows 10 to test and still the points were not passed over.

#### Description of expected behavior and the observed behavior
![no_points_passed](https://user-images.githubusercontent.com/1798497/78139879-25695d80-73f7-11ea-9e38-f59b6683fd78.gif)

#### Complete, minimal, self-contained example code that reproduces the issue
I am using a direct copy of this code/example: http://holoviews.org/reference/streams/bokeh/Selection1D_points.html

#### Stack traceback and/or browser JavaScript console output
Pulling up Chrome's developer tools I see this in the console:
```
localhost:8888/api/kernels/c2143615-0857-4c65-95a0-c95907bea20c
vendors~main.fd97bc9af8abf41fe337.js:161314 Starting WebSocket: ws://localhost:8888/api/kernels/ec078ef0-1711-46d4-ba02-e7c8f3b26df1
vendors~main.fd97bc9af8abf41fe337.js:294217 Error: widget model not found
    at WidgetManager.get_model (vendors~main.fd97bc9af8abf41fe337.js:190704)
    at WidgetRenderer.renderModel (vendors~main.fd97bc9af8abf41fe337.js:294210)
renderModel @ vendors~main.fd97bc9af8abf41fe337.js:294217
(unknown) [bokeh] setting log level to: 'info'
(unknown) [bokeh] document idle at 86 ms
lab:1 Access to font at 'about:blank' from origin 'http://localhost:8888' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
about:blank:1 Failed to load resource: net::ERR_FAILED
(unknown) [bokeh] document idle at 98 ms
```

**Comment by philippjfr** [comment]
Is this in JupyterLab? Did you install the jupyterlab extension?

**Comment by afonit** [comment]
Philip, sadly that is the case, in the new environment I did not install the extension.

I do see three related to pyviz, is one of these preferred over the others, or do all three need to be installed?

@pyviz/jupyterlab_pyviz
@pyviz/jupyterlab_holoviews
@bokeh/jupyter_bokeh

**Comment by philippjfr** [comment]
Only `@pyviz/jupyterlab_pyviz` is needed for HoloViews/Panel output. It may be the case that @pyviz/jupyterlab_holoviews interferes with the pyviz one so I would delete it.

**Comment by philippjfr** [comment]
Did that fix it?

**Comment by afonit** [comment]
Yes
