### ISSUE TITLE
RangeToolLink does not update datashaded target plot

### ISSUE THREAD

**Issue by mmorys** [holoviz/holoviews#4352]
#### Software version info
Ubuntu 18.04
python 3.7.6
bokeh 2.0.1
holoviews 1.13.1
notebook 6.0.3
browser: Chromium 80.0.3987.149

#### Description of expected behavior and the observed behavior
When using RangeToolLink and Datashader, the datashaded target plot does not update when the edges of the range tool are moved. The datashaded target plot only updates when the entire range tool is shifted.

#### Complete, minimal, self-contained example code that reproduces the issue

```
# minimal_example.py

import holoviews as hv
import numpy as np
import pandas as pd
import panel as pn
from holoviews.operation.datashader import datashade, dynspread
from holoviews.plotting.links import RangeToolLink

hv.extension('bokeh')
renderer = hv.renderer('bokeh')

# Create dummy dataset
num_pts = 1000
df = pd.DataFrame({'x':np.linspace(0,100,num_pts), 'y':np.random.random(num_pts)})

# Create scatterplot
hv_plot = hv.Scatter(df, 'x', 'y')

# Datashade plots
reference_plot = dynspread(datashade(hv_plot).opts(axiswise=True))
target_plot = dynspread(datashade(hv_plot))

# Create range tool link
range_tool_link = RangeToolLink(reference_plot, target=target_plot)

# Create bokeh doc
pn.Column(reference_plot, target_plot).servable()

# Run example using 'panel serve --show minimal_example.py' from console
```

#### Screenshots or screencasts of the bug in action
![rtlink_bug_video](https://user-images.githubusercontent.com/10374345/78148792-3e780b80-7403-11ea-8853-57a748728ba8.gif)

**Comment by srcoulombe** [comment]
Software version info

Windows 10
python 3.8.5
bokeh 2.0.1
holoviews 1.13.3
notebook 6.1.1
browser: Firefox

I couldn't reproduce the bug, see below:

![minimal_example_update](https://user-images.githubusercontent.com/19175862/103448925-54ef1400-4c6e-11eb-87cb-846e13f5dc94.gif)

**Comment by philippjfr** [comment]
Also appears to work for me, could you upgrade to HoloViews 1.14.1 and see if that fixes it for you?

**Comment by michaelaye** [comment]
i think it's fair to close?
