### ISSUE TITLE
Param Deprecation for title_format

### ISSUE THREAD

**Issue by TylerTCF** [holoviz/holoviews#4353]
Getting the below error when using holoviews and hvplot for overlaid layouts.  Do I need to change something, or is this core code in holoviews and hvplot.

`WARNING:param.OverlayPlot581527: title_format is deprecated. Please use title instead`

Sample Code
`sliced.hvplot.scatter(x='Year', y='Rate',\
                            title=str(sliced.iloc[0, 0]),\
                            legend=False,\
                            height=300, \
                            width=400,\
                            ylim=(-.05, 1),\
                            xlim=(2012.5, 2019.5)\
                           )*\
    hv.Slope.from_scatter(hv.Points(sliced[(sliced.serial==temp.iloc[i, 13])].filter(['Year', 'Rate'])))
`
Using Bokeh as the extension (v. 2.0.4) and holoviews (1.13.1).  hvplot in this example is version 0.5.2.

**Comment by philippjfr** [comment]
This has already been fixed in hvPlot. We just need a release.
