### ISSUE TITLE
Params support for unwatching

### ISSUE THREAD

**Issue by analog-cbarber** [holoviz/holoviews#4360]
The `Params` stream class will watch the parameters by default:

```python
        if watch:
            # Subscribe to parameters
            keyfn = lambda x: id(x.owner)
            for _, group in groupby(sorted(parameters, key=keyfn)):
                group = list(group)
                group[0].owner.param.watch(self._watcher, [p.name for p in group])
```

but it does not save the created `Watcher` objects returned by the `watch` method, 
so there is no easy way to unwatch them later. So if you are done with the stream but 
not the underlying parameters the stream will be kept alive and will continue to get events.

You can work around this by constructing with `watch=False` and duplicating
the code above, but it would be much nicer if this ability was built into `Params`
itself.

**Comment by petros1999** [comment]
Hi there. Μe and my collaborator, would like to work with that issue. As novices to programming we are, we would appreciate any suggestions or guidelines conserning the building of the upper ability into Params, in order to have a more favorable start of our work. Thanks in advance

**Comment by analog-cbarber** [comment]
I just made a subclass to work around this:

```python
class ParamStream(holoviews.streams.Params):
    """Extends :class:`holoviews.streams.Params` class.

    Specifically provides the ability to unregister parameter watching
    through the :meth:`unwatch` method.
    """

    def __init__(self, parameterized=None, parameters=None, watch=True, watch_only=False, **params):
        super().__init__(
            parameterized = parameterized,
            parameters = parameters,
            watch = False,
            watch_only = False,
            **params
        )

        # Super class does not keep track of watchers, so we have to duplicate code
        # here. See https://github.com/holoviz/holoviews/issues/4360.
        self._watchers = [] # type: List[Watcher]
        if watch:
            # Subscribe to parameters
            keyfn = lambda x: id(x.owner)
            for _, group_iter in groupby(sorted(self.parameters, key=keyfn)):
                group = list(group_iter)
                watcher = group[0].owner.param.watch(self._watcher, [p.name for p in group])
                self._watchers.append(watcher)

    def unwatch(self):
        """Stop watching parameters."""
        for watcher in self._watchers:
            watcher.inst.param.unwatch(watcher)
        self._watchers.clear()
```

Feel free to copy.

**Comment by philippjfr** [comment]
We'd very much appreciate a PR adding the `unwatch` support. Let me know if you need any help contributing. Sadly we don't have a developer guide yet, but you could roughly follow this one: https://panel.holoviz.org/developer_guide/index.html and then replace the `develop_install` step with this:

```
doit develop_install -c pyviz/label/dev  -c bokeh -c conda-forge -o unit_tests
```

**Comment by philippjfr** [comment]
Thanks for contributing @ alexbraditsas!
