### ISSUE TITLE
pip install holoviews[all] failed

### ISSUE THREAD

**Issue by xavArtley** [holoviz/holoviews#4375]
hello,

when trying to run the command 
`pip install holoviews[all]` I run in the following issue:
```
Collecting bzip2; extra == "all" (from holoviews[all])
  ERROR: Could not find a version that satisfies the requirement bzip2; extra == "all" (from holoviews[all]) (from versions: none)
ERROR: No matching distribution found for bzip2; extra == "all" (from holoviews[all])
```

platform: windows 10
python: 3.8 64bit
fresh install

**Comment by jmarkow** [comment]
Seeing the exact same error running the same command in a fresh conda environment.

platform: Ubuntu Bionic (18.04.4)
python: 3.7

**Comment by pjm4github** [comment]
on windows 10, python 3.7.4 try:

pip install param  
pip install numpy  
pip install pyviz_comms 
pip install panel 
pip install pandas
pip install notebook
pip install bokeh  
pip install networkx 
pip install pillow 
pip install xarray
pip install plotly 
pip install streamz 
pip install datashader
pip install selenium
pip install phantomjs
pip install ffmpeg
pip install cftime
pip install netcdf4
pip install dask
pip install scipy
pip install shapely
pip install scikit-image
pip install mock
pip install flake8
pip install coveralls
pip install path.py
pip install matplotlib
pip install nbsmoke
pip install pytest-cov
pip install nose
pip install awscli
pip install deepdiff
pip install nbconvert
pip install jsonschema
pip install cyordereddict
pip install ipython
pip install spatialpandas
pip install pscript

You may need to be administrator for cyordereddict

**Comment by philippjfr** [comment]
Sorry for the **long** delay. Please reopen if the issue still occurs, I wasn't able to reproduce anymore.
