### ISSUE TITLE
Exporting HoloMap to slides (reveal.js) from notebook

### ISSUE THREAD

**Issue by maciekgroch** [holoviz/holoviews#4381]
I am trying to save a jupyter notebook with a holomap in form of slides. For the sake of this discussion i used the example provided on your website: 
```python
import holoviews as hv
import numpy as np

hv.extension('plotly')

frequencies = [0.5, 0.75, 1.0, 1.25]

def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

curve_dict = {f:sine_curve(0,f) for f in frequencies}
hmap = hv.HoloMap(curve_dict, kdims='frequency')
hmap
```
which gives me a nice interactive plot. 
However, when I try to export it to html or slides the plot is missing. 
![image](https://user-images.githubusercontent.com/22051728/79313608-dfd18800-7f00-11ea-873a-be9fdd7ed6a1.png)

When I use different backend (bokeh) everything works perfectly. Any idea what is going wrong?
![image](https://user-images.githubusercontent.com/22051728/79313654-f24bc180-7f00-11ea-92d7-60d33a7c93e0.png)

It seems that the data is inside the output file (the sizes are the same). 

I googled the shit out of the problem... however, I cannot find any answer (I tried adding plotly.js to the directory where I run nbconvert etc.)

**Comment by philippjfr** [comment]
Sorry I didn't reply earlier. Are you seeing any errors in your browsers JS console?

**Comment by philippjfr** [comment]
Closing as non-reproducible, please reopen if you can provide more detail, e.g. JS console errors along with versions of Panel and HoloViews.
