### ISSUE TITLE
Support Combination Group and Split Violins

### ISSUE THREAD

**Issue by mas-dse-juremigi** [holoviz/holoviews#4382]
I would like to be able to a combination grouped and split violin plot with support for additional grouping levels (a combination of the 2 plots in the image below)
![image](https://user-images.githubusercontent.com/14811322/79390545-bde9fc80-7f24-11ea-8d10-bd54dfc40a9c.png)

Plotly currently supports 
Currently, to the best of my knowledge, holoviews only supports grouped violins or split violins.

Additionally, be able to subplot these violins as facets across additional dimensions. 

#### Describe the solution you'd like
an easy way to specify group categories and the category to split on simultaneously, ie:
violin.opts(opts.Violin(groups=hv.dim( split=hv.dim('foo'), split=hv.dim('bar'), clone=True)

**Comment by ahuang11** [comment]
I think it's already supported:
```
import numpy as np
import holoviews as hv
hv.extension('bokeh')

import seaborn as sns
sns.set(style="whitegrid")
tips = sns.load_dataset("tips")

import pandas as pd
tips = pd.concat([
    tips.loc[tips['day'] == 'Thur'],
    tips.loc[tips['day'] == 'Fri'],
    tips.loc[tips['day'] == 'Sat'],
    tips.loc[tips['day'] == 'Sun']
])

hv.Violin(tips, ['day', 'sex', 'smoker'], 'total_bill').opts(ylim=(-10, 60), width=600, split='smoker')
```
![image](https://user-images.githubusercontent.com/15331990/79659401-55478d80-8179-11ea-99a9-a836118628e7.png)
