### ISSUE TITLE
Reference manual needs graphviz installed when built

### ISSUE THREAD

**Issue by dmcooke** [holoviz/holoviews#4391]
The API documentation on the website includes graphviz "cruft" in most of the pages,
making it hard to read. For instance, http://holoviews.org/reference_manual/holoviews.plotting.bokeh.html is particularly bad. It would appear that the documentation
is built without graphviz installed, and so sphinx is including the generated inheritance
diagram as just the raw graphviz code.

I *think* you can install graphviz with conda in .travis.yml in the '&doc_build' section,
but I know little about conda or travis.

(Arguably, this a Sphinx bug: it shouldn't leave the raw code in output if it can't run dot.)

**Comment by jbednar** [comment]
D'oh!  That's indeed unreadable.  It must have been that graphviz was previously installed anyway and so we didn't add it explicitly, but now it's no longer installed. If having it installed would be sufficient to fix this, I think it would mean adding graphviz to `extras_require['doc']` in setup.py.

**Comment by jbednar** [comment]
The HoloViews releases page is also currently broken (missing headings for all but the current release), so I think we need some fixes and then to rebuild the site.

**Comment by philippjfr** [comment]
graphviz was added. It's still not all that readable in some cases but it's working as intended.
