### ISSUE TITLE
incompatibility with bokeh 2.0.2?

### ISSUE THREAD

**Issue by jbhiatt** [holoviz/holoviews#4406]
hello,
first of all thank you for this amazing tool! i just updated my jupyter lab, bokeh, and holoviews with conda to the latest versions and now my plotting is totally broken without any errors. i just see an empty output cell even with a very basic plotting command (like a single hv.Scatter element). however it works if i use the matplotlib extension. 
i am using the following:
holoviews 1.13.2 
bokeh 2.0.2
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.3
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.1.3
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3

are there known incompatibilities? thank you!

**Comment by jbhiatt** [comment]
update: downgrading my bokeh to 2.0.1 fixed the problem. not sure what is going on with 2.0.2.

**Comment by philippjfr** [comment]
Thanks for the issue, I've been using 2.0.2 daily without issues so I'm not sure what the issue might be. Do you see any errors on your JS console?

**Comment by philippjfr** [comment]
Oh could you also report your version of Panel?

**Comment by jbhiatt** [comment]
so strange! in the process of trying to figure out what my panel version was (0.9.5) and where to find my JS console, and inspired by our experience, i tried upgrading to bokeh 2.0.2 again and now it is working. thank you for your help and sorry for the trouble!

**Comment by ivirshup** [comment]
I believe I've been running into the same issue ... which seems to have magically fixed itself while I was documenting it. 

Here's what I was originally seeing:

![output](https://user-images.githubusercontent.com/8238804/84099509-1cc38200-aa4d-11ea-9776-0e786fd2dddd.gif)


<details>
<summary> Environment when it fails </summary>

```
-----
holoviews           1.13.2
pandas              1.0.3
sinfo               0.3.1
vega_datasets       0.8.0
-----
PIL                 7.1.2
appnope             0.1.0
attr                19.3.0
backcall            0.1.0
bokeh               2.0.2
cffi                1.13.2
cftime              1.0.3.4
colorama            0.4.1
concurrent          NA
cycler              0.10.0
cython_runtime      NA
dateutil            2.7.5
decorator           4.3.2
defusedxml          0.5.0
encodings           NA
entrypoints         0.3
future_fstrings     NA
genericpath         NA
google              NA
holoviews           1.13.2
idna                2.8
ipykernel           5.3.0
ipython_genutils    0.2.0
jedi                0.16.0
jinja2              2.10.1
jsonpointer         1.14
jsonschema          3.0.2
kiwisolver          1.0.1
markupsafe          1.1.0
matplotlib          3.2.1
mistune             0.8.4
mpl_toolkits        NA
nbconvert           5.6.0
nbformat            4.4.0
ntpath              NA
numpy               1.18.5
opcode              NA
pandas              1.0.3
pandocfilters       NA
panel               0.9.5
param               1.9.3
parso               0.5.2
pexpect             4.6.0
pickleshare         0.7.5
pkg_resources       NA
posixpath           NA
prometheus_client   NA
prompt_toolkit      2.0.9
ptyprocess          0.6.0
pvectorc            NA
pydoc_data          NA
pyexpat             NA
pygments            2.3.1
pyparsing           2.3.1
pyrsistent          NA
pytz                2018.9
pyviz_comms         0.7.4
ruamel              NA
send2trash          NA
simplejson          3.16.0
sinfo               0.3.1
sitecustomize       NA
six                 1.14.0
sphinxcontrib       NA
sre_compile         NA
sre_constants       NA
sre_parse           NA
storemagic          NA
testpath            0.3.1
tornado             6.0.3
tqdm                4.46.1
traitlets           4.3.3
typing_extensions   NA
uritemplate         3.0.0
vega_datasets       0.8.0
wcwidth             NA
yaml                3.13
zmq                 18.0.1
-----
IPython             7.15.0
jupyter_client      6.1.3
jupyter_core        4.6.3
jupyterlab          2.1.4
notebook            6.0.3
-----
```


</details>

It works fine if I install bokeh 2.0.1:

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/8238804/84099583-4a103000-aa4d-11ea-878a-7cf3bc3b2396.png">

Switching to bokeh 2.0.2 seemed to make the problem come back, until I tried switching one last time and things now work. There might still be a heisenbug out there.
