### ISSUE TITLE
conda install -c conda-forge panel=0.9.3 Cannot solve environment

### ISSUE THREAD

**Issue by MOLeary25** [holoviz/holoviews#4408]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by MOLeary25** [comment]
import HoloViews in Python 3.8 results in the error 'encode_utf8' from 'bokeh.util.string'

Followed error reported and resolution was to install later panel version

conda install -c conda-forge panel=0.9.3

When I run this I get a continual solving environment and never ends

**Comment by MOLeary25** [comment]
Didn't mean to close - rookie mistake

When I try to import HoloViews which I have installed I get the following error:

ImportError: cannot import name 'encode_utf8' from 'bokeh.util.string' (/Users/martin.oleary25/opt/anaconda3/lib/python3.7/site-packages/bokeh/util/string.py)

I have tried browsing this and other sites to see if this issue has been reported and I thought that the resolution would be 

to run Conda install-forge panel=0.9.3

However, when I try to do this I get the reported problem (needless to say the initial problem has not been resolved). 

I am new to python, and computing generally (coming to this late in life, I am studying and running this code is important for my course, but I am just getting frustrated - my knowledge of systems is limited - I am trying to get a handle on this whilst doing the course but it is proving challenging)

**Comment by philippjfr** [comment]
Try `conda install -c conda-forge panel=0.9.5 bokeh=2.0.2 holoviews=1.13.2`
