### ISSUE TITLE
hv.save and hv.output always output html for a dynamic map

### ISSUE THREAD

**Issue by b-dawes** [holoviz/holoviews#4409]
When calling `hv.save()` on a dynamic map object, holoviews ignores the `fmt` parameter as well as the file ending and always saves the output in html format with a .html file ending. `hv.output()` will also ignore the `fig` parameter.

I ran into this issue while trying to save a plot created with datashade as it generates a dynamic map object by default. 

Example:
```python
import holoviews as hv
hv.extension("bokeh")

plot = hv.DynamicMap(hv.Points(([1,2],[1,2])))

hv.save(plot, "test1.png")
hv.save(plot, "test2", fmt="png")
hv.save(plot, "test3.png", fmt="png")

hv.output(plot, fig="png")
```

The above code will create files `test1.html`, `test2.html`, and `test3.html` and an interactive output will be shown.

I would expect these calls to produce a static image of the current state of the dynamic map. If that is not possible, I think these calls should throw an error stating that png format is incompatible with a dynamic map object.

I am using holoviews 1.13.2 and python 3.7.1. It is running inside JupyterLab 1.2.6 on a Windows 10 machine.

**Comment by philippjfr** [comment]
Thanks your suggestions all seem sensible.
