### ISSUE TITLE
Support Path element in plotly backend

### ISSUE THREAD

**Issue by analog-cbarber** [holoviz/holoviews#4426]
Currently `Path` and related `Contours` plot elements are not supported in the plotly backend. It would be nice to have these.

See https://plotly.com/python/shapes/

**Comment by jbednar** [comment]
If you're up for it, you could try comparing an existing element like Curve that is implemented for both Plotly and Bokeh, seeing how the two implementations are similar and different, and then try to make a Plotly element for Path or Contours following the Bokeh example.  Making new Element types is much easier than a lot of changes one might want to make to HoloViews, particularly when there's already a guide to follow...

**Comment by analog-cbarber** [comment]
I don't actually need this right now, but I will give it a try when I have the chance...

**Comment by philippjfr** [comment]
This was in fact already implemented.
