### ISSUE TITLE
Session stateless workflow for HoloViews

### ISSUE THREAD

**Issue by jonmmease** [holoviz/holoviews#4433]
This issue is the result of an offline discussion on what it would take to make it possible to serve interactive HoloViews objects in Plotly Dash applications.

The translation of Dash callback data (e.g. from Zoom or Box Selection events) into the inputs to HoloViews interactive streams (e.g. `RangeXY` and `BoundsXY`) is relatively straightforward.

The more complex problem is the mismatch in state models between HoloViews and Dash.  

### HoloViews state model
The current HoloViews architecture is optimized for responsiveness.

Conceptually, you can decompose a rendered HoloViews object into:
  1. A plot object in the backend library (Plotly or Bokeh)
  2. A collection of interactive streams. The inputs to these streams come from callbacks on the plot object for things like zoom and selection events.

The relatively expensive operation of transforming a HoloViews object into a plot object is performed only once. After this initial "render", the plot object is efficiently mutated in response to updates to the stream values.

### Dash state model
Dash's architecture is optimized for horizontal scalability.

Conceptually, you can decompose a Dash application into:
 1. A tree of components (e.g. dropdowns, sliders, figures, etc.), where each component exposes a set of properties (e.g. the slider value).
 2. A collection of pure functions that each input a collection of component property values and output a different collection of component property values.

This approach is more scalable than the current HoloViews architecture because the server does not need to store the current session state for every simultaneous user of the app. It is less responsive than the current HoloViews architecture because the server can't make small efficient updates to the prior state of a figure in response to a callback. Instead, it must fully reconstruct the figure in response to changes in the property values that the figure depends on.

### Questions for discussion
 1. Is the current state model a fundamental characteristic of HoloViews, or is it (at least conceptually) an implementation detail?
 2. If it's an implementation detail, what would it take to support a "session stateless" paradigm as well?

My intuition is that the current state model is an implementation detail, but one that is pretty fully baked in due to the fact that this aligns with the Bokeh+Panel state model.

### Potential paradigm.
As I've thought more on this, I've come up with one potential approach.  I'm not sure if it could be made efficient enough to be practical, but I don't think it require a major change to how HoloViews works internally.

Suppose we perform the relatively expensive transformation from HoloViews element to plot+streams once during application initialization.  Could we develop an efficient clone operation, one that would clone both the plot object and the associated streams (wiring up the cloned streams to reference the cloned plot object)? 

If so, a pure function (like a Dash callback) could perform this clone at the start of a function. Then inside the function it could safely mutate the cloned plot by updating the clone's stream values, and finally return the cloned and mutated figure. This would result in an externally pure function because the mutation would not be visible outside the function.

My intuition is that the most important consideration in making this clone efficient would be to share as much state as possible between the original and the clone.  The assumption would be that the cloned figure will only be mutated using the current set of streams, so we would only need to fully clone the portions of the figure that can be mutated by the streams.

This might be complicated to implement, but it would avoid cloning the raw data arrays.  Or, maybe we could start out with performing a deep clone on everything except the data arrays and see if that's fast enough.

**Comment by jonmmease** [comment]
#### Another approach.
Here's another approach. We could build a function to transform a Dynamic HoloViews object into a pure function of its stream arguments.  This would involve traversing the tree of callbacks/inputs/streams for a HoloViews object (the way `link_selections` does), collecting the chain of pure Python functions that get called when a stream update is triggered, and then composing all of these into a stateless Python function that inputs the stream argument values and outputs a non-dynamic HoloViews Element.  This resulting function would no longer include any streams or internal state, so it would be safe to call it in a multi-threaded context.

At the moment, this approach feels a lot cleaner and like it would be potentially useful in a variety of contexts, and it wouldn't require any changes to how HoloViews handles stream state or things like memoization.

**Comment by jonmmease** [comment]
Maybe what I'm talking about is actually the inverse of `DynamicMap.collate`.

```python
    def collate(self):
        """Unpacks DynamicMap into container of DynamicMaps

        Collation allows unpacking DynamicMaps which return Layout,
        NdLayout or GridSpace objects into a single such object
        containing DynamicMaps. Assumes that the items in the layout
        or grid that is returned do not change.

        Returns:
            Collated container containing DynamicMaps
        """
        ...
```

The transform I'm talking about could be something like: "packs a container of DynamicMaps into a single DynamicMap that returns a Layout".  If this transform lifted all of the nested `Streams` up to the top-level of the resulting Dynamic Map, this would be very nearly what I'm after.

@philippjfr @jlstevens is there anything along the lines of an "uncollate" operation already in HoloViews? If not, does this idea make sense?

The only problem I see with this approach/API is that there could be a lot of argument name conflicts, and I'd rather the resulting `DynamicMap` function accept positional arguments that match the order of the streams (where each argument would accept a `dict` of the params produced by the stream).  Would it make sense for `DynamicMaps` to have an option to configure whether function arguments are specified as named kwargs (current behavior that's useful for writing DynamicMap functions by hand), or positional args (easier to work with for programmatically generating `DynamicMap` functions).

**Comment by jonmmease** [comment]
**Update:**  My current plan is to implement a `DynamicMap.uncollate` method on top of #4534 and #4532.

```python
    def uncollate(self):
        """Packs Layout of DynamicMaps into a single DynamicMap that returns a Layout

        Uncollation allows packing a Layout of DynamicMaps into a single DynamicMap that returns
        a Layout of simple (non-dynamic) elements. All nested streams are lifted to the resulting 
        DynamicMap, and are available in the `streams` property.  The `callback` property of the
        resulting DynamicMap is a pure, stateless function of the stream values. To avoid stream
        parameter name conflicts, the resulting DynamicMap is configured with
        positional_stream_args=True, and the callback function accepts stream values
        as positional dict arguments.

        Returns:
            DynamicMap that returns a container
        """
        ...
```

Note: Initially I'm only focusing on `Layout` containers, I haven't thought about it deeply enough to decide whether this makes sense for `NdLayout` or `GridSpace` containers.

With this approach, the Dash adapter will:
 1. Call `uncollate`
 2. Use the `streams` list from the resulting `DynamicMap` to build a mapping from Dash callbacks to the stream parameter values expected by the `callback` function.
 3. Build a Dash callback function that inputs Dash callback states, transforms them into HoloViews stream values, calls the pure `callback` function with these stream values, then transforms the resulting HoloViews objects into Plotly figures to return back to Dash.

I'm pretty happy with how well this integrates with existing HoloViews constructs, while solving the original need of making it possible to build dynamic HoloViews objects in a session stateless context.

Does this make sense to everyone?

**Comment by jbednar** [comment]
Sounds good to me!
