### ISSUE TITLE
Properties of plot change with newer versions of holoviews

### ISSUE THREAD

**Issue by Julian3012** [holoviz/holoviews#4445]
I use the DynamicMap and datashader to generate a plot with bokeh widgets. Yesterday I updated the packages to newer versions and now I get some errors when I try to integrate the plot into the bokeh frontend.

#### ALL software version info
Operating system: macOS Catalina

Old versions:
bokeh              1.0.4              
datashader         0.6.9              
holoviews          1.11.3       
      
New versions:
bokeh              2.0.2              
datashader         0.8.0              
holoviews          1.13.2             

#### Description of expected behavior and the observed behavior
Before the change I could integrate the plot with the state property and everything got displayed while deploying with Bokeh serve.
After the change to the new Libraries plot.state gives me the error:
```
'HoloViews' object has no attribute 'state'
```

I also tried plot.layout which gave me this error:
```
Only LayoutDOM items can be inserted into a layout.
                Tried to insert: Row
    [0] HSpacer()
    [1] HoloViews(DynamicMap, center=True, renderer=BokehRenderer, widget_location='right')
    [2] HSpacer()
    [3] Column
        [0] VSpacer()
        [1] WidgetBox
            [0] IntSlider(end=46, margin=(20, 20, 20, 20), name='lev', width=250)
        [2] VSpacer() of type <class 'panel.layout.Row'>
```
The documentation of holoviews still uses the plot.state scheme. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
dm = hv.DynamicMap(self.buildTrimesh, kdims=self.freeDims).redim.range(
                **ranges
            )
...
preGraph = (
                    rasterize(dm)
                    .opts(**rasterizedgraphopts)
                    .opts(
                        symmetric=self.cSymmetric,
                        logz=self.cLogZ,
                        color_levels=self.cLevels,
                    )
                )
...
plot = renderer.get_widget(graph.opts(**totalgraphopts), "widgets")
...
lArray.append([column(widget1)])
lArray.append([column(widget2)])
lArray.append([column(widget3)])
lArray.append([column(widget4)])
lArray.append([plot.state])

l = layout(lArray)
curdoc().add_root(l)
```

**Comment by philippjfr** [comment]
HoloViews now generates bokeh widgets via [Panel](https://panel.pyviz.org/), which allowed us to remove all widget related code from HoloViews itself. This means the API also had to change in the 1.13.0 release. The `.get_widget` method now returns a Panel object, which you can in turn render to bokeh:

```python
plot = renderer.get_widget(graph.opts(**totalgraphopts), "widgets")
bokeh_model = plot.get_root()
```

Alternatively you can use Panel more directly giving you more direct control over the widget location:

```python
hv_pane = pn.pane.HoloViews(hv_obj, widget_location=..., center=True/False)
bokeh_model = hv_pane.get_root()
```

**Comment by Julian3012** [comment]
Thank you for your fast answer! 
When I now change the actual line to
```
...
lArray.append([bokeh_model])
...
```
I do not get an error anymore, but the plot is still not displayed. The code position only outputs 'projection' and does not execute the remaining code.
