### ISSUE TITLE
Confusing example on sorting columns for tabular data

### ISSUE THREAD

**Issue by smsaladi** [holoviz/holoviews#4473]
The example here on Sorting by columns with Tabular data is somewhat confusing as each of the four plots look the same.

http://holoviews.org/user_guide/Tabular_Datasets.html#Sorting-by-columns

<img width="1208" alt="Screen Shot 2020-06-11 at 12 32 26 AM" src="https://user-images.githubusercontent.com/2942215/84358017-5d211e00-ab7b-11ea-95d8-b9787fdfad58.png">

**Comment by philippjfr** [comment]
Thanks @smsaladi, looks like a bug to me.
