### ISSUE TITLE
Ability to change html <title> value when exporting via hv.save()

### ISSUE THREAD

**Issue by drossaop** [holoviz/holoviews#4474]
When I export to an html file, the `<title>` value is always "Panel".

I believe this started happening as of version 1.13. Prior to that, I don't believe a `<title>` was set, so the file name displayed.

It would be wonderful to be able to specify a title for the page when exporting via hv.save().

**Comment by philippjfr** [comment]
So this is in fact exposed at the panel level, so if you really need this you can use:

```python
import panel as pn
pn.io.save.save(obj, filename, title='Blah')
```

We just need to expose it from HoloViews.

**Comment by drossaop** [comment]
Ah. Thank you. I did go looking in Panel, but obviously missed it.
