### ISSUE TITLE
link_selections causes elements to lose previous streams links

### ISSUE THREAD

**Issue by mmorys** [holoviz/holoviews#4488]
#### Software version info
python 3.7.7
holoviews 1.13.2
panel 0.9.5
param 1.9.3
pandas 1.0.3
numpy 1.18.1

#### Description of expected behavior and the observed behavior
When holoviews elements are created, such as Points, and a stream is linked to that element, the stream should be maintained when the element is used in `link_selections`. Observed behavior shows that `link_selections` causes all elements passed into it to lose their links to streams other than those created by `link_selections`.

Digging through the code, I found a potential solution to be a change in the `link` flag from `False` to `True` when cloning the Element in selection.py
https://github.com/holoviz/holoviews/blob/63ce77468117cf0c3c9c4927f7542f4d343a506e/holoviews/selection.py#L131

Proposed change: 
`element = hvobj.clone(link=False)` --> `element = hvobj.clone(link=True)`

I do not understand the underlying reason for setting `link=False`, and the proposed change may break some other functionality. There may be a safer/more general way to keep existing streams around.

#### Complete, minimal, self-contained example code that reproduces the issue
```
import numpy as np, pandas as pd, holoviews as hv, panel as pn
from holoviews.selection import link_selections
from holoviews.streams import RangeX

hv.extension('bokeh')

# Create dummy dataset
num_pts = 1000
df = pd.DataFrame({'x': np.linspace(0, 1, num_pts),
                   'y0': np.cumsum(np.random.randn(num_pts)),
                   'y1': np.cumsum(np.random.randn(num_pts)),
                   'y2': np.cumsum(np.random.randn(num_pts))})
ds = hv.Dataset(df)

# Create source plot
plots = [hv.Points(ds, ['x','y0'])]
# Create stream from x_range of the first plot
range_x_stream = RangeX(source=plots[0])
# Create second plot that only shows values visible in the x range of the first plot
plots.append(
    hv.DynamicMap(lambda x_range:
                  hv.Points(ds.select(x=x_range), ['y1', 'y2']) if isinstance(x_range, tuple) else hv.Points(ds, ['y1', 'y2']),
                  streams=[range_x_stream]))

# Link two plots together
unlinked = hv.Layout(plots)
linked = link_selections(unlinked)

# # Behavior 1: RangeX stream working as expected when using unlinked Layout (uncomment line below)
# pn.Column(unlinked).servable()
# # Behavior 2: RangeX stream not working when using link_selections, except when proposed change made (uncomment line below)
pn.Column(linked).servable()
```

### Behavior 1: Baseline not using `link_selections`
![holoviews_behavior_1](https://user-images.githubusercontent.com/10374345/85182455-b6154400-b256-11ea-89c9-920b5d485312.gif)
### Behavior 2: Using `link_selections` in holoviews 1.13.2
![holoviews_behavior_2](https://user-images.githubusercontent.com/10374345/85182465-bb728e80-b256-11ea-8531-6613128798ad.gif)
### Behavior 3: Using `link_selections` with proposed change
![holoviews_behavior_3](https://user-images.githubusercontent.com/10374345/85182469-be6d7f00-b256-11ea-85d3-d973d6e10850.gif)

**Comment by jlstevens** [comment]
Thanks for reporting this! Definitely looks like a bug to me: any streams that aren't clashing with what is required by linked selections shouldn't be lost. 

> Digging through the code, I found a potential solution to be a change in the link flag from False to True when cloning the Element in selection.py

```
element = hvobj.clone(link=False) 
```

That sounds very plausible! We'll have to think about the consequences of unlinking in the clones and maybe it will have to be an option as the `link_selections` level...

**Comment by ppwadhwa** [comment]
I tried it out, and I can confirm that the behavior you want is not working as you'd expect.
