### ISSUE TITLE
hv.extension('bokeh', inline=False) doesn't load javascript from CDN

### ISSUE THREAD

**Issue by ruoyu0088** [holoviz/holoviews#4490]
#### ALL software version info

* Holoviews 1.13.2
* jupyterlab 2.1.0
* bokeh 2.0.1
* panel 0.9.5

#### Description of expected behavior and the observed behavior

To reduce the size of the notebooks, I use `holoviews.extension('bokeh', inline=False)`, but the size of the notebook doesn't change.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import holoviews as hv
hv.extension('bokeh', inline=False)
```

and then check the size of the notebook.

I found how to fix this:

https://github.com/holoviz/holoviews/blob/0693a07f2af1095bca84be9c9a8a2503d1ded9ab/holoviews/ipython/__init__.py#L188

change the line to `Renderer.load_nb(inline=p.inline)`.

**Comment by philippjfr** [comment]
Oh wow, thanks for catching that. A PR would be very welcome.
