### ISSUE TITLE
DynamicMap returning NdOverlay not updating correctly

### ISSUE THREAD

**Issue by acapo402** [holoviz/holoviews#4499]
#### ALL software version info
python==3.7
holoviews==1.13.3 
bokeh==2.1.1
pandas==1.0.5
numpy==1.19.0
jupyter core==4.6.3
jupyter-notebook==6.0.3

#### Description of expected behavior and the observed behavior
I want to have a DynamicMap overlay on a scatter plot.
Selecting points on the scatter plot should update an overlay with bounding boxes (as an NdOverlay).

It seems to work regularly when only 1 point is selected, and then another single one is selected.
Selecting more than 1 point, and then selecting another group of points however produces erratic behavior.
The number of bounding boxes seems to be correct, but the locations are wrong.

Sometimes the plot will freeze or the non-selected points will fail to update their alpha, but those kinds of issues are more sporadic. The above issue is consistent.

I've used a global in the function before to confirm that the boxes are getting defined correctly.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import numpy as np
import holoviews as hv
hv.extension('bokeh')

data = pd.DataFrame(np.random.rand(100,2), columns=['x', 'y'])

points_xy = hv.Points(ds, ['x', 'y']).opts(height=750, width=750, tools=['box_select'], nonselection_alpha=0, size=6)

def get_boxes(index):
    boxes={}
    if index:
        for i in index:
            p = points_xy.iloc[i]
            boxes[i] = hv.Box(p['x'], p['y'], 0.05)
    else:
         boxes[0] =  hv.Box(0.5, 0.5, 0)
    return hv.NdOverlay(boxes)

xy_stream = hv.streams.Selection1D(source=points_xy)
boxes_xy = hv.DynamicMap(get_boxes, streams=[xy_stream])

points_xy * boxes_xy

```

#### Screenshots or screencasts of the bug in action

![working](https://user-images.githubusercontent.com/34631309/85652991-43eb9780-b67a-11ea-8432-405138fe540d.png)
![borked](https://user-images.githubusercontent.com/34631309/85652996-477f1e80-b67a-11ea-825a-b26b9ecd7ad1.png)
![extra_borked](https://user-images.githubusercontent.com/34631309/85653002-49e17880-b67a-11ea-83db-df1c2407ac28.png)

**Comment by acapo402** [comment]
Actually, my first picture was supposed to be of it working, but it failed to update the non-selected alpha...
Here is what I would expect
![actually_working](https://user-images.githubusercontent.com/34631309/85653363-f4f23200-b67a-11ea-836f-c338a47cc165.png)

**Comment by jlstevens** [comment]
I've reproduced this and I agree it is not behaving the way I would expect: after selection all selected points should be surrounded by a box. I'll mark this as a bug.

**Comment by Hoxbro** [comment]
I tried this on Holoviews 1.15.4, and the boxes seem to be overlaid correctly. Though, I noticed it was a bit slow for the first selection.

https://user-images.githubusercontent.com/19758978/232275259-10edaf94-9cfc-44f5-b6ba-03b6ca7b83d9.mp4

Will close this issue, but you are welcome to open it again if you still see the problem on the latest release.
