### ISSUE TITLE
HeatMap will not show with option colorbar=True

### ISSUE THREAD

**Issue by jhnbgvan** [holoviz/holoviews#4504]
Dear readers,  
I am trying to run the following code copied from: [https://holoviews.org/reference/elements/bokeh/HeatMap.html](https://holoviews.org/reference/elements/bokeh/HeatMap.html) in a cell of a Jupyter notebook:    
```
data = [(i, chr(97+j),  i*j) for i in range(5) for j in range(5) if i!=j]
hm = hv.HeatMap(data).sort()
hm.opts(xticks=None)
```
At the beginning of the cell, if I add the following options, the heatmap displays nicely:
`%%opts HeatMap[colorbar=False]`

Now if I change the **colobar option to True**, then the heatmap is not displayed.  

I am running a fresh Anaconda Python 3.7 installation of Pyviz on Ubuntu 20.04:
```
pyviz       0.10.3 py_0 pyviz
pyviz_comms 0.7.5  py_0 pyviz
```
Cheers,
Bagvian

**Comment by philippjfr** [comment]
I can reproduce with latest Bokeh and HoloViews, the JS error is:

```
Uncaught Error: ColorBar.bar_line_color given invalid value: {"value":"black"}
```

**Comment by philippjfr** [comment]
Appears to be fixed with latest HoloViews and latest Bokeh.
