### ISSUE TITLE
Make link_selection interact with tables

### ISSUE THREAD

**Issue by DGLaurits** [holoviz/holoviews#4505]
#### Description of problem
I want to be able to have a table that interacts with link_selection. E.g. if I have a plot over some cars, and I Box Select the ones with a max speed above 60 km/h, I want the table to highlight those cars in the same way the scatter plot does. Currently when I use a link_selection on a table the Box Select stops working, which might be a bug.

Down below I've made an exaggerated simple example of the code which is not working
```python

import pandas as pd
import holoviews as hv
from holoviews.selection import link_selections
hv.extension('bokeh')

data = {"x": [1,2,3,4,5], "y": [2,4,5,7,10]}
df = pd.DataFrame(data)
dataset = hv.Dataset(df)
dataset

bars = hv.Bars(dataset, "x", "y")
bars

scatter = hv.Scatter(dataset, "x", "y")
scatter

table = hv.Table(dataset)
table
```

If I only plot the scatter plot and bars, I can Box Select them properly linked:
![image](https://user-images.githubusercontent.com/62091619/86334900-112f3980-bc4e-11ea-8e92-194e4d002999.png)

However, if I add the table to the cocktail, Box Select draws the markup but doesn't mark anything:
![image](https://user-images.githubusercontent.com/62091619/86335637-0a54f680-bc4f-11ea-9d93-b6cc297508c4.png)

#### Solution
The most useful way to solve this would be to make the selected data points go to the top of the table. And then give the cells a different color, so you'd be able to separate them from the remaining data points.

**Comment by MarcSkovMadsen** [comment]
Thanks for trying @DGLaurits .

I really would like to have this. 

Right now my use case a long list of grid sections or an even longer list of Stations in the US providing Weather Forecasts or Weather Observations. I would like to plot them on a map and see the selected rows of the weather grid sections or weather stations in the table.

But in general my experience from table is that when having linked selections in a dashboard my users almost always request ending up with some kind of table where they have access to the underlying data.

Maybe for efficiency reasons it would be nice to be able to limit the number of rows displayed.

**Comment by MarcSkovMadsen** [comment]
### Potential Solution

I have potential solution here https://discourse.holoviz.org/t/how-do-i-link-plots-and-tables/925

![linked-brushing](https://user-images.githubusercontent.com/42288570/86385399-802d8200-bc90-11ea-8851-3b3a14e34dff.gif)

**Comment by jlstevens** [comment]
@MarcSkovMadsen Thanks for posting the workaround on discourse!

From what I can tell, this is a bug in holoviews as you shouldn't have to resort to using panel here. I don't see why the original code posted above shouldn't work. Do you agree @philippjfr ?

**Comment by Sidney-Bishop** [comment]
Hi 
when I try to run the code above from @DGLaurits  I get this error: ValueError: 'mode' is not a property of self (BoxSelectTool(id='1021', ...))

I also get the same error when running the Linked Brushing notebook: [https://holoviews.org/user_guide/Linked_Brushing.html
] 

See attached screen grab. 

Am I missing something obvious?

Any help / suggestions would be appreciated. 

Best Jason

<img width="801" alt="Screenshot 2021-01-17 at 21 21 07" src="https://user-images.githubusercontent.com/7266636/104856318-f2527500-5909-11eb-9ae3-a0e626ddde7f.png">

**Comment by jlstevens** [comment]
At a glance that might be a Bokeh version issue. What Bokeh version are you using?

**Comment by khannaum** [comment]
I have the same issue with following bokeh version

In [3]: bokeh.__version__
Out[3]: '2.0.2'

**Comment by Sidney-Bishop** [comment]
> At a glance that might be a Bokeh version issue. What Bokeh version are you using?

![image](https://user-images.githubusercontent.com/7266636/106122763-f758c500-6150-11eb-8f1b-8907c92a71bd.png)

**Comment by jlstevens** [comment]
HoloViews pins `bokeh >=1.1.0` so that *should* work. It is possible that we missed something where the older version doesn't work anymore (in this case) so could you try to upgrade to bokeh 2.2 to see if that fixes the issue? If not, we'll investigate at the HoloViews level.
