### ISSUE TITLE
Holoviews plots not displaying anymore

### ISSUE THREAD

**Issue by sarahucl94** [holoviz/holoviews#4507]
Hi all,
I have been using holoviews to create chord plots and it was working fine before. Now the plots will not be displayed anymore in my Jupyter notebook. I also tested the package using code available at: https://holoviews.org/reference/elements/bokeh/Chord.html

When I run `hv.Chord(links)` from the above example, I get the following output rather than a plot:
`:Chord   [source,target]   (value)`

If I then run the following:
```
chord.opts(
    opts.Chord(cmap='Category20', edge_cmap='Category20', edge_color=dim('value').str(), 
               labels='name', node_color=dim('index').str()))
```
I get this error
![Screenshot 2020-07-03 at 10 18 50](https://user-images.githubusercontent.com/33125090/86454073-a5fd6a00-bd16-11ea-98cb-82a2c8f6f1d0.jpg)

I was able to plot until two days ago. I have been using `python 3.7.4`
Here are the packages versions:
```
pandas 0.25.3
numpy 1.19.0
holoviews 1.13.3
```
here is my full code: https://github.com/sarahucl94/sharing_repo/blob/master/ROI_connectivity.ipynb

**Comment by philippjfr** [comment]
It looks like you're not loading the extension, have you added `hv.extension('bokeh')` or `hv.extension('matplotlib')` depending on which plotting backend you want?

**Comment by sarahucl94** [comment]
Thank you @philippjfr ! The matplotlib one worked... should have thought of that

**Comment by philippjfr** [comment]
Glad it worked and thanks for reporting back! For user questions feel free to reach out on the project discourse: https://discourse.holoviz.org/
