### ISSUE TITLE
Scatter plot with grouped categorical x axis

### ISSUE THREAD

**Issue by gioarma** [holoviz/holoviews#4509]
I would like to make an overlay of BoxWhisker and Scatter with an categorical x axis with two dimensions. My data is something like

```python
df = pd.DataFrame({
    'A': np.random.randint(0, 2, 100),
    'B': np.random.randint(0, 2, 100),
    'value': np.random.rand(100)
})
```
I can easily get a BoxWhisker with:

```python
hv.BoxWhisker(df, kdims=['A', 'B'],vdims='value')
```
![Schermata 2020-07-06 alle 19 19 10](https://user-images.githubusercontent.com/59478987/86620940-92bff800-bfbd-11ea-98f2-8e47b2d34ca3.png)

But when I try to overlay a Scatter with the data to the Box plot:

```python
hv.BoxWhisker(df, kdims=['A', 'B'],vdims='value')*\
hv.Scatter(df, kdims=['A', 'B'],vdims='value')
```
I get:
```
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
```
And indeed calling just the second line I get the `A` on the x axis and `B` on the y axis, instead of both on the same axis.
![Schermata 2020-07-06 alle 19 24 08](https://user-images.githubusercontent.com/59478987/86621313-45905600-bfbe-11ea-9cef-392086623f06.png)
 
I know this is not a bug and it is intended to work like this, but then I cannot find a way to do what I want.
If instead I just use `A` as key dimension I have no problems with the same code as above:
```
hv.BoxWhisker(df, kdims=['A'],vdims='value')*\
hv.Scatter(df, kdims=['A'],vdims='value').opts(color = 'orange')
```
![Schermata 2020-07-06 alle 19 26 22](https://user-images.githubusercontent.com/59478987/86621506-9b64fe00-bfbe-11ea-830d-ce872939da98.png)

Is there a way to achieve this or would this be a feature request?
If there is a way to do this I think you should implement it in the docs, because I did not see it there.

**Comment by philippjfr** [comment]
Thanks very sensible feature request but it's also a duplicate since it's covered by https://github.com/holoviz/holoviews/pull/3385 and #1668.
