### ISSUE TITLE
hv.save() doesn't include toolbar in HTML in 1.13.3, but does include it in 1.13.2

### ISSUE THREAD

**Issue by Dr-Irv** [holoviz/holoviews#4515]
#### ALL software version info
holoviews 1.13.3  (by using `conda install holoviews=1.13.3`)

#### Description of expected behavior and the observed behavior

I have a Holoviews graphic that I save to an HTML file (and also end up serving via a server).  With Holoviews 1.13.2, the toolbar is there.  With Holoviews 1.13.3, there is no toolbar, so you can't zoom, reset, save, etc.

I had a code working and hours figuring out why upgrading holoviews caused the problem!  Here is a simple example.

#### Complete, minimal, self-contained example code that reproduces the issue

Create a conda environment as follows:
```
conda create --name hvtest python=3.7
conda install holoviews=1.13.3 numpy
conda activate hvtest
```

Using this code: 
```python
import numpy as np
import holoviews as hv
hv.extension("bokeh")

xs = np.linspace(0, np.pi*4, 40)
fname = "hv" + hv.__version__ + ".html"
g = hv.Text(4,0,fname) + hv.Area((xs, np.sin(xs)))

hv.save(g, fname)
```
it will create the file `hv1.13.3.html`.  When you open that file in a browser, it does not have the toolbar.

But if you then do
```
conda install holoviews=1.13.2
```
and run the code, the file `hv1.13.2.html` _does_ have the toolbar.

#### Stack traceback and/or browser JavaScript console output

Not applicable

#### Screenshots or screencasts of the bug in action
Here are the two HTML files side by side.  The one on the left is from Holoviews 1.13.2.  The one on the right is from Holoviews 1.13.3.

![image](https://user-images.githubusercontent.com/15113894/87089265-2c78e680-c204-11ea-85f0-7cbbbdb07850.png)

**Comment by drossaop** [comment]
I can confirm that I'm seeing this as well after an upgrade to 1.13.3.

**Comment by philippjfr** [comment]
This was intentional but probably should have been reserved for 1.14.0. You can restore the old behavior with:

```python
hv.save(g, fname, toolbar=True)
```

**Comment by Dr-Irv** [comment]
@philippjfr It sounds like the documentation needs to be updated to reflect that!

**Comment by philippjfr** [comment]
>@philippjfr It sounds like the documentation needs to be updated to reflect that!

Absolutely, PR welcome but I've assigned it to the next milestone in any case.

**Comment by Dr-Irv** [comment]
Actually, now that I think about it, I think that `toolbar=True` should be the _default_ behavior to preserve compatibility.  Is that a possibility?

**Comment by jbednar** [comment]
Is it maybe that the toolbar should only be disabled by default for PNG or other image export, where it serves no purpose, and not for HTML export?
