### ISSUE TITLE
Timezone aware plot not local time

### ISSUE THREAD

**Issue by douglasmacdonald** [holoviz/holoviews#4526]
```hv.__version__  '1.13.3'```

I was expecting the the following code to display in local time, however, with tz aware time, it defaults to UTC.

Example

```
t = pd.date_range(start='2020-01-01 10:00', end='2020-01-01 12:00', freq='H', tz='Asia/Shanghai')
d = pd.DataFrame({'t': t, 'y': [1, 2, 3]})
hv.Curve(d, kdims=['t'], vdims=['y'])
```

![bokeh_plot (1)](https://user-images.githubusercontent.com/12778156/88082052-2de9cd80-cb79-11ea-8b5c-5e7025c6b318.png)

**Comment by philippjfr** [comment]
HoloViews should ignore timezones entirely so this is a bug.

**Comment by douglasmacdonald** [comment]
In addition, don't know what you'd expect the behaviour to be if you overlaid two sets of data with different time zones. Could it be reasonable to default to UTC?

**Comment by philippjfr** [comment]
Hmm, at that point we would actually have to start dealing with timezones, but it looks like that may be unavoidable. The issue in this case is that the PandasInterface internally looks up the values like this: `df['t'].values` which returns the datetimes in UTC. So it's not actually the plotting code at fault here. I guess all interface could simply drop timezone information when asked by the plotting code but I'd have to think about the implications some more.

**Comment by douglasmacdonald** [comment]
> Hmm, at that point we would actually have to start dealing with timezones, but it looks like that may be unavoidable. The issue in this case is that the PandasInterface internally looks up the values like this: `df['t'].values` which returns the datetimes in UTC. So it's not actually the plotting code at fault here. I guess all interface could simply drop timezone information when asked by the plotting code but I'd have to think about the implications some more.

I don't have an good suggestions, however, I don't like the sound of dropping timezone information by default. It is easier for a user to drop this if they want but harder to add it back on. Note, there is no need to worry about dealing with timezone combining with non-timezone aware; pandas already throws an error if they are trying to be combined. Extending this, you could consider if time-zones are consistent then use, otherwise 'UTC' or user to provided preferred timezone for plot Whatever you decide it has to be obvious what has happened.
