### ISSUE TITLE
object.opts() not overriding default opts

### ISSUE THREAD

**Issue by rchurt** [holoviz/holoviews#4533]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
```
holoviews==1.13.3
bokeh==2.1.1
python==3.6.9
```
Google Colab
Chrome 84.0.4147.89

#### Description of expected behavior and the observed behavior
Hopefully this isn't the result of a silly mistake on my part, but here goes.

When I define some default opts that I use for several plots and then try to override them for a single plot, the default opts are still used. See below where I'm trying to override the `yformatter` option, but the format displayed matches the default (though the `R_t.opts` command is having an effect for an option that I haven't specified already in the defaults, namely the title).

#### Complete, minimal, self-contained example code that reproduces the issue
```
hv.extension('bokeh')

# Define default plot specs
opts.defaults(
    opts.Curve(width=1000, height=820, fontsize={'title': 16, 'labels': 14, 'xticks': 11, 'yticks': 12}, xticks=12, yticks=15, yformatter=NumeralTickFormatter(format="0,0")),
    opts.Overlay(legend_position='right'))

# Format DataFrame as HoloViews Dataset
R0_dataset = hv.Dataset(R0_df)

# Plot time-dependent R0, aka R(t), grouped by location
R_t = R0_dataset.to(hv.Curve, 'Date', 'R_t', 'Location').overlay()
R_t.opts(title="R(t) by State", yformatter='%.3f')
```

#### Screenshots or screencasts of the bug in action
<img width="998" alt="Screen Shot 2020-07-24 at 6 28 23 PM" src="https://user-images.githubusercontent.com/14302923/88446011-7accde80-cddb-11ea-9ab0-7ab9de82718d.png">

**Comment by jbednar** [comment]
Next time please supply a complete reproducible example if you can!  My runnable version of your code seems to work fine:

```
import holoviews as hv
import numpy as np
from holoviews import opts
from bokeh.models.formatters import NumeralTickFormatter
hv.extension('bokeh')

opts.defaults(
    opts.Curve(width=1000, height=820, fontsize={'title': 16, 'labels': 14, 'xticks': 11, 'yticks': 12}, xticks=12, yticks=15, yformatter=NumeralTickFormatter(format="0,0")),
    opts.Overlay(legend_position='right'))

def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))
curve_dict = {f:sine_curve(0,f) for f in [0.5, 0.75, 1.0, 1.25]}

ndoverlay = hv.NdOverlay(curve_dict, kdims='frequency')
ndoverlay.opts(title="R(t) by State", yformatter='%.3f')
```
![image](https://user-images.githubusercontent.com/1695496/88599672-ef995600-d031-11ea-819a-f6f6f02187ca.png)

If that doesn't work for you, maybe you have an outdated hv version?  Mine is 1.13.2. If my version works but yours still doesn't, please make yours complete so that we can reproduce it and we can see. 

In some cases (though not the one in my code, it would seem!) you need to explicitly direct your options to Curve, as in `R_t.opts(title="R(t) by State").opts(opts.Curve(yformatter='%.3f')`. Not sure why it would be needed in your case, but I can't always predict when being explicitt like that is needed...

**Comment by rchurt** [comment]
Thanks very much for the help--directing it to Curve explicitly did the trick.

It seems to be a problem with `.overlay()`, because omitting this made the original `R_t.opts(title="R(t) by State", yformatter='%.3f')` work. Oh well!

**Comment by jbednar** [comment]
If you could adapt that into a reproducible example, there is presumably a case where options aren't being dispatched down to the underlying Elements but could be...

**Comment by rchurt** [comment]
Sure, try this:
```
import holoviews as hv
import numpy as np
import pandas as pd
from holoviews import opts
from bokeh.models.formatters import NumeralTickFormatter
hv.extension('bokeh')

opts.defaults(
    opts.Curve(width=1000, height=820, fontsize={'title': 16, 'labels': 14, 'xticks': 11, 'yticks': 12}, xticks=12, yticks=15, yformatter=NumeralTickFormatter(format="0,0")),
    opts.Overlay(legend_position='right'))

example = pd.read_csv('/content/example.csv')

ds = hv.Dataset(example)

R_t = ds.to(hv.Curve, 'Date', 'R_t', 'Location').overlay()
R_t.opts(title="R(t) by State", yformatter='%.1f')
```

You'll find that if you delete `.overlay()`, the y-axis is formatted correctly, but otherwise it reverts to the default.

[example.csv.zip](https://github.com/holoviz/holoviews/files/4986140/example.csv.zip)
