### ISSUE TITLE
Can we please get legend_orientation option?

### ISSUE THREAD

**Issue by Material-Scientist** [holoviz/holoviews#4550]
Hi, I have the issue that my legend gets clipped if I place it at the bottom:

![image](https://user-images.githubusercontent.com/40465719/90229951-0d7bfe80-de19-11ea-9913-5e5b210fef04.png)

I don't want to place it on the sides because it takes up too much space on mobile devices, making the app unusable.

In the [docs](http://holoviews.org/user_guide/Customizing_Plots.html#Legend-customization), I found an option for legend_cols, but looking at the holoviews source code, I found out that the legend_orientation is forced to 'horizontal' when the legend position is above or below the chart:

```
def _process_legend(self, plot=None):
        plot = plot or self.handles['plot']
        if not plot.legend:
            return
        legend = plot.legend[0]
        cmappers = [cmapper for cmapper in self.handles.values()
                   if isinstance(cmapper, CategoricalColorMapper)]
        categorical = bool(cmappers)
        if ((not categorical and not self.overlaid and len(legend.items) == 1)
            or not self.show_legend):
            legend.items[:] = []
        else:
            plot.legend.orientation = 'horizontal' if self.legend_cols else 'vertical'
            pos = self.legend_position
            if pos in self.legend_specs:
                plot.legend[:] = []
                legend.location = self.legend_offset
                if pos in ['top', 'bottom']:
                    plot.legend.orientation = 'horizontal'
                plot.add_layout(legend, self.legend_specs[pos])
            else:
                legend.location = pos

            # Apply muting
            for leg in plot.legend:
                for item in leg.items:
                    for r in item.renderers:
                        r.muted = self.legend_muted
```

So, can we please get an option to set the legend_orientation when it's above/below the chart?
I.e. configure the plot like shown below, but the legend_cols parameter actually taking effect and displacing the legend in 2 columns:

![image](https://user-images.githubusercontent.com/40465719/90230079-4ae08c00-de19-11ea-929e-f45cf11c9818.png)

Also [posted on the holoviz discourse](https://discourse.holoviz.org/t/can-we-please-get-legend-orientation-option/1095).

**Comment by philippjfr** [comment]
The problem here is that legend_cols is not implemented for bokeh so the orientation is the only level of control we have atm. There is an open issue to address this but for now I'll close this as a duplicate since fixing https://github.com/holoviz/holoviews/issues/4529 would address both issues.
