### ISSUE TITLE
hv.Dataset() reads array kdims in reverse order

### ISSUE THREAD

**Issue by rchurt** [holoviz/holoviews#4559]
#### ALL software version info
```
holoviews==1.13.3
bokeh==2.1.1
python==3.6.9
```
Google Colab
Chrome 84.0.4147.89

#### Complete, minimal, self-contained example code that reproduces the issue
In the code [here](https://holoviews.org/gallery/demos/bokeh/box_draw_roi_editor.html), see the following lines:
```
calcium_array = data['Calcium']
ds = hv.Dataset((np.arange(50), np.arange(111), np.arange(62), calcium_array),
                ['Time', 'x', 'y'], 'Fluorescence')
```
If I run `calcium_array.shape`, the output is `(62, 111, 50)`. But in the call to `hv.Dataset()`, the `kdims` are passed in the order (50, 111, 62).

For convenience, here's a link to [twophoton.npz](https://github.com/holoviz/holoviews/blob/master/examples/assets/twophoton.npz).

I'm a bit new to HoloViews, so maybe there's a good reason for this, but I found it a bit confusing at first glance.

**Comment by philippjfr** [comment]
Agreed that this can be confusing but it's really just following the usual array ordering, e.g. if you have a 2D array then the shape of the array corresponds to `(rows, columns)`, i.e. rows are the values along the y-axis and columns are the values along the x-axis. This is simply a convention and I agree it is confusing but for consistency with the way arrays are usually structured in the real world we decided we would effectively have to invert the key dimensions compared to the array ordering. Hope that makes some sense!
