### ISSUE TITLE
Multiple Plots Layout Weird Behavior

### ISSUE THREAD

**Issue by ziakayani** [holoviz/holoviews#4566]
I have created a plot using multiple curves. 
Individual plots work fine.
But when I try to display side by side it just mixes everything.

```
def get_line_chart(plot_data, agg, agg_by, variable_col, direction):
    curves_list = []
    xaix = sorted(plot_data[agg].dropna().drop_duplicates())
    
    for turnDirection, data in plot_data.groupby([variable_col]):
        curve = hv.Curve((data[agg], data[agg_by]), name=str(turnDirection), label=str(turnDirection)) \
            .opts(xlabel=agg, xrotation=90, ylabel=agg_by)
        curves_list.append(curve)

    from functools import reduce
    return reduce(lambda x, y: x * y, curves_list).opts(title=direction, width=700)

def create_plot(df1, maxIntersections, agg_present, agg_by, variable_col, outputFolder):
    plots = []
    for direction in ['East', 'West',  'North', 'South']:
        filtered_data = df1[df1["inboundDir"] == direction]
        plots.append(get_line_chart(filtered_data, agg_present[1], agg_by, variable_col, direction))
    from functools import reduce
    plot = hv.Layout(reduce(lambda x, y: x + y, plots)).cols(2)
    hv.save(plot, outputFolder + 'WorstIntersectionsAreaPlot{0}.html'.format(variable_col))
       
```
This is normal *NORTH* plot
![image](https://user-images.githubusercontent.com/12911287/91161700-86fed100-e6e4-11ea-8b2a-b3dcf5e66868.png)

This is normal *SOUTH* plot
![image](https://user-images.githubusercontent.com/12911287/91161848-b9103300-e6e4-11ea-9e7f-97bd59504fa1.png)

When I try to merge in a single view using + operator suddenly the second plot mixed up.

![image](https://user-images.githubusercontent.com/12911287/91163601-46548700-e6e7-11ea-876f-b118bfc68432.png)

If I add multiple plots, 1st one behaves normally, all others are mixed up. 

![image](https://user-images.githubusercontent.com/12911287/91164227-2d98a100-e6e8-11ea-87ab-a246a6752e47.png)

**Comment by MarcSkovMadsen** [comment]
Just a guess. Could it be that the values are not datetimes/ Timestamps but just strings/ objects. Then I believe the underlying algorithm tries to solve by the sort in the first dataset which gives the look you show.

Fix. Either sort your datasets on the date column or convert them to proper datetime or Timestamp.

**Comment by ziakayani** [comment]
@MarcSkovMadsen Thanks for the response. The values are in strings, and I'm sorting them,

Every graph works fine individually, But when I join them using + operator then this happens.

**Comment by philippjfr** [comment]
@ziakayani By default it will share the axes and if you're treating each value as a string then it'll merge the values. The easiest way to fix this will be to disable axis sharing by setting `axiswise=False` in the Curve opts call.

**Comment by philippjfr** [comment]
As a separate note, this bit can be simplified from:

```python
    from functools import reduce
    return reduce(lambda x, y: x * y, curves_list).opts(title=direction, width=700)
```

to:

```python
    return hv.Overlay(curves_list).opts(title=direction, width=700)
```

**Comment by philippjfr** [comment]
I'd also expect that using [hvPlot](https://hvplot.holoviz.org/) all of your code reduces to some variation of:

```python
df1.hvplot.line('timeBin', agg_by, by=variable_col, groupby="inboundDir", shared_axes=False).layout().cols(2)
```

**Comment by philippjfr** [comment]
I'm going to close. Please refer to the [Discourse](https://discourse.holoviz.org/) for usage questions.

**Comment by ziakayani** [comment]
> @ziakayani By default it will share the axes and if you're treating each value as a string then it'll merge the values. The easiest way to fix this will be to disable axis sharing by setting `axiswise=False` in the Curve opts call.

this didn't solve the problem,

`hv.Layout(plots).opts(shared_axes=False).cols(2)`

this did.

Thanks for the code suggestions also. I've installed hvplot, will look into it.
