### ISSUE TITLE
Linked-Brushing is broken?

### ISSUE THREAD

**Issue by erezinman** [holoviz/holoviews#4570]
In the [official HV guide to linked-brushing](http://holoviews.org/user_guide/Linked_Brushing.html), I'm not able use linked-brushing, as selection doesn't seem to affect the plots. 

I tried this using both FF and Chrome.

**Comment by erezinman** [comment]
I was mistaken. Sorry.

**Comment by erezinman** [comment]
Sorry for closing it. The site doesn't appear to link-brush beyond the first example.

**Comment by philippjfr** [comment]
Just discovered this myself, there was a regression in bokeh 2.2 causing this (see https://github.com/bokeh/bokeh/issues/10435).

Hopefully that'll get fixed soon but in the meantime this PR (https://github.com/holoviz/holoviews/pull/4329/files) should also fix it as long as you're on a recent version of Panel.

**Comment by philippjfr** [comment]
Bokeh 2.2.1 will fix this and hopefully will be released today.

**Comment by OsMoe** [comment]
The "python-based linked brushing" is still/again not working for me.
Even the base example from your "lasso linked select" branch does not select any data.
```
import numpy as np
import holoviews as hv
hv.extension('bokeh')
points1 = hv.Points(np.random.randn(1000, 2))
points2 = hv.Points(np.random.randn(1000, 2))
hv.link_selections(points1 + points2, selection_mode='union')
```
Bokeh version 2.2.1 is installed, and the server is not reporting any mistakes, nor is the notebook.

**Comment by philippjfr** [comment]
Is this in the classic notebook or Jupyterlab? If the latter is the pyviz extension installed? If not install it with:

    jupyter labextension install @pyviz/jupyterlab_pyviz

**Comment by OsMoe** [comment]
It was/is in Jupyterlab. The labextension fixed it.
Thank you so much for helping me this quickly.
Keep up the good work!
