### ISSUE TITLE
Segments Categorical Y axis limited to two values?

### ISSUE THREAD

**Issue by jbhiatt** [holoviz/holoviews#4602]
I am trying to create a Segments plot with a categorical Y axis with many values. However, when I generate the plot, only the first- and last-ranked axis values are being plotted. I tried modifying the toy example in the Segments Reference Gallery page and the same problem occurred (only "A" and "C" appear on the Y axis). Thank you for your help!!

```
event = ['A', 'B', 'C']
data = dict(
    start=[np.datetime64('1999'), np.datetime64('2001'), np.datetime64('1995')],
    end=[np.datetime64('2010'), np.datetime64('2020'), np.datetime64('2030')],
    start_event = event,
    end_event = event
)
seg = hv.Segments(data, [hv.Dimension('start', label='Year'), 
                         hv.Dimension('start_event', label='Event'), 'end', 'end_event'])
seg
```
![image](https://user-images.githubusercontent.com/45834867/92863631-03660500-f3b1-11ea-9d21-a74fb7d533cd.png)

**Comment by philippjfr** [comment]
Thanks @jbhiatt, this was already reported and fixed, see https://github.com/holoviz/holoviews/issues/4523.
