### ISSUE TITLE
Params stream does not correctly support transient

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#4610]
Demo code and outcome:

```python
import param
import panel as pn
import holoviews as hv
hv.extension('bokeh')

class Foo(param.Parameterized):
    
    a = param.Action(default=lambda x: x.param.trigger('a'))
    b = param.Action(default=lambda x: x.param.trigger('b'))
    
    def _callback(self, *args, **kwargs):
        print(args, kwargs)
        return hv.Curve([1,2,3])
    
    def view(self):
        pstream = hv.streams.Params(self, 
                                    parameters=['a', 'b'], 
                                    transient=True)
            
        return pn.Row(self.param,
                      hv.DynamicMap(self._callback,  streams=[pstream]))
                       
Foo().view()
```

![image](https://user-images.githubusercontent.com/890576/93203379-f5e6ad00-f719-11ea-96b1-e3f9453c97d1.png)

Clicking on the 'A' and 'B' buttons have the same result in the console:

![image](https://user-images.githubusercontent.com/890576/93203436-0f87f480-f71a-11ea-97ec-8d80c3d2ccfc.png)

I would expect `transient=True` to set the value to `None` for the button that isn't clicked, allowing me to know which button was clicked.

**Comment by jlstevens** [comment]
Additionally, I would argue for special behavior for `param.Action` generally: I think this parameter is designed explicitly for buttons where the transient behavior is always more useful. I would like to be able to detect which button was clicked or not (by checking for None) without having to explicitly create a `hv.streams.Params` instance. 

Of course, for any other parameter types, creating a `hv.streams.Params` instance and setting `transient=True` would be appropriate.

**Comment by jlstevens** [comment]
Just a note to say we are considering a new param Parameter type that might make this PR redundant. I'll link to the relevant param PR as soon as it exists.

**Comment by jbednar** [comment]
Right. Action was meant for invoking some behavior that's captured by the callable, while here you want calling the parameter to trigger some other distant action not encapsulated in the Action parameter.  I think that's a different use case and is better dealt with separately than by trying to fit it into Action.

**Comment by jlstevens** [comment]
I think I'll go ahead and close this PR: whatever approach we take, we probably want to address it at the param level, not the holoviews level.
