### ISSUE TITLE
"Bokeh show_app is currently unsupported"

### ISSUE THREAD

**Issue by maajdl** [holoviz/holoviews#4630]
I tried to use my small package available on github which is using hv+bk:

           https://github.com/maajdl/psychropyo

This works correctly on my local machine with Anaconda as well as with WinPython.
However, on "https://colab.research.google.com/"  (colaboratory), the graphics are not output.
Instead, I receive this error message:

          Bokeh show_app is currently unsupported

I could not check who is sending this message, altough I guess it should be holoviews, isn't it?

Would you have a suggestion for how to get hv+bk working on calaboratory?
I have seen examples of bokeh working on colaboratory.

Thanks,

Michel

**Comment by jlstevens** [comment]
> I could not check who is sending this message, although I guess it should be holoviews, isn't it?

Right, I don't think this is a HoloViews message but one generated by colab. I suggest you file an issue there...

**Comment by uomodellamansarda** [comment]
The same error message, but the curious thing is that the same code with the same file on collab worked correctly on  March 2020 and I could use the bokeh app I created. 
Where do you think @jlstevens I have to address the issue?

**Comment by bryevdv** [comment]
> the curious thing is that the same code with the same file on collab worked correctly on March

Google is making changes to collab all the time. I agree with @jlstevens that this is not coming from HV or Bokeh or the jupyter_bokeh notebook extension. I don't know where Google takes feedback on collab (or even if they do, publicly). but they are the only ones with any possibility of taking any action.
