### ISSUE TITLE
RGB/rasterize not releasing memory properly

### ISSUE THREAD

**Issue by kcpevey** [holoviz/holoviews#4632]
#### ALL software version info
holoviews '1.13.4.post4+g8f7c67f70' (current master)

#### Description of expected behavior and the observed behavior
I have an an image that I'm using `hv.RGB` and `rasterize` to render. Everytime I render the image, my memory usage for the python kernel increases incrementally. This incremental change matches with what `tracemalloc` tells me the image construction is consuming. Essentially, the memory allocated for the image is never released. I have to restart my kernel to release the memory. 

#### Complete, minimal, self-contained example code that reproduces the issue
A test image can be downloaded from unsplash, for example [this one](https://unsplash.com/photos/ikVBaapsTPg). Be sure to get the original size. Or you can [immediately download the file](https://unsplash.com/photos/ikVBaapsTPg/download?force=true) if you trust me enough to start the download directly :) 

This bit of code will tell us that we need about 48 MB of memory to run this
```
from PIL import Image
import tracemalloc
import holoviews as hv
hv.extension('bokeh')

path = 'shifaaz-shamoon-ikVBaapsTPg-unsplash.jpg'

tracemalloc.start()
with open(path, 'rb') as f:
    image = np.array(Image.open(f))
img = hv.RGB(image)    
rasterize(img)
snapshot = tracemalloc.take_snapshot()
top_stats = snapshot.statistics('lineno')
print("[ Top 10 ]")
for stat in top_stats[:10]:
    print(stat)
```
Now, if you repeatedly call the following code:
```
with open(path, 'rb') as f:
    image = np.array(Image.open(f))
img = hv.RGB(image)    
rasterize(img)
```
You'll see that every time it's run (I'm using jupyter to visualize), the memory consumption on your machine increases by 48 MB. 

If you remove the `rasterize(img)` step, you won't see any memory increase. I suppose this would be expected since it isn't rendered, the object isn't populated in the same way?

Also, if only call the PIL portion like this:
```
with open(path, 'rb') as f:
    image = np.array(Image.open(f))
```
You can see that this bit is properly releasing memory. So it seems to be and issue with the `hv.RGB` object.

**Comment by jlstevens** [comment]
Thanks for reporting this! 

If you could help find the source of the memory leak, we would be very happy to merge the fix. :-)

**Comment by philippjfr** [comment]
This does not appear to be a memory leak but rather a garbage collection issue:

```python
import os
import gc
import psutil
import sys

import holoviews as hv
import numpy as np

from holoviews.operation.datashader import rasterize
from PIL import Image

path = '/Users/philippjfr/Pictures/1008781_975296637784_1847562131_o.jpg'

process = psutil.Process(os.getpid())

for i in range(10):
    with open(path, 'rb') as f:
        image = np.array(Image.open(f))

    img = hv.RGB(image)

    rasterize(img)

    if len(sys.argv) == 2 and sys.argv[1] == 'gc':
        gc.collect()

    print(process.memory_info().rss)  # in bytes 
```

If I run this with `python memory.py gc` I see this:

```
269668352
271704064
271683584
271765504
271777792
271802368
271802368
271802368
271802368
271826944
```

while I see this with no GC:

```
264331264
266481664
268619776
270651392
272576512
266637312
268804096
270905344
273002496
275144704
```

In the case without explicit garbage collection you can see memory accumulate and then shrink again. Please try this out and then report the exact versions of param and holoviews.

**Comment by philippjfr** [comment]
You can also bump the number of iterations which will make it even clearer that memory use does not grow.

**Comment by kcpevey** [comment]
Holoviews 1.13.4.post6+g4a6477de6
Param 1.10.0a5

With gc:
```
362360832
412557312
412549120
412540928
412540928
412540928
412606464
412606464
412606464
412606464
```

without gc:
```
362414080
412626944
412708864
463036416
513372160
563707904
614039552
663957504
412758016
463114240
```

From the above, it *does* appear to be a garbage collection issue. 

However, when I was testing and report this, I was running inside of Jupyter lab. When I run your script in a jupyter cell, I get these results:

with gc:
```
368529408
418840576
469168128
519573504
569909248
619900928
418955264
469278720
519602176
569925632
```

without gc:
```
366977024
417370112
467701760
518090752
568430592
618409984
417468416
467791872
518115328
568451072
```

Any ideas why that would be?

**Comment by philippjfr** [comment]
Going to close since this is not a memory leak as far as I can tell.

**Comment by kcpevey** [comment]
Confirmed that when I add a `gc.collect()` after my rasterize calls, it fixes this issue. Is that the recommended long-term solution?

**Comment by philippjfr** [comment]
Not really no, if it's really causing such issues then we should determine why the garbage collection is having such issues cleaning up the references. There must be a circular reference somewhere that requires a full garbage collection pass to be cleaned up.

**Comment by jlstevens** [comment]
I'll assign this to the next milestone: if it turns out to be a difficult, fundamental problem to solve we can bump it.

**Comment by philippjfr** [comment]
I no longer believe this to be a real issue, we have been running an application which uses rasterize/datashade for over a month now without leaking memory.
