### ISSUE TITLE
Visual diff on travis.holoviews.org

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#465]
I would like to see [concat_html.py](https://github.com/ioam/ioam-builder/blob/nbpublisher/concat_html.py) updated to use imagemagick convert to enable automatic visual diffs on [travis.holoviews.org](http://travis.holoviews.org/).

The topic of visual diffing test data was initially discussed in issue #341.

**Comment by philippjfr** [comment]
Closing for now, as of right now we are not even storing the output of notebooks.
