### ISSUE TITLE
Unable to supply custom datetime axis ticks (xticks)

### ISSUE THREAD

**Issue by scottyhq** [holoviz/holoviews#4655]
#### ALL software version info
holoviews 1.13.4 
bokeh 2.2.2
python 3.8

#### Description of expected behavior and the observed behavior
I'd like to be able to have custom date ticks on a plot, for example by specifying `xticks=pd.to_datetime(['2005-01-15','2010-01-15'])`

Supplying custom datetime values to xticks does not work, it seems they are overwritten by defaults with the bokeh backend, and there is a traceback with the matplotlib backend. It seems like this should work according to http://holoviews.org/user_guide/Customizing_Plots.html. Also, supplying the number of ticks as an integer works (xticks=4), but it's common to want specific dates on the plot.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import bokeh
#bokeh.sampledata.download()

import holoviews as hv
from bokeh.sampledata.stocks import GOOG, AAPL
import pandas as pd
import numpy as np

print(bokeh.__version__, hv.__version__)
hv.extension('matplotlib')
myticks = pd.to_datetime(['2005','2010']).to_numpy()

goog_dates = np.array(GOOG['date'], dtype=np.datetime64)
aapl_dates = np.array(AAPL['date'], dtype=np.datetime64)

goog = hv.Curve((goog_dates, GOOG['adj_close']), 'Date', 'Stock Index', label='Google')
aapl = hv.Curve((aapl_dates, AAPL['adj_close']), 'Date', 'Stock Index', label='Apple')

(goog * aapl).opts(legend_position='top_left', xticks=myticks)
```

#### Stack traceback and/or browser JavaScript console output
If using the bokeh backend, there is no traceback, default ticks are just used. If using hv.extension('matplotlib') this is the end of the big traceback
```pytb
/srv/conda/envs/notebook/lib/python3.8/site-packages/holoviews/plotting/mpl/element.py in _set_axis_ticks(self, axis, ticks, log, rotation)
    423         elif isinstance(ticks, ticker.Locator):
    424             axis.set_major_locator(ticks)
--> 425         elif not ticks and ticks is not None:
    426             axis.set_ticks([])
    427         elif isinstance(ticks, int):

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by jbednar** [comment]
Looks like you are passing in a Numpy array for the ticks, and the documentation for _set_axis_ticks doesn't indicate that Numpy arrays are supported. Maybe use `.tolist()` instead of Numpy?

**Comment by scottyhq** [comment]
Hi @jbednar - i should have elaborated a bit more. i've tried passing the dates in many formats to no avail (bokeh backend is where i'd most appreciate this functionality):

1. pandas Timestamps --> no effect
1. to_pydatetime() --> no effect
1. to_list() --> `ValueError: expected an element of Seq(Float), got seq with invalid items [Timestamp('2005-01-01 00:00:00'), Timestamp('2010-01-01 00:00:00')]`
 
It appears the dates somehow get converted to floats, but I'm not sure how...

**Comment by jbednar** [comment]
Sounds like a question for @jlstevens or @philippjfr , then.  I would have expected a list of Timestamps to be valid for a datetime axis.
