### ISSUE TITLE
"hv.help(obj)" should match "obj?"

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#4663]
I can never remember IPython's help syntax for more than a few hours, so I use `hv.help`, which to me conveys explicitly that I'm requesting help. However, `hv.help` only shows a subset of what's in the IPython ? output, failing to show the docstring or signature:

![image](https://user-images.githubusercontent.com/1695496/97183163-6c3feb80-176b-11eb-822c-a9082528cf08.png)

![image](https://user-images.githubusercontent.com/1695496/97183121-60ecc000-176b-11eb-84bd-f3745e467a9c.png)

I think the information shown by `?` should all also be available from `hv.help`, in part because I don't like having any functionality that specifically depends on optional packages like IPython if it doesn't actually conceptually require that optional package.

**Comment by droumis** [comment]
closing in favor of #5421
