### ISSUE TITLE
Unexpected behavior when using alpha parameter in hv.HeatMap

### ISSUE THREAD

**Issue by mzeitlin11** [holoviz/holoviews#4673]
#### ALL software version info
jupyterlab 2.2.8
pandas 1.1.3
holoviews 1.13.5
bokeh 2.2.3

#### Description of expected behavior and the observed behavior
Passing `alpha` parameter for `hv.HeatMap` does not follow expected behavior. We expect the square with `row = 2`, `col = 1` to be the only filled square, but instead `row = 2`, `col = 2` is filled, as if the corresponding alpha value is 1, when it should be 0.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import holoviews as hv

import bokeh.io
bokeh.io.output_notebook()
hv.extension('bokeh')

df = pd.DataFrame(
    {
        "row": [1, 2, 1, 2], 
        "col": [1, 2, 2, 1], 
        "alpha": [0, 0, 0, 1], 
        "val": [.5, .6, .2, .1]
    }
)

hm = hv.HeatMap(df, kdims=["col", "row"], vdims=["val", "alpha"]).opts(
        alpha="alpha",
    )
hm

```
#### Screenshots or screencasts of the bug in action
<img width="255" alt="holoviews_issue" src="https://user-images.githubusercontent.com/37011898/97932104-296aae80-1d3d-11eb-896a-2c5bd67efc12.png">

**Comment by marcbernot** [comment]
I can reproduce.
By looking at the output of 
```python
from bokeh.plotting import ColumnDataSource
p = hv.render(hm)
p.select(ColumnDataSource).to_json(False)
```
it seems that `col` is sorted and that the corresponding permutation correctly applies to `row` and `val`but not to `alpha`.

And indeed just reordering columns and rows of the dataframe lead to the correct display.
```python
df2 = df.reindex(columns = ['col','row','val','alpha']).sort_values(by=['col','row'])

hv.HeatMap(df2, kdims=["col", "row"], vdims=["val", "alpha"]).opts(
        alpha="alpha"
    )
```
![bokeh_plot](https://user-images.githubusercontent.com/8888261/98255235-7b017c00-1f7d-11eb-8f7e-549774717fb8.png)

What's troubling is that the dataset `hm.gridded` is correct as can be seen by looking at `hm.gridded.array()` values. 

Things behave as if the initial alpha vector was feeded to the options, not the one linked to row and col that is transformed through sorting. 
What is even stranger is that it seems specific to the alpha option as it is not happening to the color option (check `hv.HeatMap(df, kdims=["col", "row"], vdims=["val", "alpha"]).opts(
        color="alpha",tools = ['hover']
    )`).
<img width="333" alt="Capture d’écran 2020-11-05 à 16 01 58" src="https://user-images.githubusercontent.com/8888261/98257762-59ee5a80-1f80-11eb-8235-d4f40b6641a0.png">
