### ISSUE TITLE
Predefined breaks for LinearColorMapper

### ISSUE THREAD

**Issue by lrdsouza** [holoviz/holoviews#4676]
I'm developing an application to analyze arbovirus infections in the neighborhoods of two cities. Heat maps are generated for each city, their color scheme varies according to the count of infections in the neighborhoods. One of the problems in generating color of these maps is the interest data distribution. The vector of infection counts for each city has very distant values, such as the vector `v1 = [1, 2, 3, 3, 4, 7, 8, 9, 15, 20, 39, 40]`. The `LinearColorMapper` with 4 colors would generate mapping intervals with size 10 breaks, such as `[1, 10), ..., [30, 40]`. So, as we can see, more than half of `v1` would be included in the break `[1, 10)`, causing many neighborhoods to be mapped to a single color. An ideal set of intervals for this problem would be `c = {[1, 4], [7, 9], [15, 20], [39, 40]}`, as it would allow for more color abundance on maps. An alternative to solve this problem would be allow the `LinearColorMapper` function to receive externally generated intervals or to add a resource in the `LinearColorMapper` function that allows selecting the algorithm for generating breaks, such as Fisher-Jenks and Jenks-Caspall.

**Comment by jbednar** [comment]
[LinearColorMapper](https://docs.bokeh.org/en/latest/docs/reference/models/mappers.html#bokeh.models.mappers.LinearColorMapper) is provided by Bokeh, not HoloViews, so you could file an issue there. Or you could simply subclass LinearColorMapper and add the functionality you like in your own code.

**Comment by philippjfr** [comment]
>Or you could simply subclass LinearColorMapper and add the functionality you like in your own code.

Definitely can't do that since it needs a JS implementation.

**Comment by lrdsouza** [comment]
@jbednar Sorry. My fault. I didn't really notice that i was opening an issue on HoloViews.
