### ISSUE TITLE
Holoviews Rectangles not able to plot minute data (blank chart) but Segments does

### ISSUE THREAD

**Issue by afzalmushtaque** [holoviz/holoviews#4679]
#### ALL software version info
Ubuntu 20.04.1 LTS
Python 3.8.5
Holoviews 1.13.5
Bokeh 2.2.3
numpy 1.19.1
pandas 0.25.3
#### Description of expected behavior and the observed behavior
Charts properly for hourly data as shown below
```
# HOURLY
import numpy as np
np.random.seed(15)
import pandas as pd
import bokeh
import holoviews as hv
hv.extension('bokeh')

offset = 15

xs = pd.date_range('1.1.2019 09:00:00', '1.1.2019 14:00:00', freq='1H')
ys = np.random.randn(len(xs)+1).cumsum()

O = ys[1:]
C = ys[:-1]
H = np.max([O, C], axis=0) + np.random.rand(len(xs))
L = np.min([O, C], axis=0) - np.random.rand(len(xs))


boxes = hv.Rectangles((xs-pd.DateOffset(minutes=offset), O, xs+pd.DateOffset(minutes=offset), C))
segments = hv.Segments((xs-pd.DateOffset(minutes=offset), O, xs+pd.DateOffset(minutes=offset), C))

boxes.opts(width=1400, height=600, show_grid=True) * segments.opts(color='red', line_width=5)
```
![hour](https://user-images.githubusercontent.com/2928898/98958018-db695e00-2527-11eb-825b-715c2dc23761.png)

Fails to chart for minute data as shown below
```
# MINUTE
import numpy as np
np.random.seed(15)
import pandas as pd
import bokeh
import holoviews as hv
hv.extension('bokeh')

offset = 15

xs = pd.date_range('1.1.2019 09:00:00', '1.1.2019 09:05:00', freq='1min')
ys = np.random.randn(len(xs)+1).cumsum()

O = ys[1:]
C = ys[:-1]
H = np.max([O, C], axis=0) + np.random.rand(len(xs))
L = np.min([O, C], axis=0) - np.random.rand(len(xs))

boxes = hv.Rectangles((xs-pd.DateOffset(seconds=offset), O, xs+pd.DateOffset(seconds=offset), C))
segments = hv.Segments((xs-pd.DateOffset(seconds=offset), O, xs+pd.DateOffset(seconds=offset), C))

boxes.opts(width=1400, height=600, show_grid=True) * segments.opts(color='red', line_width=5)

```
![minute](https://user-images.githubusercontent.com/2928898/98958143-fb008680-2527-11eb-89a8-6e50f34862b0.png)

Increasing the offset to 33 in the minute data shows the rectangles but they are incorrectly plotted
![minute_incorrect](https://user-images.githubusercontent.com/2928898/98958587-706c5700-2528-11eb-9135-7d4bc2d817dd.png)
 
#### Stack traceback and/or browser JavaScript console output
No error or warning messages can be seen on any console

**Comment by philippjfr** [comment]
Looks correct to me in 1.14.0, please reopen if the issue persists

![bokeh_plot - 2020-12-15T171715 749](https://user-images.githubusercontent.com/1550771/102241561-652a9380-3ef9-11eb-83d1-d64cb2b2caea.png)
