### ISSUE TITLE
Unexpected spatialpandas dependency in Large Data guide

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#4692]
I would expect that the Large Data user guide would work from top to bottom once datashader is installed. Instead I get:

<img src="https://user-images.githubusercontent.com/890576/99793227-f1f65300-2aed-11eb-9463-8b41e39313e7.png" width=50%></img>

The only mention of spatial pandas in the notebook is:

> 3. For polygons Datashader supports [spatialpandas](https://github.com/holoviz/spatialpandas) DataFrames.

Which doesn't say anything about it needing to be installed to run the notebook.

My preference would be for spatialpandas to be a dependency of datashader as it is needed for polygon aggregation. This example is using latest holoviews and datashader installed into a clean Python 3.7 environment.

**Comment by jbednar** [comment]
That's tricky. The immediate fix is to add spatialpandas as a dependency for the holoviews docs; those docs are datashading polygons, and Datashader only supports polygons when spatialpandas is installed.

I'm not sure that it's appropriate to make spatialpandas a dependency for Datashader. It seems to me that relatively few people will use Datashader's polygon support; I think the vast majority only use points or lines. If spatialpandas doesn't add any other dependencies, then maybe, but it's certainly not core to Datashader and appropriate for all Datashader users.

**Comment by jlstevens** [comment]
In that case I would suggest removing the Polygon aggregation example and mention in the text that with spatialpandas installed, Polygons can also be datashaded. This could also link to somewhere in the datashader docs where there is a clear example.

@philippjfr suggested he would be in favor of including it as a datashader dependency as he didn't feel it was too much of a burden.

**Comment by jbednar** [comment]
I think it should be tested for availability in the notebook before being added, and we should add spatialpandas to the website dependencies, so that the website shows polygons but any particular user won't have an error if they don't have it.

**Comment by jlstevens** [comment]
Addressed by the PR above. Can be closed when it is merged.
