### ISSUE TITLE
hv-extension takes too long to load

### ISSUE THREAD

**Issue by ananis25** [holoviz/holoviews#4741]
The statement to configure the holoviews backend takes around 5-6 seconds at the start of each session. Apologies if this is expected behavior, I wanted to confirm it. Both the machine running the notebook and the browser have a fast network connection. 

Thank you for looking.

#### ALL software version info
bokeh==2.3.0.dev2
holoviews==1.14.0
notebook==6.0.2

browsers: firefox, chrome
OS: MacOS client, Centos 7 on server

#### Complete, minimal, self-contained example code that reproduces the issue
```py
import holoviews as hv
hv.extension('bokeh')
# hv.extension('matplotlib')
```

#### Stack traceback and/or browser JavaScript console output
In the terminal running the notebook, this pops up regularly. But other issues suggest this is harmless. 
```
[IPKernelApp] WARNING | No such comm: hv-extension-comm
```
The browser console doesn't show any error messages.

**Comment by jbednar** [comment]
On my 2yo MacBook Pro the above code is always done in under 2 seconds, including time for launching Python:

```
$ time python -c "import holoviews as hv ; hv.extension('bokeh')"
1.589u 0.299s 0:01.97 94.9%	0+0k 0+0io 0pf+0w
$ time python -c "import holoviews as hv ; hv.extension('bokeh')"
1.608u 0.287s 0:01.93 97.4%	0+0k 0+0io 0pf+0w
$ time python -c "import holoviews as hv ; hv.extension('bokeh')"
1.592u 0.289s 0:01.91 97.9%	0+0k 0+0io 0pf+0w
$ time python -c "import holoviews as hv ; hv.extension('bokeh')"
1.624u 0.296s 0:01.95 97.9%	0+0k 0+0io 0pf+0w
```

The comm messages are very annoying but seem impossible to eradicate so far.

**Comment by ananis25** [comment]
Thank you for the datapoint, I see similar time taken in the terminal. The remote machine hosting the jupyter notebook is a slightly old but beefy machine. 
```bash
$ ipython -c "import time; st = time.time(); import holoviews as hv ; hv.extension('bokeh'); print(time.time() - st)"
1.5432398319244385
```
Silly question- is there a browser component to loading the bokeh/matplotlib extension too, outside the python kernel? That might be causing the long time taken in the notebook.

**Comment by jbednar** [comment]
hv.extension() does involve loading JS into the browser, but at least on my machine, running `%time import holoviews as hv ; hv.extension("bokeh")` in a fresh Jupyter session takes the same time or less than running it on the command line (1.9sec).

Note that I'm running the whole session on my laptop here, while there may be network-related delays if you're running it remotely.

**Comment by ananis25** [comment]
That'd make sense, even though the remote machine is in the same city and I'm on a good connection. 

Thank you. I'll close this and post back if I can find the issue.
