### ISSUE TITLE
Bad link in the website https://holoviews.org/reference_manual/index.html

### ISSUE THREAD

**Issue by GilShoshan94** [holoviz/holoviews#4746]
Hi,

In the website, in the API reference, there is a bad link to the holoviews.util Package.
When I click on the `util` link on https://holoviews.org/reference_manual/index.html,
It redirects me to `https://holoviews.org/reference_manual/holoviews.util` which give me the `404 Not Found` error.
It is just lacking the `.html` to the link to be correct.

I believe the correct link is https://holoviews.org/reference_manual/holoviews.util.html 

![image](https://user-images.githubusercontent.com/29143941/101844459-14d6be80-3b12-11eb-9af6-2d5cf1d102b4.png)

Thank you for those amazing tools (all the Holoviz suite).

**Comment by jbednar** [comment]
Thanks for spotting that! Care to make a PR to fix it (editing https://github.com/holoviz/holoviews/blob/master/doc/reference_manual/index.rst)?

**Comment by GilShoshan94** [comment]
@jbednar 
I did the PR : https://github.com/holoviz/holoviews/pull/4749
It is my first PR I ever do. I hope I did it correctly.

I followed this guide : https://opensource.com/article/19/7/create-pull-request-github
I did not succeed to do the git commit with the -S option, I understand it is to sign somehow... So I did without it.

Please let me know the correct way to do PR, especially in open source project, as I intend to contribute more in the future.

**Comment by jbednar** [comment]
That was perfect, thanks! Welcome to the world of open source and to the HoloViews development team in particular. We're always happy to see any fixes to docs or docstrings; users are much better able to spot those than we are!
