### ISSUE TITLE
opts for inverting individual axes does not seem to work, e.g.  opts(invert_yaxis=True) for holoviews and hvplot

### ISSUE THREAD

**Issue by hali-geoviz** [holoviz/holoviews#4759]
I notice that opts for inverting individual axes does not seem to work in latest version hvplot and holoviews (see below), e.g.  opts(invert_yaxis=True) for holoviews and hvplot

#### ALL software version info
```
# imports
import holoviews as hv
import hvplot.pandas
from holoviews import opts
import pandas as pd
import numpy as np
import bokeh
import panel as pn
```

libs = [hv, pd, hvplot, np, bokeh, pn]
libs_version = {}
for lib in libs:
    print(lib.__version__)
    libs_version[lib.__name__] = lib.__version__`

{'holoviews': '1.14.0',
 'pandas': '0.24.2',
 'hvplot': '0.7.0',
 'numpy': '1.16.5',
 'bokeh': '2.2.3',
 'panel': '0.10.2'}

#### Description of expected behavior and the observed behavior
I have been using opts for holoviews elements in order to e.g. invert yaxis vy setting invert_yaxis=True. This has been working before, but not after I just ran 

`conda update -c pyviz holoviz`

#### Minimal, self-contained example code

```
# imports
import holoviews as hv
import hvplot.pandas
from holoviews import opts
import pandas as pd
import numpy as np

# make dataset
df = pd.DataFrame(dict(A= np.random.rand(10,),
                       B=2.5 + np.random.rand(10,)))
# hvplot example
plot_hvplot = df[['A', 'B']].hvplot.scatter(x='A', y='B').opts(invert_yaxis=True)

# holoviews example
plot_holoviews = hv.Scatter(df, kdims='A', vdims='B').opts(invert_yaxis=True)

# %%
plot_hvplot
# %%
plot_holoviews
```

#### Screenshot
![image](https://user-images.githubusercontent.com/47379702/102268298-708eb680-3f1b-11eb-8c0c-a8db9269e13e.png)

**Comment by jbednar** [comment]
That's odd; I get the same results with HoloViews master (roughly an alpha release of 1.14.1) as you do after installing `holoviz`, which I believe would currently give you holoviews 1.13.5. It's hard to believe that it's been broken that long (6 weeks), but I guess it's possible?

**Comment by hali-geoviz** [comment]
Yes, it is odd. the version I had with the example above is 1.14.0 , but now I rolled back to 1.13.5 and there is still the same issue. And same when rolling back to 1.13.3. But for 1.13.3 I got one installation where this is actually working ok. 
Thus I try rolling back hvplot too from 0.7.0 to 0.5.2. Also did not help, so then tried rolling back bokeh from 2.2.3 to 2.1.1.
That forces panel to go roll back too, as below: 
-  bokeh   2.2.3-py36ha15d459_0 --> 2.1.1-py36h9f0ad1d_0
 - panel   0.10.2-py_0 --> 0.9.7-py_0
 This change did the trick. Now the opts(invert_yaxis is again working as expected). Might be holoviews will work on a later version if bokeh is not 2.2.3. Have not checked this yet.

**Comment by jbednar** [comment]
@philippjfr suggests it's a bug in Panel for linked axes, where they don't respect invert_yaxis.  A new Panel release will be required, but meanwhile using an older Panel release should fix it.

**Comment by hali-geoviz** [comment]
Yes, that might be the thing. I was actually able to upgrade holoviews to 1.14.0 again such that the following set of versions now works: 
{'holoviews': '1.14.0',
 'pandas': '0.24.2',
 'hvplot': '0.5.2',
 'numpy': '1.16.5',
 'bokeh': '2.1.1',
 'panel': '0.9.7'}
Thanks for quick feedback!

**Comment by philippjfr** [comment]
This was indeed fixed in Panel a while ago.

**Comment by hali-geoviz** [comment]
Yes, the specs on versions here are a bit old. Thanks for the update!
