### ISSUE TITLE
Conflicting info in docs for Points and Scatter

### ISSUE THREAD

**Issue by rchurt** [holoviz/holoviews#4760]
In the docs for [Scatter](http://holoviews.org/reference/elements/bokeh/Scatter.html), it says: Note: Although the Scatter element is superficially similar to the Points element (they can generate plots that look identical), the two element types are semantically quite different: Points are used to visualize data where the y variable is dependent. This semantic difference also explains why the histogram generated by hist call above visualizes the distribution of a different dimension than it does for Points.

In the docs for [Points](http://holoviews.org/reference/elements/bokeh/Points.html), it says: Note: Although the Scatter element is superficially similar to the Points element (they can generate plots that look identical), the two element types are semantically quite different. The fundamental difference is that Scatter is used to visualize data where the y variable is dependent. This semantic difference also explains why the histogram generated by hist call above visualizes the distribution of a different dimension than it does for Scatter.

So two points of confusion:
1. Each says the other is "used to visualize data where the y variable is dependent"
2. The statement "This semantic difference also explains why the histogram generated by hist call above visualizes the distribution of a different dimension than it does for [Points or Scatter]" is wrong because in both cases `hist` displays the `z` dimension.

**Comment by jbednar** [comment]
Whoa, those are some old docs, and that glaring error must have been sitting there confusing people for many years now with apparently no one ever realizing it made no sense. Scatter is the one where y is dependent (i.e. one kdim (x)), and Points is one where y is independent (i.e. two kdims (x,y)). A PR on the docs would help clear that up! 

I have no explanation for point 2; any ideas @jlstevens and @philippjfr?

**Comment by rchurt** [comment]
As a broader point, I think it would be useful to make significant changes to the `Scatter` docs, since right now they look almost identical to `Points`, but as the inconsistency mentioned above points out, these are two different functions. My vote would be to add some examples to the docs for `Scatter` modified from the docs for `Bars`, showing categorical data (where it's clear that y is dependent).

**Comment by jbednar** [comment]
That would be great!

**Comment by jlstevens** [comment]
Two mistaken characters make such a difference! As Jim says, it should be:

> Points are used to visualize data where the y variable is *in*dependent.

As for the second issue, I suspect it is also a case of old docs not being updated when they should have been.

Thanks for reporting this!

**Comment by jlstevens** [comment]
Looks like the above referenced PR has addressed this issue. Closing but feel free to comment if you think it needs to be reopened.
