### ISSUE TITLE
tiles broken?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#4768]
```
import holoviews as hv
hv.extension()

hv.element.tiles.EsriImagery().opts(width=600, height=550)
```
I am following: https://holoviews.org/reference/elements/bokeh/Tiles.html
But 
![image](https://user-images.githubusercontent.com/15331990/102913506-78cb8200-4444-11eb-8e09-ff30affafad6.png)

**Comment by philippjfr** [comment]
This still defaults to 'matplotlib':

```python
hv.extension()
```

**Comment by jbednar** [comment]
Maybe we should add a warning now requesting that users specify the extension explicitly, as there shouldn't be a default value for that eventually.
