### ISSUE TITLE
Typo in Docs Exporting_and_Archiving.html

### ISSUE THREAD

**Issue by guettli** [holoviz/holoviews#4772]
> The fig="png" part of the hv.save function call above  ...

http://holoviews.org/user_guide/Exporting_and_Archiving.html

But above call does not contain `fig="png"`.

There is a typo.

**Comment by jlstevens** [comment]
Thanks for reporting this! Marking as a simple doc fix for the next milestone.

**Comment by jlstevens** [comment]
I'll fix this now.

**Comment by jlstevens** [comment]
Fixed in the PR above.
