### ISSUE TITLE
Curved muted in Overlay does not work

### ISSUE THREAD

**Issue by kripnerl** [holoviz/holoviews#4784]
#### ALL software version info
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

(only some selected)
**bokeh                     2.2.3            py38h578d9bd_0    conda-forge**
**holoviews                 1.14.0             pyhd3eb1b0_0**  
hvplot                    0.7.0              pyhd3eb1b0_1
ipykernel                 5.4.2            py38h81c977d_0    conda-forge
ipython                   7.19.0           py38h81c977d_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1            py38h32f6830_1    conda-forge
jupyter_core              4.7.0            py38h578d9bd_0    conda-forge
jupyter_highlight_selected_word 0.2.0           py38h32f6830_1002    conda-forge
jupyter_latex_envs        1.4.6           py38h32f6830_1001    conda-forge
jupyter_nbextensions_configurator 0.4.1            py38h32f6830_2    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
**python                    3.8.6           h852b56e_0_cpython    conda-forge**
notebook                  6.1.5            py38h578d9bd_0    conda-forge
numpy                     1.19.4           py38h18fd61f_2    conda-forge

#### Description of expected behavior and the observed behavior

According to https://github.com/holoviz/holoviews/issues/3730 combination of various setting of `muted` in `opts` od `Curve` should result in muted and not muted curves in `Overlay` plot.  

Actually, `muted` option is ignored as `Overlay` is plotted. Muted option is working when a single `Curve` is plotted.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
hv.Overlay([
    hv.Curve((np.arange(5)), label='increase') *
    hv.Curve((np.arange(5)*-1+5), label='decrease').opts(muted=True)
])
```

or 

```python
hv.Overlay([
    hv.Curve((np.arange(5)), label='increase'),
    hv.Curve((np.arange(5)*-1+5), label='decrease').opts(muted=True)
])
```

#### Stack traceback and/or browser JavaScript console output

No error & I don't know how to properly copy it. Sorry.

#### Screenshots or screencasts of the bug in action

![Screenshot_20210112_122346](https://user-images.githubusercontent.com/38673295/104308512-14469480-54d1-11eb-9c09-2a7b93be4a97.png)

**Comment by jlstevens** [comment]
I've confirmed this bug. Note you don't need `hv.Overlay` on the outside if you are using `*`:

![image](https://user-images.githubusercontent.com/890576/107254211-b5efd180-69fc-11eb-855e-bda32bf8297f.png)
