### ISSUE TITLE
Overlaying a Holoviews Graph element on Holoviews Tiles element

### ISSUE THREAD

**Issue by hokieg3n1us** [holoviz/holoviews#4786]
#### ALL software version info
Python = 3.8.6
Holoviews = 1.14.1
Bokeh = 2.2.3

#### Description of expected behavior and the observed behavior
Like other Holoviews elements, such as Path, Polygons, Points, I expect the Graph element to overlay on the Tiles element, when the node coordinates are specified properly in Web Mercator. In the example below, display of the graph by itself works as expected, but overlay with the Tiles element produces an error.

#### Complete, minimal, self-contained example code that reproduces the issue
```
import pandas as pd
import holoviews as hv
import colorcet as cc

from holoviews.element import tiles

hv.extension('bokeh', inline=True, logo=False)

W = 600
H = 400

nodes_df = pd.DataFrame([('Reagan National Airport', -8576192.708945338, 4700498.362921761), ('San Francisco International Airport', -13623406.643910237, 4526067.87611727)], columns =['index', 'x', 'y']) 
edges_df = pd.DataFrame([('Reagan National Airport', 'San Francisco International Airport', 1)], columns =['start', 'end', 'count']) 

nodes = hv.Nodes((nodes_df['x'], nodes_df['y'], nodes_df['index']),)
graph = hv.Graph(((edges_df['start'], edges_df['end'], edges_df['count']), nodes,), vdims='count').opts(width=W, height=H)

tiles.CartoDark() * graph
```

#### Stack traceback and/or browser JavaScript console output
---------------------------------------------------------------------------
>KeyError                                  Traceback (most recent call last)
>~\miniconda3\envs\jumpstreet\lib\site-packages\IPython\core\formatters.py in __call__(self, obj, include, exclude)
>    968 
>    969             if method is not None:
>--> 970                 return method(include=include, exclude=exclude)
>    971             return None
>    972         else:
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\core\dimension.py in _repr_mimebundle_(self, include, exclude)
>   1314         combined and returned.
>   1315         """
>-> 1316         return Store.render(self)
>   1317 
>   1318 
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\core\options.py in render(cls, obj)
>   1403         data, metadata = {}, {}
>   1404         for hook in hooks:
>-> 1405             ret = hook(obj)
>   1406             if ret is None:
>   1407                 continue
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\ipython\display_hooks.py in pprint_display(obj)
>    280     if not ip.display_formatter.formatters['text/plain'].pprint:
>    281         return None
>--> 282     return display(obj, raw_output=True)
>    283 
>    284 
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\ipython\display_hooks.py in display(obj, raw_output, **kwargs)
>    250     elif isinstance(obj, (CompositeOverlay, ViewableElement)):
>    251         with option_state(obj):
>--> 252             output = element_display(obj)
>    253     elif isinstance(obj, (Layout, NdLayout, AdjointLayout)):
>    254         with option_state(obj):
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\ipython\display_hooks.py in wrapped(element)
>    144         try:
>    145             max_frames = OutputSettings.options['max_frames']
>--> 146             mimebundle = fn(element, max_frames=max_frames)
>    147             if mimebundle is None:
>    148                 return {}, {}
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\ipython\display_hooks.py in element_display(element, max_frames)
>    190         return None
>    191 
>--> 192     return render(element)
>    193 
>    194 
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\ipython\display_hooks.py in render(obj, **kwargs)
>     66         renderer = renderer.instance(fig='png')
>     67 
>---> 68     return renderer.components(obj, **kwargs)
>     69 
>     70 
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\plotting\renderer.py in components(self, obj, fmt, comm, **kwargs)
>    408                 doc = Document()
>    409                 with config.set(embed=embed):
>--> 410                     model = plot.layout._render_model(doc, comm)
>    411                 if embed:
>    412                     return render_model(model, comm)
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\panel\viewable.py in _render_model(self, doc, comm)
>    422         if comm is None:
>    423             comm = state._comm_manager.get_server_comm()
>--> 424         model = self.get_root(doc, comm)
>    425 
>    426         if config.embed:
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\panel\viewable.py in get_root(self, doc, comm, preprocess)
>    480         """
>    481         doc = init_doc(doc)
>--> 482         root = self._get_model(doc, comm=comm)
>    483         if preprocess:
>    484             self._preprocess(root)
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\panel\layout\base.py in _get_model(self, doc, root, parent, comm)
>    110         if root is None:
>    111             root = model
>--> 112         objects = self._get_objects(model, [], doc, root, comm)
>    113         props = dict(self._init_properties(), objects=objects)
>    114         model.update(**self._process_param_change(props))
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\panel\layout\base.py in _get_objects(self, model, old_objects, doc, root, comm)
>    100             else:
>    101                 try:
>--> 102                     child = pane._get_model(doc, root, model, comm)
>    103                 except RerenderError:
>    104                     return self._get_objects(model, current_objects[:i], doc, root, comm)
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\panel\pane\holoviews.py in _get_model(self, doc, root, parent, comm)
>    239             plot = self.object
>    240         else:
>--> 241             plot = self._render(doc, comm, root)
>    242 
>    243         plot.pane = self
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\panel\pane\holoviews.py in _render(self, doc, comm, root)
>    304                 kwargs['comm'] = comm
>    305 
>--> 306         return renderer.get_plot(self.object, **kwargs)
>    307 
>    308     def _cleanup(self, root):
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\plotting\bokeh\renderer.py in get_plot(self_or_cls, obj, doc, renderer, **kwargs)
>     71         combining the bokeh model with another plot.
>     72         """
>---> 73         plot = super(BokehRenderer, self_or_cls).get_plot(obj, doc, renderer, **kwargs)
>     74         if plot.document is None:
>     75             plot.document = Document() if self_or_cls.notebook_context else curdoc()
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\plotting\renderer.py in get_plot(self_or_cls, obj, doc, renderer, comm, **kwargs)
>    241             init_key = tuple(v if d is None else d for v, d in
>    242                              zip(plot.keys[0], defaults))
>--> 243             plot.update(init_key)
>    244         else:
>    245             plot = obj
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\plotting\plot.py in update(self, key)
>    980     def update(self, key):
>    981         if len(self) == 1 and ((key == 0) or (key == self.keys[0])) and not self.drawn:
>--> 982             return self.initialize_plot()
>    983         item = self.__getitem__(key)
>    984         self.traverse(lambda x: setattr(x, '_updated', True))
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\plotting\bokeh\element.py in initialize_plot(self, ranges, plot, plots)
>   2308         self.tabs = self.tabs or any(isinstance(sp, TablePlot) for sp in self.subplots.values())
>   2309         if plot is None and not self.tabs and not self.batched:
>-> 2310             plot = self._init_plot(key, element, ranges=ranges, plots=plots)
>   2311             self._init_axes(plot)
>   2312         self.handles['plot'] = plot
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\plotting\bokeh\element.py in _init_plot(self, key, element, plots, ranges)
>    492         subplots = list(self.subplots.values()) if self.subplots else []
>    493 
>--> 494         axis_types, labels, plot_ranges = self._axes_props(plots, subplots, element, ranges)
>    495         xlabel, ylabel, _ = labels
>    496         x_axis_type, y_axis_type = axis_types
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\plotting\bokeh\element.py in _axes_props(self, plots, subplots, element, ranges)
>    425             else:
>    426                 if isinstance(el, Graph):
>--> 427                     xtype = el.nodes.get_dimension_type(xdims[0])
>    428                 else:
>    429                     xtype = el.get_dimension_type(xdims[0])
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\core\data\__init__.py in pipelined_fn(*args, **kwargs)
>    199 
>    200             try:
>--> 201                 result = method_fn(*args, **kwargs)
>    202                 if PipelineMeta.disable:
>    203                     return result
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\core\data\__init__.py in get_dimension_type(self, dim)
>   1120         if dim_obj and dim_obj.type is not None:
>   1121             return dim_obj.type
>-> 1122         return self.interface.dimension_type(self, dim_obj)
>   1123 
>   1124 
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\core\data\pandas.py in dimension_type(cls, dataset, dim)
>     25     @classmethod
>     26     def dimension_type(cls, dataset, dim):
>---> 27         name = dataset.get_dimension(dim, strict=True).name
>     28         idx = list(dataset.data.columns).index(name)
>     29         return dataset.data.dtypes[idx].type
>
>~\miniconda3\envs\jumpstreet\lib\site-packages\holoviews\core\dimension.py in get_dimension(self, dimension, default, strict)
>    986             name_map.update({util.dimension_sanitizer(dim.name): dim for dim in all_dims})
>    987             if strict and dimension not in name_map:
>--> 988                 raise KeyError("Dimension %r not found." % dimension)
>    989             else:
>    990                 return name_map.get(dimension, default)
>
>KeyError: 'Dimension None not found.'
>
>:Overlay
>   .Tiles.I :Tiles   [x,y]
>   .Graph.I :Graph   [start,end]   (count)
>1

#### Screenshots or screencasts of the bug in action

![image](https://user-images.githubusercontent.com/36244490/104369885-1a963a00-54ec-11eb-98d1-923f5e2e5c13.png)

**Comment by jlstevens** [comment]
Definitely a bug. I agree there should be no problem overlaying graphs on top of tile sources!
