### ISSUE TITLE
Make documentation more browsable with ToC

### ISSUE THREAD

**Issue by hyamanieu** [holoviz/holoviews#4801]
#### Problem statement
It concerns all holoviz projects but I'm posting here as I believe holoviews is the core project. I spend a considerable amount of time on various holoviz documentations (hvplot, holoviews and panel). Navigating on each is not simple as a table of content is lacking.

#### Describe the solution you'd like
Bokeh's documentation has a flying table of content. This would be the best solution to me.

#### Describe alternatives you've considered
A non flying table of content would also simplify browsing the documentation.

#### Additional context
See e.g. https://docs.bokeh.org/en/latest/docs/user_guide/data.html#userguide-data with the flying ToC.

**Comment by jlstevens** [comment]
I agree there should be a nice table of contents somewhere in the docs to help with navigation.

**Comment by ppwadhwa** [comment]
I'd prefer a TOC on the side if its a full TOC.  To me, that is more out of the way and can hold more information.  Looking at Bokeh's example, it looks like sections (rather than a full TOC) are listed at the top that stay in place as you scroll.  This isn't bad either for a quick way to access different sections.

**Comment by hyamanieu** [comment]
On a desktop using Firefox, Bokeh's TOC is on the side (or perhaps I misunderstood you).
Besides upon reaching a specific section, its subsections appear and other subsections disappear so the TOC is not cluttered yet exhaustive.

**Comment by ppwadhwa** [comment]
Great, I will look more closely!  I agree that having a convenient way to navigate to different sections would be very useful.

**Comment by jbednar** [comment]
I'm confused; I don't see any clear difference between Bokeh's TOC:
![image](https://user-images.githubusercontent.com/1695496/108919016-ed16d300-75f7-11eb-81b9-54a2a1b476dd.png)
and HoloViews' existing TOC:
![image](https://user-images.githubusercontent.com/1695496/108919065-015ad000-75f8-11eb-8069-bb6259a8c1e6.png)

**Comment by hyamanieu** [comment]
James,
the "flying" toc is on the right hand side. It's the webpage ToC, not the website Toc.

![grafik](https://user-images.githubusercontent.com/15906523/108964655-08c3bd00-767c-11eb-8781-f883eb5abb99.png)

Not sure which browser/machine you're using, but below 1200px width the flying ToC indeed disappears.

**Comment by jbednar** [comment]
Ah, yes, I browse docs on a portrait-orientation monitor and Bokeh's flying TOC isn't shown in my configuration. I'm still confused, though, as your original issue description asks for a flying TOC but also says that "A non flying table of content would also simplify browsing the documentation." These sites already have a non-flying TOC, so I'm unsure what potential simplification you're referring to here. 

Was that just confusingly stated, and the real request is then "I would like to have a flying TOC for HoloViz docs pages to help me better navigate within each page" (given that the overall site navigation is already covered by the TOC on the left site)?

**Comment by hyamanieu** [comment]
There is no ToC of webpages (there is for the whole site though). [Composing Elements](http://holoviews.org/user_guide/Composing_Elements.html) for example has 4 `h2` header and 6 `h3` headers. Having a ToC with these headers would greatly help.
I am not a web developer, but I guess there are libraries doing that automatically as is done within Jupyter with the ToC add-on?

**Comment by jbednar** [comment]
If you just want those subheadings to show up on the TOC on the left, I believe that's as simple as changing the `tocdepth` on the sphinx doc configuration. So is that the specific request here, i.e. _either_ a flying toc for navigating the subheadings on the page, _or_ to change the `tocdepth` for HoloViz projects to include at least top-level headings and not just separate pages?

**Comment by hyamanieu** [comment]
I can see this flying webpage ToC on the right hand side was included in three different parts of the sphinx documentation in Bokeh  (id is `bd-toc-nav`) https://github.com/search?q=org%3Abokeh+bd-toc-nav&type=code
(The id for the website ToC on the left hand side is `bd-docs-nav`.)
However not sure how/where it is configured. Perhaps @bryevdv could point us in the right direction?

My request is rather:

- either have the web page ToC on the right hand side flying. This may mean to take out the message regarding the non-interactivity of auto generated notebooks which is exactly located where I would see this ToC. I believe this message is less important than a ToC, it could be a simple note at the top of a page.
- or have a fixed one at the top of the web page if it's easier. It's already helping a lot with long pages.

In both cases I would leave the web site ToC unchanged.

Of course if the `h2` headers appear on the left hand side ToC as subsections, it's already an improvement to me. I can understand it's the simplest way to go if it's only about changing a parameter like `tocdepth`.

**Comment by bryevdv** [comment]
All I can note is that Bokeh uses a customized vendored version of the "pydata" sphinx theme:

https://github.com/pydata/pydata-sphinx-theme


Customized and vendored because we were *very* early adopters and it was missing some features we needed at the time. But we are meaning to move over to the official theme package soon.

**Comment by hyamanieu** [comment]
I wanted to see what I could do. But the [doc Makefile includes another Makefile](https://github.com/holoviz/holoviews/blob/8914981eab6de28cd06f98c92638257403e8e202/doc/Makefile#L7) that disappeared in a 2014 commit. Not sure where to go from there.

**Comment by jbednar** [comment]
We aren't using any makefiles that I'm aware of, so presumably that's just hanging around (though I'd be reluctant to delete it without checking!).  The steps for building docs are listed in [.github/workflows/docs.yml](https://github.com/holoviz/holoviews/blob/master/.github/workflows/docs.yml).

**Comment by jbednar** [comment]
> This may mean to take out the message regarding the non-interactivity of auto generated notebooks which is exactly located where I would see this ToC. I believe this message is less important than a ToC, it could be a simple note at the top of a page.

We've previously had this note at the top of pages, and people kept missing it.  They would go to a certain spot in the page that looked interesting, play with the example and then report that the example was broken (or, worse, assume the tool was buggy and give up on it). We definitely need a flying warning like that on any pages that have content that works in a notebook or server context but not on a web page. It's conceptually fine to combine that note with a flying TOC, but I don't know how that would work at the code level.

**Comment by hyamanieu** [comment]
Moved to https://github.com/pyviz-dev/sphinx_holoviz_theme/issues/17
