### ISSUE TITLE
.opts(toolbar=None) clips x axis last tick label at far edge

### ISSUE THREAD

**Issue by dwr-psandhu** [holoviz/holoviews#4804]
#### ALL software version info
holoviews version 1.14.0, python 3.7+, jupyter notebook, windows, chrome

#### Description of expected behavior and the observed behavior
plots are fine when toolbar is enabled. Hiding toolbar with .opts(toolbar=None) results in clipping
#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
n=366 # done for making sure of tick label at right most end of x axis
df=pd.DataFrame(range(n),pd.date_range(start='2005-01-01',periods=n,freq='D'))
df.hvplot().opts(toolbar=None)
```
![hv-clipped-xaxis-label](https://user-images.githubusercontent.com/11561317/106040674-a3d27280-608f-11eb-8022-798a900a05e4.jpg)
![hv-clipped-xaxis-label2](https://user-images.githubusercontent.com/11561317/106040855-dbd9b580-608f-11eb-8e0f-07169d33b9e9.jpg)

**Comment by jbednar** [comment]
This would be an issue for Bokeh; not much we can do about it here. I believe @mattpap is already looking at improvements to Bokeh's label handling that could address the issue eventually; see https://github.com/bokeh/bokeh/pull/10828.
