### ISSUE TITLE
Support streams dictionary format in operations

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#4807]
Since https://github.com/holoviz/holoviews/pull/4787 was merged, `DynamicMap` supports a dictionary format for streams. For consistency, I think operations should support the same format (which can help resolve parameter name clashes):

```python
class example(Operation):
   streams = {'x':PointerXY.param.x, 'y':PointerXY.param.y, 'tap_x':Tap.param.x, 'tap_y':Tap.param.y}
   x = ...
   y = ...
   tap_x = ...
   tap_y = ...
```

The main wrinkle is that these are stream class parameters, not instance parameters (as in the current list format). I imagine the declared mapping would be transferred to stream instance when they are created.

Assigning to 1.14.2 as this isn't a change of API (but an extension of it) and it would be good to achieve consistency with what `DynamicMap` supports as soon as possible.

**Comment by philippjfr** [comment]
This needs to go in today or tomorrow if we want it in the 1.14.2 release.

**Comment by jlstevens** [comment]
Currently working on it. I'll know this evening if it is a quick addition or something that won't make it into the release.

**Comment by jlstevens** [comment]
Addressed in the PR above (now merged).
