### ISSUE TITLE
Syntactic sugar for Dataset.to

### ISSUE THREAD

**Issue by bdch1234** [holoviz/holoviews#4819]
Could we perhaps add some syntactic sugar for the to-method of hv.Dataset? I'm thinking something like
`ds.element_name(*args* **kwargs)`
would correspond to
`ds.to(hv.ElementName, *args, **kwargs)`,
so that we could e.g. do
`ds.scatter('x', 'y')`
or
`ds.curve('x', 'y')`

**Comment by philippjfr** [comment]
Thanks for the suggestion. IMO that would hugely pollute the namespace, and the `.to` accessor already implements this, e.g. `ds.to.scatter` works fine. These days I would strongly recommend using [hvPlot](https://hvplot.pyviz.org/) over the `.to` interface, so I'll close this.
