### ISSUE TITLE
Better error message when using sum() with plots

### ISSUE THREAD

**Issue by datapythonista** [holoviz/holoviews#4834]
I think it'd be nice to make holoviews work with Python `sum()`.

```python
sum([holoviews.Area(data=(x[num], y[num])) for num in range(8)]).cols(2)
```

This is currently raising an exception, since `sum([area1, area2, area3,  ...])` is equivalent to `0 + area1 + area2 + area3` (the `0` is the `start` in `sum(iterable, /, start=0)`). And `Area` (or other elements) `__radd__` is not implemented for `0`.

Feels like using `sum()` would make cases like the above much more readable than alternatives using `functools.reduce` or loops. I think it'd be worth implementing it, even if `Area() + 0` may not make so much sense per se.

**Comment by jbednar** [comment]
I'd recommend doing `holoviews.Layout([holoviews.Area(data=(x[num], y[num])) for num in range(8)]).cols(2)`; seems much clearer than `sum`.

**Comment by datapythonista** [comment]
That makes sense, didn't think about it. Thanks for the quick answer!

**Comment by jbednar** [comment]
Since we're abusing `+` it's not _crazy_ to support `sum`; just to avoid having people end up here, but I'd still always recommend `hv.Layout` over `sum`.

**Comment by datapythonista** [comment]
You've got pretty amazing error messages suggesting the right thing to do for some mistakes (like a misspelled `opt`). Not sure how many users would think of `sum`, but maybe raising an error message suggesting to use `Layout` when `_radd_` is called for `0` could be useful. Something like:

```python
def __radd__(self, other):
    if isinstance(other, int) and other == 0:
        raise TypeError("unsupported operand type(s) for +: 'int' and 'Overlay'. "
                        "If you are using `sum(elements)` to combine a list of elements, "
                        "we recommend you to use `holoviews.Layouts(elements)` instead.")
    ...
```

**Comment by jbednar** [comment]
I remember that I myself first thought of `sum`, before `Layout`, back in the dawn of time when I first started using hv. So I empathize. As a result I'd suggest just making this a warning if we go to the bother of checking for it, since we do know what to do here (return `self`).

**Comment by jlstevens** [comment]
I quite like the idea of raising a better exception as people do naturally try to use `sum` from time to time. 

As @jbednar says, `Layout` is the correct way to do this but I think your suggestion for improving `__radd__` with a good exception message would help point people in the right direction. If you would be happy submitting a PR, that would be very welcome!

**Comment by jlstevens** [comment]
Addressed in the PR referenced above.
