### ISSUE TITLE
Incorrect pickle dump/load for Dimension

### ISSUE THREAD

**Issue by rafgonsi** [holoviz/holoviews#4838]
#### ALL software version info
Holoviews 1.14.1, Python 3.7.6

#### Description of expected behavior and the observed behavior
`hv.Dimension` does not pickle correctly. As shown in example below, dimension loaded from pickle is different than the original.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import holoviews as hv
import pickle

path = "tmp.pkl"
d = hv.Dimension('current', label='I', unit='mA')

with open(path, 'wb') as handle:
    pickle.dump(d, handle)

with open(path, 'rb') as handle:
    d_loaded = pickle.load(handle)
    
print(repr(d))
print(d.pprint_label)

print(repr(d_loaded))  # repr does not match
print(d_loaded.pprint_label)  # note that label is not used

```
result:
```
Dimension('current', label='I', unit='mA')
I (mA)
Dimension('current')
current (mA)
```
whereas I would expect to see:
```
Dimension('current', label='I', unit='mA')
I (mA)
Dimension('current', label='I', unit='mA')
I (mA)
```

**Comment by jlstevens** [comment]
Thanks for reporting this!

`Dimension` objects should definitely pickle correctly so I consider this a relatively high priority bug.

**Comment by jlstevens** [comment]
We can close this issue when the PR referenced above is merged.
