### ISSUE TITLE
AttributeError: 'str' object has no attribute 'dataspecs'

### ISSUE THREAD

**Issue by elarroba** [holoviz/holoviews#4848]
#### ALL software version info
bokeh 2.3.0
holoviews 1.14.1
jupyterlab 3.0.9
notebook 6.2.0

#### Description of expected behavior and the observed behavior
The expected behavior is for jupyter notebook to show the plot.
Same error occurs with different kind of plots.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import holoviews as hv
hv.extension('bokeh')
data = [('one',8),('two', 10), ('three', 16), ('four', 8), ('five', 4), ('six', 1)]
bars = hv.Bars(data, hv.Dimension('Car occupants'), 'Count')

bars
```

#### Stack traceback and/or browser JavaScript console output
Traceback (most recent call last):

  File "c:\users\migue\.virtualenvs\hv-test-8p3rpe1k\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1359, in _init_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, source.data)

  File "c:\users\migue\.virtualenvs\hv-test-8p3rpe1k\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1252, in _update_glyph
    dataspecs = glyph.dataspecs()

AttributeError: 'str' object has no attribute 'dataspecs'

#### Screenshots or screencasts of the bug in action

![BugScreenshot](https://us-east-1.linodeobjects.com/edmagroup/arrobalytics/public/Screenshot%202021-02-26%20114224.png)

**Comment by philippjfr** [comment]
See https://github.com/holoviz/holoviews/issues/4845 and https://github.com/holoviz/holoviews/issues/4846. We'll release a new HoloViews with compatibility for Bokeh 2.3 in the coming days for now downgrade bokeh to 2.2.3.
