### ISSUE TITLE
Wrong location of custom datetime ticks

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/holoviews#4884]
Software information:
Holoviews 1.14.2
Bokeh 2.3.0
Python 3.8.8
Ubuntu 18.04
Browser Firefox 87.0, Chromium 89.0

With holoviews v1.14.2, we have support for custom `datetime` ticks (#4831). I updated to this version because I needed this feature.

When supplying a list of `datetime` objects, ticks are indeed shown with the correct spacing, but I've had an issue with the resulting location of ticks, which do not correspond to whatever I set. There are consistently shifted to the left by two hours.

Below is a small example reproducing the issue, with the output I get.

```
line1 = hv.VLine(dt.datetime(2021, 4, 8, 12, 0, 0)).opts(color='black', line_dash='dotted')
line2 = hv.VLine(dt.datetime(2021, 4, 8, 13, 0, 0)).opts(color='black', line_dash='dotted')
line3 = hv.VLine(dt.datetime(2021, 4, 8, 14, 0, 0)).opts(color='black', line_dash='dotted')
df = pd.DataFrame({'var': [1, 2, 3, 4],
                   'date': [dt.datetime(2021, 4, 8, 11, 30, 0), dt.datetime(2021, 4, 8, 12, 30, 0),
                            dt.datetime(2021, 4, 8, 13, 30, 0), dt.datetime(2021, 4, 8, 14, 30, 0)]})
scatter = hv.Scatter(df, 'date', 'var').opts(size=12, tools=['hover'])
plot = line1*line2*line3*scatter.opts(xticks=[dt.datetime(2021, 4, 8, 12, 0, 0),
                                              dt.datetime(2021, 4, 8, 13, 0, 0),
                                              dt.datetime(2021, 4, 8, 14, 0, 0)])

```

![image](https://user-images.githubusercontent.com/49269671/114039714-42930080-9883-11eb-9e9e-5b0afde467a4.png)
Note that tick labels correspond to the actual tick location, meaning the labels themselves are not misleading. Therefore a workaround is to account for the shift in the argument supplied. I get the desired output when I add two hours to the `xticks` I ask for.

I hope there can be a quick fix for this issue, but as an easy workaround is available, this is no urgent matter.

**Comment by Hoxbro** [comment]
Maybe related to #4863.

**Comment by TheoMathurin** [comment]
Indeed.

From your example (one hour shift on 10th March) and mine it seems likely that the input datetimes are converted to UTC time.
