### ISSUE TITLE
Heavy figures when using hv.RGB

### ISSUE THREAD

**Issue by KevinMttn** [holoviz/holoviews#4906]
#### ALL software version info
bokeh
Notebook
OS: Windows 7 Entreprise
Bokeh: '2.2.3'
Holoviews: '1.14.2'

#### Description of expected behavior and the observed behavior
I tried to use hv.RGB in order to display a jpg image of dimension 6000x4000 and size 3MB. However, after having displayed the holoviews object i started to experience freeze and notice that the notebook was 130MB. Even if the result uncompressed the jpg, i did not understood why it was this heavy.
To investigate this, i search in the notebook the section of the js about the image. I found out that it was apparently encoded in uint32 even if the image and hv.rgb were in uint8.

I used it in a notebook and provide below the code and screenshot about the behaviour. For the reproducibility, i have used another image in 4K of 1MB in the same format. It has the same behaviour with smal image but it is more noticeable on big one.

#### Complete, minimal, self-contained example code that reproduces the issue
```
from pathlib import Path
import holoviews as hv
from holoviews import opts
import numpy as np
from PIL import Image

hv.extension('bokeh')

PATH_IMAGE=Path('./test_image.jpg')
age=np.array(Image.open(PATH_IMAGE))
image.dtype
src=hv.RGB(image).opts(width=700,height=400)
src.data.dtype
src
```

#### Screenshots or screencasts of the bug in action
![notebook](https://user-images.githubusercontent.com/83012500/115784279-2f714c00-a3be-11eb-8a94-0ad5b1839061.png)
![size_ipynb](https://user-images.githubusercontent.com/83012500/115784299-34ce9680-a3be-11eb-91ee-aedf0a4c20e0.png)
![uint32](https://user-images.githubusercontent.com/83012500/115784312-38621d80-a3be-11eb-82d0-8dfd02da4f95.png)
![test_image](https://user-images.githubusercontent.com/83012500/115784319-3ac47780-a3be-11eb-8902-0640224fad53.jpg)

**Comment by jbednar** [comment]
I would assume RGB images in Bokeh  use uint32 to pack 8 bits for each color channel and 8 bits for alpha (totalling one 32-bit unit per pixel), which is an efficient way to represent an uncompressed image. A 6000 x 4000 x 4 byte uncompressed image contains 96,000,000 bytes to store the pixels, compared to which 130MB isn't a dramatic amount of overhead.  That level of compression is what makes JPGs so popular!

If your viewport has fewer than 6000 x 4000 pixels, then you could try using `holoviews.operation.datashade()` on the image, which will sample it at the screen resolution for the viewport before passing it to the browser.  That way the HTML file will be smaller, but of course it won't have any ability to zoom beyond what is visible unless you keep Python running.

**Comment by KevinMttn** [comment]
Oh yes, i forgot about the alpha channel and ended with 24 bits. It does make more sense for the uint32 in the js now thank you !

Thank you also for the tip
