### ISSUE TITLE
tiles not showing in documentation

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#4908]
Some just show white square
https://holoviews.org/reference/elements/plotly/Tiles.html
https://holoviews.org/reference/elements/bokeh/Tiles.html

**Comment by jbednar** [comment]
Yep. Many tile providers have started restricting their tiles for use only on a local host, presumably to avoid bandwidth charges from their ISPs. We should separate the list into those that can be published (the ones not white) and those that are ok only for local usage (the white ones). PR gratefully accepted!

**Comment by jbednar** [comment]
Fixed in #4940 and #4941.
