### ISSUE TITLE
Warning "Chart elements should only be supplied a single kdim"

### ISSUE THREAD

**Issue by hyamanieu** [holoviz/holoviews#4912]
#### ALL software version info
latest holoviews 1.14.3 and anything used to build the doc: http://holoviews.org/reference/streams/bokeh/Selection1D_tap.html

#### Description of expected behavior and the observed behavior
This [example](http://holoviews.org/reference/streams/bokeh/Selection1D_tap.html) from the doc should show no warning.
It shows:

> WARNING:param.Scatter: Chart elements should only be supplied a single kdim
> WARNING:param.Scatter: Chart elements should only be supplied a single kdim

It is hard to decipher where it is from.

My own model is also using a `holoviews.stream` object and since update, shows this very same warning. Previous version was `1.13.3`.

#### Complete, minimal, self-contained example code that reproduces the issue
 http://holoviews.org/reference/streams/bokeh/Selection1D_tap.html

**Comment by philippjfr** [comment]
In the example it's because of this:

```python
points = hv.Scatter(data, ['Date', 'r2'], ['block', 'id']).redim.range(r2=(0., 1))
```

which should be updated to:

```python
points = hv.Scatter(data, 'Date', ['r2', 'block', 'id']).redim.range(r2=(0., 1))
```

**Comment by hyamanieu** [comment]
Alright, i'll submit a PR for this example this week.
