### ISSUE TITLE
ValueError: 'cet_rainbow_bgyrm_35_85_c69_r_r' is not a valid value for name

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviews#4916]
HoloViews:  1.14.2

I have a dashboard at awesome-panel.org where the user can select the color map from a list based on `hv.plotting.util.list_cmaps()`. I believe those to be the supported color maps in holoviews?

But when the user selects the `cet_rainbow_bgyrm_35_85_c69_r_r` color map `hv.Area` raises the error `ValueError: 'cet_rainbow_bgyrm_35_85_c69_r_r' is not a valid value for name`.

You can reproduce by running `panel serve` on the below script

```python
import panel as pn
import hvplot.pandas
import holoviews as hv

pn.extension(sizing_mode="stretch_width")

COLOR_MAPS = hv.plotting.util.list_cmaps()

color_map = "cet_rainbow_bgyrm_35_85_c69_r_r"
assert color_map in COLOR_MAPS

data = [(
    [4.7, 4.6, 4.5, 4.4],
    [0, -0.05, -0.1, -0.15],
    [3500, 3600, 3700, 3800],
)]


plot = hv.Path(data, vdims="Cut Distance").opts(
            cmap=color_map, color="Cut Distance", line_width=4, colorbar=True, responsive=True, height=400
        )

pn.pane.HoloViews(plot).servable()
```

# Solution

Either make sure all color maps in `hv.plotting.util.list_cmaps()` can be used as color maps. Or explain how to find the list of valid color maps.

**Comment by jbednar** [comment]
The `_r_r` suffix indicates that it's a reversed reversed colormap, which shouldn't have happened.  Sounds like somewhere between colorcet and HoloViews there is code helpfully providing a reversed version of all colormaps, but this one is already reversed? We'd need to track down where that double-reversed name comes from.

**Comment by jbednar** [comment]
Thanks, @philippjfr !
