### ISSUE TITLE
Stacked area only show last label

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/holoviews#4921]
@Pill-GZ found a bug (and a solution!) for the legend of a stacked area plot only showing the last label. See https://discourse.holoviz.org/t/how-to-add-legend-for-stacked-area-plots/2193

**Comment by Pill-GZ** [comment]
The "solution" fixed the problem for areas passed in as hv.Overlay, i.e., when `is_overlay = isinstance(areas, Overlay)` is True.

I was not sure what other types of input are intended. I'd appreciate if someone familiar with the class and its design can take a look.
