### ISSUE TITLE
Trimesh support for dask dataframes very different from pandas

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#4927]
In [this example](https://examples.pyviz.org/bay_trimesh/bay_trimesh.html#bay-trimesh-gallery-bay-trimesh) I tried getting the HoloViews example at the end to work (note, that example is wrong, neither of those images are wireframes!). I did this by transforming `verts`, `tris` and `mesh` to their dask versions as `verts_ddf`, `tris_ddf` and `mesh_ddf` using:

```python
from dask import dataframe as dd
verts_ddf = dd.from_pandas(verts, npartitions=4)
tris_ddf = dd.from_pandas(tris, npartitions=4)
mesh_ddf = du.mesh(verts_ddf, tris_ddf).persist()
```

Now the datashader portion of the notebook works fine using the dask dataframes instead of the original pandas dataframes. In the HoloViews example at the end, this is no longer true. This is what works with pandas (fixing the example to show a wireframe):

```python
import holoviews as hv
import geoviews as gv
from holoviews import opts
from holoviews.operation.datashader import datashade

hv.extension("bokeh")
opts.defaults(
    opts.Image(width=450, height=450),
    opts.RGB(width=450, height=450))

wireframe = datashade(hv.TriMesh((tris,hv.Points(verts, vdims=[])), label="Wireframe"))
trimesh = datashade(hv.TriMesh((tris,hv.Points(verts, vdims='z')), label="TriMesh"), aggregator=ds.mean('z'))
wireframe + trimesh
```

With this result:

![image](https://user-images.githubusercontent.com/890576/118308706-e3dc2a80-b4b1-11eb-9807-fc0b4ca99e93.png)

But if I just replace `tris` with `tris_ddf` etc I get an exception:

```python
NotImplementedError: Dask dataframe does not support assigning non-scalar value.
```

Here is what does work, using a very different constructor:

```python
wire_nodes=hv.TriMesh((tris_ddf, hv.Nodes(verts_ddf, ['x', 'y', 'index'], [])), label="Wireframe")
trimesh_nodes=hv.TriMesh((tris_ddf, hv.Nodes(verts_ddf, ['x', 'y', 'index'], ['z'], label="TriMesh")))
wireframe = datashade(wire_nodes)
trimesh = datashade(trimesh_nodes, aggregator=ds.mean('z'))
wireframe + trimesh
```

![image](https://user-images.githubusercontent.com/890576/118308879-1dad3100-b4b2-11eb-933a-549d4b310f44.png)

This is unintuitive (and @philippjfr tells that this isn't necessary if an index column is present) and it would be nice if you could transparently replace pandas dataframes with dask ones.

**Comment by jbednar** [comment]
Here's the code involved, which I tested in this environment:

```
python=3.6.11
notebook=6.1.5
ipykernel=5.3.4
colorcet=1.0.0
datashader=0.12.1
geoviews=1.9.1
holoviews=1.14.3
pandas=1.1.5
dask=2020.12.0
```
[bay_trimesh.ipynb.gz](https://github.com/holoviz/holoviews/files/6480753/bay_trimesh.ipynb.gz)

**Comment by jlstevens** [comment]
@philippjfr Given that you understand the details of the network format in HoloViews best, do you have any suggestions for either supporting the same constructor style for dask dataframes as pandas dataframes or at minimum some way of warning users trying to use dask dataframes in the same way as works for pandas?

**Comment by jbednar** [comment]
Another option may be to change our Pandas examples to whatever works for both Pandas and Dask, if any, and if that way is a plausible recommendation for both.

**Comment by philippjfr** [comment]
Definite option. It would be more efficient in both the pandas and dask case to use the existing index rather than adding a new column with an integer index.
