### ISSUE TITLE
No registered _repr_x_ causing pytest failures.

### ISSUE THREAD

**Issue by Melendowski** [holoviz/holoviews#4930]
Given a holoviews object, I expect `_repr_mimebundle_()[0]` to be a dictionary with a key `'text/html'`.  When using a `python` kernel it does not but when using a `ipython` kernel it does. This difference is causing `pytest` failures where the underlying code calls `_repr_mimebundle_` directly but it is empty due to `pytest` running a `python` kernel.

#### ALL software version info
ipython=7.22.0
python=3.71.
holoviews=1.14.3
pytest=4.0.2

#### Description of expected behavior and the observed behavior
Given a holoviews object, I expect `_repr_mimebundle_()[0]` to be a dictionary with a key `'text/html'`.  When using a `python` kernel it does not but when using a `ipython` kernel it does.

#### Complete, minimal, self-contained example code that reproduces the issue

Testing in ipython kernel where there is a registered `_repr_x_`.

```python
In [1]: import numpy as np

In [2]: mu = 0

In [3]: sigma = 1

In [4]: n = 1000

In [5]: x = np.random.normal(mu, sigma, n)

In [6]: p = (2 * np.pi * sigma ** 2) ** (-0.5) * np.exp(-0.5) * (x-mu) ** 2 / sigma ** 2

In [7]: import holoviews as hv

In [8]: hv.extension("bokeh")

In [9]: 'text/html' in hv.Histogram([x, p])._repr_mimebundle_()[0]
Out[9]: True
```

Testing in a python kernel where this is no registered `_repr_x_`

```python
>>> import numpy as np
>>> mu = 0
>>> sigma = 1
>>> n = 1000
>>> x = np.random.normal(mu, sigma, n)
>>> p = (2 * np.pi * sigma ** 2) ** (-0.5) * np.exp(-0.5) * (x-mu) ** 2 / sigma ** 2
>>> import holoviews as hv
>>> hv.extension("bokeh")
>>> 'text/html' in hv.Histogram([x, p])._repr_mimebundle_()[0]
False
```

I was hoping to obtain some guidance on how to register this output so that my `pytest` tests do not fail incorrectly.

**Comment by philippjfr** [comment]
This is intentional and you shouldn't really call `_repr_mimebundle_` for testing. If you want to render HoloViews objects you should use the `Renderer` objects as described in http://holoviews.org/user_guide/Plots_and_Renderers.html.

**Comment by Melendowski** [comment]
@philippjfr Thank you for the quick reply.

Let me give some background, I have a object composition going on whose `_repr_html_` calls `_repr_mimebundle_` of the stored `holoviews` object.  I just want to have a test saying `_repr_html_` works. What is the best way to do this?

**Comment by philippjfr** [comment]
If you just want to test whether an object renders use `hv.render(obj)`. From there HoloViews generally just calls the underlying plotting library to turn the Bokeh, Matplotlib, Plotly figure into the appropriate representation (html, png etc.)
