### ISSUE TITLE
Freehanddraw not working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviews#4942]
If you try the [`Freehanddraw` reference notebook](https://holoviews.org/reference/streams/bokeh/FreehandDraw.html#streams-bokeh-gallery-freehanddraw), then the example does not work. 

- What you draw does not show up until you start drawing 1 or 2 times more.
- Nothing happens when you reset the plot.

It's the same if you run the code your self.

```python
import holoviews as hv
from holoviews import opts
from holoviews import streams
import panel as pn
hv.extension('bokeh')

path = hv.Path([])
freehand = streams.FreehandDraw(source=path, num_objects=3,
                                styles={'line_color': ['red', 'green', 'blue']})

path.opts(
    opts.Path(active_tools=['freehand_draw'], height=400, line_width=10, width=400))

pn.panel(path).servable()
```

https://user-images.githubusercontent.com/42288570/119033622-b7427a00-b9ad-11eb-9dd6-6f0016d4a037.mp4

**Comment by philippjfr** [comment]
>Nothing happens when you reset the plot.

Nothing is meant to happen, what would you expect here?

**Comment by MarcSkovMadsen** [comment]
I would expect my drawings to disappear. How would I otherwise remove/ reset my drawing?

**Comment by thoth291** [comment]
I'm pretty positive that the problem is triggered by using `styles` option.
This is working:
```python
path = hv.Path([])
freehand = hv.streams.FreehandDraw(source=path, num_objects=3, tooltip='1st Class',
                                   #styles=dict(line_color=['blue'])
                                  )
path.opts(hv.opts.Path(active_tools=['freehand_draw'],height=400,width=400,line_width=10,line_color='green'))
```
and this is not working (shows a line only when you start drawing a new one):
```python
path = hv.Path([])
freehand = hv.streams.FreehandDraw(source=path, num_objects=3, tooltip='1st Class',
                                   styles=dict(line_color=['blue'])
                                  )
path.opts(hv.opts.Path(active_tools=['freehand_draw'],height=400,width=400,line_width=10))
```
It sounds like a simple index issue somewhere...
