### ISSUE TITLE
hv.Curve(...).opts(interpolation='steps-post') broken when switching extensions

### ISSUE THREAD

**Issue by douglas-raillard-arm** [holoviz/holoviews#4947]
#### ALL software version info
holoviews: 1.14.3
matplotlib: 3.4.2

#### Description of expected behavior and the observed behavior
When changing the extension before displaying the plot,
`hv.Curve(...).opts(interpolation='steps-post')` gives the same plot as `hv.Curve(...)`, i.e. not a step behavior. 

#### Complete, minimal, self-contained example code that reproduces the issue
In a jupyter notebook cell:

```
import holoviews as hv
# If hv.extension('bokeh') is removed, the plot has the correct interpolation.
hv.extension('bokeh')
x=hv.Curve([1,2,3]).options(interpolation='steps-post')
hv.extension('matplotlib')
x
```

#### Screenshots or screencasts of the bug in action

Correct behavior:
![Screenshot_20210525_174614](https://user-images.githubusercontent.com/23336875/119536560-1f63d800-bd81-11eb-917b-2bf1a2d5e432.png)
Bug:
![Screenshot_20210525_174500](https://user-images.githubusercontent.com/23336875/119536393-f3e0ed80-bd80-11eb-85d0-d14bb6cf8774.png)

**Comment by jbednar** [comment]
I think that's all working as designed.  Here you've applied options for the Bokeh backend, then switched to the Matplotlib backend, for which no options have been set explicitly.  Plus, it's not recommended to switch backends dynamically using `hv.extension()`, which in addition to switching backends also sets up a lot of machinery in the notebook. Instead, if you want to dynamically switch backends, you should (a) declare that both backends should be set up in `hv.extension`, (b) declare your options for both backends you want to support, and (c) use `hv.output` to switch backends as needed.

```
import holoviews as hv
hv.extension('bokeh','matplotlib')
x=hv.Curve([1,2,3]).options(backend='bokeh', interpolation='steps-post')
x=x.options(backend='matplotlib', interpolation='steps-post')

hv.output(backend='matplotlib')
x
```
![image](https://user-images.githubusercontent.com/1695496/119547819-2f68c100-bd5b-11eb-9124-f33fc299c403.png)


```
hv.output(backend='bokeh')
x
```
![image](https://user-images.githubusercontent.com/1695496/119547848-38f22900-bd5b-11eb-8168-f68c4d75a013.png)

Notice how the logos indicate that a single HoloViews session has been started with _both_ backends, defaulting to Bokeh when listed in that order, and how you can select which backend you want dynamically as long as you've defined appropriate options for each backend.

**Comment by jbednar** [comment]
(Note that you don't need to specify the backend when you set options if you are setting options for the default backend, so `backend='bokeh'` can be omitted here, but you do need to specify the backend if you want to set options for a backend other than the current default.)

**Comment by douglas-raillard-arm** [comment]
Thanks for the details, since this code is hidden inside a generic part of my package, I'll just attempt to enable all backends (ignoring exceptions), and then always specify the backend when setting the option.

For reference this also fixes a weird issue where creating an matplotlib Figure with interactive=True: automatic display of the Axes object was not working, but `ax.figure` was working. Now it is displayed as expected when the last expression of the cell is the axis object.
