### ISSUE TITLE
using HoloMap breaks hover text for datetime values

### ISSUE THREAD

**Issue by rcravotta** [holoviz/holoviews#5000]
#### ALL software version info
Python 3.8.8 (64-bit conda)
Holoviews 1.14.4

#### Description of expected behavior and the observed behavior

Holoviews hover tool displays datetime values as expected except when using a HoloMap. When a HoloMap is present in a layout, the hover tooltip, for ALL plots in the layout, instead displays the numeric value of the datetime. If the HoloMap plot is removed, the hover tooltip for datetime returns to normal behavior.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import pandas as pd
import holoviews as hv
hv.extension('bokeh')

x = pd.date_range(start='1990-01-01', freq='60min', periods=1_000)
y = np.sin(np.linspace(0, 8 * np.pi, len(x)))

plots = {}
plots[0] = hv.Curve((x, y)).opts(tools=['hover'])
plots[1] = hv.Curve((x, y[::-1])).opts(tools=['hover'])

# comment out final plot to see earlier plot
(plots[0] + plots[1] + hv.NdOverlay(plots)).opts(title='Two Curves and an NdOverlay (expected datetime hover tooltip)')
(plots[0] + plots[1] + hv.HoloMap(plots)).opts(title='Two Curves and an HoloMap (datetime hover tooltip as numeric)')

```

#### Screenshots or screencasts of the bug in action
![HoloMap Breaks datetime hover](https://user-images.githubusercontent.com/51767883/124331291-e66b1000-db43-11eb-8a74-763946fd9445.png)
![datetime hover](https://user-images.githubusercontent.com/51767883/124331296-e703a680-db43-11eb-9456-d80923aea938.png)

**Comment by ahuang11** [comment]
A workaround is to first format your datetime as a str or add another preformatted str column and create your own hovertool
