### ISSUE TITLE
Overlay(X, Layout(...).cols(n)) ignores n

### ISSUE THREAD

**Issue by douglas-raillard-arm** [holoviz/holoviews#5003]
#### ALL software version info
holoviews 1.14.4
bokeh 2.3.2
panel 0.12.0rc3
jupyterlab 3.0.16

#### Description of expected behavior and the observed behavior
Layout columns should be preserved when a plot is overlaid on the whole layout

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
hv.extension('bokeh')

layout = hv.Curve([0, 1]) + hv.Curve([1, 2])
layout = layout.cols(1)
layout * hv.Curve([10,20])
```

#### Screenshots or screencasts of the bug in action
Current behavior:
![Screenshot_20210705_181814](https://user-images.githubusercontent.com/23336875/124503406-63ed8500-ddbd-11eb-8da8-26c23d9a1dbf.png)

Expected behavior:
![Screenshot_20210705_181916](https://user-images.githubusercontent.com/23336875/124503476-8d0e1580-ddbd-11eb-8f11-f1b78216be70.png)

**Comment by jbednar** [comment]
I agree; I also expected it to behave as you expected, preserving `cols`.
