### ISSUE TITLE
Add link selections support to AdjointLayout

### ISSUE THREAD

**Issue by peterroelants** [holoviz/holoviews#5028]
#### Description of expected behavior and the observed behavior

Linking plots in an adjoint layout like `link_selections(spreaded << histogram)` is currently not supported

See also: https://github.com/holoviz/holoviews/issues/4997#issuecomment-881749228

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import numpy as np
import pandas as pd
import datashader as ds
import holoviews.operation.datashader as hd
import holoviews as hv
from holoviews.selection import link_selections

hv.extension('bokeh')

num = 100000
np.random.seed(1)

dists = {
    cat: pd.DataFrame({
        'x': np.random.normal(x, s, num), 
        'y': np.random.normal(y, s, num), 
        'val': np.random.normal(val, 1.5, num), 
        'cat': cat
    }) for x,  y,  s,  val, cat in 
     [(  2,  2, 0.03, 10, "d1"), 
      (  2, -2, 0.10, 20, "d2"), 
      ( -2, -2, 0.50, 30, "d3"), 
      ( -2,  2, 1.00, 40, "d4"), 
      (  0,  0, 3.00, 50, "d5")]
}

points = hv.Points(pd.concat(dists), ['x', 'y'], ['val', 'cat'])
datashaded = hd.datashade(points, aggregator=ds.count_cat('cat'))
spreaded = hd.dynspread(datashaded, threshold=0.50, how='over').opts(tools=['box_select', 'lasso_select'])

# Declare dim expression to color by cluster
dim_expr = ((0.1+hv.dim('val')/10).round()).categorize(hv.Cycle('Set1').values)
histogram = points.hist(num_bins=60, adjoin=False, normed=False).opts(color=dim_expr)

link_selections(hv.AdjointLayout({'main':spreaded, 'top': histogram, 'right': histogram}))  # Does not work
# link_selections(spreaded + histogram)  # works
```
Which looks like:
<img src="https://user-images.githubusercontent.com/951093/125793120-6fb1c4fc-f479-43cb-a3d9-b54249f2b1d9.png" alt="drawing" width="300"/>
And does not have working linked selection tools

#### ALL software version info
```
Python: 3.9.6
numpy     : 1.21.0
bokeh     : 2.3.3
datashader: 0.13.0
holoviews : 1.14.4
pandas    : 1.3.0
```

**Comment by peterroelants** [comment]
From https://github.com/holoviz/holoviews/issues/4997#issuecomment-881749228 :

> I think your issue is different and should be in its own issue as a feature request, i.e., a request that `link_selections(spreaded << histogram)` be supported and for it to work like `ls = link_selections.instance() ; ls(spreaded) << ls(histogram).opts(width=125)`. I haven't tried working on that, but I do see that `link_selections` has code like:
> 
> ```
>         elif isinstance(hvobj, Element):
>            ...
>         elif isinstance(hvobj, (Layout, Overlay, NdOverlay, GridSpace)):
> ```
> 
> that knows how to process four different container types. AdjointLayout isn't in that list, but could presumably be added.

**Comment by peterroelants** [comment]
As a naive solution I tried quickly adding `AdjointLayout` to [`holoviews/holoviews/selection.py:193`](https://github.com/holoviz/holoviews/blob/989c3c304a34e5043a52eba87dd056b6e48d9eea/holoviews/selection.py#L193) as such:
```python
elif isinstance(hvobj, (Layout, Overlay, NdOverlay, GridSpace, AdjointLayout))
```

However, this only works for the first selection made on the plot, and fails for all further selections. No warnings or errors to be seen.

**Comment by peterroelants** [comment]
It seems like this might be an issue with `link_selections` on latest master, I just tried without `AdjointLayout`:
```python
link_selections(spreaded + histogram)
```
Which used to work, however, I now get the same "only first selection works" issue as illustrated in previous comment.

**Comment by peterroelants** [comment]
It seems like this is an issue with the latest master: https://github.com/holoviz/holoviews/issues/5029

**Comment by peterroelants** [comment]
Fix build on v1.14.4: https://github.com/holoviz/holoviews/pull/5030

**Comment by jbednar** [comment]
Sounds like there is a separate issue with link_selections, so a PR and a test for the naive solution would be greatly appreciated!

**Comment by peterroelants** [comment]
I file a PR to solve it the naive solution, which Philipp already merged in: https://github.com/holoviz/holoviews/pull/5030

Closing this issue.

**Comment by peterroelants** [comment]
I filed a seperate issue on the selection tool on master branch only working once: https://github.com/holoviz/holoviews/issues/5029

**Comment by jbednar** [comment]
Thanks!
