### ISSUE TITLE
Hvplot Line not displaying values

### ISSUE THREAD

**Issue by jsang-scala** [holoviz/holoviews#5054]
#### The chart is displayed in jupyter lab using hvplot in google chrome. Versions: bokeh 2.3.2
holoviews 1.14.4, hvplot 0.7.2

#### This line plot should display a line/s with the values but it is not showing the line - in other words, the line containing values appears to be hidden while the plot features (title, x axis, y axis, etc) are seen. 

```python
plot = switch_queuestat_data_df.hvplot.line(
                    x="sim_time_sec", y=["per_port_drops", "per_queue_drops", "total_drops"],
                    xlabel="Simulation Time (sec)", ylabel="Dropped Packets",
                    width=1100,  height=400,
                    title="Switch Drops per Port, per Queue, and Total vs. Simulation Time (sec)")
plot = plot.opts(toolbar='below')
renderer.save(plot, f"{save_dir}/Per port, per queue, and total drops")
```

**Comment by jbednar** [comment]
(I updated the code formatting above so it displays on the screen.)

Without the data involved, it's tough to see what the problem is, but the code looks fine to me. E.g. it works on this other data frame I happened to have open:

![image](https://user-images.githubusercontent.com/1695496/128084332-719e4f3d-b5f5-4c7e-95e0-48452be58479.png)

**Comment by jsang-scala** [comment]
Thank you for your reply! I actually re run it and was able to see the data. However, it doesn't work all the time - after running the cell several times, the values only show sometimes. Is there anything you could think of that may be causing this issue?
Thanks again!

**Comment by jbednar** [comment]
That's really odd. Maybe check your browser JavaScript console to see if there are different messages when it works and when it doesn't.

**Comment by philippjfr** [comment]
I'm going to close, but please reopen if you have any more clues on what might be happening here.
