### ISSUE TITLE
Lasso select does not work on datashader

### ISSUE THREAD

**Issue by molindoudou** [holoviz/holoviews#5055]
example from [http://holoviews.org/user_guide/Linked_Brushing.html](url)
![GIF 2021-8-6 14-54-06](https://user-images.githubusercontent.com/18715172/128470188-5e450307-2ec8-422d-92a1-2d799b4d79f5.gif)

**Comment by philippjfr** [comment]
Are you referring to the website? Because as the warning on the right says:

>This web page was generated from a Jupyter notebook and not all interactivity will work on this website. Right click to download and run locally for full Python-backed interactivity.

**Comment by peterroelants** [comment]
Regardless of website or not, there is an issue with lasso-select on data shaded NdLayouts: https://github.com/holoviz/holoviews/issues/5041

Although box selection worked in my case

**Comment by molindoudou** [comment]
> Are you referring to the website? Because as the warning on the right says:
> 
> > This web page was generated from a Jupyter notebook and not all interactivity will work on this website. Right click to download and run locally for full Python-backed interactivity.

I do work on the Jupyter notebook. and i found out that lasso select do work but work too too too slow.
![0809](https://user-images.githubusercontent.com/18715172/128652685-4ff881b2-f8ad-46fb-bca8-0b77c00939a0.gif)

**Comment by philippjfr** [comment]
>I do work on the Jupyter notebook. and i found out that lasso select does work but work too too too slowly.

I've pushed an optimization to the lasso select here: https://github.com/holoviz/holoviews/pull/5061

There's also a major speed difference between spatialpandas and geopandas, so I'd recommend installing spatialpandas if you haven't already. Better yet, if you have an Nvidia GPU you could try cuDF (with cuspatial installed). In the absence of that polygon testing on 10s or 100s of thousands of points will always be somewhat expensive.

**Comment by molindoudou** [comment]
> > I do work on the Jupyter notebook. and i found out that lasso select does work but work too too too slowly.
> 
> I've pushed an optimization to the lasso select here: #5061
> 
> There's also a major speed difference between spatialpandas and geopandas, so I'd recommend installing spatialpandas if you haven't already. Better yet, if you have an Nvidia GPU you could try cuDF (with cuspatial installed). In the absence of that polygon testing on 10s or 100s of thousands of points will always be somewhat expensive.

it work well after installing spatialpandas,thanks a lots!!!!!!
![0810](https://user-images.githubusercontent.com/18715172/128801705-4d3c1220-7705-4871-8c75-ad00f62105bd.gif)

**Comment by philippjfr** [comment]
Will close this issue as since we also have #5041
