### ISSUE TITLE
Sankey edges disappear for large datasets

### ISSUE THREAD

**Issue by atarashansky** [holoviz/holoviews#5079]
With the latest PR (#4707), I'm experiencing a bug where the edges disappear if there are a large number of links.

Here is the example table:
[test.csv](https://github.com/holoviz/holoviews/files/7124702/test.csv)

Interestingly, if you use only the first 5 rows of the table, it works. If you use the full table, all the nodes have zero height and the edges are invisible.

```python
import pandas as pd
import holoviews as hv
hv.extension('bokeh',logo=False)
hv.output(size=100)


R = pd.read_csv('test.csv',index_col=0)

def f(plot,element):
    plot.handles['plot'].sizing_mode='scale_width'    
    plot.handles['plot'].x_range.start = -600    
    plot.handles['plot'].x_range.end = 1500    

sankey1 = hv.Sankey(R, kdims=["source", "target"])#, vdims=["Value"])
#below works
#sankey1 = hv.Sankey(R.iloc[:5], kdims=["source", "target"])#, vdims=["Value"])


sankey1.opts(cmap='Colorblind',label_position='outer', edge_line_width=0, show_values=True,
                                 node_alpha=1.0, node_width=40, node_sort=True,frame_height=1000,frame_width=800,
                                 bgcolor="snow",apply_ranges = True,hooks=[f])
```

**Comment by atarashansky** [comment]
Explicitly setting `node_padding=4` fixes my issue. The padding was made larger by default it seems.

```python
sankey1.opts(cmap='Colorblind',label_position='outer', edge_line_width=0, show_values=True,node_padding=4,
                                 node_alpha=1.0, node_width=40, node_sort=True,frame_height=1000,frame_width=800,
                                 bgcolor="snow",apply_ranges = True,hooks=[f])
```

**Comment by Yura52** [comment]
@atarashansky thanks for sharing!

@philippjfr I think it can be a good idea to remind users about the `node_padding` parameter in the corresponding release notes. My feeling about the new implementation is that it can require manual adjustment of `node_padding` for getting the best result. Probably, the default value should be changed at some point, since the current one is rather optimized for the previous implementation.
