### ISSUE TITLE
Colorbar legend disappearing and moving out of view when using cnorm='eq_hist' in holoviews.operation.datashader.rasterize

### ISSUE THREAD

**Issue by Noskario** [holoviz/holoviews#5090]
holoviews: 1.14.5
bokeh: 2.3.3
pandas: 1.2.4

When plotting data using rasterize I want to include a colorbar. But with the nicest cnorm-option 'eq_hist' the legend of the colorbar disappears about .5 seconds after creation. Why is that?
Moreover, if I drag around the map a few times, each time it gets redrawn a bit more down right until it shifts out of the printable area of my notebook!

I use the New York taxi dataset also used in https://datashader.org/getting_started/Introduction.html

```
import pandas as pd
import holoviews as hv
from holoviews.element.tiles import EsriImagery
from holoviews.operation.datashader import rasterize
hv.extension('bokeh')

# You have to adapt the path
df = pd.read_csv(r'C:\Users\oskar\datashader-examples\data\nyc_taxi.csv', usecols=['dropoff_x', 'dropoff_y'])

map_tiles  = EsriImagery().opts(alpha=0.5, width=900, height=480, bgcolor='black')
points     = hv.Points(df, ['dropoff_x', 'dropoff_y'])
taxi_trips = rasterize(points, x_sampling=1, y_sampling=1, width=900, height=480).opts(colorbar=True,cnorm='eq_hist')

taxi_trips * map_tiles
```

At first everything is nice:
![start](https://user-images.githubusercontent.com/83504577/134369886-e34d54cb-b9e4-46bd-b85b-4fbf51088c9f.png)
About half a second later the legend disappears:
![after_one_second](https://user-images.githubusercontent.com/83504577/134370034-13f28709-7432-4f06-8883-58831aab64b1.png)
And after dragging around:
![after_dragging_around_a_few_times](https://user-images.githubusercontent.com/83504577/134370133-d946cf00-7b3a-4026-b841-efcf54292176.png)
Note that the legend does not disappear if the numbers are all small, only if the highest number is above 5000 it seems.
Also note, that everything works fine if using cnorm='log'.

**Comment by jbednar** [comment]
Hmm. That looks very much like a problem present in earlier Bokeh releases, but I have not ever seen that with Bokeh 2.3.3. Is there any chance you're getting Bokeh from a different environment somehow, e.g. having recently upgraded Bokeh and not restarted the browser?

**Comment by jbednar** [comment]
The example code above works fine for me on a Mac using Bokeh 2.3.3, for what that's worth (though I think I have a different dataset than you):

![image](https://user-images.githubusercontent.com/1695496/134386517-f13fc192-c3a7-4627-adfc-c17c00798042.png)
![image](https://user-images.githubusercontent.com/1695496/134386592-9a022638-1cdc-4828-948f-3ef720412f11.png)

**Comment by Noskario** [comment]
Oh, sorry for that, I had bokeh version 2.3.2. Now after quiet a lot of effort I was able to update bokeh in my anaconda and restart everything.

Now I have bokeh 2.3.3.

I still have the same source code. Now the legend of the colorbar does not disappear anymore but I cannot zoom in anymore. Are there some key-words I have to change for the updated bokeh-version?

**Comment by jbednar** [comment]
Ok, that behavior would be expected for 2.3.2. I used your same source code under 2.3.3 with no issues, so I imagine it's just an issue of restarting and rerunning everything after the upgrade. You'd see the above if Python isn't running but the JS is.

**Comment by Noskario** [comment]
Indeed, now everthing works fine, after I have restarted the computer.
Thanks a lot for helping out!
