### ISSUE TITLE
Fix unhandled numpy.round overflow return value in core/util.py:bound_range(...)

### ISSUE THREAD

**Issue by w31t1** [holoviz/holoviews#5094]
#### Tested with software version
holoviews==1.14.4
numpy==1.21.0

#### Observed behavior
The function `hv.Image` raises an `FloatingPointError` with the message `overflow encountered in multiply`:
```
[...]
venv/lib/python3.9/site-packages/holoviews/core/util.py", line 2043, in bound_range
    density = round(full_precision_density, sys.float_info.dig)
FloatingPointError: overflow encountered in multiply
```
If the `FloatingPointError` is suppressed (`np.seterr(over='ignore')`) a follow up error occur:
```
[...]
venv/lib/python3.9/site-packages/holoviews/core/sheetcoords.py", line 519, in _boundsspec2slicespec
    t_idx = int(np.ceil(t_m-0.5))
ValueError: cannot convert float NaN to integer
```
#### Own Investigation
For the input 
```
# low:np.float64 = -2.9495124669423337e-295
# high:np.float64 = 1.2846068127299913e-293
# len(vals)-1 = 349
```
the line 
`2043:full_precision_density = compute_density(low, high, len(vals)-1)` 
leads to 
`full_precision_density = np.float64(2.6558061446181644e+295)`
which produces in line 
`2044:density = round(full_precision_density, sys.float_info.dig)` 
the output 
`density = np.inf`. This output is not handled properly. 

#### Suggested changes

1. Check additional for infinity: 
```
        with warnings.catch_warnings():
            warnings.filterwarnings('ignore', r'invalid value encountered in double_scalars')
            full_precision_density = compute_density(low, high, len(vals)-1)
            density = round(full_precision_density, sys.float_info.dig)
        if density == 0 or density == np.inf:
            density = full_precision_density
```

2. Disable Overflow FloatingPointErrors for the round call:
```
        with warnings.catch_warnings():
            warnings.filterwarnings('ignore', r'invalid value encountered in double_scalars')
            full_precision_density = compute_density(low, high, len(vals)-1)
            error = np.seterr(over="ignore")
            density = round(full_precision_density, sys.float_info.dig)
            np.seterr(**error)
        if density == 0:
            density = full_precision_density
```
The suggested change is added as git patch file:
[Fix_numpy_round_overflow.txt](https://github.com/holoviz/holoviews/files/7279254/Fix_numpy_round_overflow.txt)

If possible, I will create a pull request for the issue.

**Comment by jlstevens** [comment]
Thanks for reporting this and thanks for the PR!

I'll mark this as a bug though hopefully we can close this soon when the PR is merged.
