### ISSUE TITLE
Extension fails to load matplotlib 3.4

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#5099]
With the recent matplotlib 3.4, the holoviews extension fails with:

```
WARNING:param.notebook_extension: Holoviews matplotlib extension could not be imported, 
it raised the following exception: ImportError('cannot import name 
'validate_capstyle' from 'matplotlib.rcsetup'
 (/opt/continuum/anaconda/envs/default/lib/python3.7/site-packages/matplotlib/rcsetup.py)')
```

Matplotlib 3.3 still works correctly as expected.

**Comment by philippjfr** [comment]
Confused by this, this was fixed in https://github.com/holoviz/holoviews/pull/4878

**Comment by jlstevens** [comment]
I may have had an older holoviews version in which case the problem will show up anytime an older holoviews is used with newer matplotlib. Sadly not much we can do about that without things like repodata patching.

At any rate, I can confirm it seems to be fixed now:

![image](https://user-images.githubusercontent.com/890576/141976037-4aa2e261-0f13-4a7c-983b-3c45f02df285.png)

Closing the issue.
