### ISSUE TITLE
Bar charts with NA not working when using plotly as backend

### ISSUE THREAD

**Issue by Noskario** [holoviz/holoviews#5110]
Holoviews: 1.14.6
Plotly: 5.3.1
Bokeh: 2.3.3

I want to create a bar-chart with the plotly backend. I use the `aggregate`-function to count the number of items in each category. Let me show an example.
First I create some test-data:

```
import holoviews as hv
hv.extension('plotly')
import numpy as np
import pandas as pd
samples = 100

pets = ['Cat', 'Dog', 'Hamster', 'Rabbit']
genders = ['Female', 'Male']

pets_sample = np.random.choice(pets, samples)
gender_sample = np.random.choice(genders, samples)
df=pd.DataFrame(data={'pet':pets_sample,'gender':gender_sample,})
df['pet']=pd.Categorical(df['pet'])
df['gender']=pd.Categorical(df['gender'])
# Delete male hamsters so we have an empty category-combination
df=df[~((df['pet']=='Hamster') & (df['gender']=='Male'))]
df['name']=['Animal #'+str(i) for i in range(len(df))]
df=df[['name','pet','gender']]
df
```

[![dataframe][1]][1]

When I try to plot this, using
```
bars = hv.Bars(df, kdims=['pet', 'gender'],vdims='name').aggregate(function=np.count_nonzero)

bars.opts(width=1000,multi_level=False)
```
I get the following error: `ValueError: Out of range float values are not JSON compliant`.

The reason for that is (I think) that there is one NA in the aggregated table:
```
hv.Table(df, kdims=['pet', 'gender'],vdims='name').aggregate(function=np.count_nonzero)
```
returns

[![Aggregated table][2]][2]

You can solve this problem by adding a new column to the dataframe, just consisting of ones and use `np.sum` instead of `np.count_nonzero` and then everything works:

```
df['ones']=1
bars=hv.Bars(df, kdims=['pet', 'gender'],vdims=[('ones','count')]).aggregate(function=np.sum)
bars.opts(width=1000,multi_level=False)
```

[![bar-chart][3]][3]

I think NA's should default to zero when making Bar-charts. My original approach works fine if I use `bokeh` as backend.

  [1]: https://i.stack.imgur.com/fVOUk.png
  [2]: https://i.stack.imgur.com/XcbX5.png
  [3]: https://i.stack.imgur.com/SmUQG.png

**Comment by jbednar** [comment]
I agree; there should probably be a `df.fillna(0)` somewhere. A suitable PR would be welcome!

**Comment by jlstevens** [comment]
Given that you get an exception, I'll classify this as a bug.
