### ISSUE TITLE
Empty Box-Whisker plot with the Matplotlib backend when vdims has NaNs

### ISSUE THREAD

**Issue by maximlt** [holoviz/holoviews#5120]
The following snippet correctly returns a Box-Whisker plot grouped by *carrier* with the Bokeh backend but just returns an empty plot with the matplotlib backend.

```python
import holoviews as hv
from hvplot.sample_data import us_crime, airline_flights

flights = airline_flights.to_dask().persist()
flight_subset = flights[flights.carrier.isin(['AA', 'US', 'OH'])]

ds = hv.Dataset(flight_subset, kdims=['carrier'], vdims=['depdelay'])
hv.BoxWhisker(ds)
```
![image](https://user-images.githubusercontent.com/35924738/140918683-7caaf7e2-e1cc-4d75-bde3-b3c56863025e.png)

Note that this has nothing to do with Dask, since adding `flight_subset = flight_subset.compute()` has no effect.

I've done some exploration and found out that the `depdelay` column has `NaN`s values, replacing them with `0` (or any float) fixes the issue.

**Comment by philippjfr** [comment]
Fixed by https://github.com/holoviz/holoviews/pull/5135

**Comment by maximlt** [comment]
Reopening this `1.14.8.` hasn't solved this issue.
