### ISSUE TITLE
Default aspect/padding/size of datashaded plots with the Matplotlib backend is wrong

### ISSUE THREAD

**Issue by maximlt** [holoviz/holoviews#5121]
The following snippet shows that when one renders a datashaded element (here a curve) the figure obtained is too small and with too much padding.

```python
import holoviews as hv
from holoviews.operation.datashader import datashade
hv.extension('matplotlib')

from hvplot.sample_data import airline_flights

flights = airline_flights.to_dask().persist()
ds = hv.Dataset(flights, kdims=['distance'], vdims=['airtime'])
curve = hv.Curve(ds)
datashade(curve)
```
![image](https://user-images.githubusercontent.com/35924738/140964588-3d99cb79-287a-4274-bb42-9e3a63f11d7c.png)

I can improve that by setting the `aspect` to 1 with `datashade(curve).opts(aspect=1)`:
![image](https://user-images.githubusercontent.com/35924738/140964801-70e5f643-9b40-43f5-826d-dcf14354f6c7.png)

**Comment by jbednar** [comment]
I can reproduce that, and note that `rasterize` has the same problem, while plotting the original Curve works fine:

![image](https://user-images.githubusercontent.com/1695496/141021305-b04a7ea7-d239-417d-8871-b51500a68ca7.png)
