### ISSUE TITLE
hv.Image(group="") no longer works

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#5130]
Until HoloViews 1.13.5 it was legal to use a group name of "" for an Image, but starting with v1.14.0 that gives an error:

```python
import numpy as np, holoviews as hv
hv.extension()

ls = np.linspace(0, 10, 200)
xx, yy = np.meshgrid(ls, ls)
hv.Image(np.sin(xx)*np.cos(yy), group="").opts(cmap="greys")
```
![image](https://user-images.githubusercontent.com/1695496/141535863-a5df0cb1-796f-4c84-8e4f-e37c8f763809.png)

In a brief investigation I couldn't see what code had changed, but apparently something has. In any case, searching for "capitalize" in https://github.com/holoviz/holoviews/blob/master/holoviews/core/util.py reveals various code paths that implicitly depend on the length of a string being nonzero, which doesn't seem like a safe assumption in general and is problematic in this case. 

Here, obviously group could simply be omitted, but this came up for existing code in colorcet that accepted a user argument for the group, and when the user wants a blank group they now have to set the group to the very non-intuitive value "Image", whereas the much more reasonable group="" was sufficient to suppress printing the group name before.

**Comment by Hoxbro** [comment]
A `git bisect` shows that this was introduced in #4567

**Comment by jbednar** [comment]
Thanks; that helps! Alas, #4567 is a squash of 98 commits, with changes to 51 files, so we'll probably have to `git bisect` within that PR.

**Comment by Hoxbro** [comment]
Done. Commit 969aa172c9badd2d3ce0d17022eb908c817b8fcf seem to be the culprit.

**Comment by jbednar** [comment]
Thanks! That commit doesn't seem to change any of this behavior directly, but it must have somehow triggered it, e.g. by defining a new Compositor for Images. #5131 seems to fix it by addressing the underlying assumption that a string will always have a first character, which is not true in this case.
