### ISSUE TITLE
FutureWarning: casting datetime64[ns] values to int64 with .astype(...) is deprecated 

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/holoviews#5146]
#### ALL software version info
```
numpy.__version__ = '1.20.3'
holoviews.__version__ = '1.14.6'
```

#### Description of expected behavior and the observed behavior
Casting datetime64[ns] values to int64 with .astype(...) is deprecated 

#### Complete, minimal, self-contained example code that reproduces the issue

``` python
import hvplot.pandas  # noqa
import pandas as pd

df = pd.DataFrame({
    "time": pd.date_range("2020", "2021" ,100),
    "data": 100 * [1],
})

df.hvplot.line("time", "data", datashade=True)

```

#### Stack traceback and/or browser JavaScript console output
```
C:\Users\shh\miniconda3\envs\clean_holoviz\lib\site-packages\holoviews\operation\datashader.py:428: FutureWarning: casting datetime64[ns] values to int64 with .astype(...) is deprecated and will raise in a future version. Use .view(...) instead.
  df[d.name] = vals.astype('int64')
```

**Comment by jbednar** [comment]
Sounds like a straightforward PR to make from the error message, but then if so I'm not sure why it's deprecated and not simply done automatically any more, so maybe there is more to it than that.

**Comment by philippjfr** [comment]
Yeah, I don't really understand the reasoning behind this change tbh. We rely on this a lot all over the place iirc.

**Comment by Hoxbro** [comment]
The warning was added here: https://github.com/pandas-dev/pandas/pull/38544

**Comment by jbednar** [comment]
Oh my; that link leads to a *lot* of discussion: https://github.com/pandas-dev/pandas/issues/22384#issuecomment-909660696

I'm not at all sure that the issue has been resolved one way or another, i.e. whether the deprecation will be implemented or reverted, so I'd be inclined to wait on this until such a change is released definitively in pandas.

**Comment by Hoxbro** [comment]
The change will also not be as straightforward as the error message for Holoviews, which also can handle Dask DataFrames and Series, which doesn't have a view attribute. So a function to convert would look something like this:

``` python
def convert_to_int64(x):
    if pd.isna(x).any():
        raise ValueError("Cannot convert NaN/NaT values to integer")

    if dd and isinstance(x, (dd.DataFrame, dd.Series)):  # Dask does not have view
        return x.astype("int64")
    else:
        return x.view("int64")
```

**Comment by jbednar** [comment]
Ugh! Yes, let's not make this change until we are certain we will need it.

**Comment by jorisvandenbossche** [comment]
FYI, the deprecation warning has been reverted
