### ISSUE TITLE
BoxWhisker: Cannot change box color

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviews#5159]
HoloViews. 1.14.6

I would expect the box color to be yellow and not blue. I've look through the available `.opts` but not been able to find anything that can change the box color.

![image](https://user-images.githubusercontent.com/42288570/144965516-ac27ddce-bc9a-49d3-9a67-84f0c064e74e.png)

```python
import panel as pn
import numpy as np
import holoviews as hv

pn.extension(sizing_mode="stretch_width")

box = hv.BoxWhisker((np.random.randint(0, 10, 100), np.random.randn(100)), 'Group').sort()
box.opts(box_color="yellow", whisker_color="green")
pn.template.FastListTemplate(
    main=[box,box],
).servable()
```

**Comment by marcbernot** [comment]
Indeed, `box_color` doesn't seem to do anything, use `box_fill_color` instead.
```python
import numpy as np
import holoviews as hv

hv.extension('bokeh')
box = hv.BoxWhisker((np.random.randint(0, 10, 100), np.random.randn(100)), 'Group').sort()

box.opts(box_fill_color='yellow',
         box_line_color='red',box_line_width=3,
         whisker_line_color='blue',whisker_line_width=4)
```
![bokeh_plot](https://user-images.githubusercontent.com/8888261/183252680-22460338-1042-4cc8-a518-d229cbb1d6a5.png)
