### ISSUE TITLE
Holoviews datashader not working with Python 3.10

### ISSUE THREAD

**Issue by peterroelants** [holoviz/holoviews#5196]
#### Description of expected behavior and the observed behavior

[`holoviews.operation.datashader`](https://github.com/holoviz/holoviews/blob/v1.14.7/holoviews/operation/datashader.py) in the latest release (1.14.7) is not compatible with Python 3.10. This is due to the `from collections import Callable`which should be `collections.abc import Callable` in Python 3.10.

From the [Python documentation](https://docs.python.org/3.9/library/collections.html#:~:text=collections.abc):
> Deprecated since version 3.3, will be removed in version 3.10: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.9.

The Holoviews Master branch seems to be up to date with respect to this change:
- [v1.14.7 branch](https://github.com/holoviz/holoviews/blob/27da6a3af9e867e8e6432af3f7ceec19c854b332/holoviews/operation/datashader.py#L5)
- [Master branch](https://github.com/holoviz/holoviews/blob/cc6b27f01710402fdfee2aeef1507425ca78c91f/holoviews/operation/datashader.py#L3)

#### Complete, minimal, self-contained example code that reproduces the issue

Running the following in Python 3.10.2 and Holoviews version 1.14.7 result in an error:

```python
from holoviews.operation.datashader import rasterize
````
results in:
```python-traceback
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <module>
----> 1 from holoviews.operation.datashader import rasterize

File ~/miniconda3/envs/env_a/lib/python3.10/site-packages/holoviews/operation/datashader.py:5, in <module>
      1 from __future__ import absolute_import, division
      3 import warnings
----> 5 from collections import Callable
      6 from functools import partial
      8 import param

ImportError: cannot import name 'Callable' from 'collections' (~/miniconda3/envs/env_a/lib/python3.10/collections/__init__.py)
```

**Comment by philippjfr** [comment]
Fix never got backported but is now on the branch-1.14.8
