### ISSUE TITLE
hvplot/util.py:186: ImportError: Geographic projection support requires GeoViews and cartopy.

### ISSUE THREAD

**Issue by anitagraser** [holoviz/holoviews#5212]
Yesterday's update to holoviews 1.14.8 seems to have triggered some errors, including failures in Github actions and on Readthedocs of MovingPandas:

https://github.com/anitagraser/movingpandas/runs/5220533037?check_suite_focus=true#step:5:117

Errors include:

`TypeError: '<' not supported between instances of 'Version' and 'str'`

and

`ImportError: Geographic projection support requires GeoViews and cartopy.`

The holoviews version is the only thing that seems to have changed in the environments:

![image](https://user-images.githubusercontent.com/590385/154328308-74134354-311e-48f2-a78d-457db01fee82.png)

https://github.com/anitagraser/movingpandas/issues/187

**Comment by philippjfr** [comment]
Thanks for the bug report, suspect we need a new GeoViews release.

**Comment by farshadfarahnakian1990** [comment]
Hello! I have the same problem with running the code. The holoviews version used for is 1.14.8. Please help me!

**Comment by anitagraser** [comment]
Looks good. Thank you.
