### ISSUE TITLE
When saving Holoviews DynamicMap using hv.save() only three frames are rendered

### ISSUE THREAD

**Issue by whbrewer** [holoviz/holoviews#5273]
I am wanting to export my HoloViews DynamicMap as it is viewed in a Jupyter notebook, but it only exports three frames in the resulting HTML file. I created the following sample code to demonstrate the problem I am experiencing, which is a simplified version of the example at https://holoviews.org/reference/containers/bokeh/DynamicMap.html

```
import numpy as np
import holoviews as hv
hv.extension('bokeh')

def sine_curve(phase, freq=0.5):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

dmap = hv.DynamicMap(sine_curve, kdims=['phase']).redim.range(phase=(0.,1.))

dmap # to render interactively in Jupyter notebook

hv.save(dmap, 'test.html')
```

If I run this in a Jupyter notebook, the slider will render 11 different phase diagrams (every phase shift of 0.1). However, once I save it as test.html, it will only render three total phase diagrams (0, 0.5, 1).

**Comment by mosc9575** [comment]
I tried to run the example code above in my environment and it looks like the interactivity is completly broken in the latest bokeh and holoviews version.

<details>
  <summary><b><u>Environment settings</u></b></summary>
  <blockquote>
Python version      :  3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11)</br>
IPython version     :  8.1.1</br>
Tornado version     :  6.1</br>
Bokeh version       :  2.4.2</br>
Holoviews version : 1.14.8</br>
BokehJS tatic path :  /opt/conda/envs/development/lib/python3.9/site-packages/bokeh/server/static</br>
node.js version     :  v14.8.0</br>
npm version         :  6.14.7</br>
Operating system    :  Linux-5.10.0-8-amd64-x86_64-with-glibc2.31</br>
  </blockquote>
</details>

**Comment by philippjfr** [comment]
This still works fine to me and is also expected behavior. The DynamicMap represents a continuous space and HoloViews (or rather Panel which does the actual export to HTML) has to decide how to sample this continuous function. If you want to export a specific sampling you should sample the `DynamicMap` into a `HoloMap` yourself OR specify the specific samples you want to export with `.redim.values(phase=full_set_of_phase_values)`.

**Comment by whbrewer** [comment]
Thanks @philippjfr. Yes, that fixed it.
