### ISSUE TITLE
Blue plot

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/holoviews#5303]
Noticed a blue plot on the holoviews documentation page [here](https://holoviews.org/getting_started/Introduction.html#compositional-overlays).  It could be related to https://github.com/holoviz/datashader/issues/1051.

![image](https://user-images.githubusercontent.com/19758978/167686525-003a62d3-a684-4b64-b175-5cf1ad210500.png)

**Comment by jbednar** [comment]
Yes, the blue is fairly distracting here, and I think we should do the same thing we do in Datashader, which is to make a distinction between no data (zero counts show up transparent) and data (non-zero counts are mapped to the colorbar). Bokeh has options for this, but I can't seem to make them work:

```python
import pandas as pd, numpy as np, holoviews as hv
hv.extension('bokeh')

taxi_dropoffs = {hour:arr for hour, arr in np.load('../assets/hourly_taxi_data.npz').items()}
bounds = (-74.05, 40.70, -73.90, 40.80)

image = hv.Image(taxi_dropoffs['0'], ['lon','lat'], bounds=bounds)
image.opts(width=450, tools=['hover'], clipping_colors={'NaN': 'transparent'}, colorbar=True)
image
```
<img width="465" alt="image" src="https://user-images.githubusercontent.com/1695496/167697512-7d1bc52d-00b4-400e-8ac7-c0cc4a0e364b.png">

```python
image.opts(nodata=0)
```
<img width="458" alt="image" src="https://user-images.githubusercontent.com/1695496/167697616-8b617a3c-e785-4ae6-82de-04832718cc25.png">

```python
image.data = np.where(image.data == 0, np.nan, image.data)
image
```
<img width="459" alt="image" src="https://user-images.githubusercontent.com/1695496/167697692-36a02ec8-3f4b-44f6-8dab-d299aeea0ba7.png">

We'd want it to look like the last image here, but to get that to work I had to manipulate the NumPy array directly; shouldn't it work to just specify `nodata`?

**Comment by Hoxbro** [comment]
This works without manipulating the array directly `image.redim.nodata(z=0)`

**Comment by jbednar** [comment]
Thanks! @jlstevens , any idea how `nodata=`*x* is supposed to be used if not like this?

**Comment by jlstevens** [comment]
`image.opts(width=450, tools=['hover'], clipping_colors={'NaN': 'transparent'}, colorbar=True, nodata=0)` should work as `nodata` is both an option on dimensions and a plot option for images.

**Comment by jbednar** [comment]
The image has zeros, not nans, and `nodata=np.nan` fails in any case:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/1695496/167703994-05186108-1d8c-4a9c-b0c6-8bef557f064d.png">

**Comment by jbednar** [comment]
The question is how to make the zeros in the image map to NaNs; `nodata=0` isn't meant to do that?

**Comment by jbednar** [comment]
Ah, that's it: the data is float32, with "0." instead of "0". I would have thought `nodata` would apply to floats too, but it does work if I convert to int32:

```
taxi_dropoffs = {hour:arr.astype('int32') for hour, arr in np.load('../assets/hourly_taxi_data.npz').items()}
...
image.opts(nodata=0)
```
<img width="475" alt="image" src="https://user-images.githubusercontent.com/1695496/167705253-8635e647-dc83-4766-910e-b18bff4d4c94.png">

It's slightly annoying that the hover shows NaN instead of 0, but I guess Bokeh is just filling with NaNs internally.

**Comment by jlstevens** [comment]
Oh right, this is a detail I had forgotten. It treats ints as ints because count aggregators are ints so there is the usual issue of comparing number types to think about. Might be worth a mention in the docs/an FAQ item.

**Comment by jbednar** [comment]
Right. I don't know where this data came from, but it does seem like it should have been `int`. Either need to fix the data, or add one of the above fixes to the notebook. Hmm.

**Comment by jbednar** [comment]
This is fixed on http://dev.holoviews.org/getting_started/Introduction.html and should appear on the main site when the docs are rebuilt on release.
