### ISSUE TITLE
Y-range incorrect when dataframe has NA values

### ISSUE THREAD

**Issue by psambit9791** [holoviz/holoviews#5317]
#### ALL software version info

Package              Version
-------------------- ---------
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                21.4.0
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               4.1.0
bokeh                2.4.2
Bottleneck           1.3.4
brotlipy             0.7.0
certifi              2021.10.8
cffi                 1.15.0
charset-normalizer   2.0.4
click                8.0.4
cloudpickle          2.0.0
colorcet             3.0.0
cryptography         37.0.1
cycler               0.11.0
cytoolz              0.11.0
dask                 2022.2.1
datashader           0.13.0
datashape            0.5.4
debugpy              1.5.1
decorator            5.1.1
defusedxml           0.7.1
distributed          2022.2.1
entrypoints          0.4
executing            0.8.3
fastjsonschema       2.15.1
fonttools            4.25.0
fsspec               2022.3.0
HeapDict             1.0.1
holoviews            1.14.9
hvplot               0.8.0
idna                 3.3
importlib-metadata   4.11.3
ipykernel            6.9.1
ipython              8.3.0
ipython-genutils     0.2.0
ipywidgets           7.6.5
jedi                 0.18.1
Jinja2               3.0.3
jsonschema           4.4.0
jupyter              1.0.0
jupyter-client       7.2.2
jupyter-console      6.4.3
jupyter-core         4.10.0
jupyterlab-pygments  0.1.2
jupyterlab-widgets   1.0.0
kiwisolver           1.3.2
llvmlite             0.36.0
locket               0.2.1
Markdown             3.3.4
MarkupSafe           2.0.1
matplotlib           3.5.1
matplotlib-inline    0.1.2
mistune              0.8.4
mkl-fft              1.3.1
mkl-random           1.2.2
mkl-service          2.4.0
msgpack              1.0.3
multipledispatch     0.6.0
munkres              1.1.4
nbclient             0.5.13
nbconvert            6.4.4
nbformat             5.3.0
nest-asyncio         1.5.5
notebook             6.4.11
numba                0.53.1
numexpr              2.8.1
numpy                1.22.3
packaging            21.3
pandas               1.4.2
pandocfilters        1.5.0
panel                0.13.0
param                1.12.1
parso                0.8.3
partd                1.2.0
pexpect              4.8.0
pickleshare          0.7.5
Pillow               9.0.1
pip                  21.2.4
prometheus-client    0.13.1
prompt-toolkit       3.0.20
psutil               5.8.0
ptyprocess           0.7.0
pure-eval            0.2.2
pycparser            2.21
pyct                 0.4.8
Pygments             2.11.2
pyOpenSSL            22.0.0
pyparsing            3.0.4
pyrsistent           0.18.0
PySocks              1.7.1
python-dateutil      2.8.2
pytz                 2021.3
pyviz-comms          2.2.0
PyYAML               6.0
pyzmq                22.3.0
qtconsole            5.3.0
QtPy                 2.0.1
requests             2.27.1
scipy                1.7.3
Send2Trash           1.8.0
setuptools           61.2.0
sip                  4.19.13
six                  1.16.0
sortedcontainers     2.4.0
soupsieve            2.3.1
stack-data           0.2.0
tblib                1.7.0
terminado            0.13.1
testpath             0.5.0
toolz                0.11.2
tornado              6.1
tqdm                 4.64.0
traitlets            5.1.1
typing_extensions    4.1.1
urllib3              1.26.9
wcwidth              0.2.5
webencodings         0.5.1
wheel                0.37.1
widgetsnbextension   3.5.2
xarray               0.20.1
zict                 2.0.0
zipp                 3.8.0

#### Description of expected behavior and the observed behavior

I am using the bokeh backend to plot 3-dimensional data using hv.Curve and NdOverlay. This is what I am using to generate the plot.

```
plot = hv.NdOverlay({c:hv.Curve((df2['t'], df2[c]), kdims=['Time'], vdims=['Value']) for c in selected_true}).opts(width=800, height=400)
```

I have a dataframe which has NA values - which helps create discontinuities in the plot which I need. When I plot that the dataframe, the range is not maintained as shown in the figure below.

![problem](https://user-images.githubusercontent.com/25612092/169796209-29ffb4d8-d770-4524-a647-63e7147c7e6e.png)

However, if I perform a fillna(0) on the dataframe, the range is maintained.

![problem2](https://user-images.githubusercontent.com/25612092/169796399-bf73129e-c1dd-4956-bd98-590aab9ab4ff.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```
columns = ["x", "y", "z"]
df_test = pd.DataFrame(data={"t": [1,2,3,4,5,6], "x": [1,0,2,pd.NA,5,2], "y": [-1,0,1,pd.NA,4,1.6], "z": [-0.5,2,3,pd.NA,1,0.6]})
plot1 = hv.NdOverlay({c:hv.Curve((df_test['t'], df_test[c]), kdims=['Time'], vdims=['Value']) for c in columns}).opts(width=800, height=400)
plot1

df_test = df_test.fillna(0)
plot2 = hv.NdOverlay({c:hv.Curve((df_test['t'], df_test[c]), kdims=['Time'], vdims=['Value']) for c in columns}).opts(width=800, height=400)
plot2

```

**Comment by jbednar** [comment]
Ooh, that definitely isn't nice behavior! I can reproduce it from that example.

 I think the ranges are computed by [Dimension.range](https://github.com/holoviz/holoviews/blob/master/holoviews/core/dimension.py#L1165), which in turn calls [find_range](https://github.com/holoviz/holoviews/blob/master/holoviews/core/util.py#L885) or (what I think applies in this case with multiple traces) [max_range](https://github.com/holoviz/holoviews/blob/master/holoviews/core/util.py#L909). Both find_range and max_range use nanmin and nanmax that should be robust against nans, so I can't quite spot the problem, but maybe someone else can.

**Comment by philippjfr** [comment]
Problem here is that we are not handling pandas.NA, if you use np.nan or float('nan') there's no issue.

**Comment by philippjfr** [comment]
Indeed I'll handle this but note that pd.NA is not the best thing to use missing values in numeric data. In your particular case it is indeed somewhat inefficient because the arrays are of `dtype=object` but I suppose in your real data they may be actual integer arrays.

**Comment by jbednar** [comment]
Good catch! Indeed, I didn't spot that it was pd.NA and not np.nan.  Yes, I do think we should treat pd.NA the same as np.nan, but at least for now this issue documents that using real NaNs will fix it.
