### ISSUE TITLE
Drop support of formatting Bokeh ticks with `pscript`

### ISSUE THREAD

**Issue by maximlt** [holoviz/holoviews#5327]
Ticks can be formatted by providing a function which will be compiled to JS using `pscript` (if installed) when using Bokeh. Bokeh has dropped support of this kind of approach based on `pscript`, and it has apparently never worked really well in HoloViews.

**Comment by maximlt** [comment]
@jlstevens if you agree with that, which version would be a good target? 1.15 or later?

**Comment by jlstevens** [comment]
Do you know when Bokeh dropped support? If it has been over a year or so, I think we can indeed drop this in 1.15.

**Comment by maximlt** [comment]
It seems it was removed some time in 2019 for the 2.0 release of Bokeh which happened in March 2020: https://github.com/bokeh/bokeh/pull/8965

**Comment by MarcSkovMadsen** [comment]
I'm actually using the support in some of my apps.
