### ISSUE TITLE
figures not shown with bokeh backend

### ISSUE THREAD

**Issue by douglas-raillard-arm** [holoviz/holoviews#5369]
#### ALL software version info
Mozilla Firefox 102.0
Python 3.8
bokeh==2.4.3
holoviews==1.15.0
jupyter-client==7.3.4
jupyter-core==4.11.1
jupyter-server==1.18.1
jupyterlab==3.4.4
jupyterlab-pygments==0.2.2
jupyterlab-server==2.15.0
jupyterlab-widgets==1.1.1

Ubuntu 20.04

#### Description of expected behavior and the observed behavior
A figure is not shown when it's the only expression in the cell

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
hv.extension('bokeh')

hv.Curve([0,1])
```

#### Stack traceback and/or browser JavaScript console output

No backtrace

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/23336875/181580293-39b70b7c-80ca-458c-9cb6-d77fda6beaf4.png)

**Comment by douglas-raillard-arm** [comment]
Downgrading to jupyterlab==3.4.3 seems to fix the issue, so the new release has broken something holoviews relied on.

**Comment by Hoxbro** [comment]
It works fine for me:
![image](https://user-images.githubusercontent.com/19758978/181582247-78c04d0d-8af5-4b97-b168-54ad8ca88d92.png)

Try the following things: 
1. Restart the browser 
2. Restart jupyter lab
3. Create a new notebook.

**Comment by Hoxbro** [comment]
It is properly related to browser caching.
