### ISSUE TITLE
RangeX stream event doesn't trigger the event after update to v1.15

### ISSUE THREAD

**Issue by ruoyu0088** [holoviz/holoviews#5381]
holoviews v1.15

Here is the example code, I create two DynamicMaps that share X axis and Y axis range, If I change the X axis range with PAN or ZOOM tools to one of the plots, both X axis range of the two plots are changed synchronized. The RangeX stream then trigger the callback functions to update the Curve's data. In holoviews 1.14.9, both of the two curves are changed, but after updated to v1.15, only the plot with mouse event are changed.

```python
import numpy as np
import holoviews as hv
from holoviews.streams import RangeX
hv.extension('bokeh')

def cos(x_range):
    t = np.linspace(x_range[0], x_range[1], 500)
    return hv.Curve((t, np.cos(t)))

def sin(x_range):
    t = np.linspace(x_range[0], x_range[1], 500)
    return hv.Curve((t, np.sin(t)))    

(
    hv.DynamicMap(cos, streams=[RangeX(x_range=(1, 10))]) +
    hv.DynamicMap(sin, streams=[RangeX(x_range=(1, 10))])
).cols(1).opts(hv.opts.Curve(width=600))
```

Here is the screen shot after zoom out the first plot:

![image](https://user-images.githubusercontent.com/826871/183539169-0300bdec-f821-45a6-a1fa-0d49582a16bc.png)

Here is the screen shot of v.1.14.9, both of the two Curves are updated:

![image](https://user-images.githubusercontent.com/826871/183539735-3f0d4cf7-c93c-40cb-9b1b-96742238e84a.png)

further more, the response speed of 1.14.9 is better then 1.15.

**Comment by Hoxbro** [comment]
A git bisect shows that https://github.com/holoviz/holoviews/pull/5265 is the culprit.

**Comment by philippjfr** [comment]
Could you report your current panel version? I can't reproduce with latest holoviews + panel.

**Comment by Hoxbro** [comment]
I still see the problem here is my versions:
```
pn.__version__    '0.14.0a9+gbd32dd50-dirty'
hv.__version__    '1.15.0.post10+g29ccf905e'
```
