### ISSUE TITLE
RangeToolLink turn background grey on one plot

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/holoviews#5389]
I don't know if this is how it should behave, but I find it weird that `RangeToolLink` turn the background grey. 

``` python
import holoviews as hv
from holoviews.plotting.links import RangeToolLink
hv.extension("bokeh")

c1 = hv.Curve([1, 1])
c2 = hv.Curve([1, 2])

c1 + c2

RangeToolLink(c1, c2)
c1 + c2
```

![image](https://user-images.githubusercontent.com/19758978/184477933-4283b50e-c218-430c-bb3d-92b19845db92.png)

**Comment by droumis** [comment]
The grey is the currently selected x-span. Once you add a couple of opts, [as in the example](https://www.holoviews.org/gallery/demos/bokeh/timeseries_range_tool.html), you can drag the selected bounds.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/6613202/189480175-6166188b-21ad-43c0-857b-b66a61644074.png">
