### ISSUE TITLE
Scatter polar projection main plot disappears when theta above 5.3 radians 

### ISSUE THREAD

**Issue by douglasmacdonald** [holoviz/holoviews#5396]
#### ALL software version info
hv version '1.14.9'

```
        
IPython          : 8.2.0
        ipykernel        : 6.13.0
        ipywidgets       : 7.7.0
        jupyter_client   : 7.2.2
        jupyter_core     : 4.9.2
        jupyter_server   : not installed
        jupyterlab       : not installed
        nbclient         : 0.6.0
        nbconvert        : 6.5.0
        nbformat         : 5.3.0
        notebook         : 6.4.11
        qtconsole        : 5.3.0
        traitlets        : 5.1.1
```

Chrome Version 104.0.5112.81 (Official Build) (64-bit)

#### Description of expected behavior and the observed behavior

 I am having trouble with the display of polar Scatter when the values go above 5.3 radians. Most of the plot disappears.

```
hv.extension('matplotlib')

theta = np.arange(0, 5.4, 0.1)

r = np.ones(len(theta))

scatter = hv.Scatter((theta, r), 'theta', 'r')
scatter.options(projection='polar', show_grid=True)

```

![image](https://user-images.githubusercontent.com/12778156/185417466-5e8d370a-611b-4483-9659-7369e5ed8932.png)

If you reduce the radian value then it is okay

```
hv.extension('matplotlib')

theta = np.arange(0, 5.3, 0.1)

r = np.ones(len(theta))

scatter = hv.Scatter((theta, r), 'theta', 'r')
scatter.options(projection='polar', show_grid=True)
```
![image](https://user-images.githubusercontent.com/12778156/185417749-01d389c3-d3c2-4453-bfd9-af5326dbbb01.png)

**Comment by jlstevens** [comment]
Thanks for reporting this issue!

The fact that Curves work but Scatters in this case does indicate something strange is going on (i.e. a bug!)
