### ISSUE TITLE
Change the default tool to zoom

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviews#5401]
I see over and over again that users gets confused that the default tool is pan and not zoom.

Normally the plots are zoomed out so that you can see anything. The first action you want to do (if any) is to zoom into that interesting area you have found. There is no incentive to pan first.

Its simply not a good user experience to have to first select a different tool and then do what you want. It confuses beginning users and slows you down as an experienced user. It makes it harder to mix in production with other plotting frameworks as they typically enable zoom by default. Users don't like to have to understand multiple different user interfaces.

**Comment by jbednar** [comment]
My only other thought is "please!". :-)

**Comment by maximlt** [comment]
> The only thing I'd like to check is how Bokeh Wheel Zoom tools behave on mobile.

Well pinching doesn't seem to be supported by Bokeh so wheel zoom is basically a no-op on mobile.

**Comment by jbednar** [comment]
Bokeh docs claim [pinch is supported](https://docs.bokeh.org/en/latest/docs/user_guide/tools.html?highlight=pinch#userguide-tools-scrollpinch), but I too see that they aren't, which seems like a bug report for Bokeh. I think that's separate from whether wheel/pinch zoom is the default.
