### ISSUE TITLE
http://holoviews.org/ not secure

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviews#5408]
![not-secure](https://user-images.githubusercontent.com/42288570/186826473-1a9f4b38-716b-4ce0-8737-526be580d4bb.png)

**Comment by MarcSkovMadsen** [comment]
If I change to https://holoviews.org/gallery/demos/bokeh/boxplot_chart.html it is secure. But you should configure the site to force it to use https.

I ended up using `http` from a link in a google search.

**Comment by Hoxbro** [comment]
Holoviews is served through S3. Something like [this](https://stackoverflow.com/questions/41710718/how-to-redirect-http-to-https-using-s3-cloudfront-and-route-53-using-naked-dom) should be done.

**Comment by philippjfr** [comment]
We were already using CloudFront so I just had to check the `Redirect http to https` toggle.

**Comment by philippjfr** [comment]
Thanks @Hoxbro!
