### ISSUE TITLE
BoxWhisker doesn't show outliers depending on vdim name

### ISSUE THREAD

**Issue by BMM3** [holoviz/holoviews#5431]
####  Packages
Python 3.9.7
holoviews 1.15.0
jupyterlab 3.4.4
bokeh 2.4.3
datashader 0.14.1

#### Description
The BoxWhisker doesn't seem to show the outliers when there is a space or a bracket in the name of the data.
The y limits are still set as if the outliers are included, but the outliers are not shown.
Only the y-axis name has an influence, the x-axis name can have spaces or brackets without having an effect on the outliers.

#### Example

```
import holoviews as hv
import pandas as pd

df = pd.DataFrame({'data':  [1,2,4,5,2,3,3,2,20,34],
                   'data 2':[1,2,4,5,2,3,3,2,20,34],
                   'data[': [1,2,4,5,2,3,3,2,20,34],
                   'x':     [1,1,1,1,1,1,1,1,1,1]})

(hv.BoxWhisker(df, 'x', 'data', label='data')+
 hv.BoxWhisker(df, 'x', 'data 2', label='data 2')+
 hv.BoxWhisker(df, 'x', 'data[', label='data[')+
 hv.BoxWhisker(df, 'x[', 'data', label='x['))
```

#### Screenshots
![image](https://user-images.githubusercontent.com/111486712/189067127-bc4f3021-2317-4da5-9c5e-1ad542b398b7.png)

**Comment by Hoxbro** [comment]
Get the following warning when running in a notebook. 
```
... Current lengths: ('data 2', 2), ('data_2', 0), ('index', 2)
... Current lengths: ('data[', 2), ('data_left_square_bracket', 0), ('index', 2)
```

It looks like the name of some of the data is being wrongfully sanitized.
