### ISSUE TITLE
Regression: offline bokeh plot support broken

### ISSUE THREAD

**Issue by pankajp** [holoviz/holoviews#5469]
## ALL software version info

**Python**: 3.9

### Failing versions:
bokeh: 2.4.3
holoviews: 1.15.0
panel: 0.13.0

### Working versions:
bokeh: 2.3.3
holoviews: 1.14.9
panel: 0.12.1

## Description of expected behavior and the observed behavior
bokeh plots aren't working in jupyter notebook without an internet connection due to new dependencies on cdn delivered assets

## Complete, minimal, self-contained example code that reproduces the issue
In a jupyter notebook in a browser without internet access. Easiest way to get it it to start firefox as follows (linux):

`$ env http_proxy=http://localhost:1/ https_proxy=http://localhost:1/ firefox --profile nointernet`

```
# notebook code
import pandas as pd
df = pd.DataFrame({'a':range(10),'b':range(10,20)})
import bokeh
import holoviews as hv
import panel as pn
print(bokeh.__version__, hv.__version__, pn.__version__)
hv.extension('bokeh', inline=True)
display(hv.Scatter(df))
```

## Stack traceback and/or browser JavaScript console output

Browser console showing the failing assets

```
Bokeh: BokehJS not loaded, scheduling load and callback at 
Date Tue Oct 04 2022 09:37:23 GMT-0700 (Pacific Daylight Time)
main.min.js:44:13
Bokeh: injecting link tag for BokehJS stylesheet:  https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.css main.min.js:66:15
Bokeh: injecting link tag for BokehJS stylesheet:  https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css main.min.js:66:15
failed to load https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js main.min.js:55:15
Loading failed for the <script> with source “https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js”. sample-notebook-py3.9.ipynb:1:1
Uncaught Error: Script error for "notyf"
http://requirejs.org/docs/errors.html#scripterror
    makeError require.js:168
    onScriptError require.js:1735
    load require.js:1940
    load require.js:1682
    load require.js:832
    fetch require.js:822
    check require.js:854
    enable require.js:1173
    enable require.js:1554
    enable require.js:1158
    bind require.js:134
    each require.js:59
    enable require.js:1110
    init require.js:786
    localRequire require.js:1457
    setTimeout handler*req.nextTick< require.js:1812
    localRequire require.js:1446
    requirejs require.js:1794
    load_libs main.min.js:77
    <anonymous> main.min.js:1655
    <anonymous> main.min.js:1660
    append_javascript outputarea.js:765
    append_mime_type outputarea.js:703
    append_display_data outputarea.js:664
    append_output outputarea.js:345
    handle_output outputarea.js:256
    output codecell.js:399
    _handle_output_message kernel.js:1199
    i jQuery
    _handle_iopub_message kernel.js:1239
    _finish_ws_message kernel.js:1018
    _msg_queue kernel.js:1009
    promise callback*Kernel.prototype._handle_ws_message kernel.js:1009
    i jQuery
    start_channels kernel.js:518
    _kernel_created kernel.js:413
    on_success session.js:112
    _on_success session.js:291
    jQuery 6
    ajax utils.js:797
require.js:168:17
Loading failed for the <script> with source “https://cdn.jsdelivr.net/npm/gridstack@4.2.5/dist/gridstack-h5.js”. sample-notebook-py3.9.ipynb:1:1
Uncaught Error: Script error for "gridstack"
http://requirejs.org/docs/errors.html#scripterror
    makeError http://localhost:8889/static/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:168
    onScriptError http://localhost:8889/static/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:1735
    load http://localhost:8889/static/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:1940
    load http://localhost:8889/static/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:1682
require.js:168:17
Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing sample-notebook-py3.9.ipynb:19:19
```

### Failing version:

![image](https://user-images.githubusercontent.com/776111/193878016-38cd7f85-babd-4fc6-8cb1-934e3b5e49bd.png)

### Working version:

![image](https://user-images.githubusercontent.com/776111/193878063-adb10bdf-841c-46df-8f39-d4043853d3c9.png)

Edit:
Just to add using bokeh plotting directly via `output_notebook(INLINE)` works fine offline.

**Comment by philippjfr** [comment]
I'll resolve this before the Panel 0.14 release tomorrow.

**Comment by pankajp** [comment]
Thanks a lot @philippjfr for the quick fix
There's also a failure in loading `https://cdn.jsdelivr.net/npm/gridstack@4.2.5/dist/gridstack-h5.js` other than notyf though

I see some other panel extensions do not work offline in a notebook as well, for example tabulator: https://github.com/holoviz/panel/issues/2285#issuecomment-1267325835 . Should I file individual issues for each that fail in my attempt to use, or would that be something not useful?

**Comment by philippjfr** [comment]
To be clear there's two separate issues:

1. `hv.extension` and `pn.extension` should not load external resources by default as long as `inline=True`. This is the issue I'm addressing now, so the gridstack issue also needs to be addressed in my PR. 
2. Extensions such as `hv.extension('plotly')` and `pn.extension('tabulator')` do not currently get inlined. This indeed deserves a separate issue.

**Comment by philippjfr** [comment]
Actually, I don't see the gridstack issue by default. This should only actually present an issue if you (or some other library you have imported) explicitly imports `panel.layout.gridstack`.

**Comment by philippjfr** [comment]
Ignore my previous comment, `panel.layout.gridstack` is imported by default.
