### ISSUE TITLE
external matplotlib colormaps cannot be found

### ISSUE THREAD

**Issue by keewis** [holoviz/holoviews#5476]
#### ALL software version info
```
holoviews: 1.15.1
matplotlib: 3.6.0
cmocean: 2.0
```

#### Description of expected behavior and the observed behavior
I've been trying to use the colormaps provided by `cmocean` in a new environment, and got an error stating that the colormap I requested couldn't be found.

It seems that the newest version of `matplotlib` removed `matplotlib.cm._cmap_registry`, which was used here:
https://github.com/holoviz/holoviews/blob/f051576deb8d21ec845a71cfd6f334af5362d64b/holoviews/plotting/util.py#L693-L696

Making `_cmap_registry` an alias of `_colormaps` allows me to use the external colormaps:
```python
import matplotlib.cm as cm

cm._cmap_registry = cm._colormaps
```

However, I don't think that's a long-term solution since both are internal API, so maybe use `list(matplotlib.colormaps)` instead?

cc @tacaswell, @QuLogic

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import cmocean
from holoviews.plotting import list_cmaps

list_cmaps(provider="matplotlib")
```

**Comment by tacaswell** [comment]
That is a private attribute so we reserve the right to change it with no warning on the Matplotlib side. 

The suggestion to use `matplotlib.colormaps` is correct (but will need to be version gated depending on how far back holoviews wants to support.
