### ISSUE TITLE
Lasso Select no longer working with cross filtering

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviews#5488]
I'm updating the examples at awesome-panel.org to the latest versions of Panel, hvplot and HoloViews. 

One of the most popular examples and something that makes HoloViz unique is the easy to use crossfiltering. And the `Lasso Select` is amazing.

Unfortunately it no longer works.

## Reproduce

`pip install panel==0.14.0 bokeh==2.4.3 holoviews==1.15.1 hvplot==0.8.1 shapely==1.8.5`

```python
# panel serve holoviz_linked_brushing.py --autoreload --show
import hvplot.pandas
import holoviews as hv
import panel as pn
from bokeh.sampledata.iris import flowers

pn.extension(sizing_mode="stretch_width")
hv.extension("bokeh")

accent_color = "#ff286e"

scatter = flowers.hvplot.scatter(
    x="sepal_length", y="sepal_width", c=accent_color, responsive=True, height=350
)
hist = flowers.hvplot.hist("petal_width", c=accent_color, responsive=True, height=350)

scatter.opts(size=10)

selection_linker = hv.selection.link_selections.instance()

scatter = selection_linker(scatter)
hist = selection_linker(hist)

scatter.opts(tools=["hover"], active_tools=["box_select"])
hist.opts(tools=["hover"], active_tools=["box_select"])

pn.template.FastListTemplate(
    site="Awesome Panel and HoloViews",
    title="Cross Filtering/ Linked Brushing",
    header_background=accent_color,
    main=[scatter, hist],
).servable()
```

https://user-images.githubusercontent.com/42288570/196637313-94cdfeee-218b-4d75-8d58-8acb22ad4bbc.mp4

I get no error messages anywhere. It just does not work.

## Regression

Yes. This is a regression. It used to work with `pip install panel==0.12.4 bokeh==2.4.0 holoviews==1.14.6 hvplot==0.7.3 shapely==1.7.1`. See https://gist.github.com/MarcSkovMadsen/c31afa6db9e55e3f50f582b24ad60a34

**Comment by maximlt** [comment]
Indeed I can reproduce in a notebook.

**Comment by jlstevens** [comment]
I do think this is pretty high priority.

**Comment by jlstevens** [comment]
Ok, I did a git bisect and found it was the commit where I fixed a bug where the type of selection expression for `Scatter` was defined incorrectly. 

This issue now makes sense as the above example should be using points, not scatter (lasso does *not* make sense with `Scatter` which has only one key dimension!)

This code now works on master (tested with current `conda create -n bisect -c conda-forge python=3.8 hvplot shapely panel notebook`):

```python
# panel serve holoviz_linked_brushing.py --autoreload --show
import hvplot.pandas
import holoviews as hv
import panel as pn
from bokeh.sampledata.iris import flowers

pn.extension(sizing_mode="stretch_width")
hv.extension("bokeh")

accent_color = "#ff286e"

points = flowers.hvplot.points(
    x="sepal_length", y="sepal_width", c=accent_color, responsive=True, height=350
)
hist = flowers.hvplot.hist("petal_width", c=accent_color, responsive=True, height=350)

points.opts(size=10)

selection_linker = hv.selection.link_selections.instance()

points = selection_linker(points)
hist = selection_linker(hist)

points.opts(tools=["hover"], active_tools=["box_select"])
hist.opts(tools=["hover"], active_tools=["box_select"])

pn.template.FastListTemplate(
    site="Awesome Panel and HoloViews",
    title="Cross Filtering/ Linked Brushing",
    header_background=accent_color,
    main=[points, hist],
).show()
```

I'll now close this issue as it ended up being a usage error (which was encouraged by an incorrect declaration in the code which has now been fixed)

**Comment by jlstevens** [comment]
That said, if someone knows how to easily add a warning that detects incorrect usage of scatter versus points for linked selection, please say so as that would be helpful!
