### ISSUE TITLE
Incomplete and/or broken _repr_html_() methods

### ISSUE THREAD

**Issue by Mietzsche81** [holoviz/holoviews#5489]
Many holoviews classes have broken HTML representation in Jupyter. See examples in screenshot below.

Tested on Holoviews version `1.14.4`

<img width="633" alt="image" src="https://user-images.githubusercontent.com/39289495/196725917-05d5994a-f755-454a-8f2c-4a95f6ad8937.png">

**Comment by jbednar** [comment]
I'm not able to reproduce:

<img width="951" alt="image" src="https://user-images.githubusercontent.com/1695496/197104766-daee434b-0b9e-4859-8d40-aead59d5c8d7.png">

Even without calling `hv.extension()`:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/1695496/197104870-51682cd3-d731-422d-8feb-56a7a0ecdc6f.png">

**Comment by jlstevens** [comment]
@Mietzsche81 Thanks for filing the issue!

Have you been able to reproduce this problem with 1.15.1?

**Comment by Mietzsche81** [comment]
@jlstevens @jbednar downloaded 1.15.1 on my personal device and am unable to reproduce, so it looks like a non-issue going forward.

Now I just have  to convince my team to update holoviews in our kernel :)
