### ISSUE TITLE
Docs: Update documentation to handle CORS errors for Tiles docs page

### ISSUE THREAD

**Issue by sandhujasmine** [holoviz/holoviews#5532]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
Looking at latest published docs here: https://holoviews.org/reference/elements/bokeh/Tiles.html

#### Description of expected behavior and the observed behavior
The [rendered docs page for Tiles](https://holoviews.org/reference/elements/bokeh/Tiles.html) that downloads OSM from wikipedia is blank because it is raising a CORS error:

```
Access to image at 'https://maps.wikimedia.org/osm-intl/0/0/0@2x.png' from origin 'https://holoviews.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
maps.wikimedia.org/o…intl/0/0/0@2x.png:1 
 Failed to load resource: net::ERR_FAILED
```

#### Stack traceback and/or browser JavaScript console output
```
Access to image at 'https://maps.wikimedia.org/osm-intl/0/0/0@2x.png' from origin 'https://holoviews.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
maps.wikimedia.org/o…intl/0/0/0@2x.png:1 
 Failed to load resource: net::ERR_FAILED
```

#### Screenshots or screencasts of the bug in action

<img width="1147" alt="Screen Shot 2022-12-01 at 2 09 04 PM" src="https://user-images.githubusercontent.com/359129/205169618-6124c227-760c-4753-aaae-eda901b85a96.png">

**Comment by sandhujasmine** [comment]
Does the server hosting the docs need to set the `'Access-Control-Allow-Origin'` policy header to allow accessing wikimedia.org?

```
'Access-Control-Allow-Origin': "https://maps.wikimedia.org"
```

**Comment by sandhujasmine** [comment]
Seeing a [fix](https://github.com/geopython/pygeoapi/pull/697/files) to similar issue in geopython is to use https://tile.openstreetmap.org/{z}/{x}/{y}.png instead of wikimedia for accessing the tiles. One option is to update the tile source and wording the example to point to `https://tile.openstreetmap.org/{z}/{x}/{y}.png`

**Comment by droumis** [comment]
nice catch! I can take a look

**Comment by sandhujasmine** [comment]
We are also replacing wikimedia tiles with OSM in the [`holoviews.element.tiles`](https://github.com/holoviz/holoviews/blob/master/holoviews/element/tiles.py#L174-L184) so currently deployed docs is implicitly testing OSM. Anyhow, just a minor nit to dig into the codebase. Thanks for the speedy fix
