### ISSUE TITLE
hvplot.image(rasterize=True) not working

### ISSUE THREAD

**Issue by lforesta** [holoviz/holoviews#5537]
As reported (and fixed) a while back (#4653) `hvplot.xarray.image(rasterize=True, dynamic=True)` no longer works. The displayed image resolution is not updated upon zooming into an image plot

#### ALL software version info
geoviews                 1.9.5
holoviews                1.15.0  (also tried  1.15.2)
bokeh                      2.4.3    (also tried  3.0.2)
hvplot                      0.8.2
datashader              0.14.2  (also tried  0.14.3)

#### Description of expected behavior and the observed behavior
Copied from #4653 

Zooming into a subregion of an image with raster with rasterize=True, dynamic=True should update displayed resolution

#### Complete, minimal, self-contained example code that reproduces the issue
Same script as posted in #4653 
```
import os
import xarray as xr
import hvplot.xarray
os.environ['GDAL_DISABLE_READDIR_ON_OPEN']='EMPTY_DIR'
os.environ['AWS_NO_SIGN_REQUEST']='YES'
href = 's3://sentinel-s1-rtc-indigo/tiles/RTC/1/IW/10/T/ET/2020/S1B_20200106_10TET_ASC/Gamma0_VV.tif'
da = xr.open_rasterio(href)
da.hvplot.image(rasterize=True, dynamic=True, clim=(0,0.4), aspect='equal', frame_width=600, cmap='gray')
```

**Comment by lforesta** [comment]
No news on this?
Trying to ping @philippjfr who fixed this issue for #4653

**Comment by philippjfr** [comment]
This example ran without issue for me. Could you try clearing your notebook (and closing all other notebooks if you're using JLab), saving and then reloading the page before re-running it?

**Comment by philippjfr** [comment]
If that doesn't work maybe try fetching HoloViews 1.15.4a1 with `conda install -c pyviz/label/dev holoviews=1.15.4a1` or `pip install --pre holoviews==1.15.4a1`.

**Comment by lforesta** [comment]
I was running my NB with/from VS Code, that turns out to be the issue (although I don't know the cause specifically).

I re-tried the script above with a Jupyter NB (without using VS Code) and it works with both 1.15.2 and 1.15.4a1

Thanks for checking this out @philippjfr
