### ISSUE TITLE
holoviews layout in combination with "decimate" not responsive when served with panel

### ISSUE THREAD

**Issue by zieherf** [holoviz/holoviews#5546]
#### ALL software version info
holoviews 1.15.2, Python 3.10.7, Panel: 0.14.1, Bokeh: 2.4.3

#### Description of expected behavior and the observed behavior

A holoviews layout with a larger number of curves becomes unresponsive.
The "decimate" operator is applied on each Curve object. Moving the one
plot in the example below, will freeze the layout.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
import numpy as np
import panel as pn
from holoviews.operation import decimate

hv.extension("bokeh")

x = np.random.rand(1000)
curves = [decimate(hv.Curve(x)) for _ in range(8)]
plot = hv.Layout(curves)

pn.panel(plot).servable()
```

#### Screenshots or screencasts of the bug in action
See the discussion on discourse.
https://discourse.holoviz.org/t/panel-holoviews-decimate-event-processing-not-working-possible-race-condition/4641

**Comment by CrashLandonB** [comment]
Could this be relevant to my issue: https://github.com/holoviz/holoviews/issues/5556 ?
(further discussion here: https://discourse.holoviz.org/t/how-to-upload-some-data-to-support-a-question/4701/14)
