### ISSUE TITLE
Test suite are sensitive to run order

### ISSUE THREAD

**Issue by hoxbro** [holoviz/holoviews#5565]
When trying to apply parallelization with `pytest-xdist` to the test suite (in `holoviews/pytest`), I noticed that it is very dependent on the run order.  

If the order is randomized with something like `pytest-random-order` and the following command: `pytest holoviews/tests --random-order-bucket=class`, the test suite will fail. 

Looking at the code a culprit for this could be having `Store.renderers['bokeh']` out in the open and not inside the `setUp` of the class.

**Comment by Hoxbro** [comment]
A reason could also be this line:
https://github.com/holoviz/holoviews/blob/b40916ed35166a40f7de9f620372b8cfe93f7713/holoviews/plotting/plotly/dash.py#L35

**Comment by Hoxbro** [comment]
Another case related is `pytest holoviews/tests -k InspectorTests`

![image](https://user-images.githubusercontent.com/19758978/225260634-32525c73-9775-4c10-8bbf-5c1f935c589e.png)

**Comment by Hoxbro** [comment]
Another one was discovered at: https://github.com/holoviz/holoviews/pull/5870

Where RGBElement_ImageInterfaceTests.test_reduce_to_single_values can't run with this command: `pytest holoviews/tests -k test_reduce_to_single_values but runs fine with `pytest holoviews/tests/core/`. In this case, I added a try/except as it errors out on core test.

**Comment by Hoxbro** [comment]
Works: pytest holoviews/tests/core 
Fails: pytest holoviews/tests/core/data/test_imageinterface.py::RGBElement_ImageInterfaceTests::test_reduce_to_single_values


Tried running [detect-test-pollution](https://github.com/asottile/detect-test-pollution) with the following change to the codebase:

https://github.com/holoviz/holoviews/blob/c7db69525c560723d8c0f995bee1152b031e98ed/holoviews/tests/core/data/test_imageinterface.py#L461-L476

with:

``` python
class RGBElement_ImageInterfaceTests(BaseRGBElementInterfaceTests):

    datatype = 'image'

    __test__ = True

    def test_reduce_to_single_values(self):
        try:
            super().test_reduce_to_single_values()
        except Exception:
            return
        else:
            assert False
```

And used this command a couple of time `detect-test-pollution --failing-test holoviews/tests/core/data/test_imageinterface.py::RGBElement_ImageInterfaceTests::test_reduce_to_single_values --tests holoviews/tests/core`

I got the following polluted problems:
test_delocation.py::test_decollate_spread
https://github.com/holoviz/holoviews/blob/c7db69525c560723d8c0f995bee1152b031e98ed/holoviews/tests/core/test_decollation.py#L131

test_delocation.py::test_decollate_datashade_kdims
https://github.com/holoviz/holoviews/blob/c7db69525c560723d8c0f995bee1152b031e98ed/holoviews/tests/core/test_decollation.py#L158

test_datasetproperty.py::test_datashade_curve
https://github.com/holoviz/holoviews/blob/c7db69525c560723d8c0f995bee1152b031e98ed/holoviews/tests/core/test_datasetproperty.py#L756

If I commented these out, I got `pytest holoviews/tests/core` to match only running the problematic test.
