### ISSUE TITLE
Collapsing figures in Bokeh 3 with responsive=True

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/holoviews#5599]
Follow up to #5388

--- 
_The following is copied directly from the issue, [ref](https://github.com/holoviz/holoviews/pull/5388#issuecomment-1309233647)._

For some reason, this does not work anymore:

Bokeh 2.4
![ Screenshot 2022-11-09 20 04 29](https://user-images.githubusercontent.com/19758978/200919359-f7a7d49d-5769-4ea7-a5a8-14bbb1791bc1.png)

Bokeh 3.0
![ Screenshot 2022-11-09 20 04 49](https://user-images.githubusercontent.com/19758978/200919293-9b6906bc-74d1-4cb0-b9b1-a253f5c1365f.png)

``` python
import holoviews as hv
import numpy as np

hv.extension("bokeh")

xs = np.linspace(0, np.pi * 4, 100)
data = (xs, np.sin(xs))
hv.Points(data).opts(height=200, responsive=True, title="stretch width")
```

---
Comment from @mattpap, [ref](https://github.com/holoviz/holoviews/pull/5388#issuecomment-1309246088).
> This happens when an expanding plot is added to a non-expanding container. The plot will work fine on its own, assuming CSS allows for that (usually true in width and depends in height), however not when wrapped. The previous layout allowed expanding children to expand the parent, but that's not possible anymore with the CSS layout. One has to assign sizing modes outside-in. There's new inherit sizing mode to help with this.

 ---

Comment from @philippjfr, [ref](https://github.com/holoviz/holoviews/pull/5388#issuecomment-1400085631).
> Probably to do with the way the HoloViews pane in Panel wraps the component. Hopefully an easy fix.

**Comment by philippjfr** [comment]
Haven't checked yet but https://github.com/holoviz/panel/pull/4360 should fix this.

**Comment by Hoxbro** [comment]
Fixed by https://github.com/holoviz/panel/pull/4360
