### ISSUE TITLE
New and Unexpected Warning: Tool of type could not be found and could not be activated by default.

### ISSUE THREAD

**Issue by MikeB2019x** [holoviz/holoviews#5614]
#### ALL software version info
MacOS Ventura 13.2
holoviews 1.15.4 pyhd8ed1ab_0 conda-forge
jupyter 1.0.0  py310h2ec42d9_8 conda-forge

#### Description of expected behavior and the observed behavior
Trying to specify `default_tools` in Scatter plot `opts`.  Expect no warning.  In response to the following Scatter plot of a 99K x 8 matrix of doubles:
```
(hv.Scatter(Xpca.loc[~Xpca.node.isin(['n0','n1','n57917'])], 
             kdims='x', vdims=['y','node','id','labels','date','in_deg','out_deg','tot_edge'])
            .opts(default_tools=['hover','save','box_zoom','reset'],
                  height=800, width=900, color='tot_edge', xlabel='PC1',ylabel='PC2',
                  colorbar=True, clim=(0,10), cmap='jet',show_grid=True
                 )
 )
```
Get the following warning:
```
WARNING:param.OverlayPlot09107: Tool of type 'pan' could not be found and could not be activated by default.
WARNING:param.OverlayPlot09107: Tool of type 'wheel_zoom' could not be found and could not be activated by default.
```

#### Complete, minimal, self-contained example code that reproduces the issue
Data:

x	y	node	labels	date	id	in_deg	out_deg	tot_edge
6.28234	-3.198913	n2	:TRANSACTION	2017-01-02	100276789	1	0	1
6.071874	-3.812788	n3	:TRANSACTION	2017-01-02	100276792	1	0	1
5.716742	3.669202	n4	:TRANSACTION	2017-01-02	100276813	2	0	2
5.612813	-0.583601	n5	:TRANSACTION	2017-01-02	100276814	2	0	2
5.656079	-0.364387	n6	:TRANSACTION	2017-01-02	100276822	2	0	2

Code:
```
(hv.Scatter(data, kdims='x', vdims=['y','node','id','labels','date','in_deg','out_deg','tot_edge'])
          .opts(default_tools=['hover','save','box_zoom','reset'],
                height=800, width=900, color='tot_edge', xlabel='PC1',ylabel='PC2',
                colorbar=True, clim=(0,10), cmap='jet',show_grid=True
               )
)
```

**Comment by Hoxbro** [comment]
This is reproducible by the following and is related to the change made in https://github.com/holoviz/holoviews/pull/5480:

``` python
import holoviews as hv
hv.extension("bokeh")
hv.Scatter([]).opts(default_tools=[])
```
