### ISSUE TITLE
Error when using groupby with hvplot

### ISSUE THREAD

**Issue by lforesta** [holoviz/holoviews#5615]
I'm using hvplot to plot gridded data grouped by time, as shown in this example: https://hvplot.holoviz.org/user_guide/Gridded_Data.html#2d

I can run that example without issues, but when I use my data I get an error from holoviews (see below). My cmd is:
`my_data.hvplot(groupby='time') ` where `my_data` is a `xr.DataArray`.

#### ALL software version info
```
Ubuntu 22.04
Python 3.9.16
hvplot                   0.8.2
geoviews                 1.9.5
holoviews                1.15.2
bokeh                    2.4.3
```

#### Description of expected behavior and the observed behavior
Should plot the gridded data with a slider (over the time dimension).

#### Complete, minimal, self-contained example code that reproduces the issue

The issue is probably in something missing in the input file I use, which is a custom tif file (see DataArray structure below).

```
my_data
<xarray.DataArray 'bareness' (time: 2, lat: 5051, lon: 6035)>
dask.array<getitem, shape=(2, 5051, 6035), dtype=float32, chunksize=(2, 1000, 1000), chunktype=numpy.ndarray>
Coordinates:
  * time         (time) datetime64[ns] 2018-01-06 2018-01-11
  * lon          (lon) float64 -62.42 -62.42 -62.42 ... -62.05 -62.05 -62.05
  * lat          (lat) float64 -27.7 -27.7 -27.7 -27.71 ... -28.01 -28.01 -28.01
    spatial_ref  int64 0
    mask         (lat, lon) bool False False False False ... False False False
Attributes:
    STATISTICS_VALID_PERCENT:  0
    scale_factor:              1.0
    add_offset:                0.0
    long_name:                 ('2018-01-01T00:00:00+00:00', '2018-01-06T00:0...

my_data.hvplot(groupby='time') -> returns error posted below
```

#### Stack traceback and/or browser JavaScript console output
```
File ~/repos/hvplot-env/.venv/lib/python3.9/site-packages/holoviews/core/options.py:1426, in Store.render(cls, obj)
   1424 data, metadata = {}, {}
   1425 for hook in hooks:
-> 1426     ret = hook(obj)
   1427     if ret is None:
   1428         continue
...
    298 if not isinstance(library, list):
    299     library = [library]
--> 300 return any([obj.__module__.split('.')[0].startswith(l) for l in library])

AttributeError: 'collections.OrderedDict' object has no attribute '__module__'
:DynamicMap   [time]
```

**Comment by Hoxbro** [comment]
It looks like your data is `dask.array`, which does not seem to be the case, for the example.

It is, with a high likelihood, a bug, but I need a small dataset to confirm and fix it. The data can be fake as long it reproduces the error. Can you help me with that?

**Comment by lforesta** [comment]
Apologies for the late reply. I uploaded some sample data. Here is a small script that replicates the error:

```
ds = xr.open_dataset("sample_data.nc")
# ds.bareness
ds.bareness.hvplot(groupby='time', width=500)  # -> returns error stated above
```

I also realized that the issue is connected to the `long_name` attribute set in the data array `ds.bareness`. If I remove that, the plot works:
```
_ = ds.bareness.attrs.pop('long_name')
ds.bareness.hvplot(groupby='time', width=500)  # -> works
```
This seems more of a workaround than a solution though, but it probably hints as to where to look.

However, the xarray tutorial (linked at the top) also has such attribute in place and the plot works fine:
```
air_ds = xr.tutorial.open_dataset('air_temperature').load()
print(air_ds.air.attrs)
air_ds.air.hvplot(groupby='time', width=500)
```

I tried removing the coords metadata from the example dataset (since they are missing in my data), but still I could not break this example. However, I'm relatively sure the issue is due to some missing or mis-formatted metadata in my dataset (which comes from a custom tif file).

Thanks for the help!

[sample_data.zip](https://github.com/holoviz/holoviews/files/10742006/sample_data.zip)

**Comment by lforesta** [comment]
I can now reproduce the error with the xarray dataset too:
```
air_ds = xr.tutorial.open_dataset('air_temperature').load()
air_ds.air.attrs['long_name'] = ('aaa', 'bbb')
print(air_ds.air.attrs)
air_ds.air.hvplot(groupby='time', width=500)
```

When `DataArray.attrs['long_name']` is a tuple/list, this error pops up

**Comment by Hoxbro** [comment]
Thank you for the investigation and for reducing the problem. I reduced it down to this Holoviews only problem:

``` python
import xarray as xr 
import holoviews as hv

data = xr.tutorial.open_dataset('air_temperature').load()
data.air.attrs['long_name'] = ('aaa', 'bbb')
hv.Dataset(data, ["time", "lon", "lat"]).data
```

![image](https://user-images.githubusercontent.com/19758978/219031407-3f142630-6de9-4e98-a438-b7ee2065ac8f.png)
