### ISSUE TITLE
Bokeh plot doesn't display in notebook

### ISSUE THREAD

**Issue by avissens** [holoviz/holoviews#5656]
The problem:

The command `output_notebook()` generates this response -
BokehJS 2.4.3 successfully loaded.
But no plot is shown.
I can save the plot as html though.

I know that there should be a conflict between versions of bokeh and notebook. Maybe someone can point to versions I need to use? 

bokeh               3.0.3
IPython             7.25.0
jupyter_client      6.1.12
jupyter_core        4.7.1
notebook            6.4.0
-----
Python 3.9.16

My imports:

```
import bokeh.plotting as bp
from bokeh.models import HoverTool, BoxSelectTool, ColumnDataSource
from bokeh.plotting import figure, show, save
from bokeh.io import output_notebook

```

**Comment by Hoxbro** [comment]
This is not a holoviews issue but a bokeh usage problem. 

I would suggest you ask a question here: https://discourse.bokeh.org/

But a few suggestions is to try to restart your jupyter server and create a new notebook and see if things work.
