### ISSUE TITLE
Support Bokeh 3

### ISSUE THREAD

**Issue by r-richmond** [holoviz/holoviews#5671]
Today the latest version of holoviews (1.15.4) does not support bokeh3. It would be great if it did.

example poetry config
```
[tool.poetry.dependencies]
python = "^3.10"
holoviews = ">=1.15.4"
bokeh = ">=3.0.0"
```

running `poetry lock` returns

```
Because no versions of panel match >0.13.1,<0.14.0 || >0.14.0,<0.14.1 || >0.14.1,<0.14.2 || >0.14.2,<0.14.3 || >0.14.3,<0.14.4 || >0.14.4
 and panel (0.13.1) depends on bokeh (>=2.4.0,<2.5.0), panel (>=0.13.1,<0.14.0 || >0.14.0,<0.14.1 || >0.14.1,<0.14.2 || >0.14.2,<0.14.3 || >0.14.3,<0.14.4 || >0.14.4) requires bokeh (>=2.4.0,<2.5.0).
And because panel (0.14.0) depends on bokeh (>=2.4.0,<2.5.0)
 and panel (0.14.1) depends on bokeh (>=2.4.0,<2.5.0), panel (>=0.13.1,<0.14.2 || >0.14.2,<0.14.3 || >0.14.3,<0.14.4 || >0.14.4) requires bokeh (>=2.4.0,<2.5.0).
And because panel (0.14.2) depends on bokeh (>=2.4.0,<2.5.0)
 and panel (0.14.3) depends on bokeh (>=2.4.0,<2.5.0), panel (>=0.13.1,<0.14.4 || >0.14.4) requires bokeh (>=2.4.0,<2.5.0).
And because panel (0.14.4) depends on bokeh (>=2.4.0,<2.5.0)
 and holoviews (1.15.4) depends on panel (>=0.13.1), holoviews (1.15.4) requires bokeh (>=2.4.0,<2.5.0).
So, because holoview-test depends on both holoviews (==1.15.4) and bokeh (>=3.0.0), version solving failed.
```

**Comment by r-richmond** [comment]
@Hoxbro 

Regarding the closing of the issue, It doesn't look like the version supporting v3 is out yet. Did I miss an announcement?

**Comment by Hoxbro** [comment]
No. But the PR implemented the support has been merged (this was done before your issue #5388). So was doing a bit of maintenance of the milestone tracker.  

Sorry about the confusion.

**Comment by r-richmond** [comment]
No worries that makes sense.

Would you happen to know if installing off main is a reasonable thing to do? (I.e. what is this projects strategy around branching / merging to main).

**Comment by Hoxbro** [comment]
You can install it using `conda create -n holoviews python=3.10 holoviews -c pyviz/label/dev -c conda-forge`.

If you install packages after this you may need to add `-c pyviz/label/dev` to not downgrade HoloViews.

Or use `pip install holoviews --pre`, preferably in a venv.
