### ISSUE TITLE
hv.Graph.from_network() : ignoring node attribute values for rendering

### ISSUE THREAD

**Issue by MikeB2019x** [holoviz/holoviews#5697]
#### ALL software version info
MacOS: Ventura 13.3.1 (22E261)
holoviews: 1.15.0

The subject method should produce a network plot directly from a networkx graph.  The method should identify all the node attributes and when plotting the attributes should be recognized for things like coloring.  The example below shows a simple graph and rendering using the subject method.  The attributes are present in the object but referring to the desired attribute for coloring does not work (see below).

#### Complete, minimal, self-contained example code that reproduces the issue
```
G_ = nx.Graph()
G_.add_node('n75093', attr_dict={'TYPE': ':Invoice', 'date': '2022-05-13'})
G_.add_node('n75095', attr_dict={'TYPE': ':SalesOrder', 'date': '2022-05-13'})

# temp_g.nodes(data=True)
g_plot = hv.Graph.from_networkx(G_, nx.layout.spring_layout)
g_plot.opts(node_color='TYPE', cmap='Category10')

```
![image](https://user-images.githubusercontent.com/49003263/234356883-61d8ea35-261e-453f-af6b-7a3090431c07.png)

IMPORTANT NOTE:  if the node attributes are added individually as opposed as below, then the behaviour is as expected:
```
G_.add_node('n75093', TYPE=':Invoice', date='2022-05-13')
G_.add_node('n75095', TYPE=':SalesOrder', date='2022-05-13')
```
![image](https://user-images.githubusercontent.com/49003263/234358934-2041904a-3bd1-48ab-83ce-cd485ab6798a.png)

**Comment by MikeB2019x** [comment]
It's one of a few ways.  It's arguably the most convenient.

<http://mindbridge.ai/>

Michael Bourassa

Data Scientist | *MindBridge*

+1 613-894-9189 <+1-613-894-9189>

Bourassa

mindbridge.ai

[image: twitter] <https://twitter.com/mindbridge_ai>

[image: linkedin] <https://www.linkedin.com/company/mindbridge-ai/>



[image: banner]
<https://www.mindbridge.ai/news/mindbridge-named-to-forbes-ai-50-list-of-most-promising-ai-companies>

**Comment by Hoxbro** [comment]
Is it possible for you to show a reference where this is used?

**Comment by MikeB2019x** [comment]
I've been using this for so long that I never thought to look it up and can't recall when or why I adopted it.  While it _is_ convenient and valid, it is not a standard way of adding attributes to nodes in networkx (I asked in their discussion forums :-) ). Thanks for the response but especially the question!

**Comment by MridulS** [comment]
FWIW NetworkX supports nesting of dict-of-dict-of-dict in the node/edge attributes so that would be hard to support.

The recommended way would be to indeed use `G_.add_node('n75095', TYPE=':SalesOrder', date='2022-05-13')`

**Comment by Hoxbro** [comment]
Thank you both of you for the investigation and info.  I will close the issue.

**Comment by MikeB2019x** [comment]
Last tidbit of information (also from networkx devs):  if you did want to drop a dict as the second argument for the `.add_node()` method then the way to do it is:

`G_.add_node('n75095', **{'TYPE':':SalesOrder', 'date':'2022-05-13'})`

or

```
attr_dict = {
    'TYPE':':SalesOrder', 
    'date':'2022-05-13'
}
G_.add_node('n75095', **attr_dict)
```
