### ISSUE TITLE
Panel widget buttons (NEXT and PREV) not working if the output is saved in html but works perfectly in jupyter notebook output 

### ISSUE THREAD

**Issue by debashishsamantaray** [holoviz/holoviews#5716]
#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
import holoviews as hv


df = pd.read_csv('https://raw.githubusercontent.com/miura/NEUBIAS_AnalystSchool2020/master/Arianne/Dataset/grant_complete.csv')
df.head()

#df['year'].unique() --> array([1973, 1975, 1987, 1991, 2012], dtype=int64)

df_2012 = df.loc[df['year']==2012, :].copy()
df_1973 = df.loc[df['year']==1973, :].copy()
df_1987 = df.loc[df['year']==1987, :].copy()
df_1991 = df.loc[df['year']==1991, :].copy()

point1= hv.Points(
    data=df_2012,
    kdims=['beak length (mm)', 'beak depth (mm)'],
    vdims=['species'],
)

point2 = hv.Points(
    data=df_1973,
    kdims=['beak length (mm)', 'beak depth (mm)'],
    vdims=['species'],
)

point3 = hv.Points(
    data=df_1987,
    kdims=['beak length (mm)', 'beak depth (mm)'],
    vdims=['species'],
)

point4 = hv.Points(
    data=df_1991,
    kdims=['beak length (mm)', 'beak depth (mm)'],
    vdims=['species'],
)

images = [point1, point2, point3, point4]  

# define a Panel widget to display the current image
image_widget = pn.panel(images[0])

def next_image(event):
    current_index = images.index(image_widget.object)
    next_index = (current_index + 1) % len(images)
    image_widget.object = images[next_index]

def prev_image(event):
    current_index = images.index(image_widget.object)
    prev_index = (current_index - 1) % len(images)
    image_widget.object = images[prev_index]

next_button = pn.widgets.Button(name='Next', button_type='primary')
next_button.on_click(next_image)

prev_button = pn.widgets.Button(name='Previous',button_type='primary')
prev_button.on_click(prev_image)

obj = pn.Column(image_widget, pn.Row(prev_button, next_button))
obj
#obj.save("example.html") -> saving it to html
```

#### Screenshots or screencasts of the bug in action

If I am launching this application from jupyter it's working as expected, i.e on clicking on next and previous button the points are rendered accordingly
![jupyterop1](https://github.com/holoviz/holoviews/assets/85837352/98553f5a-13b3-4572-9614-47f9d986bd0e)

But when I am trying to save it as html

obj.save("example.html"),

in the output the click events on previous and next is not working. the points are not rendered accordingly, on bydefault the images[0], i.e p1 is rendered
![html](https://github.com/holoviz/holoviews/assets/85837352/5b471a1e-1f11-4b35-932e-c41547c4d1fb)

Would any one please help on this ? I have already tried like bokeh serve and panel serve the application , still the result is same.

**Comment by Hoxbro** [comment]
`save` creates a static HTML file, and it has no idea what to do when clicking the button. 

I would suggest you add this `obj.servable()` to the end of your file and launch the app with `panel serve filename`. This will launch a server that can update the plot like what you are seeing in the Notebook.

**Comment by Hoxbro** [comment]
If you have any more usage questions, you can ask them on [Discourse](https://discourse.holoviz.org/).
