### ISSUE TITLE
Annotator not syncing with associated dataframe

### ISSUE THREAD

**Issue by jmarkow** [holoviz/holoviews#5721]
### Environment

```
bokeh==2.4.3
holoviews==1.16.0
jupyterlab==3.6.3
```

`Ubuntu 22.04.2 LTS`

Running remotely in Jupyter lab via `Chrome Version 112.0.5615.137 (Official Build) (arm64)`

### Expected behavior

Point annotations are synced with dataframe after creating new points or moving old ones.

### Observed behavior

Point annotations are not synced with dataframe.

### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
import numpy as np
hv.extension('bokeh')

img = hv.Image(np.random.randn(100,100))
cells = hv.Points([0,0]).opts(width=500, height=500, responsive=False, padding=0)
annotator = hv.annotate.instance()
annotator(img * cells, annotations=['Label'], name="Cell Annotator")
```
```
annotator.annotated.dframe()
```

### Screenshots
<img width="1078" alt="Screen Shot 2023-05-19 at 12 37 27 AM" src="https://github.com/holoviz/holoviews/assets/76247/558594fc-5f25-45da-a510-7acd4e365426">

<img width="465" alt="Screen Shot 2023-05-19 at 12 37 43 AM" src="https://github.com/holoviz/holoviews/assets/76247/91ec00a2-cbcf-484e-9303-a42a01997b6b">

**Comment by Hoxbro** [comment]
Thank you for the bug report. 

This is the same issue as https://github.com/holoviz/holoviews/issues/5712.

**Comment by jmarkow** [comment]
@Hoxbro thanks. Is there a recommended configuration of holoviews and Bokeh where annotation works?

**Comment by Hoxbro** [comment]
Unfortunately, not to my knowledge.
