### ISSUE TITLE
Grouped Bars not rendering correctly

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#5726]
Noticed this in hvplot documentation and also on the latest dev build:

http://dev.holoviews.org/reference/elements/bokeh/Bars.html

<img width="510" alt="Screen Shot 2023-05-23 at 17 54 27" src="https://github.com/holoviz/holoviews/assets/1550771/24f8b53b-20b8-424a-af48-6539e57b4757">

**Comment by Hoxbro** [comment]
This is a Bokeh problem with `ObjectNDArray`.

``` python
# This is mostly code from webpage.
import holoviews as hv
import numpy as np
import pandas as pd

hv.extension("bokeh")
samples = 100

pets = ["Dog"]
genders = ["Female", "Male"]

pets_sample = np.random.choice(pets, samples)
gender_sample = np.random.choice(genders, samples)
count = np.random.randint(1, 5, size=samples)
df = pd.DataFrame({"Pets": pets_sample, "Gender": gender_sample, "Count": count})
bars = hv.Bars(df, kdims=["Pets", "Gender"]).aggregate(function=np.sum)
```

Converting the code to Bokeh,
``` python
from bokeh.io import show
from bokeh.models import Row

bp_org = hv.render(bars)
bp_fix = hv.render(bars)
data = bp_fix.renderers[0].data_source.data
data["xoffsets"] = data["xoffsets"].tolist()

show(Row(bp_org, bp_fix))
```

![image](https://github.com/holoviz/holoviews/assets/19758978/7162fbdf-2441-4f17-bd6d-dbfe22d08aeb)

**Comment by nicolaskruchten** [comment]
Is the same thing happening for box plots or is that a different issue? https://holoviews.org/gallery/demos/bokeh/boxplot_chart.html today looks like this, whereas I would expect the boxes to be non-overlapping:

<img width="791" alt="image" src="https://github.com/holoviz/holoviews/assets/203523/a8c2e7c4-b00b-4c75-b691-15409af134d2">

**Comment by Hoxbro** [comment]
This is the same issue. If you need to use this functionality right now, you can use the following hook:
``` python
def dtype_fix_hook(plot, element):
    renderers = plot.handles["plot"].renderers
    for renderer in renderers:
        data = renderer.data_source.data
        for k, v in data.items():
            if hasattr(v, "dtype") and v.dtype.kind == "U":
                data[k] = v.tolist()

boxwhisker.opts(hooks=[dtype_fix_hook])
```
![image](https://github.com/holoviz/holoviews/assets/19758978/cf1f3ca9-3b1d-433d-83ea-271a3f593141)

**Comment by Hoxbro** [comment]
I will close the issue as we have a workaround in Holoviews.

https://holoviews.org/reference/elements/bokeh/Bars.html
![image](https://github.com/holoviz/holoviews/assets/19758978/7e4bc146-4b99-40fa-aff5-d75582510a30)

https://holoviews.org/gallery/demos/bokeh/boxplot_chart.html
![image](https://github.com/holoviz/holoviews/assets/19758978/3c65bc96-bce6-4bd8-bf09-24c4fcf8671a)
