### ISSUE TITLE
Correct invert_yaxis for holoviews.Image

### ISSUE THREAD

**Issue by GeoVizNow** [holoviz/holoviews#5727]
Thanks for the great new functionality in holoviews 1.16. I came  across one thing that seems to fail now (not sure if it did also before). 

#### ALL software version info
browser: Microsoft Edge
run env: notebook
OS: Windows 10
python: Python 3.8.10

holoviews: 1.16.0
pandas: 2.0.1
numpy: 1.23.5
bokeh: 3.1.1
panel: 1.0.2

#### Description of expected behavior and the observed behavior
When I use holoviews.Image I expect to be able to invert the y-axis such that both data and axis tick labels are inverted in sync. 
It seems currently the data are mirrored around the bottom bound when the axis tick labels are inverted. Data move out of original extents. 

#### Complete, minimal, self-contained example code that reproduces the issue
Example build on holoviews gallery example:

```
import numpy as np
import pandas as pd
import holoviews as hv
from holoviews import opts
hv.extension('bokeh')

ls = np.linspace(0, 10, 200)
xx, yy = np.meshgrid(ls, ls)

image_left = 0
image_right = 200
image_top = 800
image_base = 0

# bounds=(x0, y0, x1, y1)
bounds=(image_left, image_base, image_right, image_top)
img = hv.Image(np.sin(xx)*np.cos(yy), bounds=bounds).opts(invert_yaxis=False)
img_inv_yaxis = hv.Image(np.sin(xx)*np.cos(yy), bounds=bounds).opts(invert_yaxis=True, ylim=(100, 1700), xlim=(-50, 450))

img + img_inv_yaxis
```

#### Screenshots or screencasts of the bug in action
Results of the above shown here, xlims and ylims are expanded to show the extent of both original data and data with inverted yaxis.
![image](https://github.com/holoviz/holoviews/assets/31777090/02bfd0ed-fe39-45b5-8510-69b7e090038f)

I would be happy if you could look into this.

**Comment by ldr426** [comment]
Same issue I encountered. In the old version, inver-axis options did work.

**Comment by Hoxbro** [comment]
What was the old version?

**Comment by ldr426** [comment]
@Hoxbro 


> What was the old version?

1.14.9

**Comment by droumis** [comment]
> It seems to be related to Bokeh 2 / Bokeh 3, as I get the correct behavior with Bokeh 2: ![image](https://user-images.githubusercontent.com/19758978/244123035-8959b333-3898-4787-916c-21583cc0611a.png)

@Hoxbro , I don't understand how this is the "correct behavior with Bokeh 2"..

The user is asking about inverting "the y-axis such that both data and axis tick labels are inverted in sync."  What users are expecting is that invert_yaxis flips the entire plot, y_axis and data included.

The same bug was identified [on discourse](https://discourse.holoviz.org/t/invert-y-axis-on-contourf-plot-and-add-a-background-plot-on-same-figure/1559/5).

**Comment by Hoxbro** [comment]
_Correct_ was probably not the right word. A better word would have been _different_.

**Comment by GeoVizNow** [comment]
Sorry for misleading wording and thanks for correcting this!
