### ISSUE TITLE
Make `inline=False` the default behavior for `hv.extension`

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/holoviews#5730]
I want to start a discussion about making `inline=False` the default behavior for `hv.extension` in notebooks.

In my opinion, it would be better to have `inline=False` as the default behavior. I think `inline=True` was meant for airgap environments and not something most users need.

It will reduce the file size significantly. A quick comparison with `inline=True` and `inline=False` shows that the file size is 18 MB vs 45 KB, respectively.

Some problems that have also come up recently where it is not obvious that it is related to `inline=True`:

1) Plotly cannot load in VS code with `inline=True`:
    - https://github.com/holoviz/holoviews/issues/3733#issuecomment-1557808152
    - https://github.com/holoviz/hvplot/issues/1071

2) Bokeh gives Javascript error in Jupyter Notebook:
    - https://github.com/holoviz/holoviews/issues/5699 *

*) This seems to have been fixed by not loading MathJax by default because of https://github.com/holoviz/panel/pull/4895, but it will come back with https://github.com/holoviz/holoviews/pull/5729.

As this is a breaking change, it should be implemented at 1.17 as a minimum.

**Comment by maximlt** [comment]
Closed by https://github.com/holoviz/holoviews/pull/5729
