### ISSUE TITLE
Make gallery example using box select to control RangeXY work

### ISSUE THREAD

**Issue by GeoVizNow** [holoviz/holoviews#5736]
#### ALL software version info
browser: Chrome
os: windows
holoviews: 1.16.0
bokeh: 3.1.1
panel: 1.0.4
param: 1.13.0
numpy: 1.24.3
testing conditions: jupyter notebook

#### Description of expected behavior and the observed behavior
I am referring to the reference gallery example on code RangeXY, see [https://holoviews.org/reference/streams/bokeh/RangeXY.html](https://holoviews.org/reference/streams/bokeh/RangeXY.html). 

I am trying to make use of RangeXY, but then the box select tool seems to not work or maybe it is wrongly mapped(?) There is nothing happening when trying to select a range using it. 
When running the code below (copy from reference gallery) the hover tool tip says **'Box Select (y-axis)'** though I would expect to just say **'Box Select'** (to indicate it is usable for both axes) .

#### Complete, minimal, self-contained example code that reproduces the issue

```
# The below is a copy of the code from the example. It seems the box select tool is 
import numpy as np
import holoviews as hv

hv.extension('bokeh')

# Define an image
Y, X = (np.mgrid[0:100, 0:100]-50.)/20.
img = hv.Image(np.sin(X**2+Y**2))

def selected_hist(x_range, y_range):
    # Apply current ranges
    obj = img.select(x=x_range, y=y_range) if x_range and y_range else img

    # Compute histogram
    return hv.operation.histogram(obj)

# Define a RangeXY stream linked to the image 
rangexy = hv.streams.RangeXY(source=img)

# Adjoin the dynamic histogram computed based on the current ranges
img << hv.DynamicMap(selected_hist, streams=[rangexy])

```

#### Screenshots or screencasts of the bug in action
![2023-06-02_14-08-13](https://github.com/holoviz/holoviews/assets/31777090/2b673cfd-02ef-4aee-b340-7996ffb4a8d3)

**Comment by GeoVizNow** [comment]
I am considering to close this one as I believe I misunderstood the example. But could you first have a quick look and see if the example behaves as you expect. The histogram behaves a bit different from animation in reference gallery.
![2023-06-02_22-35-09](https://github.com/holoviz/holoviews/assets/31777090/4e0d3944-8778-4951-b894-e88052ce8c78)

**Comment by Hoxbro** [comment]
I think it works as intended.

**Comment by GeoVizNow** [comment]
Closing then, thanks!
