### ISSUE TITLE
Tool of type 'box_edit' could not be found in VSCode

### ISSUE THREAD

**Issue by allenduh** [holoviz/holoviews#5756]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
Could not find command to get Holoviews version, but I am running a Jupyter notebook in VSCode with the following version:
Jupyter version:
```
Selected Jupyter core packages...
IPython          : 7.29.0
ipykernel        : 6.4.1
ipywidgets       : 8.0.6
jupyter_client   : 6.1.12
jupyter_core     : 4.8.1
jupyter_server   : 1.4.1
jupyterlab       : 3.2.1
nbclient         : 0.5.3
nbconvert        : 6.1.0
nbformat         : 5.1.3
notebook         : 6.4.5
qtconsole        : 5.1.1
traitlets        : 5.1.0
```

#### Description of expected behavior and the observed behavior
<img width="1067" alt="Screenshot 2023-06-11 at 5 41 40 PM" src="https://github.com/holoviz/holoviews/assets/63938073/c89bb67a-3253-4eb8-89e2-c96b10a0a58e">
I expect the bottom graph (toolbar includes 'add box' icon) from this article: https://www.holoviews.org/gallery/demos/bokeh/box_draw_roi_editor.html. 

In my VSCode file, I only see a toolbar like the one in the top graph where the 'add box' icon is not included.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
from holoviews import opts
from holoviews import streams
hv.extension('bokeh')

boxes = hv.Polygons([hv.Box(0, 0, 1), hv.Box(2, 1, 1.5), hv.Box(0.5, 1.5, 1)])
box_stream = streams.BoxEdit(source=boxes, num_objects=2)
boxes.opts(
    opts.Polygons(active_tools=['box_edit'], fill_alpha=0.5, height=400, width=400))

```

We have also tried `hv.extension('bokeh', inline=False)` but the result is identical.

#### Stack traceback and/or browser JavaScript console output
`WARNING:param.PolygonPlot06232: Tool of type 'box_edit' could not be found and could not be activated by default.`

#### Screenshots or screencasts of the bug in action
<img width="958" alt="Screenshot 2023-06-11 at 5 44 52 PM" src="https://github.com/holoviz/holoviews/assets/63938073/8a78e3c4-c114-4a36-8e34-4fe644886b36">

**Comment by Hoxbro** [comment]
This is a regression and is related to changing `Hv.Rectangles` from using Bokeh's Rect to Bokeh's Quad, but the BoxEditTool does not support Quad type. For this to work, Bokeh needs to support Quad in BoxEditTool. 

To get this example to work, you can downgrade to 1.15.4.

**Comment by Hoxbro** [comment]
https://github.com/bokeh/bokeh/pull/13204 will implement Quad support in BoxEditTool. 

So when that is released, we can add the functionality back.
