### ISSUE TITLE
Missing xlabel when setting frame_height

### ISSUE THREAD

**Issue by droumis** [holoviz/holoviews#5771]
#### ALL software version info
panel: 1.0.4
holoviews: 1.16.0
hvplot: 0.8.3
bokeh: 3.1.1

#### Description of expected behavior and the observed behavior

Missing xlabel in a specific case of using an aggregation, setting `frame_height`, and displaying with Panel. I'm not sure at what level hvPlot, HoloViews, Panel the issue is but I was told to file an issue here first.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import xarray as xr
import hvplot.xarray
import panel as pn; pn.extension()

ds = xr.tutorial.open_dataset("air_temperature")

player = pn.widgets.Player(start=int(ds.lon[0].values), end=int(ds.lon[-1].values))

main_view = ds.hvplot.image('time', 'lat', groupby="lon", widgets={"lon": player})

right_view = ds.mean(['time']).hvplot.image(x='lon', frame_height=200) # does NOT show xlabel

# right_view = ds.mean(['time']).hvplot.image(x='lon', frame_height=200, xlabel='test') # does NOT show xlabel

# right_view = ds.isel(time=0).hvplot('lon', 'lat', frame_height=200) # shows xlabel

# right_view = ds.mean(['time']).hvplot('lon', 'lat', height=200) # shows xlabel

# right_view = ds.mean(['time']).hvplot('lon', 'lat') # shows xlabel

pn.Column(player, pn.Row(main_view[0], right_view))
```

#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/holoviews/assets/6613202/46288afb-c945-489e-8440-a40f165a3834)

**Comment by Hoxbro** [comment]
This is an even more MRE:
``` python
import hvplot.xarray
import xarray as xr

ds = xr.tutorial.open_dataset("air_temperature")
p1 = ds.mean("lon").hvplot.image("time", title="Test")
p2 = ds.mean("lon").hvplot.image("time", frame_height=180)
p1 + p2
```

![image](https://github.com/holoviz/holoviews/assets/19758978/0dcac16b-7779-4e12-bc57-904e94ceb835)

Checking what the underlying model is:
![image](https://github.com/holoviz/holoviews/assets/19758978/1a78ea28-e16e-4e40-8ba0-7e8e2e812bf6)

And trying to see if I can recreate it in pure Bokeh, shows the same behavior:
``` python
from bokeh.plotting import figure, gridplot, show

p1 = figure(title="title", x_axis_label="x", y_axis_label="y")
p1.line(x=[0, 1], y=[0, 1])

p2 = figure(x_axis_label="x", y_axis_label="y", frame_height=200)
p2.line(x=[0, 1], y=[0, 1])

show(gridplot(children=[[p1, p2]]))
```

![image](https://github.com/holoviz/holoviews/assets/19758978/b9f8c996-c835-490e-887b-ed6b2d6e9afb)

**Comment by droumis** [comment]
Closing this issue for now. A workaround is to add a title to the second plot, which manually aligns the top of the frame.
