### ISSUE TITLE
NdOverlay click_policy: hide doesn't work when combined with a reference plot.

### ISSUE THREAD

**Issue by Maester03** [holoviz/holoviews#5778]
#### ALL software version info
pandas: 1.5.1
holoviews: 1.16.2
bokeh: 2.4.1

#### Description of expected behavior and the observed behavior
Using an NdOverlay with as option _legend_opts={"click_policy":"hide"}_ the complete graph dissappears when the legend option is clicked.
However, when this NdOverlay plot is combined with a reference plot (e.g. hv.Ellipse), then the graph doesn't dissappear anymore when clicked on the legend. It is muted when the legend is clicked (the default behaviour).

#### Complete, minimal, self-contained example code that reproduces the issue
In the following example I create 2 plots:
- pNdOverlay is an NdOverlay which works as expected.
- pNdOverlayWithRef is the same NdOverlay combined with a hv.Ellipse and doesn't work as expected anymore.
```
import pandas as pd
import holoviews as hv
from holoviews import opts
df = pd.DataFrame({'x':[1,2,3], 'y': [2,4,9], 'y2': [3,5,10]})
p1 = hv.Scatter(df, 'x', 'y')
p2 = hv.Scatter(df, 'x', 'y2')

pNdOverlay = hv.NdOverlay({'p1':p1, 'p2':p2})
pNdOverlay.opts(legend_opts={"click_policy":"hide"})

pNdOverlayWithRef = pNdOverlay*hv.Ellipse(2,6,(1,1))

```
#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/holoviews/assets/95715329/091d2ec0-6a54-48f8-a320-1c49d22e3abc)
![image](https://github.com/holoviz/holoviews/assets/95715329/75e40fbf-6a0b-4731-822e-3db84756cce8)

**Comment by Hoxbro** [comment]
It is changing the container from a `NdOverlay` to an `Overlay`, which does not have that option set. So as a solution is to set the `opts` on the last `Overlay` like this: `pNdOverlayWithRef.opts(click_policy="hide")`

If you always want to hide the output by changing the default values of both `hv.opts.defaults(hv.opts.Overlay(click_policy="hide"), hv.opts.NdOverlay(click_policy="hide"))`

**Comment by Maester03** [comment]
Hey,
I thought that the "ndoverlay" inside the "overlay" would still have the option enabled and would still hide the graph.
Thanks a lot for the explanation. It works perfectly now.
I willl probably use the default option as you proposed.
