### ISSUE TITLE
Support for custom Element normalization functions

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#581]
The current normalization code computes the maximum ranges along each dimension, which is usually sufficient to compute the extent of the plot (e.g. the y-limits of a curve can be determined by taking the range of the value dimension of the curve), however there are cases where this isn't the case. A simple example is Spread and ErrorBars types where the y-limits are the combination of the mean and error dimensions. We could support extent normalization in this case by defining custom normalization function per Element type, which usually would just compute the range along each dimension but in cases where something more complex is required can also compute derived values.

**Comment by jbednar** [comment]
Sounds very useful.

**Comment by philippjfr** [comment]
We now have support for this using `dim` expressions.
