### ISSUE TITLE
BoxEdit doesn't work

### ISSUE THREAD

**Issue by ZachPenn** [holoviz/holoviews#5812]
BoxEdit doesn't work when trying `hv.Image * hv.Polygons([])`.  The box edit tool does not show up.  This used to work when using  holoviews=1.14.5, bokeh=2.3.3 and pyviz_comms=2.1.0.  Unfortunately, when I try these versions on my new computer (Apple M2 Max with Ventura 13.4.1), Bokeh fails as the backend.   

Note that similar errors currently appear in your reference gallery: https://holoviews.org/reference/streams/bokeh/BoxEdit.html

**Comment by ZachPenn** [comment]
Thanks for the quick response.  Unfortunately, when I downgrade to holoviews=1.15.0 and bokeh=2.4.0, when I attempt to specify `hv.notebook_extension('bokeh')`, I receive `ImportError: None of the backends could be imported`.  

Note that I first tried installing holoviews 1.15.4 and let conda determine the bokeh version (2.4.3) and this produced the same error.

**Comment by Hoxbro** [comment]
I just checked and think it is because of numpy 1.25 (fixed in https://github.com/holoviz/holoviews/pull/5636).

Can you try to downgrade numpy=1.24 and see if that works? Sorry for the inconvenience.

**Comment by ZachPenn** [comment]
I also had to roll back pyviz_comms to version to 2.1, but the following combination appears to work:
holoviews=1.15.0 bokeh=2.4.0 numpy=1.24 pyviz_comms=2.1

I will say that the initial import takes a bit longer than it used to and seems unreliable (occasionally the Jupyter cell hangs indefinitely).  Perhaps this stems from issues with my chip/browser.  Hopefully I can migrate to the latest versions of Holoviews and Bokeh soon.  These version issues are not pleasant.  Not sure why they seem to have gotten worse in the last couple years.
