### ISSUE TITLE
Hover info for holoviews.image is tracking non-inverted array values when 'invert_yaxis=True'

### ISSUE THREAD

**Issue by GeoVizNow** [holoviz/holoviews#5859]
I wanted to report an issue just seen when applying 'invert_yaxis=True' to a holoviews image the hover info is tracking wrong (non-inverted) values. 

#### ALL software version info
os: Windows 10 
ide: jupyter 
numpy: 1.23.5
bokeh: 3.2.1
holoviews: 1.17.0

#### Description of expected behavior and the observed behavior
When applying 'invert_yaxis=True' I expect the hover tracking image values to track the inverted image values. This does currently not seem to be the case. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import bokeh
import holoviews as hv
from holoviews import opts
hv.extension('bokeh')

arr = np.ones((10, 4))
arr[2:6,1:4] = np.nan
arr[6:10,:] = 2
arr 

i = hv.Image(arr)
i.opts(tools=['hover'], invert_yaxis=True, colorbar=True, cmap=['gray', 'blue'])

```
#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/holoviews/assets/31777090/7d686efd-6020-4c38-853c-d55fab819de1)

**Comment by GeoVizNow** [comment]
I would be happy to try to make a test to try to ensure this use case is working, but am not sure how to best do that. Maybe try materialize the image valur from a hover location(?). Any tips to how such a test is best structured?

**Comment by Hoxbro** [comment]
@mattpap, can you check if this is a Bokeh issue?

**Comment by GeoVizNow** [comment]
Was this a problem on the bokeh side?

**Comment by thomasteisberg** [comment]
This seems to also impact `quadmesh` as well when `rasterize=True`:

```
import numpy as np
import xarray as xr
import hvplot.xarray

test = xr.DataArray(np.random.randint(0,3,size=(10,10)), dims=['x', 'y'])

p = test.hvplot.quadmesh(ylim=(9, 0), rasterize=True)
p
```

![Screenshot from 2024-03-22 16-35-59](https://github.com/holoviz/holoviews/assets/1906581/02fa2997-7aea-4250-a172-a3c7412abafa)

Fresh install in a test environment:
```
$ mamba list | grep "bokeh\|hvplot\|xarray\|datashader\|dask"
bokeh                     3.3.4              pyhd8ed1ab_0    conda-forge
dask                      2024.3.1           pyhd8ed1ab_0    conda-forge
dask-core                 2024.3.1           pyhd8ed1ab_0    conda-forge
dask-expr                 1.0.4              pyhd8ed1ab_0    conda-forge
datashader                0.16.0             pyhd8ed1ab_0    conda-forge
hvplot                    0.9.2              pyhd8ed1ab_0    conda-forge
jupyter_bokeh             4.0.1              pyhd8ed1ab_0    conda-forge
xarray                    2024.2.0           pyhd8ed1ab_0    conda-forge
```

**Comment by Hoxbro** [comment]
Try upgrading to Bokeh 3.4. This has fixed it for me. 

![image](https://github.com/holoviz/holoviews/assets/19758978/1d9c3b33-30ca-4bb5-beb3-115c39523307)
![image](https://github.com/holoviz/holoviews/assets/19758978/afb0964c-102b-4233-939a-294c6fdba852)
