### ISSUE TITLE
Add kdim unit to widget name for dimensioned containers if provided

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/holoviews#5876]
#### Is your feature request related to a problem? Please describe.
It can be a bit puzzling for users to manipulate widgets representing parameters without the unit being displayed when there is one.

#### Describe the solution you'd like
Consider the following code where units are provided:

```python
import numpy as np
import holoviews as hv
import panel as pn

hv.extension('bokeh')


def fm_modulation(f_carrier=220, f_mod=220, mod_index=1, length=0.1, sampleRate=2000):
    sampleInc = 1.0/sampleRate
    x = np.arange(0,length, sampleInc)
    y = np.sin(2*np.pi*f_carrier*x + mod_index*np.sin(2*np.pi*f_mod*x))
    return hv.Curve((x, y), 'Time', 'Amplitude').opts(title='My custom title')


f_carrier = np.linspace(20, 60, 3)
f_mod = np.linspace(20, 100, 5)

curve_dict = {(fc, fm): fm_modulation(fc, fm) for fc in f_carrier for fm in f_mod}

kdims = [hv.Dimension(('f_carrier', 'Carrier frequency'), unit='Hz', default=40),
         hv.Dimension(('f_mod', 'Modulation frequency'), unit='Hz', default=60)]
holomap = hv.HoloMap(curve_dict, kdims=kdims)
holomap.opts(hv.opts.Curve(width=600))
```

![image](https://github.com/holoviz/holoviews/assets/49269671/b732e047-61a8-4af6-9682-990166bfed35)

No unit is specified, only the dimension name is shown. In my opinion, the following would be an improvement:

![image](https://github.com/holoviz/holoviews/assets/49269671/3b0192ce-fd77-49f3-b372-ef3156986d59)

#### Describe alternatives you've considered
Currently a workaround is to include the unit in the kdim name (unwieldy and possibly redundant) or in the plot title (not always desirable).

It's possible that it would take a very minor change but I can't find where this is done in the source code.

**Comment by Hoxbro** [comment]
It makes sense you can't find it easily. The change is needed in Panel. Right here:

https://github.com/holoviz/panel/blob/main/panel/pane/holoviews.py/#L649

Changing this line to the following:

``` python
widget_name = f"{dim.label} ({dim.unit})" if dim.unit else dim.
widget_kwargs = dict(dict(name=widget_name, options=options, value=default), **widget_kwargs)
```

You get:
![image](https://github.com/holoviz/holoviews/assets/19758978/ecc31693-35f7-477a-9f94-db6399d328be)

**Comment by philippjfr** [comment]
Would happily accept a PR to that effect, specifically it should be:

```python
widget_name = dim.pprint_label
widget_kwargs = dict(dict(name=widget_name, options=options, value=default), **widget_kwargs)
```

**Comment by Hoxbro** [comment]
Closed by https://github.com/holoviz/panel/pull/5535
