### ISSUE TITLE
Incorrect FutureWarning on pd.unique()

### ISSUE THREAD

**Issue by kuatroka** [holoviz/holoviews#5882]
After upgrading to pandas v 2.1.0, I'm getting a FutureWarning from within holoviews which I should not be be getting.

The warning 
```
/Users/yo_macbook/Documents/dev/sec_raw_files_dl/venv3.10/lib/python3.10/site-packages/holoviews/core/util.py:1175: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  return pd.unique(values)
```

The code where you can see that the pd.unique() is applied on a Series (as it should be), so the warning should not appear.

Code 
```
cik_dropdown = pn.widgets.Select(name='CIK',
                                    options=pd.unique(common_df['cik'].squeeze()).tolist(),
                                    value=pd.unique(common_df['cik'].squeeze()).tolist()[0])
```

#### ALL software version info
holoviews = (1.17.1)
pandas = 2.1.0
bokeh = 3.2.2
panel = 1.2.2

#### Description of expected behavior and the observed behavior
There should not be any warning

#### Complete, minimal, self-contained example code that reproduces the issue

```
cik_dropdown = pn.widgets.Select(name='CIK',
                                    options=pd.unique(common_df['cik'].squeeze()).tolist(),
                                    value=pd.unique(common_df['cik'].squeeze()).tolist()[0])

```

#### Screenshots or screencasts of the bug in action

Thanks

**Comment by Hoxbro** [comment]
This will be fixed when https://github.com/holoviz/holoviews/pull/5854 is merged.
