### ISSUE TITLE
Pandas FutureWarning: 

### ISSUE THREAD

**Issue by dave-c-vt** [holoviz/holoviews#5903]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

- holoviews 1.17.1
- python 3.10
- jupyterlab 4.0.6
- notebook 6.5.2
- pandas 2.1.1 <--------
- bokeh 3.2.2
- os ubuntu-20.04

##### Expected behavior

No warnings

##### Observed behavior

```bash
holoviews/core/data/pandas.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return dataset.data.dtypes[idx].type
```

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from datetime import datetime, timedelta
import pandas as pd
import hvplot.pandas

data = pd.DataFrame(
    {
        "Timestamp": [datetime.now(), datetime.now() + timedelta(minutes=1)],
        "Ch1_Avg_m/s": [1, 2],
        "Ch2_Avg_m/s": [2, 3],
    }
)
data.hvplot()

```

#### Screenshots or screencasts of the bug in action

```bash
.../venv/lib/python3.10/site-packages/holoviews/core/data/pandas.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return dataset.data.dtypes[idx].type
.../venv/lib/python3.10/site-packages/holoviews/core/data/pandas.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return dataset.data.dtypes[idx].type
```

- [x] I may be interested in making a pull request to address this

**Comment by Hoxbro** [comment]
Thank you for the issue. 

A fix has already been made in https://github.com/holoviz/holoviews/pull/5854. For now, if you don't want the warning either downgrade Pandas or if you are more daring try out the dev release of HoloViews 1.18.0a1.
