### ISSUE TITLE
New pandas version causes Future Depracation Warning

### ISSUE THREAD

**Issue by HTenkanen** [holoviz/holoviews#5912]
Hi,

we just updated our environment with new versions of `pandas`, `hvplot` and `holoviews` and after this update, we receive the following "FutureWarning":
![image](https://github.com/holoviz/holoviews/assets/6659534/9444906c-7296-405c-ad97-0f2ca37946a1)

We have Python 3.11, pandas v2.1.1, hvplot v0.8.4 and holoviews v1.17.1. It seems that the [dimension_type](https://github.com/holoviz/holoviews/blob/main/holoviews/core/data/pandas.py#L39) method might need an update to get rid of this warning.

**Comment by Hoxbro** [comment]
Thank you for the issue.

A fix has already been made in https://github.com/holoviz/holoviews/pull/5854. For now, if you don't want the warning either downgrade Pandas or if you are more daring try out the dev release of HoloViews 1.18.0a1.

**Comment by HTenkanen** [comment]
@Hoxbro Okay, perfect thanks for the update! I think we are not in a big hurry and will wait for the next release.
