### ISSUE TITLE
Downsample updates on target plot not triggering from RangeToolLink updates

### ISSUE THREAD

**Issue by droumis** [holoviz/holoviews#5973]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

Python              :  3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:17) [Clang 16.0.6 ]
Operating system    :  macOS-13.5.2-arm64-arm-64bit
holoviews           :  1.18.0
bokeh               :  3.3.0
hvplot              :  0.9.0

#### Description of expected behavior and the observed behavior
The LTTB downsampling on the target plot is not being triggered from range updates on the RangeToolLink source.

Very likely related to https://github.com/bokeh/bokeh/issues/13507

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import pandas as pd
import numpy as np
import hvplot.pandas
from holoviews.plotting.links import RangeToolLink

n_samples = 1000
data = np.random.randn(n_samples)

df = pd.DataFrame({'time': np.arange(len(data)), 'value': data})
plot = df.hvplot(x="time", y="value", height=500, downsample=True)
minimap = df.hvplot(x="time", y="value", height=150)
link = RangeToolLink(minimap, plot, axes=["x", "y"])

(plot + minimap).opts(shared_axes=False).cols(1)
```

#### Screenshots or screencasts of the bug in action

In this video, the downsampling is not being triggered by the RangeTool updates to the source plot, but it is being updated from wheel-zoom events on the target plot

https://github.com/holoviz/holoviews/assets/6613202/8863d4af-a013-4c0b-a7da-9dedfffc33ff

- [ ] I may be interested in making a pull request to address this

**Comment by droumis** [comment]
Bokeh [PR 13603](https://github.com/bokeh/bokeh/pull/13603) is supposed to fix this but with a dev install of Bokeh, I'm having trouble getting anything from HoloViews/hvPlot to render so I haven't been able to test yet. 

@Hoxbro When you get a chance, could you please try to:
```
cd [bokeh]
git pull
git checkout branch-3.4
conda activate [your HV dev env]
pip install -e [bokeh] --no-deps
```
then try to plot the sample code in this issue's description and let me know if anything renders? If yes, does adjusting the minimap overlay trigger a new downsampling in the main plot?

**Comment by Hoxbro** [comment]
With the changes in https://github.com/holoviz/panel/pull/6072 and running Bokeh 3.4.0.dev4, I get this output:


https://github.com/holoviz/holoviews/assets/19758978/8e5a43e7-0cb2-4126-a99a-0f06a4786cb5
