### ISSUE TITLE
Rasterize updates on target plot not triggering from RangeToolLink updates

### ISSUE THREAD

**Issue by droumis** [holoviz/holoviews#5974]
#### ALL software version info
Python : 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:17) [Clang 16.0.6 ]
Operating system : macOS-13.5.2-arm64-arm-64bit
holoviews : 1.18.0
bokeh : 3.3.0
hvplot : 0.9.0

#### Description of expected behavior and the observed behavior
Rasterize on the target plot is not being triggered from range updates on the RangeToolLink source.

Very likely related to https://github.com/holoviz/holoviews/issues/5973 and therefore https://github.com/bokeh/bokeh/issues/13507

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import pandas as pd
import numpy as np
import hvplot.pandas
from holoviews.plotting.links import RangeToolLink

n_samples = 1000
data = np.random.randn(n_samples)

df = pd.DataFrame({'time': np.arange(len(data)), 'value': data})
plot = df.hvplot(x="time", y="value", height=400, rasterize=True)
minimap = df.hvplot(x="time", y="value", height=150)
link = RangeToolLink(minimap, plot, axes=["x", "y"])

(plot + minimap).opts(shared_axes=False).cols(1)
```

#### Screenshots or screencasts of the bug in action

https://github.com/holoviz/holoviews/assets/6613202/b9c64653-1b40-4625-8850-ae655ed559e1

- [ ] I may be interested in making a pull request to address this

**Comment by Hoxbro** [comment]
Same as in #5973 

https://github.com/holoviz/holoviews/assets/19758978/d584dd30-9e97-4e5d-a6a5-b34868391c54
