### ISSUE TITLE
Image disappears upon click with tap tool activated

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/holoviews#6011]
Holoviews 1.18.1
Bokeh 3.3.1

I think this is a regression as I'm not seeing this bug in older versions (e.g. 1.17.0).

When `TapTool` is enabled, clicking on a plot will make `Image` and `RGB` elements disappear. It does not happen if it's disabled.

```python
import numpy as np
import holoviews as hv
import panel as pn

pn.extension()

ls = np.linspace(0, 10, 200)
xx, yy = np.meshgrid(ls, ls)

bounds = (-1, -1, 1, 1)
img = hv.Image(np.sin(xx)*np.cos(yy), bounds=bounds)
points = hv.Points([(0, 0)]).opts(color='red', size=10, tools=['tap'])

pn.Column(img*points).servable()
```

No error in Python of JS.

![Capture vidéo du 07-12-2023 14 44 09](https://github.com/holoviz/holoviews/assets/49269671/ee371170-c5b8-4065-b90d-3c616cbfd929)

**Comment by TheoMathurin** [comment]
I'd like to try and fix this as it's very annoying, especially since you can't get the image back once it's disappeared.

Does someone know where to look? Thanks!

**Comment by Hoxbro** [comment]
I think it is a WebGL problem can you try: 

``` python
import numpy as np
import holoviews as hv
import panel as pn

pn.extension()
hv.extension("bokeh")
hv.renderer("bokeh").webgl = False

ls = np.linspace(0, 10, 200)
xx, yy = np.meshgrid(ls, ls)

bounds = (-1, -1, 1, 1)
img = hv.Image(np.sin(xx) * np.cos(yy), bounds=bounds)
points = hv.Points([(0, 0)]).opts(color="red", size=10, tools=["tap"])

img * points
```

**Comment by Hoxbro** [comment]
This is a MRE in pure Bokeh. Can you please open an issue upstream?

``` python
import numpy as np

from bokeh.plotting import figure
from bokeh.io import output_notebook, show

output_notebook()

x = np.linspace(0, 10, 300)
y = np.linspace(0, 10, 300)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx) * np.cos(yy)

p = figure(width=400, height=400, output_backend="webgl")
p.image(image=[d], x=0, y=0, dw=10, dh=10)
p.add_tools('tap')

show(p)
```

**Comment by TheoMathurin** [comment]
Sure! Thanks for the quick investigation.

**Comment by Hoxbro** [comment]
I will close this issue as there is nothing we can do in HoloViews.

**Comment by TheoMathurin** [comment]
Issue posted upstream [here](https://github.com/bokeh/bokeh/issues/13678)
