### ISSUE TITLE
Implement support for the rasterize operation to automatically/easily attach an index array during the aggregation step

### ISSUE THREAD

**Issue by droumis** [holoviz/holoviews#6019]
From talking with @Hoxbro, it is my understanding that this may be at least partially addressed with the Selector support in [HoloViews #5805](https://github.com/holoviz/holoviews/pull/5805) - Supports Datashaders `where` and `summary` aggregators and add `selector` option to rasterize enabling instant hover inspection of value dimensions.

@Hoxbro, please add updates/details and what, if anything, is left to do.

**Comment by Hoxbro** [comment]
Correct, this is currently supported, either by 
1) have `ds.where` as an aggregator
2) Use the `selector`

``` python
import datashader as ds
import holoviews as hv
import numpy as np
import pandas as pd
from holoviews.operation.datashader import rasterize

hv.extension("bokeh")

num = 10000
np.random.seed(1)

dists = {
    cat: pd.DataFrame({
        "x": np.random.normal(x, s, num),
        "y": np.random.normal(y, s, num),
        "s": s,
        "val": val,
        "cat": cat,
    })
    for x, y, s, val, cat in [
        (2, 2, 0.03, 0, "d1"),
        (2, -2, 0.10, 1, "d2"),
        (-2, -2, 0.50, 2, "d3"),
        (-2, 2, 1.00, 3, "d4"),
        (0, 0, 3.00, 4, "d5"),
    ]
}

df = pd.concat(dists, ignore_index=True)

# Option 1
plot1 = rasterize(hv.Points(df), aggregator=ds.where(ds.min("s")))

# Option 2
plot2 = rasterize(hv.Points(df), selector=ds.min("s"))
```

Where you can get the data by showing the plot and run `plot.last.data`, which will give the data in a `xarray.Dataset`:

![image](https://github.com/holoviz/holoviews/assets/19758978/68737191-afee-4e74-b6d1-23e4537386d3)
