### ISSUE TITLE
Autoranging on multi-line plots limits view to a single line

### ISSUE THREAD

**Issue by droumis** [holoviz/holoviews#6033]
#### ALL software version info
Python              :  3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:17) [Clang 16.0.6 ]
Operating system    :  macOS-13.5.2-arm64-arm-64bit
Panel comms         :  default

holoviews           :  1.18.0
bokeh               :  3.3.0
hvplot              :  0.9.0
jupyterlab          :  4.0.7

#### Description of expected behavior and the observed behavior
Interacting, via zoom or pan, on a plot with multiple lines limits the viewport to a single line if `autorange='y'` is set.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import pandas as pd
import numpy as np
import hvplot.pandas

length = 100
parameters = [
    (0, 1),      # Mean 0, SD 1
    (100, 20),   # Mean 100, SD 20
    (1000, 200), # Mean 1000, SD 200
    (-500, 50)   # Mean -500, SD 50
]

df_ = pd.DataFrame({f"{i}": np.random.normal(mean, sd, length) for i, (mean, sd) in enumerate(parameters)})
df_ = df_.reset_index().melt(id_vars=['index'], var_name='source', value_name='value')
df_['source'] = df_['source'].astype(int)

# Single Line Plot
s = df_.hvplot(x="index", y="value", downsample=True, autorange='y').opts(width=450, shared_axes=False)

# Multi Line Plot
m= df_.hvplot(x="index", y="value", by='source', downsample=True, autorange='y').opts(show_legend=False, width=450, shared_axes=False)

s + m

```

#### Screenshots or screencasts of the bug in action

https://github.com/holoviz/hvplot/assets/6613202/f8a62e34-b017-4f02-a88d-4a8e440c9b24

- [ ] I may be interested in making a pull request to address this

**Comment by droumis** [comment]
Update from @jlstevens:

Together with @maximlt, they found out there is a more general problem with autoranging and overlays that is probably the cause; probably a regression since the multi-axis work. As such it will need to be fixed for the next holoviews release.

JLS will have another look this week

**Comment by droumis** [comment]
@jlstevens, any update from last week?

**Comment by jlstevens** [comment]
I'm currently working on it - unfortunately, this is a really tricky bit of code!

**Comment by droumis** [comment]
Hi @jlstevens, could you provide a status update on this?

**Comment by jlstevens** [comment]
I had to step away from my debugging attempts for a while but I can now look into this once more. My goal is to open a PR this week. Thank you for the reminder!

**Comment by droumis** [comment]
Hi @jlstevens, any progress on that PR?

**Comment by jlstevens** [comment]
Sorry I got distracted by other priorities once again. Perhaps there is someone else who could be assigned to work together with me on this? That will help keep me on track and help get this fixed faster.

**Comment by philippjfr** [comment]
Turned out to be a small oversight in the existing implementation, so I fixed it.

**Comment by jlstevens** [comment]
Thank you! 

I really thought I had to do something in the Python code to accumulate over the elements of the overlay. I realize my mental model of how the callback was invoked was wrong.

Anyway, I'm just glad it is fixed :-)
