### ISSUE TITLE
`subcoordinate_y` not working with DynamicMap triggered by Panel widget

### ISSUE THREAD

**Issue by droumis** [holoviz/holoviews#6071]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

<details> <summary> versions </summary>

```
Python              :  3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]
Operating system    :  macOS-13.5.2-arm64-arm-64bit
Panel comms         :  default

holoviews           :  1.18.2a2.post7+gbfbde096b

bokeh               :  3.3.2
colorcet            :  3.0.1
cudf                :  -
dask                :  2023.12.1
datashader          :  0.16.0
geoviews            :  -
hvplot              :  0.9.0
ibis                :  -
IPython             :  8.18.1
jupyter_bokeh       :  -
jupyterlab          :  4.0.7
matplotlib          :  3.8.2
networkx            :  3.2.1
notebook            :  7.0.6
numba               :  0.58.1
numpy               :  1.24.4
pandas              :  2.1.1
panel               :  1.3.4.post38+g171f100d-dirty
param               :  2.0.1
PIL                 :  10.1.0
plotly              :  -
pyarrow             :  14.0.1
scipy               :  1.11.4
skimage             :  0.22.0
spatialpandas       :  -
streamz             :  -
xarray              :  2023.10.1
```

</details>

#### Description of expected behavior and the observed behavior
I'd expect to be able to wrap a `subcoordinate_y` plot in a DynamicMap triggered by a Panel widget.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
SUBCOORD_Y = True

def return_overlay(run):
    if not run:
        return hv.Overlay(hv.Curve([]) * hv.Curve([]))
    return (hv.Curve([0,1], label='1').opts(subcoordinate_y=SUBCOORD_Y) * hv.Curve([1,0], label='2').opts(subcoordinate_y=SUBCOORD_Y))

run_button = pn.widgets.Button(name='run')
pn.Column(hv.DynamicMap(pn.bind(return_overlay, run=run_button)), run_button)
```

#### Stack traceback and/or browser JavaScript console output
```
Traceback (most recent call last):
  File "/Users/droumis/src/holoviews/holoviews/plotting/bokeh/element.py", line 1848, in _init_glyphs
    renderer, glyph = self._init_glyph(plot, mapping, properties)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/droumis/src/holoviews/holoviews/plotting/bokeh/element.py", line 1527, in _init_glyph
    center = y_source_range.tags[1]['subcoordinate_y']
             ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'subcoordinate_y'
```

#### Screenshots or screencasts of the bug in action

https://github.com/holoviz/holoviews/assets/6613202/2fdd9426-157c-492f-9ce1-3448407aa72a

- [ ] I may be interested in making a pull request to address this

**Comment by droumis** [comment]
Environment changed and having trouble reproducing. closing for now

**Comment by droumis** [comment]
Just checking out my issues to check if still valid.

This is still a valid issue.

**Comment by thuydotm** [comment]
As we use DynamicMap here, the plot will just be updated inplace, not replaced entirely. That means, the plot and its axes information only get initialized once. Adding/updating `subcoordinate_y` later won't make any effects. Something likes this should work:

```python
SUBCOORD_Y = True

def return_overlay(run):
    if not run:
        return (hv.Curve([], label='1').opts(subcoordinate_y=SUBCOORD_Y) * hv.Curve([], label='2').opts(subcoordinate_y=SUBCOORD_Y))
    return (hv.Curve([0,1], label='1') * hv.Curve([1,0], label='2'))

run_button = pn.widgets.Button(name='run')
pn.Column(hv.DynamicMap(pn.bind(return_overlay, run=run_button)), run_button)
```

Discussed with @hoxbro and we agreed that the KeyError about `subcoordinate_y` is quite confusing. Will make it a warning with clearer messages.

**Comment by thuydotm** [comment]
While writing tests for this, we realized it's not about axes not updated. It's about the labels not being set for initial plots. Label mismatching between initial and updated plots causes the error.
