### ISSUE TITLE
Blank figures with `holoviews` + `bokeh` + `Jupyter Lab Desktop`

### ISSUE THREAD

**Issue by alcrene** [holoviz/holoviews#6082]
I’ve been trying out [Jupyter Lab Desktop](https://github.com/jupyterlab/jupyterlab-desktop) and ran into a weird issue with bokeh plots not being displayed.

It only occurs when I try to show a bokeh plot, through holoviews, in Jupyter Lab Desktop.

- FAILS: _holoviews_ + _bokeh_ + _JLab Desktob_
- WORKS: _holoviews_ + _matplotlib_ + _JLab Desktob_
- WORKS: _holoviews_ + _plotly_ + _JLab Desktob_
- WORKS: _holoviews_ + _bokeh_ + _browser_  (running `jupyter lab` on CLI)
- WORKS: _bokeh_ + _JLab Desktob_ (plain `bokeh` plots, constructed without holoviews)

#### ALL software version info

- **OS**: Pop!OS 22.04
- **Browser**:
  -  Works on : _Firefox_ 121, _Chromium_ 120 (flatpak)
  - Does not work on _Jupyter Lab Desktop_ 4.0.11  & 4.0.7

Pruned `pip list`:
```
Package                   Version
------------------------- ---------------
bokeh                     3.1.1
conda                     23.11.0
ipython                   8.12.2
ipywidgets                8.1.1
jupyter-bokeh             3.0.7
jupyter_client            8.6.0
jupyter_core              5.7.1
jupyter_server            2.12.5
jupyterlab                4.0.11
jupyterlab_myst           2.1.0
jupyterlab_pygments       0.3.0
jupyterlab_server         2.25.2
jupyterlab-widgets        3.0.9
jupytext                  1.16.1
libmambapy                1.5.6
nbclient                  0.8.0
notebook_shim             0.2.3
param                     2.0.2
pip                       23.3.2
pyviz_comms               3.0.1
pyzmq                     25.1.2
tornado                   6.3.3
websocket-client          1.7.0
```

#### Description of expected behavior and the observed behavior

Jupyter Lab desktop containerizes a conda environment with Jupyter Lab, so for this test I made sure to run everything from the same environment: in both examples, both Jupyter Lab and the ipykernel are running from the same `jlab_server` environment.

When I run this test notebook in **Jupyter Lab Desktop**, there seems to be some issue with bokeh not finding some graphics library
![Capture d’écran du 2024-01-25 09-41-48](https://github.com/holoviz/holoviews/assets/4419684/eb0f513e-5719-45a9-a8e7-3c1b2ee0f1f9)

However if I load the same environment used by Jupyter Lab Desktop on CLI, then run it in a **browser**, things work as expected:
```
conda activate /opt/jlab_server
jupyter lab
```
![Capture d’écran du 2024-01-25 09-39-28](https://github.com/holoviz/holoviews/assets/4419684/6c6bf407-481f-4f11-bda3-e4d1291ab0f3)

Funny enough, creating a simple bokeh plot *does* work in JLab Desktop. (I’m not fluent in bokeh, so I didn’t test anything more complicated.)

![Capture d’écran du 2024-01-25 10-42-14](https://github.com/holoviz/holoviews/assets/4419684/bd33aa28-8d4e-4148-ad73-3fb14da9ee5e)

I think this issue also spills over to _panel_: I have an interactive Tabulator widget which is non-interactive in JLab Desktop.
However I wasn’t able to make a good MWE with _panel_, since a lot of widgets do seem to work.

#### Workaround

- Use matplotlib or plotly
- Use the browser instead of Jupyter Lab Desktop
- Turn off WebGL rendering by executing `hv.renderer("bokeh").webgl = False` in a cell

#### Possibly an upstream bug

It is certainly possible that this is an issue upstream, which for me only triggers when I use holoviews.
But since I wasn’t able to produce a MWE which doesn’t involve holoviews, I think it makes sense to post the bug report here.

**Comment by Hoxbro** [comment]
Can you try running this in Jupyterlab Desktop?

``` python
import holoviews as hv
hv.extension("bokeh")
hv.Curve(range(10))
```

**Comment by alcrene** [comment]
The result is the same. (That’s actually the first thing I tried)

**Comment by alcrene** [comment]
Here’s the result with a completely new test environment:

```
jlab env create /opt/jld_bokeh_test "python==3.11" bokeh holoviews
```
From within JLD, select Settings -> Server -> Custom Python environment -> `opt/jld_bokeh_test`

Then when I run a test notebook I get as above: 

![Capture d’écran du 2024-01-25 11-19-23](https://github.com/holoviz/holoviews/assets/4419684/73d59ca6-424e-4611-901b-45de70d862d4)

**Comment by Hoxbro** [comment]
Can you try `hv.render("bokeh").webgl = False` before running the cell.

**Comment by alcrene** [comment]
That raises a Python exception:
![Capture d’écran du 2024-01-25 12-09-41](https://github.com/holoviz/holoviews/assets/4419684/9d25d9a0-843c-4910-8ed2-9357b8d9668f)

**Comment by Hoxbro** [comment]
Sorry it is `renderer`

**Comment by alcrene** [comment]
Ah yes, then that works around the issue.

![Capture d’écran du 2024-01-25 12-18-43](https://github.com/holoviz/holoviews/assets/4419684/786eec4d-ebad-4e58-a3c9-6b3a88b04efc)

I’ve added it to the list of workarounds in my initial post.

**Comment by Hoxbro** [comment]
This is a Bokeh problem. Can you please report the issue there?

A MRE with pure Bokeh is:
``` python
from bokeh.plotting import figure
from bokeh.io import output_notebook, show

output_notebook()
p = figure(output_backend="webgl")
p.line(x=list(range(8)), y=list(range(8)))
show(p)
```

**Comment by alcrene** [comment]
Done: https://github.com/bokeh/bokeh/issues/13665

Thank you for your help !
