### ISSUE TITLE
Incorrect Datashader colourmap being displayed

### ISSUE THREAD

**Issue by RoryMMMM** [holoviz/holoviews#6084]
#### ALL software version info
Pandas == 1.3.4
Bokeh == 3.3.3
Holoviews == 1.18.1 
Notebook == JupyterLab Version 3.4.7 (Running in Docker)
Browser == Chrome Version 118.0.5993.88 (Official Build) (64-bit)
OS == Ubuntu 22.04

#### Description of expected behavior and the observed behavior
I'm using Datashader in Holoviews to plot Lat/Lon data along with a tiled baselayer. I'm using near identical code to the tutorial on the [examples.holoviews](https://examples.holoviz.org/gallery/opensky/opensky.html
) site. I'm changing the colourmap that is being used to plot the categorical code, and the legend shows that the colourmap is being changed, however the colourmap on the actual plotting isn't changed. Is this a bug or is this a user error? 

#### Complete, minimal, self-contained example code that reproduces the issue

```
# I'm using GB's of data, I cant really include that here...
# Load data and model
df = pd.read_parquet(infile)
df[['x','y','Agg-Class']]

x	y	Agg-Class
0	-2.270930e+06	4.002873e+06	Cargo
1	1.011061e+07	6.379699e+05	Tanker
2	8.984002e+06	6.473626e+05	Tanker
3	8.553550e+06	8.272227e+05	Tanker
4	8.047425e+06	1.057635e+06	Tanker
...	...	...	...
1775596	3.668608e+05	6.662439e+05	Tanker
1775597	3.575693e+05	7.042833e+05	Tanker
1775598	3.745975e+05	7.037140e+05	Tanker
1775599	3.746290e+05	7.036748e+05	Tanker
1775600	3.748925e+05	6.974126e+05	Tanker

def categorical_color_key(aggregator, cmap):
    """Generate a color key from the given colormap with the appropriate number of colors for flightpaths"""
    from matplotlib.colors import rgb2hex
    from matplotlib.cm import get_cmap
    ncats = len(df[aggregator.column].unique())
    return [str(rgb2hex(get_cmap(cmap)(i))) for i in np.linspace(0, 1, ncats)]

plot_width  = 850
plot_height = 600
x_range = (-4.0e6, 4e6)
y_range = (-5.0e6, 3.8e6)

map_tiles  = hv.Tiles('https://api.maptiler.com/maps/dataviz/{Z}/{X}/{Y}.png?key=<my key>', name="MapTiler").opts(width=plot_width, height=plot_height)

aggregator = ds.count_cat('Agg-Class')
datashaded = hd.datashade(hv.Points(df, ['x', 'y']), 
                          x_range=x_range, 
                          y_range=y_range, 
                          aggregator=aggregator, 
                          color_key=categorical_color_key(aggregator, 'cool'))

map_tiles * datashaded

```
#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/holoviews/assets/44571945/fb8d756f-e758-4306-a1a3-c735352d6a49) 

- [ ] I may be interested in making a pull request to address this

**Comment by RoryMMMM** [comment]
This is a little weird. I've downloaded the census notebook example and without changing anything the issue is being seen there too. 

 In the census example image from the examples.holoviz website "White" people are shown as blue in the legend and plot:
![bokeh_plot (11)](https://github.com/holoviz/holoviews/assets/44571945/220b52f1-d31c-4117-908f-ad4db47ce554)

 When the notebook is downloaded and run locally  "White" people are shown as blue in the legend but orange in the plot:
![bokeh_plot (10)](https://github.com/holoviz/holoviews/assets/44571945/586206a8-90df-4421-948a-28bbfe473a4b)

**Comment by Hoxbro** [comment]
The difference you are seeing between local and deployed example could be related to https://github.com/holoviz/datashader/issues/1202

**Comment by RoryMMMM** [comment]
Possibly... My concern is that Dask has d[eprecated the use of fastparquet ](https://github.com/dask/dask/pull/10743)so it gets difficult when testing with up to date libraries.

**Comment by Hoxbro** [comment]
Can you try with holoviews 1.18.2?

**Comment by RoryMMMM** [comment]
![image](https://github.com/holoviz/holoviews/assets/44571945/44044281-04ff-47e2-a19c-69a62c853f4c)
That seems to have done it. I'll check with my dataset now

**Comment by RoryMMMM** [comment]
![image](https://github.com/holoviz/holoviews/assets/44571945/be71e867-eab6-4dae-8e8e-5a0a3750e17b)

Works here too! Thanks for the quick response!
