### ISSUE TITLE
Rasterize with categorical colormap causing browser hanging

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#6096]
#### ALL software version info
holoviews=1.18.1
datashader=0.16.0
bokeh=3.3.0
notebook=6.5.4

#### Description of expected behavior and the observed behavior

When I run the code below, it works but my browser hangs unresponsively (not even scrolling the browser window) for tens of seconds after rendering the plot and then again whenever I try to do anything with the plot (like zooming into it).

```python
import holoviews as hv, datashader as ds, numpy as np, pandas as pd
from holoviews.operation.datashader import rasterize

hv.extension('bokeh')
np.random.seed(3)

def random_cov():
    A = np.random.randn(2,2)
    return np.dot(A, A.T)

def rand_gauss2d(value=0, n=100000):
    g = 100*np.random.multivariate_normal(np.random.randn(2), random_cov(), (n,))
    return np.hstack((g,value*np.ones((g.shape[0],1))))

dataset = pd.concat([pd.DataFrame(rand_gauss2d(i), columns = ["x","y","k"]) for i in range(5)])
dataset["k"]=dataset["k"].astype(str)

rasterize(hv.Points(dataset), aggregator=ds.by('k'))
```

<img width="823" alt="image" src="https://github.com/holoviz/holoviews/assets/1695496/caddde90-d02b-4d40-b72d-20f7f7c89997">

**Comment by Hoxbro** [comment]
Try update bokeh to 3.3

**Comment by jbednar** [comment]
Uh-oh; 3.3.0 is the latest available on Anaconda defaults. Upgrading to 3.3.4 did fix it, but required me to install from the `bokeh` channel. Need to update defaults!

**Comment by jbednar** [comment]
Ok, Anaconda defaults has been updated to 3.3.4, so I hope this problem won't hit others now.
