### ISSUE TITLE
HoloViews produces blurry plots

### ISSUE THREAD

**Issue by Yura52** [holoviz/holoviews#6115]
#### Software
```
OS: macOS 12.5
Browser: Firefox, Safari

python=3.10.12
bokeh=3.3.3
holoviews=1.18.1
jupyterlab=4.1.0
```

#### The bug & How to reproduce

In JupyterLab, the following snippet produces two plots (attached below), and the line in the second plot is blurry.

```
# CELL 0
import bokeh.plotting
import bokeh.palettes
import bokeh.io
import holoviews as hv

bokeh.io.output_notebook()
hv.extension('bokeh')

# CELL 1
x = [0, 1, 2, 3]
y = [1, 2, 3, 2]
width = 500
height = 300
color = bokeh.palettes.Set1_3[1]

# CELL 2
p = bokeh.plotting.figure(width=width, height=height)
p.line(x, y, width=2, color=color)
bokeh.plotting.show(p)

# CELL 3
hv.Curve((x, y)).opts(
    width=width,
    height=height,
    show_grid=True,
    color=color,
)
```

#### Screenshots

The first plot:

![0](https://github.com/holoviz/holoviews/assets/8861742/2a6c94a2-4ab1-4167-8570-56dc79b2393a)

The second plot:

![1](https://github.com/holoviz/holoviews/assets/8861742/e301e68d-a401-49f5-a078-5dfc017945c7)

**Comment by Hoxbro** [comment]
Do you see the same result whit this: `p = bokeh.plotting.figure(width=width, height=height, output_backend='webgl')`

**Comment by Yura52** [comment]
This makes the first image also blurry

**Comment by Hoxbro** [comment]
I think it is a Bokeh problem, then. Can you report it upstream?

**Comment by Yura52** [comment]
Sure, thank you for the quick reply!

(not sure whether to keep this issue open or closed)

**Comment by Yura52** [comment]
@Hoxbro Is there a quick fix to the HoloViews default settings that I can use while waiting for the official fix in Bokeh?

**Comment by Hoxbro** [comment]
Yes. `hv.renderer("bokeh").wegl = False`

I will close the issue, as there is nothing we can do on HoloViews side of things.
