### ISSUE TITLE
HexTiles with Bokeh backend does not support log axes

### ISSUE THREAD

**Issue by banesullivan-kobold** [holoviz/holoviews#6117]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

```
                OS : Darwin
            CPU(s) : 12
           Machine : arm64
      Architecture : 64bit
               RAM : 32.0 GiB
       Environment : Jupyter
       File system : apfs

  Python 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:33:12)
  [Clang 15.0.7 ]

         holoviews : 1.18.3
             bokeh : 3.3.1
             numpy : 1.25.2
             scipy : 1.11.2
           IPython : 8.15.0
        matplotlib : 3.7.2

```

#### Description of expected behavior and the observed behavior

When using `hv.HexTiles`, support `.opts(logx=True, logy=True)` with the `bokeh` backend.

This works well with the `matplotlib` backend and is handled here:

https://github.com/holoviz/holoviews/blob/c3c211e0101318d676820c404cf85a04ba42554d/holoviews/plotting/mpl/hex_tiles.py#L48-L49

![download](https://github.com/holoviz/holoviews/assets/144726278/9a89d3c2-171d-4619-a6d8-4534e1a084db)

#### Complete, minimal, self-contained example code that reproduces the issue

```py
import numpy as np
import holoviews as hv
from holoviews import opts
hv.extension('bokeh')

np.random.seed(44)
data = np.exp(np.random.randn(100000, 2) + 20)

hv.HexTiles(data).opts(logx=True, logy=True)
```
![bokeh_plot (1)](https://github.com/holoviz/holoviews/assets/144726278/f6e7bc6b-6d46-4745-b4db-f1a04ed93adb)

#### Stack traceback and/or browser JavaScript console output

N/A

#### Screenshots or screencasts of the bug in action

- [x] I may be interested in making a pull request to address this

**Comment by Hoxbro** [comment]
@mattpap is log-log hextiles supported in Bokeh?

**Comment by mattpap** [comment]
> is log-log hextiles supported in Bokeh?

No, it's limited to linear scales/axes only, see e.g.:
https://github.com/bokeh/bokeh/blob/b627a152c21b6484de867db41b8163a74ebb9566/bokehjs/src/lib/models/glyphs/hex_tile.ts#L116-L117
We should add a warning for this, similarly to what we did for `Rect` glyph's `width` and `height`.

**Comment by Hoxbro** [comment]
Thank you @mattpap.

I will close this issue as there is nothing we can do in HoloViews; if you want this supported, you can open an issue on Bokehs [issue tracker](https://github.com/bokeh/bokeh).
