### ISSUE TITLE
Holoviews has been quarantined by sonatype for 17 days

### ISSUE THREAD

**Issue by s-banach** [holoviz/holoviews#6138]
My work puts this security scanner between us and pypi.
`Found security vulnerability sonatype-2021-0532 with severity >= 9.8 (severity = 9.8)`
Has sonatype ever contacted you about this supposed security issue?
I'm still trying to figure out if they have legitimate issues, or it's totally bogus.

**Comment by Hoxbro** [comment]
Likely a false positive. 

Never heard of this. Can you copy what the vulnerability is? I can't seem to google my way to it.

**Comment by s-banach** [comment]
I'm asking our internal bureaucracy if they have any more information about the supposed vulnerability.
It's probably totally bogus security theater.

**Comment by s-banach** [comment]
"This is a common issue where they call out deserialization of untrusted data." -- Cybersecurity guy.
