### ISSUE TITLE
looking for graph visualization example  

### ISSUE THREAD

**Issue by haseebkhawaja** [holoviz/holoviews#6143]
i am looking for some example 
for holoview graph visualization where i click on the node, the node will be selected and also clicking the node, the onclick() function will be called... and  in onclick function, something will be printed..

**Comment by droumis** [comment]
Hi @haseebkhawaja, please use the [HoloViz Discourse forum](https://discourse.holoviz.org/) for usage questions. You can find more info about our community channels at [holoviz.org/community ](https://holoviz.org/community.html)

**Comment by haseebkhawaja** [comment]
Thanks for support..

**Comment by Hoxbro** [comment]
This is not a support forum, so no need to thank for that. 

As @droumis suggested, try opening an issue on discourse, and maybe try to see how far you can get by yourself.
