### ISSUE TITLE
After deep zoom in Holoview difference between hover values is changing unexpectedly: 100, 300, 200, 400, 200, 200, 300, 300, so on.

### ISSUE THREAD

**Issue by zyuzin2024** [holoviz/holoviews#6156]
See below, back to back difference between hover values is changing unexpectedly: 100, 300, 200, 400, 200, 200, 300, 300, so on.
 
hover value                       click value
1538685910861211000 (1538685910861210880)
1538685910861211100 (1538685910861211136)
1538685910861211400 (1538685910861211392)
1538685910861211600 (1538685910861211648)
 
1538685910861211799 - target value
 
1538685910861212000 (1538685910861211904)
1538685910861212200 (1538685910861212160)
1538685910861212400 (1538685910861212416)
1538685910861212700 (1538685910861212672)
1538685910861213000 (1538685910861212928)

**Comment by Hoxbro** [comment]
You need to provide much more information than this... 

Please share a [minimal, reproducible example (MRE)](https://stackoverflow.com/help/minimal-reproducible-example). In general, a complete script only with the essential code, which can be copied/pasted and immediately run as-is with no modifications.

**Comment by droumis** [comment]
Hi @zyuzin2024, Please provide a minimal reproducible example of what you are reporting and the versions of the software that you are using. This is an open-source package and to have any hope of addressing user issues, we need users to provide more complete information.

**Comment by droumis** [comment]
@zyuzin2024 if you are still experiencing an issue, please open a new issue with a complete reproducible example and as much context as you can provide
