### ISSUE TITLE
Cannot set font size for `hv.Text` when using `matplotlib` backend

### ISSUE THREAD

**Issue by sztal** [holoviz/holoviews#6159]
As in the title. It seems there is no way to set font size on `Text` elements. Niether `size` nor `fontsize` option in `opts` works.

#### ALL software version info

`holoviews=1.18.3`
`matplotlib=3.8.0`

#### Description of expected behavior and the observed behavior

The following should work:

```
hv.Text(0, 1, "TEXT").opts(
    size=30  # or 'fontsize'
)
```

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks
hv.Text(0, 1, "Text").opts(size=30)
```

And the second approach does not work too.

```
hv.Text(0, 1, "Text").opts(fontsize=30)
```

#### Screenshots or screencasts of the bug in action

- [Yes] I may be interested in making a pull request to address this

**Comment by Hoxbro** [comment]
Can you share a [minimal, reproducible example (MRE)](https://stackoverflow.com/help/minimal-reproducible-example)?

In general, a complete script that only has the essential code, which can be copied/pasted and immediately run as-is with no modifications. This is much more useful than snippets.

**Comment by Hoxbro** [comment]
Does this work `hv.Text(0, 1, "Text", 30)`?

**Comment by sztal** [comment]
Yes, this works, thanks a lot!!

**Comment by sztal** [comment]
Just in case, as far as I am considered, this issue may be closed. Thanks once again!
