### ISSUE TITLE
NdOverlay with more than 25 plots ignore styling

### ISSUE THREAD

**Issue by BMM3** [holoviz/holoviews#6164]
#### ALL software version info
pandas:  2.1.3
holoviews:  1.17.1
bokeh:  3.2.2
python: 3.12.0

#### Description of expected behavior and the observed behavior
I'm creating an overlay plot with NdOverlay where I can give each plot a separate color, style or size. However, when I'm adding more than 25 plots to the NdOverlay, the styling of the different plots is gone and every plot gets the same color, style and size.

#### Example
In the following example you can change the variable "numberOfPlots" from 26 to 25. At 25 the different colors will be shown in the plot, but at 26 all the points will have the same color.

```
import colorcet as cc
import holoviews as hv
import pandas as pd
import itertools

numberOfPlots=26
pIter = itertools.cycle(cc.palette['glasbey_category10'])
overlayPlots = {}
y = [1,2]
count = 0
for _ in range(numberOfPlots):
       df = pd.DataFrame({'x':[1,2], 'y':[yi+count for yi in y]})
       p = hv.Scatter(df, 'x', 'y')
       p.opts(color=next(pIter))
       overlayPlots[count] = p
       count = count + 1

poverlay = hv.NdOverlay(overlayPlots, kdims='hue')
poverlay
```

#### Screenshots or screencasts of the bug in action
A ndoverlay with 24 plots:
![24_plots](https://github.com/holoviz/holoviews/assets/111486712/820fddbb-9413-4e34-b68c-baa17e78985f)

A ndoverlay with 26 plots:
![26_plots](https://github.com/holoviz/holoviews/assets/111486712/e5b6bb5a-9a1e-4054-ba2a-71b356d76152)

**Comment by Hoxbro** [comment]
This is because we have a limit on how many plots we can combine before we do a smarter batch. This option is `legend_limit`, and by default, it is 25.

**Comment by BMM3** [comment]
By setting the `legend_limit` to 26 or by setting `batched=False` solved my issue.
Thanks a lot for the fast reponse!

**Comment by BMM3** [comment]
@Hoxbro : can you refer me to the documentation of the "batched" option?
I'm curious as to what it exactly does.

**Comment by Hoxbro** [comment]
I can't find any documentation on it.

Let's say we have 26 curves we want to show. If they are not batched,  all the curves need to create their own axes, legends, titles etc.,  and then they must be combined. Then, each object will be serialized, sent to the frontend, and then unserialized and created javascript objects.

That is a lot of overhead. What batched does is it combines the data in each curve and creates one curve, reducing the overhead significantly. 

Why 25 as the limit and why is it called `legend_limit`, I don't know :sweat_smile:
