### ISSUE TITLE
BoxWhisker: outliers are not displayed on bokeh backend

### ISSUE THREAD

**Issue by alxthm** [holoviz/holoviews#6166]
#### ALL software version info

Python: `Python 3.9.17`
Relevant requirements:
```
bokeh==3.4.0
holoviews==1.18.3
matplotlib==3.8.3
```
Browser: firefox 124.0.1 (64-bit), macOS

#### Description of expected behavior and the observed behavior

On bokeh backend, the BoxWhisker plot does not display outliers (normally rendered as dots or circles, outside the box limits).

The plot does work as expected on a matplotlib backend.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
import numpy as np

x = np.random.randn(1000)
print(max(x)) # prints `2.8981705376936917` in this example

# here, outliers are displayed as expected (see screenshots)
hv.extension('matplotlib')
hv.BoxWhisker(x, vdims='Value')

# here, no outliers are displayed
hv.extension('bokeh')
hv.BoxWhisker(x, vdims='Value')
```

#### Stack traceback and/or browser JavaScript console output

Looking at the browser console, this warning appears each time I try to plot a BoxWhisker:

```
[bokeh 3.4.0] attempted to retrieve property array for nonexistent field 'radius'
```

#### Screenshots or screencasts of the bug in action

<img width="927" alt="Screenshot 2024-04-01 at 13 16 04" src="https://github.com/holoviz/holoviews/assets/33730312/f1fdd26c-a6f8-413b-98e6-d650917a78e0">

- [x] I may be interested in making a pull request to address this (with some help and pointers!)

**Comment by BMM3** [comment]
It might be linked to the following issue: #5431
