### ISSUE TITLE
Holomap with NdOverlay's don't update depending on legend_position

### ISSUE THREAD

**Issue by BMM3** [holoviz/holoviews#6176]
#### ALL software version info
holoviews : 1.17.1
pandas : 2.1.3
numpy : 1.26.2

#### Description
The holomap is not updating the plot according to the buttons in certain situations. The example below shows the issue that I have with the following conditions:
- The holomap has multiple dimensions
- The holomap contains NdOverlay plots with different legends
- The legend_position is set.

I've seen the holomap working perfectly fine with only 1 dimension (so no 'button' in the following example).
I also know that it still works fine when I don't set the legend_position.

#### Example

```
import pandas as pd
import holoviews as hv
df = pd.DataFrame({'x':  [1,2,1,2], 
                   'button':  [1,1,2,2], 
                   'y': [2,3,4,5],
                   'y2': [4,5,6,7],
                   'y3': [8,9,10,11],
                   'y4': [12,13,14,15],
                   })

p1a = hv.Curve(df[df['button']==1], 'x', 'y')
p1b = hv.Curve(df[df['button']==1], 'x', 'y2')
p2a = hv.Curve(df[df['button']==1], 'x', 'y3')
p2b = hv.Curve(df[df['button']==1], 'x', 'y4')
p3a = hv.Curve(df[df['button']==2], 'x', 'y')
p3b = hv.Curve(df[df['button']==2], 'x', 'y2')
p4a = hv.Curve(df[df['button']==2], 'x', 'y3')
p4b = hv.Curve(df[df['button']==2], 'x', 'y4')

p1 = hv.NdOverlay({('y'):p1a, ('y1'):p1b}, kdims=['y'])
p2 = hv.NdOverlay({('y3'):p2a, ('y4'):p2b}, kdims=['y'])
p3 = hv.NdOverlay({('y'):p3a, ('y1'):p3b}, kdims=['y'])
p4 = hv.NdOverlay({('y3'):p4a, ('y4'):p4b}, kdims=['y'])

hmap = hv.HoloMap({
      (1,'y_y1'):p1,
      (2,'y_y1'):p3,
      (1,'y3_y4'):p2,
      (2,'y3_y4'):p4,
}, kdims = ['button', 'y'])

# For this hmap the plot is still updateding:
hmap.opts(hv.opts.NdOverlay(ylim=(0,20)))

# When the legend_position is set, the plot is not updateing anymore:
hmap.opts(hv.opts.NdOverlay(ylim=(0,20), legend_position='right'))

```

#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/holoviews/assets/111486712/1bb2c2fb-145d-4425-b9cd-f68dc163f4fd)

**Comment by Hoxbro** [comment]
This seems to work fine for me, can you try and update to a newer version of HoloViews?


https://github.com/holoviz/holoviews/assets/19758978/d81ea274-c1d6-44ef-8cae-2c3d21f71414
