### ISSUE TITLE
Stacked bars not rendered correctly with datetime axis

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/holoviews#6288]
With HoloViews 1.19.0, #6145 brought an interesting feature with continuous axis support for hv.Bars.

However, now when the `stacked` option is enabled, bars are not rendered correctly on a datetime x-axis. As an aside, xlims seem to be ignored.

```python

import datetime as dt
import holoviews as hv
import pandas as pd

data = pd.DataFrame({"x": pd.to_datetime(["2017-01-01T00:00:00",
                                          "2017-01-01T00:00:00",
                                          "2017-01-01T01:00:00",
                                          "2017-01-01T01:00:00",
                                          "2017-01-01T02:00:00",
                                          "2017-01-01T02:00:00"]),
                     "cat": ["A", "B", "A", "B", "A", "B"],
                     "y": [0, 2, 1, 5, 1, 2]})
hv.Bars(data, ["x", "cat"], ["y"]).opts(
    width=600, stacked=True, xlim=(dt.datetime(2017, 1, 1), dt.datetime(2017, 1, 2)))
```

![issue_bars](https://github.com/holoviz/holoviews/assets/49269671/1eaec104-42d0-4cbc-8f1c-728d7f684bbe)

The horizontal elements displayed extend across the x-axis just as HLine or HSpan.

I have no error in python or in the browser.

**Comment by TheoMathurin** [comment]
Any idea where to look for in order to fix this? I'm willing to spend some time as this bug prevents me from updating to 1.19.

**Comment by MarcSkovMadsen** [comment]
On holiday ⛱️ find the PR adding support for continous axis. Find the file(s) that changed. Try to debug basic example and figure out how it works.

**Comment by philippjfr** [comment]
I'll take a quick look at it, I suspect we didn't consider the grouped/stacked conditions at all.
