### ISSUE TITLE
Correct (/control) spacing in layout

### ISSUE THREAD

**Issue by arafune** [holoviz/holoviews#6311]
#### Complete, minimal, self-contained example code that reproduces the issue
https://holoviews.org/gallery/demos/bokeh/mandelbrot_section.html

The output of  the code shown in the above webpage is same as on my Mac. I would like to control the space between two rows of the figures. 

For me, the space is too wide, I would like to change it.  Actually my own problem is same. I would like to change the spacing between two plots using .col(1).

Here is my own code:

import holoviews as hv
import xarray as xr
from holoviews import opts, streams
hv.extension("bokeh")

def crosshair_view2(dataarray: xr.DataArray) -> None:
    """Show Crosshair view."""

    # Create two images
    posx = hv.streams.PointerX(x=0)
    posy = hv.streams.PointerY(y=0)
    vline = hv.DynamicMap(lambda x: hv.VLine(x or -100), streams=[posx])
    hline = hv.DynamicMap(lambda y: hv.HLine(y or -100), streams=[posy])
    img = hv.Image(dataarray, kdims=list(dataarray.dims))
    profile_x = hv.DynamicMap(lambda x: img.sample(**{dataarray.dims[0]: x if x else 0}), streams=[posx])
    profile_y = hv.DynamicMap(lambda y: hv.Curve(dataarray.sel({dataarray.dims[1]: y if y else 0}, method = "nearest")), streams=[posy])
    return  (img * hline * vline + profile_y).cols(1)

**Comment by maximlt** [comment]
I get this view when I run the code in https://holoviews.org/gallery/demos/bokeh/mandelbrot_section.html.

![image](https://github.com/holoviz/holoviews/assets/35924738/35aeda7d-fd5c-4751-aac5-ce8aa6b9f986)

I was no able to run your code, it is incomplete. Please provide more details as your issue is unclear to me.
