### ISSUE TITLE
How to add Y-profile on the top of the image ?

### ISSUE THREAD

**Issue by arafune** [holoviz/holoviews#6312]
The examples shown in this page:
https://holoviews.org/reference/streams/bokeh/PointerX.html

is really nice for me.  I would like to show the both of X- and Y-axis profile.  
I have searched the web, but I have not found the appropriate method.  

The description of operator "<<"  is missing ?

And If you can, let me know hot to add "autorange" feature on the profile plot.

**Comment by maximlt** [comment]
Hi @arafune,

HoloViews users are highly recommended to ask usage questions on the [HoloViz Discourse Forum](https://discourse.holoviz.org/). Could you please ask this question there and close this issue? Thanks!
