### ISSUE TITLE
`pn.state.curdoc` is `None` inside of a popup-function

### ISSUE THREAD

**Issue by jerry-kobold** [holoviz/holoviews#6332]
Recently HoloViews added the capability to open a popup when selecting points in a plot. However the function invoked this way does not seem to propagate the `pn.state.curdoc` correctly, which results in a break in any logic that depends on this.

#### ALL software version info
OS X Sonoma M1
```
bokeh==3.4.2
holoviews==1.19.1
panel==1.4.4
pandas==2.2.2
```

#### Description of expected behavior and the observed behavior

When you add a subscriber to a stream, that subscriber has access to the current Bokeh document. However, when the popup function is invoked, this document is set to `None`.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import holoviews as hv
import numpy as np
import pandas as pd
import panel as pn

from holoviews.streams import Selection1D

hv.extension("bokeh")
pn.extension()

data = np.random.default_rng().random(size=(10, 2))
df = pd.DataFrame(data, columns=["x", "y"])

def make_plot():
    return hv.Points(df, kdims=["x", "y"]).opts(framewise=True, tools=["box_select"])

dm = hv.DynamicMap(make_plot)

def debug(*args, **kwargs):
    print("debug:", pn.state.curdoc)

def popup(index):
    print("popup:", pn.state.curdoc)

sel_stream = Selection1D(source=dm, popup=popup)
sel_stream.add_subscriber(debug)

pn.Column(dm).servable()
```

If you run this with `panel serve` and select some points in the plot, the `debug` function will print a valid document, while the `popup` function will not.

**Comment by jerry-kobold** [comment]
Thanks, I wasn't sure where to post it, so I went with this repo because it touched `pn.state`.

**Comment by jerry-kobold** [comment]
FWIW, I was able to work around this problem by doing something like this:

```python
def popup(curdoc, index):
    pn.state.curdoc = curdoc
    # do stuff with index that depends on curdoc

sel_stream = Selection1D(source=dm, popup=partial(popup, pn.state.curdoc))
```

**Comment by philippjfr** [comment]
Yep that should work, any chance you'd consider submitting a fix to HoloViews, I think all that's needed is adding something like:

```python
from panel.io.state import set_curdoc
...
with set_curdoc(self.plot.document):
    popup = popup(**stream.contents)
```

here:

https://github.com/holoviz/holoviews/blob/main/holoviews/plotting/bokeh/callbacks.py#L691
