### ISSUE TITLE
hv.extension(inline=False) not working

### ISSUE THREAD

**Issue by michaelaye** [holoviz/holoviews#6385]
#### ALL software version info
<details>
    <summary>Software Version Info</summary>

```plaintext
* holoviews 1.19.1
* bokeh 3.5.2
* jupyter_bokeh 4.0.5
```    
</details>

#### Description of expected behavior and the observed behavior
- Expected: notebook does not contain bokeh javascript 
- Observed: Empty new notebook contains bokeh javascript despite `inline=False`
- 
#### Complete, minimal, self-contained example code that reproduces the issue

```python
import holoviews as hv
hv.extension("bokeh", inline=False, logo=False)
```

#### Screenshots or screencasts of the bug in action
```
     "data": {
      "application/javascript": [
       "(function(root) {\n",
       "  function now() {\n",
       "    return new Date();\n",
       "  }\n",
       "\n",
       "  const force = true;\n",
       "  const py_version = '3.5.2'.replace('rc', '-rc.').replace('.dev', '-dev.');\n",
       "  const reloading = false;\n",
       "  const Bokeh = root.Bokeh;\n",
       "\n",
       "  // Set a timeout for this load but only if we are not already initializing\n",
       "  if (typeof (root._bokeh_timeout) === \"undefined\" || (force || !root._bokeh_is_initializing)) {\n",
       "    root._bokeh_timeout = Date.now() + 5000;\n",
       "    root._bokeh_failed_load = false;\n",
       "  }\n",
```
- [ ] I may be interested in making a pull request to address this

**Comment by hoxbro** [comment]
> Expected: notebook does not contain bokeh javascript

This is a wrong expectation. `inline=True` (which is the default) means that the libraries are not embedded into the file. You still need a bit of JavaScript to run.

**Comment by michaelaye** [comment]
i see, thanks for confirming. I asked this [here](https://discourse.holoviz.org/t/hvplot-extension-inline-false-not-working/5612/2) a year ago, but alas, nobody replied.

**Comment by hoxbro** [comment]
That must have fallen through the cracks. Sorry about that.

**Comment by michaelaye** [comment]
oh i don't expect the holoviews team to have time to read all discussion, was just hoping that somebody knows and replies...

**Comment by michaelaye** [comment]
followup: is it normal/as-designed, that a 2nd time execution of a cell with `import hvplot.xarray` removes that minimal Javascript again from the notebook?

**Comment by michaelaye** [comment]
which interestingly does NOT happen with `import holoviews as hv;hv.extension(inline=False)`

**Comment by hoxbro** [comment]
This will be improved in the next hvplot release, so it is added each time you import it. See https://github.com/holoviz/hvplot/pull/1359
