### ISSUE TITLE
No way to suppress delineations between QuadMesh cells in bokeh backend

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/holoviews#6467]
<details>
    <summary>Software Version Info</summary>
```plaintext
holoviews 1.20.0
Bokeh 3.5.2
```
</details>

QuadMesh elements display fine gray or white lines between individual cells. From the docs:

![Image](https://github.com/user-attachments/assets/19e982c9-125b-4147-99aa-eb0c2ef89c5a)

While with matplotlib backend, this is the default:
![Image](https://github.com/user-attachments/assets/1d90c7cb-d9d8-4145-a2d4-1cd962e811f5)

When you have small cells with respect to plot size, these separating lines can really mess with the apparent colours (I think this may be what is seen [here](https://stackoverflow.com/questions/72448687/python-using-hvplot-quadmesh-for-xarray-data-shows-blended-colors-in-a-plot)). Even in the general case, I'd like to be able to have my `hv.QuadMesh` yield the same visual output as my `hv.Image`, i.e. a continuous area instead of patches of colour detached from each other.

However, I have not found a way to do that. Clearly grid lines are not to blame. Then I tried setting `line_alpha` and `line_width` to 0, which from [this issue](https://github.com/holoviz/holoviews/issues/4016) I thought would work, to no avail. Maybe this can be done with a hook.

Interestingly I have the result I want by default using pure Bokeh (with the `figure.quad` glyph which is used by Holoviews) whether you create a multi-cell quad or aggregating several quads.

MRE:

```python
import numpy as np
import holoviews as hv

hv.extension('bokeh')

n = 8  # Number of bins in each direction
xs = np.logspace(1, 3, n)
ys = np.linspace(1, 10, n)
zs = np.arange((n-1)**2).reshape(n-1, n-1)
hv.QuadMesh((xs, ys, zs)).opts(line_width=0, line_alpha=0)
```

- [x] I may be interested in making a pull request to address this

**Comment by TheoMathurin** [comment]
Sorry I don't understand the reason why the plot generated with Holoviews yields these separated cells while it's not the case with pure Bokeh given the same input data.

Surely I won't modify the data itself to accommodate for this behaviour, all the more so as the cells are not necessarily contiguous.

Also in my use case I need to work with Holoviews elements throughout and cannot switch to a bokeh figure.

**Comment by hoxbro** [comment]
Can you give me your Bokeh code for comparison?

**Comment by TheoMathurin** [comment]
Sure, a simple example:

```
from bokeh.plotting import figure, show

p = figure(width=400, height=400)
p.quad(top=[2], bottom=[1], left=[1],
       right=[2], color="#BAAA69")
p.quad(top=[3], bottom=[2], left=[1],
       right=[2], color="#B3DE69")
p.quad(top=[4], bottom=[3], left=[1],
       right=[2], color="#69B3DE")
p.quad(top=[5], bottom=[4], left=[1],
       right=[2], color="#DEB369")
show(p)
```
![Image](https://github.com/user-attachments/assets/1df7c995-07ea-409d-abfd-6d4392ec6204)

**Comment by TheoMathurin** [comment]
Oh when I tried this in Bokeh I was convinced I didn't get them, and in fact they're also visible with multiple quads if you look closely. It's probably due to the input data that is not the same, but I find the gray lines much less conspicuous in the plots generated with Bokeh.

I could open an issue upstream but I do not know if this can be fixed. While in Holoviews QuadMesh is exposed as a raster element to the end user, in Bokeh a collection of quads may not be tantamount to a raster so one cannot expect them to look the same.

**Comment by hoxbro** [comment]
This could be because we change `output_backend`, try `p = figure(width=400, height=400, output_backend="webgl")`

**Comment by TheoMathurin** [comment]
I don't see a difference when disabling/enabling webgl, whether I'm running the Bokeh MRE or the Holoviews MRE.

**Comment by hoxbro** [comment]
@mattpap, are you aware of this problem?

**Comment by mattpap** [comment]
This is most likely a problem with painting rectangles with grid aligned edges with fractional coordinates. In some cases, e.g. `{H,V}Strip` and `{H,V}Span` glyphs, we round coordinates to nearest pixels to avoid this behavior. I suppose we need to apply this approach in general.

**Comment by mattpap** [comment]
> I don't see a difference when disabling/enabling webgl, whether I'm running the Bokeh MRE or the Holoviews MRE.

By design there should be no difference between these. `webgl` backend should do whatever `canvas` backend does. If there are any differences, it should be considered as a bug unrelated to this issue.

**Comment by TheoMathurin** [comment]
> This is most likely a problem with painting rectangles with grid aligned edges with fractional coordinates. In some cases, e.g. `{H,V}Strip` and `{H,V}Span` glyphs, we round coordinates to nearest pixels to avoid this behavior. I suppose we need to apply this approach in general.

Thanks for the insight. Should I open an issue there then?

**Comment by mattpap** [comment]
> Thanks for the insight. Should I open an issue there then?

That would be ideal.

**Comment by TheoMathurin** [comment]
Issue here: https://github.com/bokeh/bokeh/issues/14192

As mentioned in the issue, the artefacts are much less visible in Chromium on my computer using Bokeh code. With HoloViews however, I don't see any difference when changing browser.

**Comment by mattpap** [comment]
Differing fractional font sizes can easily affect this, by changing size of side panels and thus position of the cartesian frame and quads themselves. Given that every browser (or even same browser on different platforms) may render text differently, then significance of this issue will vary.

**Comment by TheoMathurin** [comment]
I'll close this as there is nothing that can be done about this really (see discussion upstream).
