### ISSUE TITLE
Datashader support

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#908]
The new datashader support in HoloViews is great -- we can now easily choose between a "normal" HoloViews plot, a decimated one, or an aggregated one, making it simple to work with large or small datasets.  But there are still a few wrinkles to iron out:
## Automatic bin array sizing

The height and width of the datashader bin array must currently be set explicitly, but the plot size in pixels is available from the underlying Bokeh plot, and so we should be able to attach some streams that provide that size to datashader for its bin array dimensions instead.  It will always be important for users to be able to override such automatic values, but having them be automatic would be vastly more convenient in most cases.
## Unifying shading and colormapping

There are now two completely separate mechanisms for "shading", i.e., rendering a data array stored in an `hv.Image` object into a set of RGBA pixels for display.   The "backend" mechanism is called by the display hook for `hv.Image` objects, to provide "rich display" of the object in Jupyter.  This mechanism provides a colormap to the backend (Matplotlib or Bokeh) and requests that the backend render the image.  Presumably the backend mechanism allows Bokeh to provide accurate hover information, as it has direct access to the underlying data values.  The backend mechanism is also fully automatic, from the user perspective, being called behind the scenes whenever such an object needs to be displayed.

The other mechanism is provided by `hv.operation.datashader.shade()`, which explicitly turns an `hv.Image` object into an `hv.RGB` object, performing the colormapping from within Python using specialized functions in Datashader.  The `shade()` mechanism has functionality not present in Bokeh or Matplotlib's colormapping, namely doing histogram equalization, using the alpha channel to provide a mask, and allowing arbitrary data normalization functions if needed.  However, it currently must be invoked explicitly, using `shade()` to create a different HoloViews object type that no longer has information about the original data values, and is thus a "dead end" just for visualization, of the type that we try to avoid in HoloViews.   It would be nice to put this functionality into the plot options instead so that it can be invoked automatically on rich display, to avoid such dead ends and make the user experience more straightforward.
## Shading categorical aggregates

Categorical aggregates currently end up as an NdOverlay of Images, which can't normally be viewed directly as the topmost image obscures all the rest.  Thus these aggregates have an additional wrinkle similar to the issue for shading above -- they must first be converted explicitly into something visible, rather than allowing the user to use the same representation for working with data and for viewing it, as is an explicit goal of HoloViews.  Instead, we should be able to generalize the notion of compositors, perhaps covering the shading case above as well, allowing such overlays to be combined and shaded automatically on rich display.

These changes would make using datashading much more convenient, intuitive, and seamless in HoloViews.  Tasks:
- [x] Automatic plot sizing for `aggregate()`
- [x] Shading as a plot option
- [x] Compositors for shading categorical aggregates

**Comment by jlstevens** [comment]
Good summary!

Sounds like ``shade`` will be unnecessary once we offer linear/log/eq_hist modes for color mapping. 

As for compositors, they already exist is a more restricted (and undocumented form) but they are really just operations that hooks into the plotting system with the following properties:

* They always has a return value.
* This means that if they don't know how to handle a particular input, it is simply returned.
* If they know how to handle an input, it processes accordingly allowing final transformations to occur in the plotting system.

As such they are really just predicates+operations where the predicate determines if the input is suitable to apply the operation. Compositors are especially useful for Overlays/NdOverlays of Images because by default you only see the top layer - setting a compositor allows these image layers to act as channels by allowing the plotting system to convert these layers to an RGB element.

As such, ``compositor`` would be a plot options for ``Overlay`` and ``NdOverlay`` only accepting a compositor. E.g

```
%%opts Overlay [compositor=toRGBA]
red * green * blue
```

Where ``toRGBA`` could be defined as ``Compositor(stack(hv.Image, [3,4]), lambda x: hv.RGB(x))```. Here ``stack(hv.Image, [3,4])`` defines a predicate that is true when you have a stack of 3 or 4 Images and the lambda function converts the overlay to an RGB element.

With this generalization, you could define fancy predicates that apply according to group and label - so for instance you might enforce that the groups are 'Red', 'Green' and 'Blue' before automatically converting to RGB.  It will also be necessary to make it easy to compose compositors together.

**Comment by jbednar** [comment]
Thanks for expanding on that.  Presumably such functionality would be useful not just for overlays, but for any object?  It's just a generalized transformation of one or more elements or containers, right?

**Comment by kidpixo** [comment]
I know it is an old one and closed, but I was searching a way to 

overlay 3 images I got from `holoviews.operation.datashader.rasterize` in a single RGB

and this seems a doable way.
In the documentation i found this snippet ([holoviews.core.options — HoloViews](http://holoviews.org/_modules/holoviews/core/options.html))

    For instance, a compositor may be defined to automatically display
    three overlaid monochrome matrices as an RGB image as long as the
    values names of those matrices match 'R', 'G' and 'B'.

but I am not able to create something similar and there are no example whatsoever. Any help?

**Comment by jlstevens** [comment]
Just a note that new bokeh colormappers that will be better able to support datashader are being worked on: https://github.com/bokeh/bokeh/pull/8743

**Comment by jbednar** [comment]
> It would be nice to put [shade] functionality into the plot options instead so that it can be invoked automatically on rich display, 

Current support in bokeh makes this approach unnecessary, so I've marked it "done". There are still some gaps between Bokeh's colormapping what shade() can do, namely using alpha to indicate value for a single color and mixing categorical colors, but those are separate issues and should be addressed outside of this one.
