### ISSUE TITLE
Testing notebooks that aren't for documentation

### ISSUE THREAD

**Issue by jlstevens** [holoviz/holoviews#99]
Unit tests are great as they are quick and easy to run but they do take a little effort to implement.

As we have facilities for testing notebooks, why don't we have one or more notebooks with examples of edge-cases that we know have caused trouble in the past?

This notebook could be tested but not built/published on the website as documentation (wouldn't be meaningful learning material) . This might sometimes be an easier way to implement tests in some instances than via nosetests.

**Comment by philippjfr** [comment]
Closing, best we can do at the moment is nbsmoke testing.
